### ISSUE TITLE
No way to turn off pool?

### ISSUE THREAD

**Issue by malkomalko** [tgriesser/knex#1047]
Looking at https://github.com/tgriesser/knex/issues/823 and reading the source the pool should be able to be turned off by setting max to 0, however the pool parameter is still required for lib/client#acquireConnection.

Thoughts?

**Comment by wubzz** [comment]
What reasons are there for wanting to turn off pool?

The issue is very old, so at the risk of no response, I will be closing this. But please reopen if it's still an issue.

**Comment by beltschatsar** [comment]
Wish to reopen this issue since it seems needed for issue #2660

**Comment by beltschatsar** [comment]
Would rather need the driver's pool instead of just turning it off so will create a specific issue for that instead.

**Comment by elhigu** [comment]
Turning off the pool would be automatically supported if we allow to select used connection for knex instance. In that case one could just use driver directly to get connections and then run queries against the connections that one is creating / releasing by oneself.

This issue is too vagueto be reopened.
