### ISSUE TITLE
Migrations Issue

### ISSUE THREAD

**Issue by iammerrick** [tgriesser/knex#1061]
``` javascript
exports.up = function(knex, Promise) {
  return knex.schema.table('texts', function (table) {
    table.integer('document_id').unsigned().references('id').inTable('documents');
  }) 
};

exports.down = function(knex, Promise) {
  return knex.schema.table('texts', function (table) {
    table.dropColumn(['document_id']);
  });
};
```

This reports the error: 

_Knex:warning - migrations failed with error: The column document_id is not in the texts table_

This is using version 0.9

**Comment by rhys-vdw** [comment]
Are you sure the column doesn't exist?

**Comment by iammerrick** [comment]
Positive. :-) I am using sqlite if that means anything.

**Comment by chrisbroome** [comment]
What does your `knexfile.js` look like? knex migrations use the environment variable `NODE_ENV` to select which config in the `knexfile` to run. If unspecified, `NODE_ENV=development`. So if you don't have a key in your `knexfile` that corresponds to your `NODE_ENV`, it won't work.

I mention this because you might be looking at a database file that was specified in a different environment. Just a thought.
