### ISSUE TITLE
Knex not working with oracledb(official version) ?

### ISSUE THREAD

**Issue by sivacreatives** [tgriesser/knex#1071]
Hi,

Knex only supports unofficial version of oracle (https://github.com/joeferner/node-oracle). This unofficial version cannot be installed correctly and not supported any more.

Is there any ways to use official version of oracle (https://github.com/oracle/node-oracledb) with knex ? 
Why knex did not support the official version of oracle ?

**Comment by blah238** [comment]
See https://github.com/tgriesser/knex/issues/646 and https://github.com/tgriesser/knex/pull/990

**Comment by sivacreatives** [comment]
thx i made it working with oracledb

**Comment by mrodrig** [comment]
Just curious why this module is still using the unofficial Oracle driver since it's no longer supported.  I've tried to install the `oracle` module to be able to use `knex`, but it fails because of compilation errors (that appear to be due to a different Oracle Instant Client than expected), but the official driver `oracledb` installs fine.
