### ISSUE TITLE
not full promise interface (queries cannot be used in chains)

### ISSUE THREAD

**Issue by alex-milanov** [tgriesser/knex#1105]
I am trying to chain couple of queries one after another - create table, insert, select ...

I want to create something like this:

```js
createTable()
  .then(insertMockUsers)
  .then(selectUsers)
```

The problem is the .then interface is not acting like a promise interface.

Currently I can do this:
```js
var selectUsers = knex.select().from("users");
selectUsers.then(...)
```
`knex.select().from("users")`  creates knex query object and 
`.then` both executes the query itself and allows us to chain things afterwards. 
Looks like a promise interface, but it's not. 
You can only chain things afterwards but not the action `selectUsers` itself as it is not a promise.

My current solution is a `promisifyKnexQuery` function:
```js
function promisifyKnexQuery(knexQuery){
  return function(){
    var deferred = Promise.pending();

    knexQuery.then(function(result){
      deferred.resolve(result);
    },function(err){
      deferred.reject(err);
    })

    return deferred.promise;
  }
}
```

which can be used like this:
```js
var insertUsers = promisifyKnexQuery( knex("users").insert(mockUsers) );

createTable().then(insertUsers).then(selectUsers)

```

The solution for a proper promise interface is to implement a `toPromise()` method. Which would return a promise function that can be used both to start promise chain and be used inside a promise chain.

```js
var insertUsers = knex("users").insert(mockUsers).toPromise();
```

**Comment by tgriesser** [comment]
Yep, I'm going to fix this before 1.0 by making the backing data for the query chain immutable and throwing if the query is mutated after the promise is executed. Otherwise you'll want to use the `.clone` method to re-use query partials.

**Comment by tgriesser** [comment]
See also #966

**Comment by rhys-vdw** [comment]
Workaround:

```js
var selectUsers = () => knex.select().from("users");

createTable()
  .then(insertMockUsers)
  .then(selectUsers)
```

**Comment by raijinsetsu** [comment]
The promise-like functionality used by transactions is even worse and leads to a hang in my TypeScript application.  Here is an example:

```
let session = {
    commit = (txn: Knex.Transaction) => Promise<void> {
        if (!this._commitPromise) this._commitPromise = txn.table('session').insert(...);
        return this._commitPromise;
    }
};

let token = {
    session: session,
    commit: (txn: Knex.Transaction) => Promise<void> {
        if (!this._commitPromise) {
            this._commitPromise = this.session.commit(txn)
                .then(() => {
                    return txn.table('session').insert(...);
                });
            });
        return this._commitPromise;        
    }
};

```

The intent of the logic is to:
1. prevent multiple concurrent commits of the same model
2. allow committing the session indepedent of the token
3. committing the session automatically, if not already done, when committing the token

The following works:
```
knex.transaction((txn) => {
    return token.commit(txn);
});
```

This does not:
```
knex.transaction((txn) => {
    return session.commit(txn);
});
knex.transacation((txn) => {
    return token.commit(txn);
});
```

The "promise" for the session, although resolved, does not invoke the new "then" clause added by the independent token commit.

To fix this issue, I have had to wrap all of the Knex promise-like stuff in another real promise like so:
```
let session = {
    commit = (txn: Knex.Transaction) => Promise<void> {
        if (!this._commitPromise) {
            this._commitPromise = new Promise<void>((resolve, reject) => {
                txn.table('session').insert(...).then(resolve).catch(reject);
            });
        }
        return this._commitPromise;
    }
};
```

**Comment by elhigu** [comment]
@raijinsetsu `QueryBuilder` instance is not a promise, but it is a thing called `thenable` (check terminology in https://github.com/promises-aplus/promises-spec)... So your `.toPromise()` is currently actually the same that `QueryBuilder.then`.

One big difference between promise and thenable is that thenable does not have to be triggered already. If you have promise it is already running its code to resolve its status... so builder pattern is not really possible to be implemented if every query builder instance would be promise.

For the converting `QueryBuilder` instance to promise, one may use e.g. `Promise.resolve()` (from Promise specification).

e.g.
```js
let session = {
    commit = (txn: Knex.Transaction) => Promise<void> {
        if (!this._commitPromise) this._commitPromise = Promise.resolve(txn.table('session').insert(...));
        return this._commitPromise;
    }
};
```

Btw. using `commit` word to tell that insert query is sent to DB was really confusing to me... It took me a while to understand that you actually were not committing transaction when calling `.commit(txt)`, but only storing data do DB :)

That being said. If this fundamental API is being changed hopefully old API is stabilized to 1.0 before creating Knex 2.0 with new design (otherwise every single knex app will break in that update).

**Comment by elhigu** [comment]
https://github.com/knex/knex/pull/2226#issuecomment-329589115
