### ISSUE TITLE
error: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by feesjah** [tgriesser/knex#1136]
I'm getting this error running knex 0.9.0 on heroku
 ```Jan 13 02:11:53 fixtrack app/web.1: [0] Knex:Error Pool2 - error: remaining connection slots are reserved for non-replication superuser connections 
Jan 13 02:11:53 fixtrack app/web.1: [0] Knex:warning - Pool2 - Error: Pool was destroyed 
Jan 13 02:11:53 fixtrack app/web.1: [0] Unhandled rejection Error: Pool was destroyed 
Jan 13 02:11:53 fixtrack app/web.1: [0]     at Pool._destroyPool (/app/node_modules/knex/node_modules/pool2/lib/pool.js:536:20) 
Jan 13 02:11:53 fixtrack app/web.1: [0]     at Pool.<anonymous> (/app/node_modules/knex/node_modules/pool2/lib/pool.js:458:18) 
Jan 13 02:11:53 fixtrack app/web.1: [0]     at Pool.<anonymous> (/app/node_modules/knex/node_modules/pool2/lib/pool.js:493:17) 
Jan 13 02:11:53 fixtrack app/web.1: [0]     at tryCatcher (/app/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23) 
Jan 13 02:11:53 fixtrack app/web.1: [0]     at Promise.errorAdapter (/app/node_modules/knex/node_modules/bluebird/js/main/nodeify.js:36:34) 
Jan 13 02:11:53 fixtrack app/web.1: [0]     at Promise._settlePromiseAt (/app/node_modules/knex/node_modules/bluebird/js/main/promise.js:579:21) 
Jan 13 02:11:53 fixtrack app/web.1: [0]     at Promise._settlePromises (/app/node_modules/knex/node_modules/bluebird/js/main/promise.js:697:14) 
Jan 13 02:11:53 fixtrack app/web.1: [0]     at Async._drainQueue (/app/node_modules/knex/node_modules/bluebird/js/main/async.js:123:16) 
Jan 13 02:11:53 fixtrack app/web.1: [0]     at Async._drainQueues (/app/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10) 
Jan 13 02:11:53 fixtrack app/web.1: [0]     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14) 
Jan 13 02:11:53 fixtrack app/web.1: [0]     at processImmediate [as _immediateCallback] (timers.js:374:17) ```

Is there something I should be doing to avoid this error? like closing connections ? I have set my pool to 20, is that too much ?

**Comment by elhigu** [comment]
The error message says it all. "Remaining connection slots are reserved...."

https://devcenter.heroku.com/articles/concurrency-and-database-connections#maximum-database-connections

Heroku hobby tier has limit of 20 connections, maybe you have more instances running, which uses those connections too or if you have some separate connection with other sql client at the same time or something like that. 

Of course it is possible that there is offbyone error somewhere... you may try to lower max connection amount to 19.

**Comment by feesjah** [comment]
Alright thanks, that gives me some peace of mind, I thought that might have been the case, but still found it strange that I had the error since the connections count was set to 20. But it makes sense that it might have been caused by running some other task on the db from the terminal. Just wanted to make sure, thank you :)

**Comment by BionanoDev** [comment]
We are have trouble with this error and PostgresQL.    

Our testers can sit one one page and just refresh a bunch of times then the error happens.   

We have tried adjusting the min/max settings for the pool, but nothing is changing.

**Comment by elhigu** [comment]
@BionanoDev if you can provide way to reproduce your problem, we might be able to help

**Comment by rossPatton** [comment]
I am also having this issue. I am using postgres via digitalocean, which has a way higher connection limit than heroku. The app has little to no traffic (is under active alpha development).

Since the database is under very active development, tables changing constantly, I've just been destroying and seeding a new one every now and then.

After a recent deployment, the site now immediately crashes, and I get this error. According to pgbench, I have _150_ active connections. Which is absolutely insane.

My guess is that my connections are never being closed. I'm no postgres expert, clearly, but this seems pretty wild.

Unfortunately, it's not clear to me whether this issue is coming from knex, my app, or digitalocean, so i'm trying to investigate. Digitalocean community boards tend to think this error is caused by either bots, or by an app not closing the connection. But this issue leads me to believe that knex should close connections automatically if the server goes down or restarts?

**Comment by elhigu** [comment]
Maybe you have multiple application instances running. Knex should never use 150 connections if pool has lower limit than that. Usually this kind of errors are caused because of combination of too big pool max limit and code that doesn't handle transactions propertly (if transactions are no committed / rolled back, then connections are not released to the pool). You can check out pool stats from inspecting `knex.client.pool`. Documentation for pool methods are found here https://github.com/vincit/tarn.js/

**Comment by dpankros** [comment]
I just ran into something similar.  In my case, I was using Apollo and each datasource (the part that accesses knex) was RECREATING knex each time, rather than using the existing knex instance.  Once that was switched most of the issues went away.  I had a couple other small issue unrelated to knex (read: irrelevant for this discussion) that needed to be fixed too.

More detailed explanation: The SqlDataSource constructor was passed the knex configuration _instead of_ the knex _instance_.  This caused each datasource to recreate knex and the pool, allowing for connections open the order of (pool size) * (# of datasources).  We have numerous SqlDataSources so the problem was compounded as the datasources are recreated on each graphql query.
