### ISSUE TITLE
Update Lodash dependency from v3 to v4

### ISSUE THREAD

**Issue by o100ja** [tgriesser/knex#1214]
The lodash file structure has been changed making the following lines break with an error:
```MODULE_NOT_FOUND,Cannot find module 'lodash/object/assign'```
So basically the problem as I see it is deep require statements similar to:
```var assign = require('lodash/object/assign');```
Not sure why this these weren't like more like:
```var assign = require('lodash').assign;```
in the first place but here is an idea where to start.

**Comment by rhys-vdw** [comment]
When you require the file directly (`lodash/object/assign`) only that file is included in the project. This reduces the overall size of the webpack build of knex, designed to be run in browser. This is particularly true of lodash v4, which I understand has been restructured to reduce the amount of code included per module.

Since the file structure is considered part of the API, for this reason, I think it's unlikely that you'll find that it's broken on in v3, which is the current version used by Knex.

Upgrading to version 4 would be good, and will involve updating each of these import statements, and also checking each method invocation to check that the new functions are being used (there have been many changes to the API). If someone is willing to take on this task I ask that `require` be replaced by `import` in all places where possible.

**Comment by o100ja** [comment]
Thanks for the info, regarding the footprint constraint, as I mentioned in Gitter it makes sense.
But if that is the case I've found 31 occurrences of ```var _ = require('lodash');``` in the knex/lib dir. where some of them are redundant (eg. /lib/raw.js). Maybe these can be modified as well to accommodate the constraint.

If I find the time in the next couple of weeks I'll address the issue but I can't make any promises. 
Except when coding ;)

**Comment by rhys-vdw** [comment]
Ha ha no problem. Yeah, it achieves nothing unless the imports are partial
in every instance. I guess some contributors do this out of habit and some
do not. My preference is to use individual function imports.
