### ISSUE TITLE
How to use the knex Schema Builder?

### ISSUE THREAD

**Issue by skleeschulte** [tgriesser/knex#1219]
I need some advice on using the Knex.js Schema Builder. I want to use the promise interface and I'm familiar with how promises work. However it is not clear to me how the Schema Builder uses promises and how it generally works. I don't understand it from reading the docs, and googling didn't help either. Some of the following examples/questions might be redundand...

**(1) What is the correct way of chaining Schema Builder methods (like createTable)?**

```
// (a):
knex.schema.createTable('table1', ...);
knex.schema.createTable('table2', ...);

// (b):
knex.schema.createTable('table1', ...).createTable('table2', ...);

// (c):
knex.schema.createTable('table1', ...).then(() => {
    knex.schema.createTable('table2', ...);
});

// (d):
knex.schema.createTable('table1', ...).then(schemaBuilder => {
    return schemaBuilder.createTable('table2', ...);
});

// (e): another way?
```

**(2) When will which changes actually be written to the database?**

```
// (a):
knex.schema.createTable('table', ...);
```

Is anything written to the database, or is it necessary to "commit" the changes? If committing is necessary, how? (By calling `then` (e.g. `knex.schema.createTable('table', ...).then(r => r);`)?)

```
// (b):
knex.schema.createTable('table1', table => {
    table.increments('id');
}).then(() => {
    knex.schema.createTable('table2', table => {
        table.increments('id');
    });
});
```

In which order will the tables be created and the columns be added? Will the second table be created at all?

```
// (c):
knex.schema.dropTable('table').then(r => r);
knex.schema.createTable('table', ...).then(r => r);
```

Will the drop table statement be executed twice?

**(3) Is it necessary/possible to reset the Schema Builder?**

I ask because one always works with the same Schema Builder "instance" instead of doing something like `new knex.schema()`.

**(4) Is there a way to output the generated SQL as a string instead of sending it to the database?**

I think this would help me to understand what the Knex.js Schema Builder is doing.

**Comment by wubzz** [comment]
1) I generally go by method B because its a lot easier to read. There's no "correct" way, just personal preference imo.

2) The moment you call `.then` the active querybuilder's query will be run. That's why in example C) of 1) you had to return a new `knex.schema.createTable(..)`, as in a new query builder instance.

3) I'm not sure on a use case of resetting the builder _(I can't swear, but I don't think it exists currently)_, but basically doing what you did in C) 1) is one way of doing it, instantiating a new query builder. Neccessary ? Definitely not. See B) 1)

4) You can always call `.toString()` or `.toSQL()` **before** running `.then` to see the generated SQL. Example:
```javascript
console.log(
	knex.schema.createTable('test', function(table) {
		table.specificType('test', 'smallint')
	})
		.createTable('test2', function(table) {
			table.string('test', 50);
		}).toString()
);
//create table "test" ("test" smallint);
//create table "test2" ("test" varchar(50))
```
An alternative to this is the `debug` config flag, and also the `query` event.

**Comment by skleeschulte** [comment]
Tanks @wubzz!! This already helps a lot! But there is still some behaviour that I don't understand or at least don't see documented anywhere. Here is an example:

    // (i):
    const promise1 = knex.schema.createTable('table1', () => {});
    const promise2 = knex.schema.createTable('table2', () => {});
    promise1.then(() => promise2);

With `debug: true` this produces the following output:

    [ { sql: 'create table "table1" ()', bindings: [] } ]
    [ { sql: 'create table "table2" ()', bindings: [] } ]

With a slight modification, this behaves differently:

    // (ii):
    const schemaBuilder = knex.schema;
    const promise1 = schemaBuilder.createTable('table1', () => {});
    const promise2 = schemaBuilder.createTable('table2', () => {});
    promise1.then(() => promise2);


With `debug: true` the console now reads:

    [ { sql: 'create table "table1" ()', bindings: [] },
      { sql: 'create table "table2" ()', bindings: [] } ]
    [ { sql: 'create table "table1" ()', bindings: [] },
      { sql: 'create table "table2" ()', bindings: [] } ]

(In addition an error is thrown, complaining because table1 already exists.)

Obviously there must be some "property getter magic" for `knex.schema`. Is this documented somewhere? Do I get a new Schema Builder whenever I access `knex.schema`?

It looks like I can do all my changes to one Schema Builder:

    // (iii):
    const schemaBuilder = knex.schema;
    schemaBuilder.createTable('table1', () => {});
    schemaBuilder.createTable('table2', () => {});
    schemaBuilder.then(() => {});

And this assures that the SQL commands are executed in the right order?

Or I can create independent Schema Builder promises and have to make sure that they run in the right order myself:

    // (iv):
    const actions = [
        knex.schema.createTable('table1', () => {}),
        knex.schema.createTable('table2', () => {})
    ];
    bluebird.reduce(actions, () => {});

Can you/anyone confirm this and/or point to some documentation about this?

**Comment by wubzz** [comment]
@skleeschulte In `//(ii)` you are using the same querybuilder for both declarations, which means both declarations add to the generated sql. In short, this means it will generate two CREATE TABLE statements for that particular querybuilder instance, which you are then running twice by using `.then(() => promise2)`. The `//(i)` would be the better approach for what your example is doing as it creates two separate querybuilders, one for each table. See here for reference how knex handles this:
https://github.com/tgriesser/knex/blob/master/src/util/make-knex.js#L96
https://github.com/tgriesser/knex/blob/master/src/client.js#L72

I would still promote using a single chained querybuilder with `.createTable(.., ..).createTable(.., ..)`.

`//(iii)`: Yes. The order of the SQL should be as you chain calls to the schemabuilder.

`//(iv)` There is nothing stopping you from using bluebird or any other promise library to run several knex querybuilders at once, in fact I would even dare to promote it. For example Bluebird's `map` in conjunction with `spread` can be handy at times.


The key thing here is that calls to `knex.schema` will generate a new querybuilder instance, separating you from your existing querybuilder. There is seldom a good reason to do this, it's in my personal opinion better to use the same instance to ensure the query order and it provides cleaner code by only running one promise rather than a promise per created table.
