### ISSUE TITLE
format of date

### ISSUE THREAD

**Issue by fsebbah** [tgriesser/knex#1225]
Hi,
I have a query with 2 dates at the format "YYYY-MM-DD". In the table, the field is stored on the format "YYYY-MM-DD HH:mm"
If I build my query with:
.whereBetween(date,[date1,date2])
knew return 0 rows

If I try with:
.whereBetween(date,['%'+date1+'%','%'+date2+'%'])
The result is the same

If I want force the format of the field:
.whereBetween("date_format(date,'%Y-%m-%d')",[date1,date2])
I have an message of error:
_Unhandled rejection Error: select `id`, `employee_id`, `category_id`, `days`, `label`, `date`, `date_end` from `event_view_abs` where `date_format(date,'%Y-%m-%d')` between '2016-02-17' and '2016-02-18' and `parent_id` in (2, 50) and `cb_pointage` = 1 order by `employee_id` asc, `date` asc - Unknown column 'date_format(date,'%Y-%m-%d')' in 'where clause'
_
Thanks for your help.
Franck

**Comment by thedevkit** [comment]
[Moment.js](http://momentjs.com/) is your friend.

```
whereBetween('date',
        [ (moment().subtract(ageBounds[1] + 1, 'years').add(1, 'day').format('YYYY-MM-DD')),
          (moment().subtract(ageBounds[0], 'years').format('YYYY-MM-DD')) ]
      )
```

**Comment by fsebbah** [comment]
Hi,
Thanks for your response, At the begining I tried with moment but the problem was the same.
Sample: date1= '2016-02-29' 
date2= '2016-03-05'
whereBetween['birthday',moment(date1).format('YYYY-MM-DD'),moment(date2).format('YYYY-MM-DD')]
In your sample, if we define int1='2016-02-29'  and int2='2016-03-05'
The result is : 2016-03-08 and 2016-03-07. Not the dates defined??
Thanks,
Franck

**Comment by fsebbah** [comment]
Hi,
I change my code and I integrated your comment:
                    .whereBetween('date',[moment().subtract(date3, 'years').add(parseInt(diffDays)*-1, 'day').format('YYYY-MM-DD'),moment().subtract(date3, 'years').add(parseInt(diffDays2)*-1, 'day').format('YYYY-MM-DD')])
But the problem is the same.

If the sql include only one date:
.andWhere('date','%'+args[2]+'%')
It's ok.
I think, there is a problem with date and whereBetween.
Thanks,
Franck

**Comment by wubzz** [comment]
@fsebbah Can you give us a more detailed example? For example the exact code you are using, and also the database rows that you are trying to select. Reading the comments in this issue I'm having a hard time understanding what the problem is here.

Since the column isn't just a date column, but also contains HH:MM:ss, a 'Between' can be hard to understand. I'll give you a few examples:

Let's say I have two database rows with the following dates:
```javascript
2016-03-07 10:00:00
2016-03-10 12:00:00
```

This will return both rows:
```javascript
db('test')
	.whereBetween('date', ['2016-03-07', '2016-03-11'])
	.select()
```

This will only return one row:
```javascript
db('test')
	.whereBetween('date', ['2016-03-07', '2016-03-10'])
	.select()
```
Because 2016-03-10 defined as the "end" point of the between clause, is less than 2016-03-10 12:00:00.

This will not return any rows:
```javascript
 db('test')
	.whereBetween('date', ['2016-03-07 11:00:00', '2016-03-10 11:00:00'])
	.select()
```
Because the starttime is greater than 10:00:00 and the end time is less than 12:00:00.

I believe you're experiencing strange resultsets because you are ignoring the HH:mm:ss. If you do not want to take HH:mm:ss into consideration, then your best bet is to append 00:00:00 to the start date, and 23:59:59 to the end date. 

Like so:
```javascript
.whereBetween(date, [date1 + ' 00:00:00', date2 + ' 23:59:59'])
```


To your point about `date_format(date,'%Y-%m-%d')` throwing an error, you are getting that error because knex will treat the first parameter as a valid column. If you still want to use this method, then you can try using raw.
```javascript
.whereRaw('date_format(date, \'%Y-%m-%d\') BETWEEN ? AND ?', [date1, date2])
```

I feel like I'm rambling quite a bit in this reply, but please supply us with proper information so we can assist you further. While Momentjs is an outstanding library, I see absolutely no reason why it would be needed here.

**Comment by fsebbah** [comment]
Hi Wbuzz, 
Thanks for your response.
I read your message and I test your solutions. I send you my feedback after.
Franck

**Comment by fsebbah** [comment]
Hi wubzz,
This solution works : .whereRaw('date_format(date, \'%Y-%m-%d\') BETWEEN ? AND ?', [date1, date2]).
It was very hard for me to understand how work with date format.
I won many days thanks to you.
