### ISSUE TITLE
Knex migration fails to migrate database

### ISSUE THREAD

**Issue by teckays** [tgriesser/knex#1234]
`knex migrate:latest` throws an error:

```
Knex:warning - migrations failed with error: create table "table_name" ("id" serial primary key, "email" varchar(255), "createdDate" timestamptz) - relation "table_name" already exists
error: create table "table_name" ("id" serial primary key, "email" varchar(255), "createdDate" timestamptz) - relation "table_name" already exists
```

It's true that the table exists, but doesn't it has to drop before running the migration?

```
exports.up = function(knex, Promise) {
  return Promise.all([
    knex.schema.createTable('table_name', function(table){
      table.increments('id').primary();
      table.string('email').unique();
      table.dateTime('createdDate');
    }),
  ])
};

exports.down = function(knex, Promise) {
  return Promise.all([
    knex.schema.dropTableIfExists('table_name')
  ])
};
```

**Comment by whytheday** [comment]
Why don't you use [createTableIfNotExists](http://knexjs.org/#Schema-createTableIfNotExists)? Also, seems kind of strange you would create the table outside of the migration script and then try to create it again in the script. If you are trying to test the migration you should use "knex migrate:rollback" to call the down portion of the migration.

**Comment by teckays** [comment]
@whytheday 
> Also, seems kind of strange you would create the table outside of the migration script ...

I'm not creating it outside, I just run different migrations, let's say I have my base schema file, then create another migration file with schema updates, change a field type for example, and the migration fails because the table already exists, I'm not creating the tables manually, it's just different migrations files applied and the tables don't drop when upgrading the schema.

> If you are trying to test the migration you should use "knex migrate:rollback"

doesn't `rollback` resets the previous migration?

**Comment by rhys-vdw** [comment]
> I'm not creating it outside, I just run different migrations

If you're modifying an existing table you should use `knex.schema.table`[http://knexjs.org/#Schema-table].

> doesn't rollback resets the previous migration?

Yes.

**Comment by Chinyeins** [comment]
Hi, i´m having problems with migrate:rollback. Seems not to bee working. it says already at the base migration & don not drop tables specified in the down method

heres my migration:
`
exports.up = function(knex, Promise) {
    return Promise.all([
        knex.schema.createTable('users', function (table) {
            table.increments('id').primary();
            table.string('username');
            table.string('password');
            table.string('email');
            table.string('name');
            table.timestamp('date');
        }),

        knex.schema.createTable('points', function (table) {
            table.integer('user_id');
            table.integer('xp');
        }),

        knex.schema.createTable('settings', function (table) {
            table.integer('user_id');
            table.json('settings');
        })
    ]);
};

exports.down = function(knex, Promise) {
    return Promise.all([
        knex.schema.dropTableIfExists('users'),
        knex.schema.dropTableIfExists('points'),
        knex.schema.dropTableIfExists('settings')
    ]);
};
`

**Comment by Chinyeins** [comment]
how can i quote the code ?  the code button dont work ... jesus

**Comment by elhigu** [comment]
@Chinyeins Check `migrations` table in your DB. There is listed every migration that has been ran for your DB.

Only those migrations which has been applied to your DB can be rolled back... there is no command in knex which would allow you to tell to rollback certain migration file.

If you have some strange tables because of typos etc. use your SQL console to fix them.

**Comment by teckays** [comment]
@elhigu I don't think that using SQL console, specially in a production environment, is something we'd like to have. I might be wrong but I'm used to how Django handles schema migrations, as long as you create a new migration file it will always apply no matter what, it will know to alter table/column and to the necessary changes, renaming, change field type, dropping etc. Would be really nice to have this on with knex too.

**Comment by elhigu** [comment]
@teckays If you need to fix you DB by hand, even in production you are probably going to need SQL console access (ofc would be better to get DB dump from production, create migration and update production with migration that fixes stuff). 

This time I suggested it, because @Chinyeins did need to find out why migrations were not working as he/she (can't tell from the profile pic which one) thought they would. It is not the normal procedure with knex, just needed to resolve why this stuff is happening.

About how django does things, `Knex` is not a framework neither it is an ORM, so it is not issue of knex when migrations are applied to DB. I believe its responsibility of ORM or framework which should tell when migrations are run.

> as long as you create a new migration file it will always apply no matter what, it will know to alter table/column and to the necessary changes, renaming, change field type, dropping etc. Would be really nice to have this one with knex too.

Yep, there is at least one issue about that feature, that would be nice :+1:

**Comment by Chinyeins** [comment]
Hi guys, i now fixed the problem by just making a migrate:latest and after that migrate:rollback.

If I have enough time, I'll try to set migrate tables into knex config and do it again. 

Tanks for respond. 

Its he by the way - Bifi is maskulin, which girl would use a wiener as profile pic, but never mind. 

:D
