### ISSUE TITLE
value of boolean column selected is not true or false in mysql?

### ISSUE THREAD

**Issue by chenweiyj** [tgriesser/knex#1240]
I use boolean to create the table schema by knex. However, when I do `knex('table').select()`, I cannot check it with true or false. It returns 0 or 1. 

Is it possible to check it with true of false? Otherwise, each time I check the boolean field, I have to write two check expressions like `filedA === false || filedA === 0`.

**Comment by wubzz** [comment]
@chenweiyj Sorry for the late reply. This is not a knex issue as this is how the underlying `mysql` driver handles the response. You can find them [here](https://github.com/felixge/node-mysql).

To answer your question, the mysql driver supports a configuration property called `typeCast`. With this function you can convert values based on database datatypes automatically, without having to do it elsewhere in your code. I built an example for you based on their documentation *(I personally don't work with mysql):*

```javascript
var db = require('knex')({
client: 'mysql',
connection: {
host: 'localhost',
user: 'mysql',
password: 'mysql',
database: 'mysql',
typeCast: function(field, next) {
	if (field.type == 'TINY' && field.length == 1) {
		return (field.string() == '1'); // 1 = true, 0 = false
	}
	return next();
}
}
});
```

Note that this will apply to *all* fields on *all* tables on *all* queries using this connection.

Alternatively, you can just use `!fieldA` instead of `fieldA === false || fieldA === 0`. In JavaScript, `0` is faulty, and `1` is truthy, so you don't have to check for both.

**Comment by chenweiyj** [comment]
@wubzz Thank you. It helps.

**Comment by GabeAtWork** [comment]
For future reference, I have found `typeCast` is not called for sqlite databases, at least as far as I could see.

I tried to apply this `typeCast` function on my databases. It works for dev/prod dbs as they are mySQL, but it doesn't for sqlite, as the `typeCast` function doesn't even seem to be called.

I've opened an issue about it: #2170

**Comment by MartinMuzatko** [comment]
Does that also work for setting values?

I want to use `true` and `false` when working with knex, not 0 and 1.

**Comment by FabianTe** [comment]
Is `typeCast` even supported anymore?

**Comment by MartinMuzatko** [comment]
knex doesn't care whether or not you use 1/0 or true/false when saving. But reading is mostly different.
Like dates should be cast to a `new Date`, and numbers to `Number`, BOOLEAN tinyint should be true or false.

**Comment by elhigu** [comment]
@MartinMuzatko are you saying that knex should do that conversion? Knex does not care how database returns different column types (actually knex doesn't even know anything about column types of the server)... so if your driver likes to return those fields for example as strings, then knex will return them as strings.

**Comment by FabianTe** [comment]
After reading into this and the several database drivers, I am unsure about this.

On one hand it is annoying that I have to manually parse some value types. In the application I am developing, I am exposing database tables via an API generically by using the `INFORMATION_SCHEMA`. For that use case it is annoying that knex.js (or the underlying db drivers) sometimes don't return the expected value type (like in the case of `BIT`, which is a `Buffer` in mysql and a boolean in mssql). Also *in my case* it is not optimal that I have to query the database schema to get the column types, because knex.js does this also, resulting in the same query twice. **So first I thought since I am using knex.js to not have to worry about database specific queries and such, it would also only be logical that knex.js handles type converison.**

But on the other hand, then knex.js would have to assume that all users interpret `BIT` as a boolean value and return it as such. What about users that actually would like to use the `Buffer` returned by the mysql package? No idea why someone would do that, but if knex.js just defined that it will handle `BIT`s as booleans, there might be some conflicts.

Personally, I just implemented a "type conversion layer" on top of my database layer, for all CRUD operations. That works fine but is not optimal because I have to maintain my own type conversion for each database flavor my application needs to support and I am essentially doing the same the underlying libraries already do.

**Comment by elhigu** [comment]
> Also in my case it is not optimal that I have to query the database schema to get the column types, because knex.js does this also, resulting in the same query twice. 

Knex does not query column types separately from DB. Knex just sends the query to database driver and then gets the result that driver gives. Knex doesn't know anything about schema of the database or DB types of returned values. 

> So first I thought since I am using knex.js to not have to worry about database specific queries and such, it would also only be logical that knex.js handles type converison.

I don't know if all the database drivers are returning database types of returned values with query results to knex (at least pg driver does). If that would be true we could setup some hooks to make that value mapping, which would solve part of the problem. In addition to that you would also need to setup your db drivers to not do any automatic conversions to get input values in consistent format (many drivers actually returns timestamps and dates in javascript Date objects, which may cause significant performance issues).

If you like to investigate which drivers actually returns information about db types of returned columns and which drivers supports overriding default type parsers, please open new feature request. With that info we could figure out to provide presets for drivers to behave more compatible way or if that is not enough, also conversion layer is not out of the question.
