### ISSUE TITLE
Redshift client

### ISSUE THREAD

**Issue by krainboltgreene** [tgriesser/knex#1255]
Hello, I've just been through the amazing pain of using the pg client to talk to redshift.

I notice there isn't a redshift client for knex, or maybe I haven't noticed. Since the differences are very fresh in my mind I'd love to help on that.

**Comment by rhys-vdw** [comment]
Yes please! The more the merrier. At some stage we're going to have to break these into different modules... @tgriesser?

**Comment by tjwebb** [comment]
@krainboltgreene have you filed specific issues for pg + redshift? I'm using knex with redshift very successfully.

**Comment by krainboltgreene** [comment]
Here's some examples:

  1. `knex.fn.now()` uses `CURRENT_TIMESTAMP`, but only leader nodes can use that.
  2. `uuid` isn't a data type on redshift, but it still tries
  3. `text` is `varchar(256)`, which is kinda small
  4. `index()`, `unique()`, `primary()` are essentially no-op, but it still tries to do them.
  5. `increments()` doesn't work, no SERIAL data type.
  6. `timestamp()` tries to do `timestamp with zone`, but that doesn't exist on redshift
  7. Not sure where this one goes wrong, but: with Bookshelf.js it tries to use `returning {{idAttribute}}`, but redshift doesn't support this.

I had do quite a bit to get my setup to work, so I'm not sure how you're getting by @tjwebb unless you're *just* running SELECTs.

**Comment by krainboltgreene** [comment]
Honestly if someone pulled pg out into a module I would totally immediately write the redshift one with the changes I detailed here.

**Comment by rhys-vdw** [comment]
It should be fairly straight forward to add a new client extending or
copying the pg dialect in this repo. We can split them out later if
necessary.

**Comment by krainboltgreene** [comment]
I'm not that adept yet at contributing to node projects D:

**Comment by krainboltgreene** [comment]
1. Doesn't seem "solvable" with the current system.
 2. Changed to `character varying(65535)`
 3. Changed to `character varying(65535)`
 4. No idea how
 5. No idea what to do
 6. Fixed
 7. Removed
 8. Switched to `character varying(65535)`
 9. ???

See: https://github.com/tgriesser/knex/pull/1263

**Comment by codechaotic** [comment]
The current postgres client utilizes [pg-cursor](https://github.com/brianc/node-pg-cursor) to handle streaming. Unfortunately due to a bug in this dependency streaming doesn't behave properly and always downloads the full result set before the stream begins. Please see the related [isse](https://github.com/brianc/node-pg-cursor/issues/14) for details.

I believe that instead of extending the current pg client to create a redshift client, a redshift client should be built mostly from scratch using Java Database Connectivity (JDBC) as Amazon recommends in [their documentation](http://docs.aws.amazon.com/redshift/latest/mgmt/connecting-to-cluster.html). I've outlined an implementation in a fork [here](https://github.com/codechaotic/knex).

In order to use it:

 - There is an added dependency on node [JDBC](https://github.com/CraZySacX/node-jdbc).
 - The Java JDK (Version 8 or higher) must be installed. OpenJDK works fine.
 - The Amazon Redshift JDBC Driver must be made available. Currently in the fork I've hard-coded a version and path for this (JDBC 4.2–compatible driver) but it could easily be set as configurable. I did not include the driver in the repository due to terms in the [user-license agreement](https://s3.amazonaws.com/redshift-downloads/drivers/Amazon+Redshift+JDBC+Driver+License+Agreement.pdf) and I believe it ought to be managed as a dependency another way.

My fork still needs tests and such, but I believe the concept is there. Thoughts?

**Comment by krainboltgreene** [comment]
Java as a dependency would be a no-go for my usage.

**Comment by codechaotic** [comment]
What about the ODBC option? There is a node module [here](https://www.npmjs.com/package/odbc) which looks promising. It uses unixODBC which would have to be available in the local environment. No Java though!

**Comment by elhigu** [comment]
https://github.com/tgriesser/knex/pull/2233
