### ISSUE TITLE
Suggestion/question, bulk updates

### ISSUE THREAD

**Issue by vegarringdal** [tgriesser/knex#1271]
Would hav been nice with a bulk updates like we have on bulk inserts

Something like 
knex.batchUpdate(tablename, ids, columns, chunkSize)

ids array and columns array have to be same size or it should throw error.

Is this possible?

**Comment by wubzz** [comment]
@vegarringdal I don't understand why `chunkSize` is needed here. You'd have to run an update query for each individual object, not an array of objects.

The syntax would probably be something like
```javascript
knex.batchUpdate(tableName, [whereFields], [data])
```

A function like this would also have to throw an error if any of the `[whereFields]` are undefined on the data object, since missing a column in a where clause can be deadly. I have nothing against this idea, but I also don't see a big use case for it.

**Comment by vegarringdal** [comment]
True about, didt think about the chucksize param to much last night.

I was thinking one option should be array of primary id's and under data, undefined key should just be skipped.

On first error, just trow error and rollback

Use case, was just a question/suggestion:-)

**Comment by wubzz** [comment]
Perhaps rethinking the API for batch procedures is in order if we're adding another one. If we add `batchUpdate` then there's no reason not to add `batchDelete` as well, using `[data]` with `[whereFields]`. I could see the following be convenient:

```javascript
Previous:
knex.batchInsert(tableName, data, chunkSize);

New:
knex.batch(tableName, data).Insert(chunkSize);
knex.batch(tableName, data).Update([whereFields]);
knex.batch(tableName, data).Delete([whereFields]);
```

@rhys-vdw What do you think about this?

**Comment by vegarringdal** [comment]
@wubzz 

Will I be able to do something like this then, and it skips the undefined under data keys?
And if whereFields is undefined it inserts, and sets null values where data is undefined.
Then that could be usefull

```
var data = [
    {
        something: "bladsbla",
        somethingElse: undefined,
        somethingEee: "blasdsbla",
        somethingCool: undefined
    }, {
        something: undefined,
        somethingElse: undefined,
        somethingEee: "dd",
        somethingCool: undefined
    },{
        something:undefined,
        somethingElse:undefined,
        somethingEee:"blasdsbla",
        somethingCool:undefined
    }];

var whereFields = [
    {
        id: "5"
    }, {
        id: undefined
    },{
        id: "4"
    }];


knex.batch('users', data).Upsert(whereFields);

```

**Comment by wubzz** [comment]
@vegarringdal In your `.Upsert()` example, the *UPDATE* query would ignore undefined values *(as far as I know this is intended)*, while the *INSERT* would use `valueForUndefined` defined on a dialect-basis. For postgres this would be `DEFAULT`.

I don't agree with running an insert if whereFields is left undefined in calls to `.Upsert()`. At that point you might as well just use `.Insert` instead of `.Upsert`. The point of an *UPSERT* is to update a row if it exists, otherwise create it.

For this reason I would expect a `TypeError` to be thrown in `.Upsert()`, `.Delete()` and `.Update()` if it is not an array.

**Comment by elhigu** [comment]
Just trying github voting system with that -1 :D This could be kind of nice feature, but I feel (as I feel about bulk insert) that this would be better to be in some knex utility library to prevent knex core being overwhelmed with random helpers...

Also @vegarringdal @wubzz I don't see much use for bulk update / delete / upsert functions, since update / upsert updates rows with just one set of values (same values for one or multiple rows) and delete doesn't take values at all. 

So only thing there is left to do is to code your loop in a way that queries are sent one by one to DB and not created at once and resolved concurrently (since you should use transaction here,  one has to use the same connection for all the queries... so no concurrency here anyways).

**Comment by wubzz** [comment]
@elhigu I can agree a seperate utility module would be nicer, but perhaps we would want to revisit the whole "extending knex" dilemma first? We don't need extend functionality to build these or move `batchInsert`, but it would certainly be beneficial.

I think you misunderstood the `Update` function, as it won't be "one set of values", but rather each object in the `[data]` Array would be updated using the `[whereFields]`. So every property on that object would be set in the database. That way each object has its own *set values*.

```javascript
knex(table)
.where(_(object).pick.apply(this, whereFields))
.update(object);
```

The `Delete` would just be a loop using `[whereFields]`.

**Comment by elhigu** [comment]
@wubuzz I think I got it right, what I meant was that each query done by these new batch functions would contain just one set of values to update with each of the DB queries that batch function does... effectively these new helpers are just loops for running multiple queries in the same transaction. 

So all these new ones (update, upsert, delete) could be implemented with a generic batch function:
```js
knex.batch(values, queryGeneratorFunction, [batchSize]);
```

where `queryGenerator(trx, values)` returns Promise / thenable which could be resolved with `Promise.resolve()` before continuing to send next value. BatchSize was added there to e.g. be able to write delete, which takes 100 ids in one batch and creates `delete().whereIn(...)` etc.

Anyways I don't have strong opinion about this matter, just preference to have something that is enough generic or nothing at all.

**Comment by luc0** [comment]
Meanwhile, I have done my own gist for that:
[https://gist.github.com/luc0/6da72d2ea4d8c599b8e838ebe1e9a18e](https://gist.github.com/luc0/6da72d2ea4d8c599b8e838ebe1e9a18e)
I have to add parameter binding

**Comment by noosxe** [comment]
Is there any progress related to bulk update ?
What is the recommended way of doing bulk updates with knex ?

**Comment by wmhafiz** [comment]
i would like to know as well!

**Comment by elhigu** [comment]
@noosxe there has been no progress with this and IMO this is out-of-scope feature for knex, since it really only loops over multiple update commands. I recommend to use some higher level library than knex (or if someone likes to create knex-utils library or something like that, it would be good solution too).

Closing as out-of-scope.
