### ISSUE TITLE
Separate knex object with connection pool for non-transaction queries? 

### ISSUE THREAD

**Issue by wsieroci** [tgriesser/knex#1273]
Hi,

as far as I know every transaction is using one connection from the pool until transaction commits or rollbacks. If number of standing transactions equals maximal number of connections in the pool then non-transaction queries cannot be executed and they have to wait for connection. I am wondering if it is good idea to have two separate knex objects (and connection pools) for connecting with database. One for transactions and one for non-transaction queries. What do you think? I see this problem in circumstances when we have many users using simultaneously our service (lets say 1000) and if only small number of them is doing active standing transaction requests (lets say 10) then the rest has to wait. Is it correct? 

Cheers,
Wiktor

**Comment by elhigu** [comment]
@wsieroci I have been thinking about adding `maxConcurrentTransactions` value to prevent transactions from hogging all the connections...  

I think your idea sounds viable for now, since there is no official support for this in `knex`. Nothing prevents you from doing 2 separate pools / knex instances to handle this situation.

**Comment by wsieroci** [comment]
Yeah, I think it is quite good idea to have setting value like that.
