### ISSUE TITLE
If it's NULL, let it be NULL

### ISSUE THREAD

**Issue by teh-botol** [tgriesser/knex#1276]
I have NULL data in DATE column. But when fetching using bookshelf (using knex), it's return `Thu Jan 01 1970 07:00:00 GMT+0700 (SE Asia Standard Time)` equal to `new Date(null)` or `new Date(0)`.

After checking knex@0.10.0, I found `parseType` function:

```
// file: .\knex\lib\dialects\maria\index.js
// line: 117
function parseType(value, type) {
  switch (type) {
    case 'DATETIME':
    case 'TIMESTAMP':
      return new Date(value);
    case 'INTEGER':
      return parseInt(value, 10);
    default:
      return value;
  }
}
```

In regards to NULLABLE column type. IMHO, it's should respect the NULL data.

But with `parseType` function above, if the data is NULL will produce:
- start of javascript Date Object for DATETIME and TIMESTAMP
- and `NaN` for Integer

**Comment by elhigu** [comment]
IMO datetimes / timestamps should be returned as strings so that user can decide if he wants to convert them to  JavaScript Date objects. However that change would probably break too many clients so probably better to leave that conversion there...

Anyways converting `NULL` really sounds like a bug. Some simple test case + PR to fix it would be nice.

**Comment by wubzz** [comment]
Worth checking is also if other dialects handle dates the same way, since your case is `maria`.

**Comment by wubzz** [comment]
I tried looking at this here: https://github.com/tgriesser/knex/pull/1308/files

Would have expected that to work, but it did not. Currently no env to debug maria so I'm leaving this until I can get one setup.

**Comment by peteallen** [comment]
I have a scenario where I'm inserting into a table in postgres with a nullable jsonb column. If I set the property to null in object I'm inserting with knex, it creates the record with an empty object (`{}` instead of `NULL`) in the jsonb column in postgres. Is this the same issue you're discussing here, or something different?

**Comment by rhys-vdw** [comment]
@peteallen could you share the generated query?

**Comment by peteallen** [comment]
Nevermind, my mistake. It didn't occur to me until I was putting together a simplified example to share, but I was doing "falsy coalescence" under the bad assumption that an empty object is falsy, e.g. 

```
knex('organization').insert({
  name: 'Test organization',
  options: options || null
});
```  

where `options` apparently can be an empty object (and, as I've learned, an empty object is truthy).

**Comment by offlinehacker** [comment]
The same bug is so mysql and mysql2

**Comment by apateiro** [comment]
I was having the same problem getting NaN when retrieving NULL from INTEGER fields under Maria 10.1.20 and I was able to solve it by applying the changes proposed by @wubzz on https://github.com/tgriesser/knex/pull/1308/files

Maybe that PR should be revisited. At least its working for INTEGERS.

**Comment by offlinehacker** [comment]
nah, in case of MySQL they are returned as zero strings

**Comment by nesium** [comment]
I just ran into this. What's the official take on this issue? Saving null and fetching a valid date is obviously not the result one would expect.

**Comment by offlinehacker** [comment]
Our solution was to allways put a date, since we had just fields like
createdAt, updatedAt

**Comment by ppinel** [comment]
@wubzz, I tested your fix. It's working when I apply the changes in the `node_modules/knex/lib` directory in one of my projects.
Is this still an issue to be fix?

**Comment by ppinel** [comment]
Well, I am in a rush right now on two projects. I'll try.

**Comment by ppinel** [comment]
@wubzz I tried for more than 1 hour to run test.
I had to skip sqlite3 install, fix lint error (not warning), etc.
I end up with `1) mariadb | mariasql "before all" hook:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.`
I tried several configurations.
If you have a quick fix or point me in the right direction, I'll be ok to continue.

**Comment by FelixButzbach** [comment]
Just stumbled over this problem as well.
Knex returned '1899-11-30T02:00:00' for date fields with null in it from our mariadb database
I "solved" it with the following test:
`let birthday = user.dt_nascimento.toISOString().slice(0,10);
birthday = birthday === "1899-11-30" ? null : birthday;`

This should work because nobody that born in this year will register in our page, or update their data...
Maybe it helps somebody...

**Comment by kibertoad** [comment]
@FelixButzbach Which version of Knex was that? From my understanding this shouldn't be happening if you used mysql driver in any of particularly recent Knex version.

**Comment by FelixButzbach** [comment]
@kibertoad I can't tell for sure, but I think it is with 0.13.0. Also, we use MariaDb if that makes any difference.

**Comment by kibertoad** [comment]
@FelixButzbach Well yeah, I think problem was only reproduceable with Maria :). I assume upgrading is not an option?

**Comment by FelixButzbach** [comment]
@kibertoad I see. We are in a relatively big upgrading process, knex will probably be upgrade as well.
The problem is fixed in the latest version of knex?
As I told in my first comment, I found a good workaround and we are using it ever since...

**Comment by kibertoad** [comment]
@FelixButzbach Yeah, it should be resolved if you switch from maria dialect (which was since removed) to just mysql driver; if you ever decide to do that, I would be grateful if you shared your experience of how that worked out.
Haha, yeah, workarounds are fun, but it's always better not to have them :D

**Comment by FelixButzbach** [comment]
@kibertoad I updated knex to the latest version (0.15.2) and I am now using the mysql driver. The problem is gone!
When a date field is NULL in the database, it is returned as undefined :)

Thanks for all the work!

**Comment by kibertoad** [comment]
You are welcome! Glad it helped :)

**Comment by boutdemousse** [comment]
Using knex 0.16.5, mysql 2.17.1, moment 2.24.0 :
I get the very same issue with `NULL` date values.
Is this bug reappearing out of nowhere ?

**Comment by kibertoad** [comment]
Please check out #3092. Chances are, your db congiguration is to blame, or your column was not created nullable. Check db for triggers created by mysql.

**Comment by boutdemousse** [comment]
Well almost : actually this is a problem with moment.js as I am using a `typeCast` in the configuration.
The `field.string()` returns `null` as it should be so there is no problem on the knex side. 
Thank you for your quick answer !
