### ISSUE TITLE
Binary columns returned as UInt8Array

### ISSUE THREAD

**Issue by raijinsetsu** [tgriesser/knex#1301]
NodeJS has a built-in Buffer object which, to my understanding, allocates memory outside of the interpreter's heap. This means that you can store large amounts of data without running in to the v8 engine's artificial memory limit. Additionally, Buffer out performs the typed arrays in NodeJS (see this article: https://bl.ocks.org/MidnightLightning/7900466).

I'm asking that binary columns are returned as Buffers instead of UInt8Array objects for these reasons. For backwards compatibility, and compatibility with browsers, returning buffers instead of arrays could be controlled by an option on the connection.

**Comment by wubzz** [comment]
Is this really something that knex should handle? I feel like this is something each respective dialect module should take care of. Knex is just a wrapper around the specific dialect, no?

MySQL has its `typeCast` option, and postgres has `pg-types`.

**Comment by raijinsetsu** [comment]
Knex is not just a wrapper. It allows a programmer to operate on all supported dialects in the same way (at least, most of the time). If one driver returns a string for bigInteger columns and another returns a number, then it is Knex that is responsible for converting to a common return type as necessary.

In this case, it seems like some drivers will return Buffers and others UInt8Array objects and Knex should "fix it up". I should not need to have separate branches of logic simply to deal with the discrepancies between drivers - that is what I am using Knex for.

I'm digging through the mysql driver source. The documentation indicates that it returns buffers for binary columns but I can see it is returning UInt8Array objects. If the problem is with the driver, I'll open an issue there. In the mean time, I will pass a typeCast option on the connection object used when initializing the database connection so that I know, for certain, that the return will be a buffer. I didn't realize, until I re-read Knex's documentation several times, that the connection object is passed directly to the driver.

**Comment by wubzz** [comment]
Exactly, Knex provides a unified API that works across all dialects to build queries. Doesn't necessarily mean it should be responsible for driver-specific cases such as parsing datatypes.

Converting to the correct datatypes is such a fundamental part of any driver module that I personally do not feel Knex should be responsible for. My two cents.

**Comment by raijinsetsu** [comment]
How can it be unified if it is not dealing with differences between drivers?

**Comment by raijinsetsu** [comment]
To put it another way: converting to "the correct datatype" is a decision made by the driver's implementer(s). Not all drivers made the same decision for all datatypes and there will be discrepancies. Knex's dialects should handle these discrepancies either by fixing up the driver (like you suggested with the typeCast and pg-types options) or by manipulating the response (probably harder to do).

I haven't dug deeply enough in to the Knex code to find out if it is already doing this for some driver + datatype combinations.

**Comment by elhigu** [comment]
@raijinsetsu As far as I know `knex` does not interfere with types that any of the dialect drivers are returning... some drivers allow changing types as @wubzz  mentioned. 

Hiding all differences between database implementations is a fight `knex` can't win... E.g. native column types depends on dialect and certain query construct are working just with certain dialects, not long ago foreign key cascade couldn't be used with sqlite etc.

Currently converting data types got from DB driver falls to that same category, which is choice of the developer who uses `knex` to decide what dialects are supported by developer's code.

However if someone really could implement some unified type parser API to `knex` which could support all dialects without great overhead I would say go for it :+1:  It might not be as easy as one would thing since conversion cannot be done on `knex` side of code, it must be implemented is each dialect's driver. When dealing with JavaScript values we have already lost the information about the original column type e.g. if original value was bigint or text etc.
