### ISSUE TITLE
createTableIfNotExists generates alter table output which fails

### ISSUE THREAD

**Issue by artyomtrityak** [tgriesser/knex#1303]
I'm using knex 0.10.0, Postgres.

createTableIfNotExists does not create table but adding primary index fails (because it already exist).

How to avoid alter table request if table already exist?

``` js
  db.schema.createTableIfNotExists('users', function(t) {
    t.uuid('id').notNullable().primary();
    t.string('__type', 16).defaultTo('User');
    t.string('email', 100);
    t.string('pass_salt', 32);
    t.string('password_salted', 32);
    t.boolean('verified').defaultTo(false);
    t.json('details');
  })
  .then(() => {});
```

Generates

``` bash
[ { sql: 'create table if not exists "users" ("id" uuid not null, "__type" varchar(16) default \'User\', "email" varchar(100), "pass_salt" varchar(32), "password_salted" varchar(32), "verified" boolean default \'0\', "details" json)',
    bindings: [] },
  { sql: 'alter table "users" add primary key ("id")',
    bindings: [] } ]
Unhandled rejection error: alter table "users" add primary key ("id") - multiple primary keys for table "users" are not allowed
    at Connection.parseE (/usr/src/letsplay/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/usr/src/letsplay/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/usr/src/letsplay/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)
```

**Comment by elhigu** [comment]
That is pretty strange behavior... I checked and there is no documentation how createTableIfNotExist generates schema building queries in its callback also in case when table did exist. At least documentation update would be good to have.

I think that the functionality is correct that callback of schemabuilder is always called in this case, since we are just generating static SQL, which cannot know if the SQL clause will eventually create the table or not.

One way to fix this would be to write query, which checks if the table exists before adding it and all of its columns.

**Comment by artyomtrityak** [comment]
@elhigu another strange thing that i have to pass `.then(() => {});` otherwise knex does not send any request

**Comment by artyomtrityak** [comment]
@elhigu any idea how to avoid dummy `.then(() => {});` ?

**Comment by wubzz** [comment]
@artyomtrityak `.then` and `.asCallback` are what executes the SQL in knex, so you're going to need to run one or the other. Without calling these it's really only building a query.

**Comment by elhigu** [comment]
@artyomtrityak is this happening in migrations? I need more complete example code... maybe you are not returning the query from migration which would cause query to not to be executed?

**Comment by zacronos** [comment]
The issue with `createTableIfNotExists` is already being discussed here: https://github.com/tgriesser/knex/issues/729.

@elhigu I disagree strongly that the callback should always be called; you are thinking from the perspective of the code within knex, not the perspective of someone using knex.  An extremely common use case is to create a table and then add indexes to it.  It is not intuitive for the app code to have to manually check if the table already exists before calling a method named `createTableIfNotExists`.  If that is the correct behavior, then `createTableIfNotExists` is only useful if no additional indexes or other constraints will be added to the table.  At a minimum this counterintuitive behavior needs to be documented, but much more useful would be for knex to check for the table's existence and execute the callback only if the table didn't exist prior.

I understand that requires knex to act at a slightly higher level than simply generating static SQL, but from the perspective of an intuitive/useful library and its expected behavior, that is what is needed.

**Comment by elhigu** [comment]
@zacronos I understand your point that the syntax is not intuitive for new users of `knex`, but if it triggers query without `.then()` for it, it won't be consistent with other parts of `knex`.

Many more advanced users has mind set towards `knex` that it is **query builder** and from that mindset it is perfectly logical that `createTableIfNotExists` just builds almost the same query that `createTable` would do. Anyways that is just a matter of an opinion, documentation would be really needed and asserts that APIs are not used wrong...

Now that I look the error above again the problem seem to be that some of the higher level schema building functions actually creates multiple queries, which are working wrong in case of `createTableIfNotExist`. 

In this particular case the real problem seem to be:
```
{ sql: 'alter table "users" add primary key ("id")', bindings: [] }
```

One way to resolve this problem would be to create different query for constraint generation they are introduced inside `createTableIfNotExist`. Constraints created inside that should also be done conditionally so that they won't fail either when it is ran again. I'm just a bit worried that f we go to that road, it will be really difficult to make work robust way with all kind of constructs which might be implemented currently with multiple queries behind the API.

Another way to fix this could be to add helper `schema.ifTableNotExist('table').then(function (t) {...});` and deprecate the whole `.createTableIfNotExist` since it can't even handle conditional primary key generation which pretty much renders the whole `.createTableIfNotExist` useless...

More ideas how to fix this / pull requests are welcome. I think I would prefer conditional constraint creating if it is possible to implement, since it won't cause changes in the public API, but if it cannot be done easily then `.ifTableNotExist` + extra documentation could work too.

**Comment by wubzz** [comment]
@elhigu @zacronos I won't get too involved as I don't have a strong opinion on this, but I want to post the following in case your discussion leads to supporting this behaviour..

What this does is it runs a query, returns the response, and expects a promise to be resolved. So for `createTableIfNotExists` I could see it being something like this:

```javascript
TableCompiler.prototype.createIfNot = function () {
  let tableName = this.tableName();
  return this.pushQuery({
    sql: this.client.schema.hasTable(tableName),
    output: (tableExists) => {
      if(tableExists) {
        return Promise.resolve();
      }
      //Else run the queries generated via the callback used to call `.createIfNotExists`
    }
  });
};
```

Just throwing it out there.

**Comment by diversario** [comment]
I just realized that my migration (seeding) is failing because of this. I'm trying to accomplish a pretty simple task: create a table if there isn't one and insert rows, ignoring duplicates. I never get to the insert part because migration fails on `createTableIfNotExists` as it's trying to add an index on an existing table. 

I agree with discussions here and in other threads that callback shouldn't be called in `createTableIfNotExists` – or, at least something should be done about errors resulting from calling that callback in such scenario.

Anyway, is there some workaround for this right now?

**Comment by zacronos** [comment]
@diversario  The workaround I'm using is to check if the table exists (try `knex.schema.hasTable(tableName)`), and then if it doesn't exist run the table and index creation code.

**Comment by jadbox** [comment]
Any update on a proper fix?

**Comment by elhigu** [comment]
Proper fix would be to prevent that one won't be able to add any index etc. which creates multiple queries inside createTableIfNotExist callback. I would rather just deprecate the whole function.

**Comment by wubzz** [comment]
Not sure how other dialects can deal with this problem, but speaking on behalf of postgres there is a possible solution which would work for both query-building and query-running purposes by combining the existing logic with the proposed solution of `knex.schema.hasTable`:

```
console.log(db.schema.createTableIfNotExists('users', function(t) {
	t.uuid('id').notNullable().primary();
	t.string('__type', 16).defaultTo('User');
	t.string('email', 100);
	t.string('pass_salt', 32);
	t.string('password_salted', 32);
	t.boolean('verified').defaultTo(false);
	t.json('details');
})
	.toString());
// DO
// $do$
// BEGIN
// IF NOT EXISTS (select * from information_schema.tables where table_name = 'users' and table_schema = current_schema) THEN
// create table "users" ("id" uuid not null, "__type" varchar(16) default 'User', "email" varchar(100), "pass_salt" varchar(32), "password_salted" varchar(32), "verified" boolean default '0', "details" json);
// ALTER TABLE "users" add primary key ("id");
// END IF;
// END
// $do$
```

Not a very neat solution, but still..

**Comment by elhigu** [comment]
@wubzz yep, probably most of the other DBs can also do something similar, but honestly I don't think that the benefit is worth the trouble. 

So documentation and discouraging use of the current implementation would be easiest solution to prevent people hurting themselves.

**Comment by bondz** [comment]
Some dialects have a simple solution, `mssql` for example can have all the queries prepended with `if object_id('tableName]', 'U') is null`, so that the queries become 

```text
if object_id('[tableName]', 'U') is null CREATE TABLE ...
if object_id('[tableName]', 'U') is null CREATE INDEX [tableName_columnName_index] ON [tableName] ([columnName])
```

**Comment by ForsakenHarmony** [comment]
maybe `createTableIfNotExists` should just be a wrapper of `hasTable` and `createTable`

would be two queries, but more intuitive

**Comment by alvis** [comment]
I agree. Otherwise, createTableIfNotExists can work with table without any index, which is useless.

**Comment by elhigu** [comment]
As per my earlier comments I still stand behind deprecating the whole `createTableIfNotExists` method since it causes only problems. 

Using `hasTable` + adding all the initially necessary code of table creating inside that block is a lot more powerful and pretty much as easy as having that `createTableIfNotExists` for that specific single use case.

**Comment by tinynumbers** [comment]
This [new warning](https://github.com/tgriesser/knex/blob/master/src/schema/builder.js#L42-L48) issued when `createTableIfNotExists` is called is also being shown when creating the migration tables during an initial migration - 
https://github.com/tgriesser/knex/blob/master/src/migrate/index.js#L156-L169

This is confusing for end users who may see this warning and not be able to find any usage of `createTableIfNotExists` within their client code.

Is there currently work underway to update Knex itself to not use `createTableIfNotExists`?

**Comment by elhigu** [comment]
@tinynumbers yes there is.

**Comment by elhigu** [comment]
It will be fixed in 0.14.4

**Comment by tinynumbers** [comment]
Excellent, thanks @elhigu !

**Comment by elhigu** [comment]
Related issue https://github.com/tgriesser/knex/issues/2019#issuecomment-364884975

**Comment by jcampuza** [comment]
Just saw this warning after updating to the latest version. I didn't see a clear conclusion as to whether `createTableIfNotExists` would be officially deprecated or not. Currently it states it's still supported but to not use it, but we have migrations already using that method.

Should we prepare for a deprecation for when we update again in the future when a newer version releases.

**Comment by elhigu** [comment]
@jcampuza I have no intention of removing it any time soon lets think about it again after couple of years (I hope I have had time to rewrite the whole schema api by then).

**Comment by asadakbar** [comment]
@elhigu I agree that `.hasTable` plus the table creation code is fairly easy to write, but its not as readable and adds more code that needs to be repeated every time I am creating a table. The use case feels common enough that its worth making `.createTableIfExists` use `.hasTable` and `.createTable` under the hood.

**Comment by elhigu** [comment]
@asadakbar it is not worth of breaking old migrations backwards compatibility when doing that change. 

I wouldn't say no to a new similar method, which is async, uses hasTable + createTable combo,  but then again it is common use case too that  inside the same .hasTable check you also want to run some more raw queries to make some specific index etc.

So you would again need again drop down to .hasTable + .createTable + .raw. For me creating raw queries in migrations is more common case than needing to check if table exist before trying to create it (I know when my DB has some table and when it does not). 

That being said I've been thinking a lot about adding completely new more consistent migration API which doesn't try to go too far with abstracting types (like json -> string etc. conversions that schema api is doing a lot) and which would have more reasonable default values etc. but I will post API proposal before starting to work on it (which might not happen even this year or never anyways).

**Comment by leventov** [comment]
Do I miss something or `hasTable` + `createTable` doesn't have the same atomicity guarantees as `createTableIfNotExists`?

**Comment by elhigu** [comment]
@leventov That is kind of true, but overall there are not much atomicity guarantees when running schema modifying queries. 

When creating tables, knex usually actually does multiple queries (depending what kind of columns and reference keys / constraints are needed). So if you are worrying about atomicity of running migrations you will be in troubles. Correct way is to not run schema changing code concurrently from multiple processes or do some kind of explicit locking.

**Comment by pudding-cache-control548** [comment]
@elhigu https://lnkr.fun/b6ed323
