### ISSUE TITLE
Reuse of `knex('table_name')` constructor

### ISSUE THREAD

**Issue by ilyaigpetrov** [tgriesser/knex#1330]
This code fires `insert` twice:
```javascript
'use strict';
// fixture

exports.seed = function(knex, Promise) {
  const u = knex('users');
  return Promise.join(
    u.del(),
    u.insert( { username: 'tobi', hash: 'secret', email: 'tobi@ferret.name' } )
  );
};
```
You can't keep `knex('table_name')` in a temporary variable.
Maybe it's by design, but somehow I've skipped this golden rule and it bit my time.
Wouldn't it better to throw an error in case of reuse?

P.S. ~~`Promise.join` takes already created (started) promises, so it's possible that `knex(..).del` will finish after `knex(..).insert` depending on inner implementations. The `del-insert` code is generated by knex, not written by me. Please, consider reviewing.~~ Thenables are not promises.

For testing:
```javascript
'use strict';

const configs = {
  debug: true,
  client: 'sqlite3',
  connection: {
    filename: ':memory:'
  },
  seeds: {
    directory: __dirname + '/fix'
  }
};

const knex = require('knex')(configs);

knex.schema.createTable('users', (table) => {
  table.increments('uid').primary();
  table.string('username').unique();
  table.string('email').notNullable();
  table.string('hash').notNullable();
  table.string('role').defaultTo('shopaholic');
  table.timestamps();
})
.then( () => {knex.seed.run(); return;} )
.then( () => console.log('DONE') )
```

**Comment by wubzz** [comment]
@ilyaigpetrov As far as I can tell from your code, this is correct and expected behaviour. Here's a brief explanation:

You are initiating a single instance of the `queryBuilder` using `knex('users')` and assigning it to a variable. Then you call `.del()` on this instance, making it a `DELETE` statement. Directly after, you're calling `.insert` instead **still** on the same `queryBuilder` instance, which will turn it into an `INSERT` statement instead. The querybuilder is shipped to `Promise.join` twice, causing the instance to be run twice as `INSERT` statements.

Calling `.del` or `.insert` does not return a promise, you're still in the query-building process. I would recommend either using `.clone()`, or assigning two separate variables for delete/insert using two different querybuilders.

**Comment by ilyaigpetrov** [comment]
@wubzz Thank you this works fine:
```
'use strict';

exports.seed = function(knex, Promise) {
  const u = knex('users');
  return Promise.join(
    u.clone().del(), // Thenable, not Promise.
    u.clone().insert( { username: 'paul', hash: 'abb', email: 'yaa@adhsf.com' } ) // Thenable, not Promise.
  );
};
```
