### ISSUE TITLE
Status of the connection? Reconnect?

### ISSUE THREAD

**Issue by nerdpad** [tgriesser/knex#1341]
I am using PG and Knex.

How can I find if Knex was able to successfully connected to database server. And When the server drops the connection, how do I reconnect?

**Comment by karlem** [comment]
Actually I have the same issue... The only way how to fix this I come up with is like this:

 `_registerErrorListenerOnPool () {
    this._connection.client.pool.on('error', (err) => this._handlePoolError(this._connection.client.pool, err));
    this._connection.client.pool.on('warn', (err) => this._handlePoolError(this._connection.client.pool, err));
  }

  _handlePoolError (pool, err) {
    console.log('isPool: live: ', pool.live);
    console.log('isPool: Destroyted: ', pool.destroyed);

    if (pool.destroyed === true &&
      this._reconnectTimer === null) {
      this._tryReconnect();
    }
  }

  _tryReconnect () {
    console.log('_tryReconnect');

    this._connection.client.initializePool(this._connection.client.config);

    this._registerErrorListenerOnPool(this._connection);
  }`

and then set up a pool config object:
`pool: {
          acquireTimeout: 2000,

          requestTimeout: 5000,

          syncInterval: 2000,

          ping (connection, cb) {
            connection.ping(cb);
          },

          min: 1
        }`

all the time out are so short just for testing purposes. But I don't think this is quite right... Any other (better) suggestions?

**Comment by wubzz** [comment]
As far as I know knex does not expose any way of "validating" that it is able to reach the database unless you start using the library in some fashion, such as issuing a query. *(Correct me if I'm wrong)*

As for reconnecting, the [pool2](https://github.com/myndzi/pool2) library should take care of this. When a connection is severed for whatever reason, pool2 should replace that connection with a new connection in the pool. Knex asks pool2 for a connection any time that a query is about to be run.

Currently in 0.10 there is a nasty bug about this in `mysql2` if that's what you're using. See #1315 

Default ping functionality is also going to be added in the next version of knex which will validate that the connection is still healthy to be used. This should include support for when connections are dropped by the server. See #1296

**Comment by NerdPad** [comment]
@karlem Do you think there are any shortcomings to your solution?

@wubzz What do you think about the "solution" provided by @karlem

**Comment by karlem** [comment]
@wubzz But how you can prevent query from being hanged? I just can't recognize whether is db down or not (so I can't log it etc..)...
@NerdPad I think it's not ideal at all... Because I'am basically forcing pool2 to destroy every time query takes too long and then creating a new pool.. So it doesn't necessarily mean that database is down... So I'am not able to log it properly... Actually my solution is not in production... That's just proposal which I come up with after I went through the k'nex and pool2 code

**Comment by wubzz** [comment]
@karlem Kind of depends what you mean by "hanged" queries -- Hanged via server dropping connection? Hanged because complex query that takes a while? Hanged because pool is full? Hanged because in a transaction and not calling commit?

There's a lot of reasons to consider, and each scenario could be different per dialect. Would need a more detailed description and scenario to answer that, perhaps belonging in a seperate issue.

@NerdPad I believe the changes in 0.11 solves all the cases for reconnects. There is currently no way, even in 0.11, to "ask" knex if it can reach the database server aside from running a query of some kind, as far as I know.

**Comment by karlem** [comment]
@wubzz Good question.. But I mean when DB server drop connection. So the only thing I need it's to log it and try to initiate a new one after a while. I believe that's the same problem for @NerdPad. And it's ok that it's going to be implemented in 0.11, but we need to go live now.. So do you have any recipe how to dealing with this? Or how you personally handle this? (If you using knex in production)

**Comment by wubzz** [comment]
@karlem It's still dependant on the dialect you use. The solution implemented in 0.11 applies a default `ping` function to the default `pool2` configuration which will run a `SELECT 1` query to validate that the connection is still valid, and if it isn't, then it will return a new connection. This proved to work across all dialects tested.

An example in postgres that this change fixes:
```javascript
let selectVersion = () => knex.raw('SELECT version()')

selectVersion()
.then(() => {
debuger; //Kill connection on the database server, IE via pgAdmin 'terminate'.
return selectVersion();
})
.then((res) => {
//res is present
})
.catch((err) => {
//Do not reach this point.
});
```

You can do the same thing in 0.10 if you want, the code used for each dialect is available in #1296 .

**Comment by NerdPad** [comment]
For my previous question, it looks like I can just rely on Pool2 on acquiring a new connection on query, and log errors while querying (which I am already doing).

The only error that I am currently not able to log is when I initialize knex, and there is an error (eg: Service max connection has reached), knex writes error on console (Knex:Error .....), how do I log these?

**Comment by elhigu** [comment]
Closing in favor of #1833
