### ISSUE TITLE
Can't use 'is' keyword

### ISSUE THREAD

**Issue by Roam-Cooper** [tgriesser/knex#1353]
I can't use the 'is' keyword on a grouped join because lib/formatter.js doesn't include 'is' in the list of operators.
```javascript
knex('tablename').join('tablename', function() {
                    this.on('tablename.columnname', 'is', knex.raw('?',['null']));
                })
```
Yields me:
> TypeError: The operator "is" is not permitted

**Comment by Roam-Cooper** [comment]
I also can't soft-mod knex to include the operator because the operators var is not on the Formatter prototype and therefore isn't exported. :cry:

**Comment by rhys-vdw** [comment]
AFAIK There is no `IS` operator in SQL. There is the `IS NULL` operator.

Currently joins to not support value comparisons by default - just column comparisons. But you can achieve what you want like so:

```js
knex('tablename').join('tablename', function() {
  this.on(knex.raw('?? is null', 'tablename.columnname'));
});
```

**Comment by Roam-Cooper** [comment]
Yeah, I just ended up doing the entire grouped join as raw. And yup, that's correct sorry, but the IS NULL comparison is what I want to do, which is totally valid to use for joins in Postgresql, but I'm not sure if it's _specific_ to Postgresql.

I believe that if Mysql et al supports using 'is null' in a join as well then it would be useful for the join/grouped join to allow one to do this as we use it to control a join based on a "deleted" column being null, that we use for paranoid deletion (ie not deleting anything at all).

So should I leave this issue open as a feature request, or close it?

**Comment by rhys-vdw** [comment]
So, the feature you want is not support for `IS NULL`. It's support for comparison of columns to values.

`this.on('column', 5)` is invalid also (it interprets `5` as a column name). If we supported passing a value (rather than a column name) as the second argument of `on` then we'd support passing `null` too.

If you would like support for the above, then I'd suggest opening a new feature request that doesn't talk about `is null` specifically.
