### ISSUE TITLE
Add limitation of table name on PostgreSQL

### ISSUE THREAD

**Issue by WhiteCat6142** [tgriesser/knex#1377]
PostgreSQL throws error when table name is over 63chars.
Add a option that cut long table names.

**Comment by elhigu** [comment]
The problem is somewhere else than knex if you are running to an issue like this. Converting invalid table names to valid  table names for certain dialect should not be knex's responsability to fix. Just use shorter table names?

If there is a really good use case supporting this, I might change my opinion though.

**Comment by WhiteCat6142** [comment]
The reason is compatibility.
Some application work on Sqlite but not on PostgreSQL.I acknowledge that this is not knex's responsibility,but I thought it will be a good util for transition.
