### ISSUE TITLE
[Question] Savepoints

### ISSUE THREAD

**Issue by johanneslumpe** [tgriesser/knex#1413]
I've been trying to use nested transactions to no avail. I was expecting that the following code would insert a single row, then create a savepoint and roll back to said savepoint when throwing the error in `trx2`. Instead no row was inserted, because I assume the whole transaction gets rolled back. @rhys-vdw Any ideas?

```js

const createNewTransactionRecord = db => (
  db('transactions')
  .insert({ status: 'pending' })
  .returning('id')
);

const updateTransactionRecordWithStatus = (db, transactionId, status) => (
  db('transactions')
  .update({ status })
  .where('id', transactionId)
);

knex.transaction(trx => (
  createNewTransactionRecord(trx)
  .then(([ id ]) => (
    trx.transaction(trx2 => (
      updateTransactionRecordWithStatus(trx2, id, 'complete')
      .then(() => trx2('transactions').then(() => { throw new Error('Boom'); }))
    ))
  ))
));
```

**Comment by jurko-gospodnetic** [comment]
The error you throw gets converted to a rejected promise returned from a the nested `transaction()` call. That promise is then directly returned from the external `transaction()` call as well. In fact, you get the effect of rolling back both transactions.

If you want to keep the external transaction running, handle the rejected promise returned by the nested transaction instead of simply returning it as the external transaction's result.

So something like this should work (warning: untested code):

```
const createNewTransactionRecord = db => (
  db('transactions')
  .insert({ status: 'pending' })
  .returning('id')
);

const updateTransactionRecordWithStatus = (db, transactionId, status) => (
  db('transactions')
  .update({ status })
  .where('id', transactionId)
);

knex.transaction(trx => (
  createNewTransactionRecord(trx)
  .then(([ id ]) => (
    trx.transaction(trx2 => (
      updateTransactionRecordWithStatus(trx2, id, 'complete')
      .then(() => trx2('transactions').then(() => { throw new Error('Boom'); }))
    ))
    .catch(() => (
      console.log("I’m sorry to have kept you waiting, but I’m afraid my walk has become rather sillier recently.")
    ))
  ))
));
```

**Comment by johanneslumpe** [comment]
@jurko-gospodnetic Thanks for clearing that up!
