### ISSUE TITLE
mssql bigint support

### ISSUE THREAD

**Issue by sandorfr** [tgriesser/knex#1442]
Mssql dialect currently crashes when bigint are used. This is due to the way [tedious handles them](http://pekim.github.io/tedious/api-datatypes.html). 

I'm working on a pull request (#1441) but I'm unable to build the source atm (probably related to #1180).

Looking forward to your feedback and help regarding the build / tests.

**Comment by rhys-vdw** [comment]
#1180 is a problem in installing an this repository as an npm dependency. If you're working on a PR you should build source locally using `npm run babel`.

**Comment by sandorfr** [comment]
@rhys-vdw ok works now, but I had to `rimraf` the node_modules and remove the build script in order to do the package restore.

The build script requires bash (not very windows friendly). I think moving  to plain node script would be easier. I work on a PR for that matter it if you are interested.

**Comment by rhys-vdw** [comment]
> The build script requires bash (not very windows friendly).

See #1425. Perhaps you can help test this PR.

**Comment by elhigu** [comment]
As far as I could figure this out the problem is that we need to tell to mssql driver in which format it should pass javascript variables to DB.

https://github.com/tgriesser/knex/blob/master/src/dialects/mssql/index.js#L107

`req.input()` actually takes more parameters which can be used to define in which format value should be sent. https://github.com/patriksimek/node-mssql

So before calling req.input one could check if value is number and bigger than 32bit and smaller than 53bit and send it as int8 instead of int4. If number is bigger that min/max_safe_integer it should throw an error since value has been clamped to fit 53bit.

Any thoughts? I haven't tested any of this... doing conversion in `prepBindings` didn't feel like appropriate fix, since we still wouldn't tell to driver how value should be passed.

**Comment by sandorfr** [comment]
Thanks for pointing me in the right direction. I'll look into this and update my PR branch accordingly.

**Comment by sandorfr** [comment]
@elhigu I started a new PR with a new implementation. I did not use isSafeInteger because it would probably break on older node version.

**Comment by sandorfr** [comment]
Closing this resolved issue and will open new ones about failing unit tests later.
