### ISSUE TITLE
Throw error of undefined values in SELECT queries

### ISSUE THREAD

**Issue by wubzz** [tgriesser/knex#1448]
Per the discussion in #1417:

**Explanation**
Currently `insert` and `update` handle `undefined` values via `valueForUndefined` -- this works great, and should remain the same. The issue arises with `select` queries since one certainly would not want `valueForUndefined` in this case. Throwing an error is the most optimal solution to prevent faulty application code and faulty queries.

The current implementation throws an error message `SQL queries with undefined where clause option` which  definitely gets the point across, but could be more informative. It's also currently only implemented for Postgres.

**Proposal**
I suggest we remove the existing validation check and move it out to the [compiler(Reference)](https://github.com/tgriesser/knex/blob/master/src/query/compiler.js#L37). In this function we have all the information we need: the query method, the bindings, and the generated query. With this we can validate **before** `prepBindings` is called and throw an informative error including information about the query being run. This would also be applied to all dialects since the compiler applies for all. We also have the ability to emit the `query-error` event from this function.

Thoughts? @elhigu @rhys-vdw @mdrmuhaimin

**Comment by elhigu** [comment]
Sounds doable place. As far as I know that place in knex should catch all undefined value errors in bindings.

Though I would like to throw synchronous error already when query builder is called with invalid parameters.

About `query-error` event. In my opinion that should be emitted only for those errors which are happening on query execution time (i.e. after .then() was called), after the `query` event.

I would like to approach this issue by creating bunch of test cases with undefined values in API calls (also in other places than just where statements). In select, from, orderBy, inside sub query function s... and after having good tests coverage of potential use cases, check what is convenient way to solve the issue.

When tests are written we  can also document that undefined handling to documentation so that it won't be "undefined behaviour" anymore.

**Comment by wubzz** [comment]
@elhigu I like that idea, we definitely need to test more with undefined values. I vote for giving it its own suite in both unit and integration tests.

`query-error` I had the same thought, it doesn't really fit in. However, we could have a generic `error` event or `builder-error` / `compiler-error`, something like that. There's no reason not to help the enduser when possible. It could then be emitted wherever we have these checks. Generally these events are good for logging purposes or within a query-builder chain.

**Comment by wubzz** [comment]
Closing this as it has since been solved.
