### ISSUE TITLE
Failure to work when the DB server was not available on startup

### ISSUE THREAD

**Issue by haizz** [tgriesser/knex#1455]
If the DB server wasn't available on knex initialization time the knex has to be restarted to run any queries when the DB server goes back up.

Steps which reproduce behavior on my system:
1. Stop PostgreSQL server.
2. Start knex app.
3. Some time after knex initialization: `Knex:Error Pool2 - Error: connect ECONNREFUSED 192.168.99.1:5432`
4. Start PostgreSQL server.
5. Try to access DB from knex: `Error: Pool is destroyed`

**Comment by haizz** [comment]
Is there any estimated plan on fixing this?
Meanwhile, what would be a decent workaround?

**Comment by elhigu** [comment]
You could try to catch that exception and re-initialize knex after a while. 

I have no estimates when this is going to be fixed... Pull requests are welcome 🙂

**Comment by johanneslumpe** [comment]
@elhigu Just catching that exception and then re-initializing knex could potentially cause a major headache, especially if other libraries like `bookshelf` are use as well, as we would have to re-initialize those as well. It gets even worse if we inject our models into route handlers, as those would need to be re-initialized as well, meaning that we'd basically have to restart the whole server. This seems like a common enough issue to get it fixed.

The error happens when trying to acquire a connection. Instead of having to reinitialize knex from the consumer side, do you think it is reasonable that we try to replace the `client` on the fly? In [`make-knex`](https://github.com/tgriesser/knex/blob/master/src/util/make-knex.js) the injected client is referenced directly in some methods, making it harder to just swap out `knex.client` for a newly initialized one on the fly. If we instead always referenced `knex.client`, then this would allow us to hot-swap the client.

@elhigu @rhys-vdw do you see any issues with that idea?

**Comment by wubzz** [comment]
@elhigu @johanneslumpe Based on the structure of pool2 and the error at hand, I think it isn't necessarily correct to claim that this falls on knex's table to take care of. Of course we could make a fix in knex, but feels more like to me that pool2 should expose some kind of function to "reinitialize" itself. Knex is still intact in this scenario. The part that's broken is the pool instance on the client, not the client itself.

Another hacky fix could be to use pool2's `destroy` option, which is a callback called when the pool is destroyed. In that callback one could re-initialize the pool using the very same function that initialized it to begin with. Not the best of solutions, tho.

**Comment by johanneslumpe** [comment]
@wubzz That's a good point actually. As a short terms solution I am something very hacky where I actually bring the server to a grinding halt, then exit the process and have my monitoring solution restart it.

So your temp solution would be to do this:

```js
knex.pool.destroy();
knex.initializePool(knex.config);
```

Did I understand that correctly?

**Comment by wubzz** [comment]
@johanneslumpe To prevent having to handle this manually, I was thinking something more like:
```javascript
db = knex({
connection: {...},
pool: {
destroy: () => {
db.client.initializePool(db.client.config);
}
}
});
```

It should work, but like I said is definitely not a recommended solution. Could end up getting stuck in an endless loop in cases where the server never goes back up, or down for a long period of time. Perhaps a max attempts/interval would be suitable even for this hacky solution. This is just my interpretation of the `destroy` option, and I haven't tested any of this, so I could be completely wrong..

**Comment by johanneslumpe** [comment]
@wubzz Yeah because the loop issue I've just added a plugin to my server instance. Still testing but the main idea is this:


```js
export const register = (server, { knex, maxNumRetries = 5, retryAfter = 2000 }, next) => {
  let retryScheduled = false;
  let numRetries = 0;

  server.on('request-error', (request, err) => {
    if (err.message === 'Pool is destroyed') {
      const canRetry = numRetries < maxNumRetries;
      if (!retryScheduled && canRetry) {
        retryScheduled = true;
        setTimeout(() => {
          knex.client.pool.destroy();
          knex.client.initializePool(knex.client.config);
          retryScheduled = false;
          numRetries++;
        }, retryAfter);
      } else if (!canRetry) {
        // crash server here after logging to external source
      }
    }
  });

  next();
};
```

**Comment by PymZoR** [comment]
Any news on this ?

**Comment by elhigu** [comment]
@PymZoR I suppose this works now. Lets reopen if this is still problem.
