### ISSUE TITLE
TravisCi add oracle Database

### ISSUE THREAD

**Issue by williamgueiros** [tgriesser/knex#1491]
hello, I'm  working to add Oracle in TravisCi on the project, for running integration tests.

See the result in link, please add comments if you dislike.

 https://github.com/williamgueiros/knex/pull/1

do you think is possible, add environment variables(ORACLE_LOGIN_ssousername, ORACLE_LOGIN_password) on your ThavisCI?

![captura de tela 2016-06-13 as 19 43 32](https://cloud.githubusercontent.com/assets/19972/16026706/b568da88-31a6-11e6-931f-2d95e0c74103.png)

see more information in:
https://github.com/cbandy/travis-oracle

**Comment by williamgueiros** [comment]
PR after 

https://github.com/tgriesser/knex/pull/990

**Comment by elhigu** [comment]
Looks interesting, I'm very excited of this 👍  

Even though I suppose that anyone can extract those login / password from environment configuration by sending pull request which prints them to build log as plaintext. Which doesn't really matter since it is only a test database and nothing serious.

If this works it would be great reference to achieve the same for mssql.

**Comment by williamgueiros** [comment]
@elhigu ok after that, i will start MSSQL feature.

**Comment by kibertoad** [comment]
PR was merged, issue can be resolved.
