### ISSUE TITLE
Problem with knex migration.

### ISSUE THREAD

**Issue by monera23** [tgriesser/knex#1505]
I made a migration to add new column in a database on server. Then to rollback the changes I deleted the entry of the migration in knex_migrations table. Now when I try to do the migration again it shows error that column already exists but when I try to remove the column in database with query it shows that the column in not present.  How do I revert back to the previous configuration of database . Need help on it.

**Comment by elhigu** [comment]
Check that you typed everything correctly. Scenario that you just described is not possible... If db says that it cannot add column because it is already there it means that column is there. You must be able to see that column when you query info of schema of the table.

Also you should use knex rollback and down migrations for rolling back migrations.
