### ISSUE TITLE
SELECT "someValue" as COLUMNNAME

### ISSUE THREAD

**Issue by oliverhr** [tgriesser/knex#1530]
Is this posible with knex, I tried something like this:

```
Knex
      .select(`${value} as identifier`, 'timestamp')
      .table('tablename')
...
```

But I get and error:

```
column "XXX-XXXXX-XXXX" does not exist

{
...
name: 'error',
  length: 128,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '8',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '2892',
  routine: 'errorMissingColumn'
}
```

**Comment by jurko-gospodnetic** [comment]
There seems nothing wrong with what you tried. You just just used the template string to construct the actual string passed to `knex`, which seems to have been equivalent to `Knex.select('XXX-XXXXX-XXXX as identifier', 'timestamp')...`.

The problem seems to be on your end - the actual referenced column not actually existing in the database table `tablename`.

**Comment by oliverhr** [comment]
Hi @jurko-gospodnetic I tried as you suggest but did not work, but finally found the solution `Knex.raw`.
, I'using postgres and here the trick is the simple quotation marks around the value.
```
Knex
      .select(Knex.raw(`'${value}' as identifier `), 'timestamp')
      .table('tablename')
...
```

**Comment by elhigu** [comment]
@oliverhr you can use `??` to do identifier replacement with `knex.raw` which also does adding correct quotes depending on dialect

```js
knex('tablename').select(knex.raw('??', [`${value} as identifier`]), 'timestamp')
```

**Comment by oliverhr** [comment]
Cool, @elhigu thank you!!!
