### ISSUE TITLE
How to update a foreign key?

### ISSUE THREAD

**Issue by jhnferraris** [tgriesser/knex#1551]
I'm trying to change the `onUpdate` and `onDelete` values of a foreign key using knex. I've check out this link http://knexjs.org/ and saw that there is no method to modify a foreign key.

That leaves me to using `knex.schema.raw`. But before I do that, is there another way to update a foreign key?

Thanks!

**Comment by jhnferraris** [comment]
Update: 

So I saw this http://knexjs.org/#Schema-foreign, must have missed it. Anyway,

I tried modifying the foreign key

    exports.up = function(knex, Promise) {
       return knex.schema.table('wallet', table => {
          table.foreign('user')
           .references('user.id')
           .onDelete('CASCADE')
           .onUpdate('CASCADE')
       })
   };

But when i tried migrating up, it prompted the error

```
Knex:warning - migrations failed with error: alter table "wallet" add constraint "wallet_user_foreign" foreign key ("user") references "user" ("id") on update CASCADE on delete CASCADE - constraint "wallet_user_foreign" for relation "wallet" already exists
```

Does this mean I can't update an existing foreign key? Is it good practice to delete the old foreign key then just create a new one?

**Comment by jyanik** [comment]
Currently, it is not possible without using ```knex.raw()``` or ```table.dropForeign()```. Knex doesn't offer support to modify columns (see #46).

Neither is good practice, but I'd avoid dropping/creating foreign keys on large sets of data when you don't have to.

**Comment by jensMG** [comment]
> I'd avoid dropping/creating foreign keys on large sets of data when you don't have to

Thanks for the info. Can you further expain on your recommendation not to do so? I have a user table and a authorization id table and would like to adjust the onDelete in users to cascade so authorization token will be deleted when a user is deleted.

**Comment by vvo** [comment]
Hey, this is now doable since #46 was fixed!

Here's an example that will update a foreign key to add ON DELETE CASCADE, with the proper down migration too:

```js
exports.up = function(knex) {
  return knex.schema.alterTable("users", (table) => {
    table.dropForeign("organization_id");

    table
      .foreign("organization_id")
      .references("organizations.id")
      .onDelete("CASCADE");
  });
}

exports.down = function(knex) {
  return knex.schema.alterTable("users", (table) => {
    table.dropForeign("organization_id");

    table
      .foreign("organization_id")
      .references("organizations.id")
      .onDelete("NO ACTION");
  });
}
```

**Comment by MatMercer** [comment]
We had a very "clunky" situation regarding this functionality, we had to update the table names and columns, and we forgot to update foreign_keys references, this caused a de-sync between fk name and column name.

Say you have a FK called A, and a renamed one called B.

The issue was the fact that at up, we delete old name A FK, then add a new B one. But at down, we need to delete only the B FK. This causes the next up to fail, because remember, the up expects it to have A name.

And at down, we can't recreate the old name with `table.foreign('A_NAME').references('id').inTable('table');` because knex expects fk name == column name.

So I had to manually add safe methods, to delete each of them if needed. It would been way easier if knex allowed us to `table.foreign('A_NAME').rename('B_NAME')...`
