### ISSUE TITLE
"There is no pool defined on the current client" is a bad error message

### ISSUE THREAD

**Issue by krainboltgreene** [tgriesser/knex#1583]
Search for this message in the issue list and you'll get quite a few issues where they ALL have entirely different source problems. Ranging from: No environment defined, bad client name, no client key defined, no connection defined, etc.

Instead we need better messages about our client, type constrained if possible. I should know when I accidentally type `pgsql` instead of `pg` or `postgres`. I should know when my *configuration* is missing the **client** key, a pretty freaking important key.

**Comment by hulbert** [comment]
Can we outline specifically each case since they may need to be addressed separately? Starting with your list:

1. No environment defined

2. incorrect client name in knex configuration, e.g. `psql` instead of `pg`

3. no client key defined -- not sure what this means?

4. incorrect connection configuration

5. there is also the case where the pool is destroyed; this is not a configuration issue and could potentially use a more descriptive error message potentially with a link to a wiki page like Angular & React do

I use Hapijs a lot and they do a good job of configuration checking. Keep in mind w/r/t configuration validation for knex, the docs list a supported case (see below) that makes this pretty darn hard (missing configuration, though perhaps it can be deferred until a query is issued to the datbase--i.e. with a promise or callback):

```js
var knex = require('knex')({}); // configure w/ empty object
var pg = require('knex')({client: 'pg'}); // configure without connection

knex('table').insert({a: 'b'}).returning('*').toString();
pg('table').insert({a: 'b'}).returning('*').toString();
```

**Comment by krainboltgreene** [comment]
Here's an example of "no client key defined"

```
var pg = require('knex')({adapter: 'pg'});
```

**Comment by gotoAndBliss** [comment]
"There is no pool defined on the current client" gets returned for any psql error. For example, a validation UNIQUE error would return this for me. 

Knowing that this error is the catch all error for any error that comes from psql, I was curious if anyone had a way to step in *before* this error? Is there a way to log psql directly without knex failing generically ( and in this case incorrectly )?

**Comment by tgriesser** [comment]
@gotoAndBliss this message has been changed to "Unable to acquire a connection" in 0.12 which is more indicative of the actual error. It should only occur if you have either not supplied a proper connection configuration or have already called `knex.destroy()` and the connection pool has drained and cleaned up.

I don't see how you'd be seeing this error if the client is properly configured.

**Comment by gotoAndBliss** [comment]
I'm using Knex@0.12.1 -- And can confirm it returns that same message `There is no pool defined on the current client`. This is a new PG install on a windows box where as I knew the same code worked for my Mac. So I'm guessing there's something corrupt about PG. I understand this is amiss from the OP, but any idea @tgriesser , how I could debug this? My PSQL server is running, I can log into it with the credentials supplied in my Knex config.

**Comment by tgriesser** [comment]
@gotoAndBliss if you are on 0.12.1, the message couldn't be "There is no pool defined on the current client", that line is no longer anywhere in the codebase.

Maybe run setting env to `DEBUG=knex:*` to see if there's any output from the pool or otherwise that helps?

**Comment by gotoAndBliss** [comment]
@tgriesser That helped me solve it. Thanks so much for your help.

**Comment by tgriesser** [comment]
Yep!

**Comment by krainboltgreene** [comment]
🎉 Kudos on picking a more descriptive error message. This should definitely help future users avoid time wasted.

:+1:
