### ISSUE TITLE
v0.11.9 read json field as string

### ISSUE THREAD

**Issue by smilingpoplar** [tgriesser/knex#1590]
v0.11.7 doesn't have this problem

**Comment by Dynom** [comment]
I'm not an active part of the Knex community, so my apologies if I step out of line.

Could you please provide additional information about the problem you have:
  * What you try to do (in knex DSL)
  * The expected outcome and
  * The actual outcome?

I don't expect anyone to help you otherwise. And frankly I think it's just plain rude to be this brief.

**Comment by smilingpoplar** [comment]
@Dynom Sorry to be too brief. Here's the problem I encounter:

I've a json array `[1, 2]` stores in a postgres's json field. Then I use bookshelf to read its value. With knex v0.11.7, I can read the array value `[1,2]` correctly. But when I upgrade knex to v0.11.9, the  read value becomes `“[1,2]”`.

**Comment by Dynom** [comment]
Thanks for clarifying!

**Comment by elhigu** [comment]
@Dynom not stepping out of line at all. Its just great if whole community helps to resolve the problems 👍  Pretty much every collaborator has ended up being collaborator just by commenting issues and reviewing code / sending pull requests for the problems they had encountered.

@smilingpoplar I'll try to have time to look into this at some point in future, if it is easy to reproduce. There should not have been any changes to this between 0.11.7 and 0.11.9, so it would be nice if you can trace this bug to knex and not to any other changed library version.

**Comment by elhigu** [comment]
@smilingpoplar did you find if the problem was related to knex?

**Comment by smilingpoplar** [comment]
@elhigu I updated knex to v0.11.10 today, and it's ok. No idea if it's my problem only.
