### ISSUE TITLE
knex.schema.createTable does not work

### ISSUE THREAD

**Issue by alexey2baranov** [tgriesser/knex#1628]
Hello! this code does not create table in my local DB. No error throwened and no console output. What's wrong with it?
```
var knex = require('knex')({
    client: 'pg',
    connection: {
        host     : '127.0.0.1',
        user     : 'postgres',
        password : '***',
        database : 'kp-bookshelf',
        charset  : 'utf8'
    }
});

knex.schema.createTable('user', function(table) {
    table.increments();
    table.string('name');
    table.string('email', 128);
    table.string('role').defaultTo('admin');
    table.string('password');
    table.timestamps();
});
```

**Comment by wubzz** [comment]
@alexey2baranov You need to call `.then` or `.asCallback`

**Comment by alexey2baranov** [comment]
@wubzz 
where ? after createTable()? if so, nothing changed

**Comment by alexey2baranov** [comment]
oh sorry table was created! i was surprised. why should i use then()???

**Comment by wubzz** [comment]
@alexey2baranov Knex is a query-building library, so simply calling `createTable` will do nothing except generate the SQL string.

This will show you the generated SQL:
```javascript
console.log(knex.schema.createTable('user', function(table) {
    table.increments();
    table.string('name');
    table.string('email', 128);
    table.string('role').defaultTo('admin');
    table.string('password');
    table.timestamps();
}).toString());
```

To have knex run the SQL, you need to call `.then` or `.asCallback` as an execution function. This can also be chained with other promises.

**Comment by alexey2baranov** [comment]
yes it works but anyway i can't understand why I should use then()?? as I can see when working with promises Promise body function always executed not matter with then() or without then()

**Comment by alexey2baranov** [comment]
@wubzz 
yes it works but anyway i can't understand why I should use then()?? as I can see when working with promises Promise body function always executed not matter with then() or without then()

**Comment by tgriesser** [comment]
Because in knex a promise isn't actually created internally until `.then` is called, for historical reasons (and which is something I'm looking to change eventually). The reason is that you can chain several schema building calls:

```js
knex.schema
  .createTable('user', function(table) {
    table.increments();
    table.string('name');
    table.string('email', 128);
    table.string('role').defaultTo('admin');
    table.string('password');
    table.timestamps();
  })
  .createTable('account', function(table) {
    table.increments();
    table.string('name');
    table.string('email', 128);
    table.timestamps();
  })
```

And then you call `.then` when you want to execute.

So the issue is because it's not actually coerced into a promise until `then`, `catch`, `asCallback`, etc. are called - which happens internally when working within the up/down migration methods. 

I'm looking into different approaches to make this more obvious, such as marking when a chain is only used for string building purposes, and then checking if any unmarked builders are not turned into promises on `process.exit`, as this is a pretty common issue that folks run into when starting to use knex.

For the schema builder, I'm also considering just a `process.nextTick` which would automatically execute the chain if `toString` / `toSQL` etc weren't called.

**Comment by alexey2baranov** [comment]
@tgriesser 
Thank you for full reply.  Now i know internal logic i can understand this behavior. I think as this behavior is not intuitive have to be documented in manual.

**Comment by elhigu** [comment]
@alexey2baranov it is documented in http://knexjs.org/#Interfaces any pull requests for improvements to docuementation are welcome. 

In addition to Tim's explication: Query builder object in `knex` is something that `Promise A+` spec calls `thenable` https://promisesaplus.com/#point-7 . Thenable is an object that implements `.then` function to make object to interact with promises nicely. Indeed as Tim said this seems to be less obvious functionality to many developers.

**Comment by amir-s** [comment]
Actually if you execute:

```
let knex = require('knex')({});

console.log(knex.schema.createTable('user', function(table) {
    table.increments();
    table.string('name');
    table.string('email', 128);
    table.string('role').defaultTo('admin');
    table.string('password');
    table.timestamps();
}).toString());
```
You'll get 

```
/Users/<username>/Projects/<name>/node_modules/knex/lib/schema/columncompiler.js:96
    for (var i = 0, l = this.modifiers.length; i < l; i++) {
                                      ^

TypeError: Cannot read property 'length' of undefined
    at ColumnCompiler.getModifiers (/Users/<username>/Projects/<name>/node_modules/knex/lib/schema/columncompiler.js:96:39)
    at ColumnCompiler.compileColumn (/Users/<username>/Projects/<name>/node_modules/knex/lib/schema/columncompiler.js:74:88)
    at ColumnCompiler.toSQL (/Users/<username>/Projects/<name>/node_modules/knex/lib/schema/columncompiler.js:65:23)
    at /Users/<username>/Projects/<name>/node_modules/knex/lib/schema/tablecompiler.js:170:65
```

Any idea why `.toString()` doesn't work on `createTable`?

**Comment by wubzz** [comment]
@amir-s The reason is because you are not specifying which dialect you are trying to use knex for, which matters a lot even for mere query building purposes.  Change `let knex = require('knex')({});` to `let knex = require('knex')({client: 'pg'})` or which ever dialect you prefer.

This is technically a bug because the base `columncompiler` does not have the property `modifiers` which is instead assigned on every single individual `columncompiler` on a per-dialect basis. But still, I would rather see the `client` option being mandatory than anything else, which would also solve the bug.

Even in this case specifying the client matters, since different dialects have different `modifiers`. For example mysql has `unsigned` while postgres does not.

**Comment by amir-s** [comment]
@wubzz You're absolutely right.

I agree that this is a bug. The `client` option should be mandatory, or it should throw a meaningful and proper exception in these kind of cases.

Thanks.

**Comment by wubzz** [comment]
It seems it is documented as required but is not actually required.. I'll make a PR for this.

**Comment by intellimat** [comment]
thanks a lot guys,
I spent a whole day triyng to make it work, and THEN it was the fu**ing 'then()'

**Comment by colbyallenc** [comment]
Where do you put then `.then()` ???

**Comment by waitingsong** [comment]
Thanks a lot guys,  also a whole day with it.

**Comment by orangeChu** [comment]
> Where do you put then `.then()` ???

```javascript
knex.schema.createTable('user', function(table) {
    table.increments();
    table.string('name');
    table.string('email', 128);
    table.string('role').defaultTo('admin');
    table.string('password');
    table.timestamps();
})**.then()**;
```

**Comment by BroJenuel** [comment]
Sorry for coming back here... I have this but it does not work, I am using SQlite3.
```
import { app } from 'electron';
import knex from 'knex';
import { isNightly } from '../../config';
const dataPath = app.getPath('appData') + (!isNightly ? '\\believers-sword' : '\\believers-sword-nightly');
const filePath = dataPath + `\\StoreDB\\Store.db`;
const StoreDB = knex({
    client: 'sqlite3',
    useNullAsDefault: false,
    connection: {
        filename: filePath,
    },
});

export default () => {
    // setup clip_notes
    StoreDB.schema.hasTable('clip_notes').then((exists) => {
        if (!exists) {
            return StoreDB.schema
                .createTable('clip_notes', (table) => {
                    table.increments('id').primary();
                    table.integer('book_number');
                    table.integer('chapter');
                    table.integer('verse');
                    table.string('content');
                    table.timestamps();
                })
                .then((response) => {
                    console.log('created');
                    console.log(response);
                });
        }
    });
};
```
