### ISSUE TITLE
Wrong query in case of empty array in whereIn

### ISSUE THREAD

**Issue by sarveshseri** [tgriesser/knex#1635]
```javascript
var knex = require('knex')({client: 'pg'});

var queryString;

queryString = knex.select('*').from('table').whereIn('a', [1, 2]).toString();
console.log(queryString);
// select * from "table" where "a" in ('1', '2')
// which is right query
// But it does not work well with empty array.
queryString = knex.select('*').from('table').whereIn('a', []).toString();
console.log(queryString);
// select * from "table" where 1 = '0'
```

**Comment by absolux** [comment]
@sarveshseri 
but it works well, returning an empty array as result without errors

**Comment by sarveshseri** [comment]
Yes. Its is converting empty array whereIn into a `where(_not())`. Though it works well. Its not the correct choice just looking at the query.

**Comment by elhigu** [comment]
@sarveshseri that feature is intentional. As @absolux said that is made to prevent error when people are using `whereIn` and passing empty array to it. Otherwise everyone would need to write  boilerplate around every use of `whereIn` when array to pass to it is got e.g. from result of another query.

Functionality of `where 1 = '0'` is equivalent with `where anything in ()` if only latter would be valid SQL...
