### ISSUE TITLE
Cordova problem - SchemaBuilder not delegating methods

### ISSUE THREAD

**Issue by lvffilho** [tgriesser/knex#1670]
When i call the current methed, nothing is executing. I debug code and saw that schemabuilder dynamic methdos like createTable, createTableIfnotExists are not being called

        KnexModule.schema.createTableIfNotExists('Person', function(table) {
            table.increments('id');
            table.string('user_name');
        })

**Comment by tgriesser** [comment]
This is the source of a lot of confusion in knex, but the code isn't actually executed until you attach a handler (.then, .catch, .asCallback). For 1.0 I'm planning on logging warning messages when folks don't add handlers or otherwise use a query chain as a partial to make this issue easier to debug.

**Comment by lvffilho** [comment]
But what do i need to attach if im just using the api?
In this case, what do i have to do?
Can u give an example?

**Comment by tgriesser** [comment]
Yes, see the example I gave above: you need to attach one of `.then`, `.catch`, `.asCallback`

**Comment by lvffilho** [comment]
Sorry, i dint see the example. I´ll take a look... tnx
