### ISSUE TITLE
 Join query results in sub object

### ISSUE THREAD

**Issue by NetanelBasal** [tgriesser/knex#1695]
I have relationship between user and post and when I run:

```js
 knex.from('posts').innerJoin('users', 'users.id', 'posts.user_id').then(res => {
    console.log(res);
  })
```

I am getting flat object with all the keys like this:
```js  
{
    "id": 1,
    "title": "Modi error facere est voluptatum rerum.",
    "content": "aliquam qui nihil",
    "user_id": 1,
    "name": "Judah",
    "email": "Catharine.Kemmer59@yahoo.com"
 }
```

There is a way to divide the user to be in its own object like this?

```js
{
    "id": 1,
    "title": "Modi error facere est voluptatum rerum.",
    "content": "aliquam qui nihil",
    "user_id": 1
    "user": {
      "name": "Judah",
      "email": "Catharine.Kemmer59@yahoo.com"
    }
  }
```

**Comment by tgriesser** [comment]
No, not with knex... You'd need a higher level orm abstraction like [bookshelf](bookshelfjs.org) or [knex-orm](https://github.com/kripod/knex-orm) or something. 

You could also explicitly specify the columns instead of doing `select *` and use a package like [treeize](https://www.npmjs.com/package/treeize) to achieve that result as well.

**Comment by NetanelBasal** [comment]
Thanks!
