### ISSUE TITLE
Adding expressions to existing raw query

### ISSUE THREAD

**Issue by zam6ak** [tgriesser/knex#1718]
Is it possible to modify existing raw query via query builder.
My goal is to use `knex.raw(existingLongComplicatedSqlText)` and then dynamically 'add to it' several `where` clauses. 
Is this possible? if so an example would be great!

Regards
z

**Comment by wubzz** [comment]
For `SELECT` queries one could probably do something like this:

```javascript
const existingLongComplicatedSqlText = 'TEST';
const raw = knex.raw(`(${existingLongComplicatedSqlText})`);

knex.select(raw)
.where('column', 'value')
.toString();

//select (TEST) where "column" = 'value'
```

But not so much for `INSERT` or `UPDATE`

**Comment by elhigu** [comment]
@zam6ak I would need to have exact example what you are trying to do. Basically what you are doing is impossible, because `raw()` query doesn't contain semantics what is in there, so there is no way to add stuff there. 

However you can write raw queries and their arguments separately and combine then in the end to one complete raw query like this:

Es6:

```js
knex = require('knex')({ client: 'pg' });
raw1 = 'This is a raw query and here will be the expression ? and here is another ?';
raw2 = 'Raw 2 sql with one ? parameter';
raw3 = 'raw3 with value ? binding';
raw4 = '(raw4 with most nested value ?)';

knex.raw(raw1, [
  knex.raw(raw2, [knex.raw(raw4,  ['Im really deeply nested'])]),
  knex.raw(raw3, [1])
]).toSQL();

{ method: 'raw',
  sql: 'This is a raw query and here will be the expression Raw 2 sql with one (raw4 with most nested value ?) parameter and here is another raw3 with value ? binding',
  bindings: [ 'Im really deeply nested', 1 ],
  options: {},
  __knexQueryUid: '8c4d9dbf-32f1-4abb-99cb-ff3ff7012eca' }
```

So you can see that raw values are combined directly to single query and value bindings are preserved even from nested raw statements.
