### ISSUE TITLE
Make quoting identifiers optional.

### ISSUE THREAD

**Issue by ravshansbox** [tgriesser/knex#1761]

**Comment by elhigu** [comment]
Any particular reason why this would be useful feature?

**Comment by ravshansbox** [comment]
yes, specifically for oracle. In my case with oracle `knex.raw('select * from table')` works, but `knew('table').select()` doesn't work, because knex is generating query as `select * from "table"`. AFAIK oracle is case insensitive for unquoted identifiers.

**Comment by elhigu** [comment]
@atiertant any ideas if this is somehow possible with oracle or should people just write their code case-sensitive way?

**Comment by atiertant** [comment]
@elhigu we should implement a fromRaw method

**Comment by elhigu** [comment]
@atiertant I have no idea what you mean by `fromRaw` method :) 

I was trying to ask if this is a good idea to support disabling identifier quoting on oracle or if there are better ways to get around the problem (e.g. some other global setting in database)? Would disabling quotes introduce any other potential problems?

**Comment by atiertant** [comment]
@elhigu like `whereRaw` for where clause, you could use `fromRaw` to add raw in from clause, like this you could do:
`knex.select('*').fromRaw('table')`

**Comment by mxii** [comment]
Would be great, would eliminate my problem with table-names including dots. They need to be escaped with quotes and this isn't possible with knex right now.

**Comment by ravshansbox** [comment]
I'm not sure if fromRaw and whereRaw clauses are best options. How about unquoted column names? Maybe better to implement global option in configuration?

**Comment by elhigu** [comment]
@ravshansbox I agree that `fromRaw` doesn't solve this problem at all, just adds shortcut to `.from(knex.raw(...))` which is not nice either. I would say that if it will be implemented, it would be at first only for oracle dialect and instead of parsing + quoting it would just validate + use without quotes to prevent SQL injection stuff. 

We may continue this discussion if someone seriously considers implementing / testing / documenting this feature.

**Comment by atiertant** [comment]
@elhigu @ravshansbox i'm not sure using unquoted column/table name is the best way too... but `fromRaw` would be at least in the knex spirit and could be useful for many other things...

**Comment by elhigu** [comment]
@atiertant I'll add it as a separate issue, it is just a missing API which I didn't even knew didn't exist

**Comment by jtal** [comment]
This a problem for Oracle users. It would be nice to optionally remove the quotes or force the case to upper (as Oracle does for table names).

If not, knex users who have Oracle need to change all of their scripts / queries to use quotes and if they use third party software (for example for reporting) they'll need to contact those companies to ask them to add quotes.

Is there anyone working on this in knex?

**Comment by elhigu** [comment]
@jtal I don't believe that anyone is working on this. I fail to see the point how 3rd party software generated queries would require changes? 

One can run queries like that already by using `knex.raw('select * form NonQuotedTableName')`.

**Comment by atiertant** [comment]
@elhigu @jtal we could add an option to make formater to not add quote but i'm sure there are many hardcoded quote in the code...

**Comment by jtal** [comment]
@elhigu Yes I am aware of the existence of knex.raw() but I am talking software that does not use knex but accesses the same Oracle database that knex accesses.

The app that uses knex comes in and creates lower case tables for example. Every other client application that connects to the database assumes the table name should be all caps by default because that is how Oracle works. Default is caps, for anything else use quotes.

If the "other software" are shell scripts that generate SQL then you just have to go through any that have been affected by knex and add quotes. If its an ORM or datawarehousing / business intelligence suite hopefully you can inject quotes into the name of the table itself. So, raw() is not the answer.

If you are doing a small project with Oracle or if its a bigger project but you have control over all the parts, this will just be something you have to deal with.

But if you are, for example, the downstream user of a large project which indirectly uses knex because of infrastructure below that is not under your control, this issue is going to be really annoying.

**Comment by sant123** [comment]
Hi, is there some advance to this issue? Thanks.

**Comment by elhigu** [comment]
In next release you will be able to create custom quoting functionality https://github.com/tgriesser/knex/issues/2084

**Comment by Gabriel-Aquino** [comment]
> @elhigu like `whereRaw` for where clause, you could use `fromRaw` to add raw in from clause, like this you could do: `knex.select('*').fromRaw('table')`

Thanks bro! It works for me. I basically have used:

.select()
      .fromRaw('myschema.mytable');

and query was wrote as: select * from myschema.mytable.

before it, was: select * from "myschema"."mytable" and it was throwing an error. Thank you!!!
