### ISSUE TITLE
DeprecationWarning: Using Buffer without `new`...

### ISSUE THREAD

**Issue by jonstuebe** [tgriesser/knex#1763]
I'm getting a deprecation warning on node 7.0.0:

`DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.`

**Comment by ravshansbox** [comment]
I'm also getting this warning.

**Comment by AlexTes** [comment]
It's not knex' code causing this warning. The warning is caused by one or more of the following dependencies:
* 1 node_modules/babel-generator/
* 1 node_modules/bl/
* 1 node_modules/deep-equal/
* 1 node_modules/fsevents/node_modules/bl/
* 1 node_modules/pg/
* 1 node_modules/util/
* 2 node_modules/buffer-writer/
* 2 node_modules/mocha/
* 6 node_modules/safe-buffer/
* 14 node_modules/packet-reader/
We should update the packages that have fixed their use of the deprecated buffer creation. And create issues / PR's with the one's that haven't.
