### ISSUE TITLE
Relation "users" does not exist (Postgres)

### ISSUE THREAD

**Issue by spamguy** [tgriesser/knex#1770]
I honestly don't know if this is a knex thing, a node-postgres thing, or a Postgres thing.

Let's say I have a database 'diplomacy', a public schema, and a table 'users' (all lowercase). I have an app of which its first query is [getting a user account by its email address](https://github.com/spamguy/diplomacy/blob/master/server/cores/user.core.js). It errors immediately. knex's debug output:

    1|dipl.io  | { method: 'select',
    1|dipl.io  |   options: {},
    1|dipl.io  |   timeout: false,
    1|dipl.io  |   cancelOnTimeout: false,
    1|dipl.io  |   bindings: [ 'email@email.com', 1 ],
    1|dipl.io  |   __knexQueryUid: '2e057a84-e702-40fa-81cd-201888efe618',
    1|dipl.io  |   sql: 'select "id", "email", "password", "password_salt" from "users" where "email" = ? limit ?' }
    1|dipl.io  | error:  error: relation "users" does not exist
    1|dipl.io  |     at Connection.parseE (/var/www/diplio/node_modules/pg/lib/connection.js:554:11)
    1|dipl.io  |     at Connection.parseMessage (/var/www/diplio/node_modules/pg/lib/connection.js:381:17)
    1|dipl.io  |     at Socket.<anonymous> (/var/www/diplio/node_modules/pg/lib/connection.js:117:22)
    1|dipl.io  |     at emitOne (events.js:96:13)
    1|dipl.io  |     at Socket.emit (events.js:188:7)
    1|dipl.io  |     at readableAddChunk (_stream_readable.js:176:18)
    1|dipl.io  |     at Socket.Readable.push (_stream_readable.js:134:10)
    1|dipl.io  |     at TCP.onread (net.js:551:20)

The table definitely exists, it's spelled in lowercase, and my DB user has all privileges on it. If I enter psql using the same credentials as knex and paste this query verbatim, it runs fine. Weirder still, [I have a node script](https://github.com/spamguy/diplomacy/blob/master/import.js) that runs fine using the exact same knex object.

I wish I knew more. It doesn't happen on my local machine, just my Ubuntu production environment. I tried user sockets and hostnames for authentication. I couldn't arrange a remote debugging through `node --inspect`, so I'm mostly guessing what's going on.

**Comment by elhigu** [comment]
Try to connect to your remote db with `psql` when you get that right (remember to explicitly tell username, password and selected database). 

Sounds like you are not connecting the correct DB server or database just isn't initialized, I'm sure this has nothing to do with knex. 

That error is returned directly from your database knex doesn't have much to do with it. According to your DB you have connected to some database, but there is no table called "users". 

Also try running your code with DEBUG=knex:* environment variable. That might show something interesting.

I'll close this issue since for now this doesn't seem like a bug in knex. You can keep on commenting here if you still have problems.
