### ISSUE TITLE
how to reset column selection for query?

### ISSUE THREAD

**Issue by helios1138** [tgriesser/knex#1779]
IIRC, previously it was possible to call something like `q.select(null)` to reset previously added column names. 
Currently it seems that you can only append new columns to the selections but no way to clear/replace them

**Comment by alechirsch** [comment]
+1

**Comment by elhigu** [comment]
That has never been documented feature, at least I wouldn't like that clearing columns of select would be done by overloading the same call with magic value like `.select()` e.g. `.clearSelect()` would be a lot more robust API... 

But knex doesn't really support of taking out parts of query and I don't think it should go to that road right now since it will add bunch of more surface for errors (there is already very small amount of people maintaining the current code base).

Having possibility to clear only select won't add much value to library without having possibility to modify all parts of the query.

**Comment by wubzz** [comment]
`.clearSelect()` exists, closing.
