### ISSUE TITLE
Knex Performance

### ISSUE THREAD

**Issue by scf4** [tgriesser/knex#1795]
I'm connected to a Postgres database and testing performance of very simple queries.

It seems there's a ~100ms overhead on building queries:

````
await db('items').whereIn('id', [1, 2]);
````
~220ms

````
await db.raw('select * from "items" where "id" in (1, 2)');
````
~112ms

Is this expected? 100ms is quite a long time IMO. The raw query is the exact same query the first example executes.

Update:

````
await db.raw(db('items').whereIn('id', [1,2]).toString());
````

This performs about as well as the raw example. What is Knex doing that takes an extra 100ms and how can I disable it?

**Comment by elhigu** [comment]
You are benchmarking it wrong... no idea why it takes so long without seeing actual code.

```js
const knex = require('knex')({ client: 'pg', connection: 'postgres///knex_test' });
const _ = require('lodash');
Promise = require('bluebird');
const start = new Date().getTime();
knex.transaction((trx) => {
  return Promise.mapSeries(_.range(10000), () => trx.raw('select 1'));
}) .then(() => console.log("10k queries inside single connection took", new Date().getTime() - start, "ms"));
```

on my laptop it was ~2.5 seconds for 10k queries.

**Comment by seeden** [comment]
@elhigu on my mac book laptop same query took 140seconds. How did you get your good score?

**Comment by elhigu** [comment]
node v6.2.1, knex 0.12.6

```
$ node knexquerytest.js
10k queries inside single connection took 2404 ms
```

You need to kill tests program after it has done the queries, because I didn't call knex destroy() in the end. How did you manage to get 140 seconds?

**Comment by scf4** [comment]
I'm having some performance issues with knex again and only just saw your response @elhigu 

Try this out: https://gist.github.com/scf4/10af79a95d17aa9692a3e63e2baf0e1a

1000 queries with knex.raw takes 263ms

1000 queries with regular pg takes 15ms;

100 queries takes 57ms and 1ms respectively.

A single query takes 5ms and 1ms.

**Comment by elhigu** [comment]
@scf4 do you know what are you benchmarking exactly with that code? 

As far as I can see all the test code in the gist should be actually DB bound and the test setup should hide all the differences of node.js side execution, since test code is generating queries concurrently and then just waiting that they are sent through the DB connection.

Anyways the speed difference is interesting... and I don't see any reason why there should be that big difference... are node-postgres versions used by knex and  direct pg code the same? One possiblity would be that pg driver actually accepts more queries to be sent to DB before response of earlier query has arrived. But AFAIK that has not been supported by pg...

Can you run the code with DEBUG=knex:* to get more information what is taking so long with knex?

**Comment by google-master** [comment]
let r = [];
  for(let i = 0; i < num; i++ ) {
    r.push( await fn() );
  }
//  let r = await Promise.all(Array(num).fill(fn()));
  console.log(r)
...
`select random()`
... then, results are almost the same

**Comment by himharsh1997** [comment]
> node v6.2.1, knex 0.12.6
> 
> ```
> $ node knexquerytest.js
> 10k queries inside single connection took 2404 ms
> ```
> 
> You need to kill tests program after it has done the queries, because I didn't call knex destroy() in the end. How did you manage to get 140 seconds?
> 
> @seeden are you testing against local or remote database? If you use remote DB this test should run really slow, because it makes really small queries and always waits small response before continuing, so each query will be slowed down by latency of TCP roundtrip time...

select 1 doesn't require to go to any table so can't decide the performance base on your example.
