### ISSUE TITLE
Error: pool is draining and cannot accept work

### ISSUE THREAD

**Issue by finalight** [tgriesser/knex#1818]
I have this problem; inserting the record then reading out from it again

```
 knex
            .insert(body, 'id')
            .into('product_categories')
            .then(function(result) {
                // knex.destroy();
                // knex = initConnection();
                if (result.length > 0) {

                    return knex('product_categories')
                        .where('id', result[0])
                }

            }).then(function(rows) {
                console.log(rows);
            })
```

I not sure how to resolve this issue

**Comment by elhigu** [comment]
I'm pretty sure that you example code doesn't output that error message, because knex.destroy() is commented out. 

Why are you destroying knex instance, between inserting and reading?

I don't know what is inside initConnection(), but I suppose that error shouldn't happen if both of the commented lines are uncommented. If only knex.destroy() is uncommented you should be getting that error, because you tell knex to destroy and then immediately after you are trying to do query.

**Comment by finalight** [comment]
no, the error is exactly as I've stated, with regards to the codebase that I've given above. Codes are commented on purpose and I've forgot to remove it.

but anyway I've managed to solve the error with this codebase instead

```
knex.transaction(function(trx) {

            knex.insert(body, 'id')
                .into('product_categories')
                .transacting(trx)
                .then(function(result) {
                    return knex('product_categories')
                        .where('id', result[0])
                        .transacting(trx);
                })
                .then(trx.commit)
                .catch(trx.rollback);
        })
        .then(function(result) {
            console.log(result);
            knex.destroy();
            callback(null, result);
        })
        .catch(function(error) {
            knex.destroy();
            console.log(error);
            callback(error);
        });
```

**Comment by elhigu** [comment]
great
