### ISSUE TITLE
Execute knexjs by some pre-saved object

### ISSUE THREAD

**Issue by calebeaires** [tgriesser/knex#1821]
I need to work with this library using functions like procedures by pre-saved object

I have this this object:
```
 let query = {
     select: ['id','name','city'],
     from: 'users'
}
```

Knex works with functions

```let sql = knex.select('id','name','city').from('users');```

I need something like this (make key from an object call those function):

```
let sql = knex.queryObject({
     select: ['id','name','city'],
     from: 'users'
});
```

Is there some extension that do that?

**Comment by wubzz** [comment]
@calebeaires This sounds like a very special case and I don't personally see it befitting the knex API. What do you think @tgriesser ?

In any case since knex does not make any assumptions in the order of function calls to the query builder, you could make your own simple wrapper function that does this for you.

```javascript
let queryBuilder;
Object.keys(query).forEach((key) => {
    const fnArgument = query[key];
    if(!queryBuilder) {
        queryBuilder = knex[key](fnArgument);
    } else {
        queryBuilder[key](fnArgument);
    }
});
```

Maybe not the most elegant example but I think you can understand what I mean by this

**Comment by elhigu** [comment]
sounds like it would be better to implement as separate module... I don't know that there is currently anything like that already.
