### ISSUE TITLE
Insert gives "duplicate key value violates unique constraint 'table_pkey'"

### ISSUE THREAD

**Issue by SaintDako** [tgriesser/knex#1855]
Hi! Currently running into what seems to be some sort of "sync" problem with Knex + Postgres. When I run the following:

```
knex('levels')
    .insert({
        levelName: "Not unique!"
    });
```

I get the following error:

```
Unhandled rejection error: 
                    INSERT INTO "levels" ("levelName")
                    VALUES ($1)
                 - duplicate key value violates unique constraint "levels_pkey"
```

The primary ID for this table is `levelId`, so I hardcoded it to the next value and it worked fine. Thus, I'm assuming that knex doesn't "know" of the current serial value.

When I run a select and then chain the insert, it works fine:

```
knex.select()
    .table('levels')
    .limit(1)
    .then((rows) => {
        // do nothing with result
        return knex('levels')
            .insert(...)
     })
```

Am I doing something wrong?

**Comment by SaintDako** [comment]
Update: the "select then insert" approach is also not working now... I'm stumped.

**Comment by SaintDako** [comment]
Found the problem! It's because I was inserting the primary key column's value with each row in my bootstrap file, which wasn't actually updating the table's auto_inc value. Entirely my fault. Sorry!

**Comment by janoist1** [comment]
@Dakkers Many thanks for exposing this, I've also ran into it. 👍

**Comment by dyllandry** [comment]
@Dakkers Same solution here. Manually inserting ids anywhere will not update the table's auto_inc value, so it will try an insert with id=1 to start and run into already existing and conflicting rows.

**Comment by JoeChapman** [comment]
This was a big help, thanks

**Comment by evasyuk** [comment]
I am very glad that everyone of you ran into this trouble and noone explained how to fix that.

In order to get rid of this problem you need to perform manual counter reset to appropriate number.

example query to run: ALTER SEQUENCE product_id_seq RESTART WITH 1453
how to find 'product_id_seq' using DBeaver: open desirable table, open details for exact column, take a look at pkey_constraint

<img width="1680" alt="Screenshot 2019-11-30 at 00 19 50" src="https://user-images.githubusercontent.com/4641605/69891709-4b76d800-1307-11ea-8915-717cc62df38b.png">
![Uploading Screenshot 2019-11-30 at 00.19.43.png…]()

**Comment by evasyuk** [comment]
I am very glad that everyone of you ran into this trouble and noone explained how to fix that.

In order to get rid of this problem you need to perform manual counter reset to appropriate number.

example query to run: ALTER SEQUENCE product_id_seq RESTART WITH 1453
how to find 'product_id_seq' using DBeaver: open desirable table, open details for exact column, take a look at pkey_constraint

**Comment by dyllandry** [comment]
> I am very glad that everyone of you ran into this trouble and noone explained how to fix that.
> 
> In order to get rid of this problem you need to perform manual counter reset to appropriate number.
> 
> example query to run: ALTER SEQUENCE product_id_seq RESTART WITH 1453
> how to find 'product_id_seq' using DBeaver: open desirable table, open details for exact column, take a look at pkey_constraint

The fundamental problem: Don't manually insert primary keys because postgres' auto_increment value will not update, and when it is later used to automatically set a new row's primary key, it will conflict with an existing row.

Somewhere in resolving this problem, if you do want to take advantage of postgres' auto increment feature, you must stop manually setting new rows' primary keys and modify the auto_increment value to catch it up.

If you're confused, ask for clarification. Please don't insinuate that everyone who took the time to contribute here is unhelpful.

**Comment by evasyuk** [comment]
@dyllandry IMHO you are facing in the wrong direction. Seems like I should agree that problem is fundamental and you has to avoid inserting primary_key within your business logic, but I faced this problem after perfoming 'batchInsert' operation. In this case I can not avoid insert of primary_keys operation. Seems like this problem is inavitable, while you are still quite right

**Comment by dyllandry** [comment]
@evasyuk right. If you have to do it, just be aware auto_inc must be caught up.

**Comment by evasyuk** [comment]
so far the best solution described in the similar topic: https://github.com/knex/knex/issues/2130

**Comment by CEXYRaj** [comment]
@evasyuk  how do you know which number to put in the following query 
ALTER SEQUENCE product_id_seq RESTART WITH 1453

**Comment by evasyuk** [comment]
@

> @evasyuk how do you know which number to put in the following query and when to run this one
> ALTER SEQUENCE product_id_seq RESTART WITH 1453
> 
> I am facing the same issue and using "batchInsert"
> 
> my function is as following
> 
> `createChunkData() { `return` new Promise((resolve, reject) => { knex.batchInsert(`sys_${this.entity}`, this.CHUNK, this.CHUNK_SIZE) .returning('id') .then(ids => this.updateReindexIds(ids)) .catch(reject) .finally(resolve); }); }`

Too hard to even understand your problem..

but if you face the same problem(you added manually items with 'primary_key' values), the best solution would be to reset 'primary_key' counter to the biggest number in your 'primary_key' column

PROS: it should work

CONS: once you set 'primary_key' manually, you might loose a lot of numbers to be primary.
for example, you added 2 items with 'primary_key' 1, 1444443  => doing max('primary_key') will give you 1444443 => you will loose ability to use number from 2 to 1444442 (unless you will set them manually via batchInsert again)


<img width="820" alt="Screenshot 2020-03-26 at 17 29 49" src="https://user-images.githubusercontent.com/4641605/77664963-9e942b00-6f87-11ea-9234-968d5b24a4cb.png">
