### ISSUE TITLE
new feature for support schema load ?

### ISSUE THREAD

**Issue by chenghung** [tgriesser/knex#1862]
The rails framework generate a schema.rb file after running migration.

New comer of project developer can quickly prepare their development database by load schema instead of running hundreds migrations.
Also developer can quickly prepare testing database by load schema too.

Is it possible that knex support rails-like schema mechanism ?
for example:
1. generate a schema.js or schema.json after running migration
2. add command 'knex schema:load' for load schema.js

**Comment by elhigu** [comment]
1. it is possible, but sounds like a really hard to implement properly
2. would be easy if there would be a way to load schema

I haven't got any problems to run all migrations when initializing development database. When running tests, running migrations has not been bottleneck either, since I run migrations just once when test suite starts and between tests I just truncate all the sequences and tables, so I don't have to drop DB and initialize schema again. Truncating is actually also a lot faster than drop, create, load schema at least with postgresql (milliseconds vs. hundreds of milliseconds).

This issue is also probably a duplicate, there has been quite a lot of discussion of schema files earlier.

**Comment by wubzz** [comment]
@chenghung @elhigu Is this an open feature request or can this be closed?

**Comment by elhigu** [comment]
This can be closed. If someone is up to task of writing this support in separate lib and if it is well implemented we may recommend it in knex documentation and even support some kind of integration layer to it if it helps its usage.
