### ISSUE TITLE
Support for scalar values in .on, .andOn, etc. or similar

### ISSUE THREAD

**Issue by boutell** [tgriesser/knex#1923]
Right now if I need to compare something to a scalar value (a simple string I'm passing in) in an "on" clause I have to write:

```
          q.leftJoin('opinions as my_opinions', function() {
            this.on('my_opinions.post_id', 'posts.id');
            this.onIn('my_opinions.user_id', [ query.my_user_id ]);
          });
```

How about:

```
this.onScalar('my_opinions.user_id', query.my_user_id)
```

It would make sense to also have `andOnScalar` and `orOnScalar`.

**Comment by blackmatch** [comment]
I really want this.

**Comment by elhigu** [comment]
There are much more in this issue to have overall better ways to do identifier references without need to use knex.raw everywhere and this one would be the other way around.

I would prefer some other way to achieve this than duplicate every API with variants for referring values instead of identifiers. Something like: 

`this.on('my_opinions.user_id', literal('im not identifier'))`

**Comment by wubzz** [comment]
Closing in favour of #2707
