### ISSUE TITLE
[Help]: need figure out how to do Read/Write Splitting with mysql

### ISSUE THREAD

**Issue by qimenxiaozi** [tgriesser/knex#1951]
As i know mysql now support cluster model,  could you please help me to figure out how to do Read/Write Splitting with knex?

**Comment by elhigu** [comment]
How do you do read/write splitting with mysql driver? Do you have separate IP where to send reads and other for writes or does mysql know how to route queries correctly from any of the nodes?

**Comment by qimenxiaozi** [comment]
yes. i use separate IP.
an example code for node-mysql as below:
var mysql = require('mysql');
let pool = mysql.createPoolCluster();
pool.add('master', {
	// master config
});
pool.add('slave', {
	// salve config
});

**Comment by elhigu** [comment]
Sounds like you need to create 2 knex instances, one for master and one for slave and select by hand each query where to send them... What happens if master goes down? Is one of the slaves promoted to master automatically? How the client code gets information about that? Is there list of IPs in slave configuration?

Sorry, I don't know exactly how mysql clustering works and I don't have time to look into it right now, so I might not be much of help.
