### ISSUE TITLE
knex violates promises contract on del()

### ISSUE THREAD

**Issue by jmilkiewicz** [tgriesser/knex#1952]
Hey

I think I found a pretty nasty bug regarding promises changing its value when using del().
I am not sure if other operations (like update) and/or other database engines are affected, but for sure this problem on  Postgre  kiasaki/alpine-postgres  and knex v0.12.7.

The problem is:
1  insert a singe row to db:
`db('documents').insert({customer_number:1, contract_number:'b',document_number:222,contract_number_prefix:'ab'}).then(console.log)`
2. Delete via del()
`var res = db('documents').del();`
3. resolve returned promise more than once:
`res.then(console.log)` returns 1  (OK)
`res.then(console.log)` returns 0 (Incorrect)
`res.then(console.log)` returns 0 (Incorrect)
`res.then(console.log)` returns 0 (Incorrect)

Why a subsequent resolving promise returns different value - first 1 and then 0 ?

**Comment by wubzz** [comment]
@jmilkiewicz Knex does not create a "single promise" when you use it like in your example. `res` is still just a query builder, not a promise. Everytime you call `.then` on res, a real  DELETE query is being run on the database. The first time you run it the previously inserted row is deleted, so the resolved result is 1, as in one row deleted. The next few times you run it, there are no more rows to be deleted, which is why the resolved result is 0.

`.del()` always returns the number of affected rows. So this is correct behaviour.

**Comment by jmilkiewicz** [comment]
@wubzz 
So `res` having  a promise like interface (`then` method) is not a promise but is only a query builder ?  Do i get it right ?

**Comment by wubzz** [comment]
Yes, that is one way to put it. `.then` executes the query builder.

**Comment by elhigu** [comment]
@jmilkiewicz any object with `.then()` method in Promise A+ spec is called `thenable`. As far as I remember specs doesn't say that calling `.then()` twice for thenable always  must return the same value (would be nice though, but also would prevent to trigger the same query builder multiple times).

**Comment by jmilkiewicz** [comment]
@elhigu 
If you claim that del returns a promise than you are clearly violating promise contract. Look at https://promisesaplus.com/#requirements - it is clearly stated that value/reason MUST not change when promise is fulfilled/rejected. So then/catch shall be free of side-effects - no SQL delete shall be executed if you chain it with "then".
IMHO documentation shall be updated to state that del (i do not know if other methods suffer from the same problem) returns "thenable" which is NOT a promise.

**Comment by elhigu** [comment]
@jmilkiewicz I'm **not** claiming that `del()` returns **promise**. It **returns** `QueryBuilder` which is **`thenable`**.

If documentation says that some of the `QueryBuilder` methods are returning `Promise` the documentation is wrong (I didn't find anything that claims QueryBuilder being Promise, but it has an API to interact with Promises). 

```js
// instance of QueryBuilder
let queryThenable = knex('foo').del(); 

// instance of Promise (bluebird promise actually)
let resultPromise = query.then(res => res); // res == 1 (one row in the table)

// through the promise result won't change and query won't be triggered again
resultPromise.then(res => console.log("res is still 1:", res));

// through the thenable query is triggered again
resultPromise.then(res => console.log("res should be now 0:", res));
```

**Comment by jmilkiewicz** [comment]
@elhigu 
I was just about to write if you didn't make a mess with variables...
To make myself clear: i know how to work with del() to return number of rows removed and consume that information many times: `del().then(_.identity)`.
Nevertheless i still think that the design decision to let del() return something you can "treat" like promise (then/catch methods) but at the same time clearly violating promise contract is simple a mistake. More, documentation does not mention a word on that promise contract violating behaviour.
For me a documentation is clear: 

> Coerces the current query builder chain into a promise state, accepting the resolve and reject handlers as specified by the Promises/A+ spec. As stated in the spec, more than one call to the then method for the current query chain will resolve with the same value, in the order they were called; the query will not be executed multiple times.

IMHO it means that executing  `then` multiple times on QueryBuilder must resolve with the same value each time.

**Comment by elhigu** [comment]
You are right, that part of docs is wrong, thanks for showing the place. There is probably huge amount of code that relays on a fact that queries can be triggered multiple times by calling `.then()` multiple times so it would be huge change for the users if implementation is changed.

Documentation should say that `.then()` returns a promise instead of changing the state of query builder to be read-only and to act like a Promise. I'll open an issue about it to doc branch.

Both ways are correct according to Promise specs. It is more the matter of taste how one would like to use the library. 

This is only my opinion that the current way triggering query multiple times is actually better. If `QueryBuilder` mutates to read-only state every time when `.then()` is called it would force people to do something like `query.clone().then()`to allow to trigger the same query builder multiple times. 

Other way around I rarely use result directly read from database, but map the values somehow before. So if there is need to use them again mapped value works fine and won't trigger new queries. I don't remember ever having to create dummy promise with `.then(_.identity)` just to prevent re-executing the query. IMO current way has less clutter when writing code.

Actually I would prefer each query builder to be immutable and always return new object when builder methods are called... I can understand if someone else likes it better some other way.

Anyways... looks like documentation of `.then` needs to be fixed and how `.then` behaves in the future is up to @tgriesser to decide (he has mentioned in some issues that he doesn't like the current way either).

**Comment by jmilkiewicz** [comment]
thx for information. 
If i were to design it i would make a queryBuilder immutable. It would allow one to use chain methods for where, group, sort, projection and so on. The queryBuilder would have 3 "termination" methods (probably with arity 0): select, delete, update. 
All of them would execute the query and return a promise (as queryBuilder is immutable - they will never mutate it).
So if one would like to reuse a particular query, would need ti store queryBuilder and simple call one of terminating methods to re-execute.

You are right that in most cases you will map result of your query in `then,` but my query was simply a "delete", so there is nothing to map....
