### ISSUE TITLE
Empty error

### ISSUE THREAD

**Issue by RWOverdijk** [tgriesser/knex#1966]
```js
var knex = require('knex')({
  client: 'sqlite3',
  useNullAsDefault: true,
  connection: { filename: "./mydb.sqlite" }
});

knex.transaction(transaction => {
  transaction.rollback().catch(() => {
    console.log('Not called.');
  });
}).catch(() => console.log('This is where it all goes to.. Poop.'));
```

Remove the last catch, and you'll find yourself an unhandled rejection undefined. It took me a long time to track down.

Why does the rollback not fail? What's the purpose of .transaction() being a promise that can reject here?

**Update:** I haven't tracked down the place that actually rejects.

**Comment by wubzz** [comment]
@RWOverdijk The 'catch' handlers argument is `undefined` because `.rollback` was not given an argument such as an Error object it would normally get. Basically issuing a rollback without a given "error" reason. Of course this is ok and works, but the end result is that the error handler receives `undefined`, which is expected behavior at that point.

The rejection happens here: https://github.com/tgriesser/knex/blob/master/src/transaction.js#L125

And the rejection always happens on the "main" promise generated from `knex.transaction((tr) => {})` which is why the outer catch is called, so calling `.catch` on `.rollback` has no effect, . Also, errors are already caught in the query runner: https://github.com/tgriesser/knex/blob/master/src/transaction.js#L117

I'm pretty sure @tgriesser had thoughts on addressing some of these limitations in 1.0, unless I'm mistaken?

**Comment by RWOverdijk** [comment]
@wubzz Indeed, I found that earlier today. It's weird to me, though. I'd expect it to use whatever is returned from within the callback itself. Not actual rollbacks. I've made my peace with the implementation and worked around it.

**Comment by elhigu** [comment]
Mikael Lepistö @elhigu 10:08
@RWOverdijk afaik transaction is started at the same moment when knex.transaction() is called... what exception are you getting when running rollback() I think it should never fail, just silently ignore for example if connection was broken before running it... what do you think that would be the correct functionality here?

Wesley Overdijk @RWOverdijk 10:20
@elhigu I expect no exception at all.
But if I do get an exception, I expect it to not be undefined.

Mikael Lepistö @elhigu 10:21
hmm.. doesn't rollback causes transaction to reject? so exception is undefined because you didn't pass argument to rollback?

Wesley Overdijk @RWOverdijk 10:22
@elhigu No. If you actually do something the rollback doesn't cause an exception.

Mikael Lepistö @elhigu 10:22
so if you do transaction.rollback(new Error('poop'))

Wesley Overdijk @RWOverdijk 10:22
It's just if you don't execute any queries, then it throws.
Just like the docs say, I just disagree. Especially with the undefined part.
Never reject with undefined. It's nearly impossible to track down.

Mikael Lepistö @elhigu 10:23
hmm.. did you check what is happening with DEBUG=knex:* I didn't know it is possible to start transaction without queries (every transaction starts with BEGINquery)

Wesley Overdijk @RWOverdijk 10:24
@elhigu Except if your code throwns an exception before starting a query
The gist is a working example.
All it needs is sqlite3 and knex.

Mikael Lepistö @elhigu 10:24
ok, so that callback is executed before begin query is sent?

Wesley Overdijk @RWOverdijk 10:26
@elhigu
  knex:tx trx1: Starting top level transaction +0ms
  knex:query BEGIN; +9ms
  knex:query ROLLBACK; +5ms
  knex:tx trx1: releasing connection +4ms
This is where it all goes to.. Poop. undefined

Mikael Lepistö @elhigu 10:27
and if you do
 knex.transaction(transaction => {
  transaction.raw('select 1').then(() => {
    transaction.rollback().catch(() => {
      console.log('Not called.');
    });
  })
}).catch(() => console.log('This is where it all goes to.. Poop.'));

Wesley Overdijk @RWOverdijk 10:28
?
That's what I have
 knex.transaction(transaction => {
  transaction.rollback().catch(() => {
    console.log('Not called.');
  });
}).catch(error => console.log('This is where it all goes to.. Poop.', error));
ah
you changed it

Mikael Lepistö @elhigu 10:28
yep, I still can't use gitter snippets :grinning:

Wesley Overdijk @RWOverdijk 10:28
That still throws an exception

Mikael Lepistö @elhigu 10:28
works different to slack

Wesley Overdijk @RWOverdijk 10:29
 // If we get here, that means that neither the 'Old Books' catalogues insert,
// nor any of the books inserts will have taken place.
I think I understand.
It always throws if there's a rollback
The undefined is because I don't reject with anything
That's very weird to me

Mikael Lepistö @elhigu 10:30
So you would like to be able to swallow the exception caused by rollback() by adding .catch() as you have done... maybe I get it now.

Wesley Overdijk @RWOverdijk 10:31
I'd expect .rollback().catch()
Not .rollback() and the catch on the thing that accepts a callback
Which, if it fails, I'd say is because the database is unavailable or something
Once I have the transaction, that's the thing I want to catch

Mikael Lepistö @elhigu 10:36
yeah... I think that it would be nice if both could be used to catch the exception... first rollback() and if it doesn't then the transaction, which resolves / rejects depending if you catched the exception already in rollback. But I have no idea how to implement that nicely. Because rollback() call which actually passes information about the rejection of the transaction doesn't know if the promise returned by it is going to catch the exception...
and how knex works is that knex.transaction() returns the transaction promise and thing that is passed to (trx) => {} callback is the transaction connection.
Api you are trying to do would be pretty annoying to implement, because it would need to create fake promise returned by rollback() whose .catch() method would tell how to resolve the transaction promise returned by knex.transaction.

Wesley Overdijk @RWOverdijk 11:13
Yeah I know. It made it difficult for me to handle nice, multi-adapter transactions.
But it works now, it's fine. I know I catch the exceptions, therefor I can safely use it the way I want.

**Comment by joepie91** [comment]
> The 'catch' handlers argument is `undefined` because `.rollback` was not given an argument such as an Error object it would normally get. Basically issuing a rollback without a given "error" reason. Of course this is ok and works, but the end result is that the error handler receives `undefined`, which is expected behavior at that point.

While I understand the technical explanation, I'd still consider this a usability stink that needs to be resolved. It's commonly understood that "while you can reject/throw with non-Error values, you should never actually do that" (precisely because of this "missing stacktrace, impossible to debug" scenario).

Would it then not make sense to detect when there's going to be a rejection with something that isn't `instanceof Error`, and instead reject with a substitute Error, something along the lines of `new Error(`Rejected with non-Error value: ${err}`)`? That would at least give the user a stacktrace with an approximate source.

**Comment by wubzz** [comment]
@joepie91 I'm perfectly fine with addressing the issue of rejecting with `undefined`, couldn't agree more. My intention was only to explain what was happening.

Not entirely convinced what the "default" rollback message would in that case be.

**Comment by wubzz** [comment]
#1970
