### ISSUE TITLE
Database connection is not correctly destroyed after knex 0.12.2

### ISSUE THREAD

**Issue by kirrg001** [tgriesser/knex#1973]
Hey 👋

I have recently updated knex from `0.12.2` to `0.12.7` and noticed that the database connection is not closed when calling `connection.destroy`. The result is, that a process doesn't exit.

Here is a snippet:
```
....
this.connection = knex(...);

return this.connection.transaction(function(txn) {
   return doSomething(txn)
       .finally(function() {
           return self.connection.destroy()
                .then(function () {
                    debug('Destroyed connection');
                });
       });
})
```
NOTE: debug('Destroyed connection') get's called.

**I have tested all knex versions and it starts in `0.12.3`.**

The code works for me with `0.12.2`, but does not with `0.12.3`.
Is there anything i can change in my code to get it working with > `0.12.2`?

Otherwise, I went through the changes, maybe related to the pool update https://github.com/tgriesser/knex/pull/1702?

Thank you so much!
Kate

**Comment by wubzz** [comment]
Based on the changelog I would guess #1731 causes this in some way. Some changes to `acquireConnection` was done so that connections are properly returned to the pool.

**Comment by kirrg001** [comment]
I have tested with MySQL only. Tested multiple `mysql` versions.

**Comment by wubzz** [comment]
@kirrg001 Ah yes, makes sense the timeout would cause the process not to exit, but it also makes sense why @tgriesser added it. In order to properly release connections back to the pool, the two handlers must be seperate for `TimeoutError` and `pool.acquire`, and so a timeout check is inevitable.

I agree `clearTimeout` should be called when an error occurs as well.

Does your app's process "eventually" exit, or does it idle beyond `acquireConnectionTimeout` with its default value of `60000` ms?

Unfortunately I don't have an answer to this problem right now. Will try look into this some more.

**Comment by kirrg001** [comment]
> Does your app's process "eventually" exit, or does it idle beyond acquireConnectionTimeout with its default value of 60000 ms?

It exits after the timeout.

My use case is a bit complex and 3 database connections are created, one of these connections can throw an error at the moment if the database does not exist, knex tries to acquire a connection to this target database and fails. That's why clearing the timeout solves this issue for me. Thanks for your fast support here.

**Comment by wubzz** [comment]
@kirrg001 I see, I thought your app remained idle eventhough all attempts of acquiring connections were successful, but I understand now that's not the case.

I'll merge this in right now, definitely a bug. Thanks for the report!

**Comment by wubzz** [comment]
@kirrg001 FYI: Pushed 0.12.8

**Comment by kirrg001** [comment]
Thanks so much 🐩
