### ISSUE TITLE
CreateTableIfNotExist fails in sqllite

### ISSUE THREAD

**Issue by bondz** [tgriesser/knex#2016]
```typescript
async function createOrUpdateTable(tableName: string) {
    await knex.schema.createTableIfNotExists(tableName, (table) => {
      table.increments();
      table.timestamps();
      table.string('tableID').unique().index();
    });
  }
```

Calling the function twice with the same argument fails.

The method fails trying to recreate the `unique index` on the second call.

**Comment by elhigu** [comment]
Duplicate: https://github.com/tgriesser/knex/issues/1303

tldr; When createTableIfNotExists contains unique index initialization it actually generates multiple queries, where the first one is create table and another one creates the index.

So second query will fail when that code is ran second time... probably one shouldn't be allowed to create index inside createTableIfNotExist callback.

Here are printed queries generated from your schema create call:

https://runkit.com/mikaelle/58f669d2546adf0012e0c2e6

I would recommend to never use createTableIfNotExist, because it doesn't do what you like to do most of the times.
