### ISSUE TITLE
bookshelf, needed or not?

### ISSUE THREAD

**Issue by shai32** [tgriesser/knex#2046]
I have a good knowledge in sql and writing complex queries.

I am struggling why should I use bookshelf.js,
it seems that knex provide everything needed for using sql.

is bookshelf main feature is the 'withRelated', if so I can use leftJoin
if its simpler create, I can use insert.

So I am missing something?, should using only knex its ok for full production app?

**Comment by roytz** [comment]
What a stupid question...

**Comment by mattbrunetti** [comment]
It also provides a framework for augmenting database objects, i.e. giving them more methods, so it all around (relationships too) gives you more abstraction on your data.

**Comment by shai32** [comment]
can you give a real world use example for something that is much better to use bookshelf then knex?

do you think bookshelf is  a must for a a professional server api?

**Comment by elhigu** [comment]
@shai32 You need some ORM in addition to knex if you like to be able to automatically convert DB rows to javascript objects, which allows you to fetch related data (for example through many to one relation) automatically as nested object hierarchy instead of just joined attributes (creates lots of data duplication because many joins duplicates parent tables fields for example where there is something-many relation).

ORM's also provides you hooks to do stuff and for example modify query before / after actually executing it and hooks for doing validations before inserts / data updates etc. 

If you are not using any ORM most probably you will end up writing many of the features that ORM provides out of the box by hand. 

Feel free to continue discussion here even that issue is closed.

**Comment by shai32** [comment]
When i am using knex, I am getting the result as  javascript object. so why do i need ORM?

**Comment by shai32** [comment]
anyone?

**Comment by elhigu** [comment]
@shai32 I already listed bunch of reasons in my last comment. TL;DR most importantly to work with related data efficiently and to be able to get different type of JS object for rows from different tables etc.
