### ISSUE TITLE
Does knex have support to temporary tables?

### ISSUE THREAD

**Issue by calebeaires** [tgriesser/knex#2080]
When trying to list a temporary table (mysql), knex does not retrieve data. On the other hand, if I create the same table as not temporary, everything is ok.

Here is the query I am using to retrieve data:

```javascript
                knex.from('users').withSchema('myDatabase').limit(10).offset(0)
                    .then((list) => {
                        console.log(list);
                    });
```

**Comment by elhigu** [comment]
Temporary tables should be possible to create, but I suppose they work only inside single connection. So unless you are using pool with single connection, they probably cannot be used.

**Comment by wubzz** [comment]
Generally a better idea when using temporary tables is to run within a transaction since it will only untilize a single connection.

**Comment by mfbx9da4** [comment]
I am trying to do a join query based on a large array. I would like to:

1. create a temp table from array of values
2. join on temp table

How would I do that?

**Comment by osher** [comment]
IMHO - as it's written now, it will not auto-delete.

If you want to keep using it as a permanent table - (what will leave your code db-provider independent) - then  I advise you to:

create the temporary table with an additional column and fill in that column a value unique for this transaction. This will let you filter the records in that table so that you can delete in the end of that transaction the records which are part of it. This way will work even if your app db-user does not have permissions to create tables.

Another way to do that is add that unique value to the table-name, and drop it completely instead of filtering it. This will require the app-user permissions to create and drop tables, which is usually a security risk, but some work this way anyway.


Alternatively - if you do expect to couple your code with `mysql` - then you may look into creating your table using mysql dependent syntax with something like `knex.raw` .
(im in your situation, but chose to stay db-provider independent).

**Comment by rnd111** [comment]
Is there any example temporary table ? assuming I use a transaction?

**Comment by doronoded** [comment]
I have tried all different variations to create a temporary table in a transaction and then insert values to it, and all my tries failed in an error "Invalid object name".
I've created the table (once using knex schema builder, and also using raw query with "#" at the beggining of the table name to make it temporary) but I get the same error afterwards trying to insert values to it (both using raw, and query builder).
I've tried using a transaction to wrap both queries in, and it didn't work.
Did anyone got this to work, and can share how?
