### ISSUE TITLE
If subquery is originated from different dialect than base query, no errors are thrown and mixed dialect query is generated

### ISSUE THREAD

**Issue by elhigu** [tgriesser/knex#2088]
In tests query from one dialect is created then it is cloned and used as a subquery which is done for other dialect.

It would be better if knex would always use dialect (client) of the base query to select how sub/raw queries are compiled. Not really critical bug, since user should not be combining queries of different clients anyways.
 
Found during this PR:
https://github.com/tgriesser/knex/pull/2063#discussion_r117631922

**Comment by wubzz** [comment]
I added

```javascript
if(this.client.dialect != value.client.dialect) {
    throw new Error('Different dialects detected');
}
```

To `formatter.js` -> `unwrapRaw`. Ironically majority of our unit tests blew up after that, since the [testsql](https://github.com/tgriesser/knex/blob/master/test/unit/query/builder.js#L63) function that asserts the unit tests actually directly alters the client of the builders.

With that said it seems the base client already overwrites the dialect of the binding to the same dialect as the base builder, since the `queryCompiler` that compiles the binding is the [original client](https://github.com/tgriesser/knex/blob/master/src/formatter.js#L94). Example:

```javascript
const sql = clients
        .postgres
        .queryBuilder()
        .select()
        .from('accounts')
        .whereIn('id',
          clients
            .mysql
            .queryBuilder()
            .from('accounts')
            .where({isAdmin: 1})
          )
        .toSQL();

//select * from "accounts" where "id" in (select * from "accounts" where "isAdmin" = ?) -- No backticks `` from mysql
//bindings: [1]
```

**Comment by elhigu** [comment]
I  have vague feeling, that I fixed this one at least partly... lets close and see if it comes up again some day :)
