### ISSUE TITLE
Using Knex without connection, then execute with connection

### ISSUE THREAD

**Issue by andresmatasuarez** [tgriesser/knex#2090]
Hi guys

Let's say I have a service called QueryBuilderService where I have the details of each of the queries I use in my app.

Let's say I have another service, DatabaseService, which uses QueryBuilderService but also takes care of handling transactions and reusing multiple queries (for example, createUser() in DatabaseService calls createUser() and getUser() in QueryBuilderService, within a transaction).

My question is: I am currently using a knex connection inside both services. I create it in DatabaseService and I pass it to QueryBuilderService as a constructor argument. Basically it looks like this:
```javascript
class DatabaseService() {
  constructor() {
     ...
     this.query = new QueryBuilderService(myKnexConnection);
  }

  getUsers() {
    return this.query.getUsers()
    .then(/* do something */);
  }
}

class QueryBuilderService() {
  constructor(knexConnection) {
     ...
     this.knex = knexConnection;
  }

  getUsers() {
    return this.knex.select('users');
    //etc etc etc
  }
}
```

I want to get rid of that dependency: I want QueryBuilderService to use knex as a query building library only and no longer receive the connection in the constructor. I know this can be achieved, what I don't know is how to specify the connection from the "outside" (when calling any QueryBuilderService method  from DatabaseService).

Do you guys have any idea?

Thanks in advance!

**Comment by wubzz** [comment]
I might be mistaken but I think you're confusing `myKnexConnection` with an instance of `require('knex')({...})`. The knex instance is not a connection in itself, all that stuff is handled "in the background" of knex, so to speak. See pool settings in initialize.

Spontaneous response is you won't be able to completely get rid of having to supply the argument one way or the other, but perhaps an idea is to have static methods in order to lose the need for a constructor. For example:

```
const dbClient = require('knex')({...});

class DatabaseService {
	static getUsers() {
		return QueryBuilderService.getUsers(dbClient);
	}
}

class QueryBuilderService {
	static getUsers(queryBuilder) {
		return queryBuilder.from('users').select();
	}
}
```

Hope I didn't misunderstand.

**Comment by elhigu** [comment]
You can use knex as a plain query builder if you initialize it without connection parameters like this:

```js
const knex = require('knex')({ client: 'pg' });
const userOneQuery = knex('UserTable').where('id', 1);
```

Notice that query was just built, but not compiled to sql and bindings nor it is executed.

If you want now execute the query above, there is no official way to do it with knex. However for example in tests there is currently used trick where you would execute that query like this:

```js

const dbConnectionKnex = require('knex')({
  client: 'pg',
  connection: { /* connection setup */ }
});

// run query built in 1st part of example
let queryToExecute = userOneQuery.clone();
queryToExecute.client = dbConnectionKnex.client;
queryToExecute.then(res => {
  console.log('Fetched user one!', res);
});

```

Anyways this is not nice at all and may be broken by accident in future knex versions, because this is not documented functionality of knex and will never be in this format.

Other less hacky way to do this would be to always pass connection that is used to run the query to each query method that is how for example objection ORM recommends passing the connection pool / transaction in which knex instance its query should be ran.

**Comment by andresmatasuarez** [comment]
@wubzz @elhigu thanks for your response

I wasn't confusing anything and certainly I was expecting to pass the connection down to the builder service one way or another. But I was looking for a "cleaner" solution than having to pass the knex connection to QueryBuilderService through method arguments, be them static or instance.

For example, when I need to do some things within a transaction, I am doing something like this:
```javascript
  const trx = this.knex.transaction(...);
  return this.query.createUsers(...).transacting(trx)
  .then((id) => this.query.getUser(id))
```
".transacting()" executes the query withing the given transaction. I was looking for a solution similar to that, like, say, ".withConnection" in place of ".transacting". They aren't really much different and looking at what @elhigu suggested, there seems to be an actual need for this.

**Comment by elhigu** [comment]
@andresmatasuarez actually transacting implementation is doing pretty much the same thing that my hack does https://github.com/tgriesser/knex/blob/0d55cfd28612ee7fe7002edf83f0efc30f8bd8b9/src/interface.js#L42

It basically sets query.client to be trx. So `.connection()` method (which is already in API but not really implemented properly) could be implemented pretty much the same way with `.transacting`.

**Comment by andresmatasuarez** [comment]
@elhigu Correct me if I'm wrong, but in order for me to use `.transacting(connection)` I still need to get hold of a connection object. If I am using a pool, which I am, how can I get the connection object? 

And for methods that do not require transaction setup, wouldn't that hurt performance a little?

**Comment by elhigu** [comment]
@andresmatasuarez I haven't tried that, but it might be enough to pass knex instance in and connection is acquired from pool. Maybe you could try that out? Performance impact of getting connection from pool is irrelevant.

**Comment by andresmatasuarez** [comment]
@elhigu I will let you know as soon as I try

**Comment by andresmatasuarez** [comment]
But, do we agree that at least better naming is needed?

**Comment by wubzz** [comment]
@andresmatasuarez I'm sorry but a `connection` object in knex is not a query builder, so it does not expose functions such as `.select('users')`, therefor it's confusing stating that the **connection** is sent to the query building functions, when clearly its the knex instance object..

`transacting` you will eventually find to be repetative and also pointless since the two objects share the same query building capabilities. Thus it's usually easier just to instantiate the query building sequence with `client.select('users')` where client is _either_ knex object _or_ transaction object. Side note: "forgetting" to add `.transacting` in a chain makes for a not so fun debug session as transaction gets hung up.

`withClient` I don't understand? The client **is** the knex object/transaction object, the very same object creating the build chain..

As for when transactions should be created -- that should be up to the DatabaseService as it is holding the knex object, imo.

**Comment by elhigu** [comment]
@andresmatasuarez Just to be clear about the @wubzz suggestion earlier that I gave a thumb. I hope you are aware that you can use trx object pretty much the same way with knex instance and do queries, which are made inside transaction for example like this.

```js
trx('MyTable').where('id', 2);
``` 

So calling to `.transacting` is usually not needed. I have no comment to the other application design related discussion (I decided long ago that I won't take part other people architecture decicions, but just provide answers how different things can be done with knex).

**Comment by andresmatasuarez** [comment]
@wubzz @elhigu thanks again guys for your responses

Yeah, you are technically right guys, I used connection/client interchangeably when in fact they are not. I am well aware of that but I only did it because i was putting the emphasis on separating everything from the query building capabilities of the library. Im sorry if it was misleading.

Moving on, I do understand what you guys are trying to say. That both a transaction object and the knex client support query building methods. However, and taking into account my app design, I do not consider "transacting" (or a supposed "withCient" method ) as pointless.

In fact, it allows me to have a query builder service independent from any knex instance or transaction. For example:
```javascript
Import Knex from 'knex';
const knex = Knex ()
class QueryBuilderService {
  getUsers() {
    return knex.select ('users')
  }
}
```
I can do queryService.getUsers ().transacting (trx1)
Or queryService.getUsers ().transacting (trx2)
or queryService.getUsers ().transacting (anotherKnexInstance)

I handle the actual query to the db independently from the query building service. 

The way you propose implies to have each query service method receive a knex instance as argument. Or receive it once in the constructor. But thats exactly what I am currently doing, and thanks to transacting, I have a way to change the underlying instance when executing the query

Hope I made my point. am I missing something?

**Comment by elhigu** [comment]
@andresmatasuarez I don't see much difference between:

```js
queryService.getUsers ().transacting (trx1).where(someMoreFilters)
```

and

```js
queryService.getUsers(trx1).where(someMoreFilters)
```

except that latter is more robust, because it will fail earlier synchronous manner if you don't provide any knex instance / transaction and a bit less code and it uses knex in a way that knex is documented to work.

**Comment by andresmatasuarez** [comment]
I am currently using the second way above, but the main drawback is that when you have multiple query building methods, and each of them accept multiple parameters, method signatures become pretty messy. Of course that's nothing that can't be solved by using an arguments object, but having every method accept the same mandatory object blurs the focus on the actual logic behind the method a bit, which is the query it builds. It's less expressive and more boilerplate in my humble opinion.

And in the case you really don't want to pass the Knex instance/Transaction to every method, you can move it to constructor zone, so you can access it via `this.client`. And every time you need to change the instance/transaction you will do something like this:
```javascript
queryService.setClient(trx);
return queryService.getUsers(...).then()
```
or in a more fashionable way:
```javascript
return queryService.withClient(trx).getUsers(...);
```

And that's exactly where I am pointing at

**Comment by elhigu** [comment]
Closing the issue, feel free to keep on discussion though.

**Comment by timbrownsf** [comment]
Perhaps what I'm asking for is different than this question, but is there anyway to avoid passing a trx around through all of my methods? It's not clear toe why we can't set the current trx in knex and have all queries use it...

**Comment by elhigu** [comment]
Because multiple queries can be done concurrently by multiple users in multiple transactions. Knex would have to know to which transaction each query must be sent.
