### ISSUE TITLE
andOn is not binding by default

### ISSUE THREAD

**Issue by adnanoner** [tgriesser/knex#2103]
I expected that `.andOn` would bind variables/constants by default but found out that I need to bind this through `knex.raw('?', variable)`. I'm kind of missing why this is expected behaviour as it would lead someone to a possible SQL injection. Could someone explain? Thanks!

**Comment by elhigu** [comment]
Unlike `.where` `.on` and its variants uses identifiers on both sides (in case when parameters are strings). This is because usually people are using two column references with `.on`. 

So method signature is something like this:

```js
.on(columnReferenceIfStringValueIfNumber, columnReferenceIfStringValueIfNumber);
```

for example:

```js
knex('wat').join('otherTable', builder => builder.on('a','b')).toSQL().sql
'select * from "wat" inner join "otherTable" on "a" = "b"'
```

anyways you are right that for some reason number values are interpolated directly to code:

```js
> knex('wat').join('otherTable', builder => builder.on('a', null)).toSQL().sql
'select * from "wat" inner join "otherTable" on "a" = "null"'

> knex('wat').join('otherTable', builder => builder.on('a', 1)).toSQL().sql
'select * from "wat" inner join "otherTable" on "a" = 1'

> knex('wat').join('otherTable', builder => builder.on('a', undefined)).toSQL().sql
'select * from "wat" inner join "otherTable" on "a" = "undefined"'
```

So you are right, bindings are not used for integer, for every other value I saw conversion to identifier being done. So there might be an sql injection hole, but I cannot think of case where that might be since surely you are not passing column names directly from user to your query.

Anyways... the way numbers are not passed as binding seems like a bug and would happily accept pull request fixing that. Actually as far as I know the whole feature that numbers are not passed as identifiers looks like a bug according to documentation:

> If you need to use a literal value (string, number, or boolean) in a join instead of a column, use knex.raw.

But I know many users that has been using the fact that they've been able to pass numbers there without knex.raw as a feature, I'd rather just add documentation for it and change passing to be done properly as a binding.

**Comment by wubzz** [comment]
I believe explanation above is satisfying. Closing!
