### ISSUE TITLE
does knex support Transaction Propagation feature?

### ISSUE THREAD

**Issue by zzsoszz** [tgriesser/knex#2135]
like this
[Transaction-propagation](http://orientdb.com/docs/3.0.x/java/Transaction-propagation.html)

**Comment by elhigu** [comment]
@zzsoszz This cannot really be implemented general way in node world, because event loop driven one threaded system doesn't have thread local storage which is used in Java to do this kind of magic features, where there is global context stored for every thread...

You need to implement the place where you are storing context to store transaction in application level if you like to. Save points should work already if you are actually starting new transactions inside one started one.
