### ISSUE TITLE
knexfile.js provide connection?

### ISSUE THREAD

**Issue by KieronWiltshire** [tgriesser/knex#2144]
Instead of passing connection details in the knexfile.js as the `client` parameter, is it actually possible to supply a knex instance as the `client` parameter?

Basically I have a database.js file which is "required" by other files in my app. This database reads from a single config file. I hate the idea of having the file twice and would prefer to just do something like this in my knexfile.js

```
var connection = require('./app/database');

module.exports = {
  client: connection,
  migrations: {
    directory: './app/migrations',
    tableName: 'migrations'
  }
}
```

Is this possible?

**Comment by elhigu** [comment]
I really don't understand the question... could you explain a bit more what are you trying to achieve exactly. Why you can't just require the same connection settings in your knexfile?

Are you trying to reuse the same knex instance for running migrations client and your application? If that is the case, it is impossible, since you cannot share data like that between multiple node processes (migration runner and your application)...

**Comment by KieronWiltshire** [comment]
Nope, basically I have an application that has a configuration file provider, but you may never know where that configuration file will reside. It's only possible to get the configuration file through a dependency passed through a constructor.

It's difficult to explain, just look at how I'm currently resolving this issue here:
https://github.com/Quture/database/blob/master/src/database.js#L96

**Comment by elhigu** [comment]
Yeah, I skimmed the code through and looks like you are reading your own customizable configuration and creating then knex configuration partly against it... you could have require you configuration in knexfile I suppose and then do all that configuration generation parts there maybe. 

Closing this since its more of architecture issue of code that is using knex, than really a knex issue... and the functionality how stuff should work if knex instance is passed to knexfile is not clear at all (migration reads knexfile, which requires knex instance which is initialized with parameters of knex file... ). In this case knex file which dynamically set up its configuration could be solution for you.
