### ISSUE TITLE
mssql insert query - wrong value for boolean statement

### ISSUE THREAD

**Issue by fpattis** [tgriesser/knex#2159]
hi,

when i create an insert statement for mssql that contains a boolean value - which for mssql is a bit - the resulting sql contains a boolean instead of a bit. example: 

let tuple = {
    active: true
};

knex('table').insert(tuple).toString();

// prints: insert into [table] ([active]) values (true)
// should print: insert into [table] ([active]) values (1)

sql-server error: Invalid column name 'true'.

sql-server version 2012
npm packages:
mssql@"3.3.0"
knex@0.12.9

**Comment by kblomster** [comment]
I have the same issue. You cannot use the keywords `true` and `false` for `bit` fields in T-SQL, but the string literals `'TRUE'` and `'FALSE'` work and will get translated to 1 and 0 respectively. Lowercase works too I think.

**Comment by elhigu** [comment]
@fpattis why are you using `.toString()`? Queries are sent to driver as SQL string and array of bindings and driver will do the conversion from true/false -> 1/0 etc. 

`toString()` method does variable interpolation on knex side, which is not very safe and might expose your app to SQL injection attacks etc. if you try to run those queries.

**Comment by kblomster** [comment]
I can't speak for @fpattis but in my case I'm actually using knex as a supplement for a different database library (Sequelize) that doesn't have a sensible query builder. Since I'm also trying to avoid having to configure two connections because I'm lazy, I'm running knex-generated queries through Sequelize for a few specific and hacky usecases that I should really get rid of. Sequelize doesn't support bound parameters with MSSQL even though the underlying driver does, so I can't rely on that either.

I acknowledge that what I'm doing is stupid and on a very basic level the wrong way to interact with an SQL server, but at least in my case this stuff is for internal use only with no publicly accessible surfaces. Nevertheless I would argue that `.toString()` should generate correct syntax for the dialect, to ease debugging if nothing else.

Relatedly I also noticed that `.toString()` doesn't prefix string literals with `N` either in MSSQL, which results in Unicode strings not working properly (in MSSQL you need to write Unicode string literals like `N'我来自北京'`).

**Comment by elhigu** [comment]
@kblomster I actually hope that I can somehow deprecate the whole method and provide another .nativeSql attribute or getter to result of .toSQL() which can be given directly to DB driver (currently .sql string uses ? for bindings, which are not native binding chars for all of the databases). 

That being said you are right, that currently it would be desired for `.toString()` to return valid and safe SQL. Which means that knex should implement value replacement code properly (not an easy task to make sure that it works perfectly).

**Comment by fpattis** [comment]
hi, sry for the delayed answer.I was using the toString() method in order to add some MSSQL specific expressions. I had to addSET IDENTITY_INSERT dbo.users ON;
in front of the insert statements and; SET IDENTITY_INSERT dbo.users OFFafterwards in order to be able to seed some records where I wanted to provide the ID.
    Am Montag, 18. September 2017, 12:46:53 MESZ hat Mikael Lepistö <notifications@github.com> Folgendes geschrieben:  
 
 
@kblomster I actually hope that I can somehow deprecate the whole method and provide another .nativeSql attribute or getter to result of .toSQL() which can be given directly to DB driver (currently .sql string uses ? for bindings, which are not native binding chars for all of the databases).

That being said you are right, that currently it would be desired for .toString() to return valid and safe SQL. Which means that knex should implement value replacement code properly (not an easy task to make sure that it works perfectly).

**Comment by elhigu** [comment]
.toNative() is now available in 0.14.1
