### ISSUE TITLE
[Postgres] citext[] incorrectly deserialized

### ISSUE THREAD

**Issue by oladon** [tgriesser/knex#2183]
Create a table `foo` with two columns `id` and `bar`, and run a query such as the following:

```
knex.select('id', knex.raw('array_agg(bar)'))
.from('foo')
.groupBy('id');
```

If `bar` is type `text`, you'll get the output you expect:

```
{
  id: 42,
  bar: [
    1,
    2,
    3
  ]
}
```

However, if `bar` is type `citext`, the resulting array will be stringified:

```
{
  id: 42,
  bar: '{1,2,3}'
}
```

I've temporarily worked around the issue by casting the array_agg() to `text[]`, but it's definitely a work-around. :)

**Comment by elhigu** [comment]
It is up to `node-postgres` package to decide how to deserialise data read from DB.

**Comment by roytz** [comment]
https://github.com/brianc/node-pg-types/issues/56#issuecomment-323223477

**Comment by oladon** [comment]
Thanks roytz!

**Comment by hi2u** [comment]
I know this is a bit outside the scope of Knex itself... but wondering how others have solved it?

I've looked into the linked issue above, but it seems that the `OID` number for `CITEXT` + `CITEXT[]` differ across different postgres servers/instances due to `CITEXT` being an extension rather than built-in type.

Normally we'd just be able to do something simple like:

    pg.types.setTypeParser(types.builtins.TIMESTAMPTZ, 'text')

...but the OID number would need to be different on every server.

I don't really want to have to hard code different values in for every server.  

Is there some more elegant solution to this kind of thing?  Ideally any unknown types that is an array in postgres should just come back as a string array in JS I would have thought... so could there somehow be a setting to at least do that? (even without being CITEXT-specific)

**Comment by elhigu** [comment]
Maybe postgres forums can help you.
