### ISSUE TITLE
One connection per request?

### ISSUE THREAD

**Issue by mochini** [tgriesser/knex#2186]
I use knex within the context of an express request and my config gives me a pool of 3-5 connections.

I want all queries in my request to occur within a transaction but the logic is split up between many files and modules. I know I can use knex's `transacting` syntax, and thats what I'm doing, but it requires me to pass around the transaction in almost every function which is kind of a pain.

I'd much rather do something like:

```
 knex.raw('BEGIN TRANSACTION')

... lots of other code

 knex.raw('COMMIT')
```

This would also be awesome for running my test suite as I could rollback the transaction after every test and reset the database back to where it was at the beginning of my test.

The problem is that with multiple connections available to knex. Not all of my queries are run through the same connection, so even if I start a transaction with `knex.raw()`, if even one of my queries is run on a different connection, i lose the transaction batch...

Is there a way to tell knex to use the same connection for every query in a request?

Thank you in advance!

**Comment by elhigu** [comment]
There is no really support in knex for that case you are describing.

However in your case, instead of passing transaction to everywhere, you would end up passing connection to everywhere, so it wouldn't help much either. 

Also this is kind of duplicate to https://github.com/tgriesser/knex/issues/2153 and some others.

**Comment by calebeaires** [comment]
@mochini do you get this issue resolved? If so, how do you get an workaround?

**Comment by wubzz** [comment]
I have a few apps in production where I had the same architectural challenge. I ended up doing something similar to this:

```javascript
class ErrorHandler {
	static middleware() {
		return async (error, req, res, next) => {
			await req.transaction.rollback();

			res.status(500);
			res.json({});
		};
	}
}

class ResponseService {
	static middleware() {
		return async (req, res, next) => {
			try {
				await req.transaction.commit();

				res.status(200);
				return res.json(res.locals.JSON);
			} catch (error) {
				return next(error);
			}
		};
	}
}

class Employees {
	static load(db) {
		return db('Employees').select();
	}
}

//Middleware creating transaction
app.use((req, res, next) => {
	knex.transaction((tr) => {
		//Assign to req
		req.transaction = tr;
		next();
	});
});

//Random route
app.get('/myroute',
	async (req, res, next) => {
		try {
			//Use transaction object when issuing queries
			res.locals.JSON = await Employees.load(req.transaction);
		
			return next();
		} catch (error) {
			return next(error);
		}
	},
	ResponseService.middleware()
);


//Error handler
app.use(ErrorHandler.middleware());
```

Basically every incoming request creates a new transaction object which is then sent as an argument to whatever function needs it, while also making it available in any and all middlewares via `req.transaction`. The `Response` handler will commit the transaction prior to sending the response, and the `ErrorHandler` rolls the transaction back and replies with an error.

The difference here compared to description of issue is that the `transaction` object is being sent around instead of the `knex` object, which results in enforcing the use of a single connection. As elhigu stated above you probably won't get around having to send the object around regardless. *(Note that `.transacting` isn't needed, going directly on transaction works just as well)*


This is not necessarily a 'good solution' in any way, but so far it has at least been enough for my apps use cases.

**Comment by nareshsr** [comment]
You can create a connection and destroy connection for every request

```
const config = {
    client: 'mysql2',
    connection: {
      host: process.env.DB_HOST,
      user: process.env.DB_USER,
      password: process.env.DB_PASS,
      database: process.env.DB_NAME
    },
    pool: {
      min: Number(process.env.DB_POOL_MIN),
      max: Number(process.env.DB_POOL_MAX)
    },
    acquireConnectionTimeout: Number(process.env.DB_TIMEOUT)
  }
  var Knex = require('knex')

  this.functioname = () => {
    var output = {}
    return new Promise(function (resolve) {
      var knex = new Knex(config)
      knex(tablename)
        .select()
        .then((result) => {
          if (result.length > 0) {
            output.error = false
            output.result = result
          } else {
            output.error = true
          }
          resolve(output)
        })
        .catch((err) => {
          err.error = true
          resolve(err)
        })
        .finally(() => {
          knex.destroy()
        })
    })
  }
```

**Comment by wubzz** [comment]
@nareshsr That's gonna blow up your server resources on heavy load.

**Comment by bakewellcake** [comment]
any updates to this?

**Comment by elhigu** [comment]
yep, still closed
