### ISSUE TITLE
Sets the comment for an increments column

### ISSUE THREAD

**Issue by zhongzhi107** [tgriesser/knex#2210]
```
knex.schema.createTable('accounts', function(t) {
  // .comment() does not work
  t.increments().comment('AUTO_INCREMENT ID');
});
```

**Comment by elhigu** [comment]
@zhongzhi107 I suppose this is a bug report. In bug reports would be helpful to add also information, what system does right now or what kind of error is thrown, which database is used and what would be expected functionality / query.

Anyways looks like indeed comment is not created for that column at least on mysql:

https://runkit.com/embed/74wcu7p7z5b5

Do you know which would be expected output for your query?

**Comment by zhongzhi107** [comment]
@elhigu Thanks for your reply.

The following result is what I expected:
```
create table `accounts` (`id` int unsigned not null auto_increment primary key comment 'AUTO_INCREMENT ID')
```

This is my system environment information:

```
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.1
BuildVersion:	15B42

> mysql --version
mysql  Ver 14.14 Distrib 5.7.16, for osx10.11 (x86_64) using  EditLine wrapper

> node -v
v7.6.0

> npm list knex
├── UNMET PEER DEPENDENCY pm2@2.x
  └── knex@0.13.0 
```

**Comment by richraid21** [comment]
I dug through the code and found the problem.    

On [line 62](https://github.com/tgriesser/knex/blob/b5d93f10b1a96c47681f5e08a03d79b10a5fb226/src/schema/columncompiler.js#L62) of the common `src/schema/columncompiler` , `getModifiers()` specifically excludes columns of type `increments`. An initial look makes me think this was to avoid the possibility of a user setting a different, disallowed modifier on an incremental column, such as `nullable`.    

Removing this check however does not solve the entire problem. 

If the user does not explicitly define a column name, the generated SQL for adding the comment is incorrect: it renders a `undefined` as the column name. This is due to the default column name being [injected at the generic level](https://github.com/tgriesser/knex/blob/b5d93f10b1a96c47681f5e08a03d79b10a5fb226/src/schema/columncompiler.js#L48), thus, the dialect level `comment()` method is unaware of the column name.

I'd be happy to implement a fix if anyone has suggestions. 

@elhigu ?

**Comment by elhigu** [comment]
@richraid21 sorry, but I'm not very familiar with that part of the code to be able to say anything from top of my head and I'm currently a bit busy to start figuring out. Anyways if you have some suggestion how to do it I'll happily check it out if it makes sense to mee too.

**Comment by richraid21** [comment]
My first implementation of a working solution moves the check for default column names into the prototype of the generic `columncompiler`: 

```
ColumnCompiler.prototype.defaults = {}

ColumnCompiler.prototype.defaults.columnName = function() {
  if (this.isIncrements) {
    return 'id';
  } else {
    throw new Error(`You did not specify a column name for the ${this.type}column.`);
  }
}
``` 

Then any code, regardless of whether it was declared in the generic or dialect specific, could access the defaults via `this.defaults.columnName()`. It is a function so the user does not have to worry about checking the type. 

An example implementation in the postgres dialect would be: 

```
  comment(comment) {
    const columnName = this.args[0] || this.defaults.columnName();

    this.pushAdditional(function() {
      this.pushQuery(`comment on column ${this.tableCompiler.tableName()}.` +
        this.formatter.wrap(columnName) + " is " + (comment ? `'${comment}'` : 'NULL'));
    }, comment);
  }
```

If the column type is not allowed to have a default, the same error would be thrown, because the logic is still present.

**Comment by richraid21** [comment]
@elhigu This can be closed. PR#2243
