### ISSUE TITLE
Add support for using knex across multiple branches 

### ISSUE THREAD

**Issue by jamesone** [tgriesser/knex#2215]
I think it'd be awesome if we were able to get rid of this message:

`Error: The migration directory is corrupt, the following files are missing:`

Im sure a lot of people are using knex across multiple branches which contain new migrations.

This would allow us to easily switch between branches, create new migrations, run them, and continue developing. At the moment if we do this, we'll come across the above error.

Is this 'technically' possible todo with knex? Maybe it'd be worth looking into how **django (python)** does it? They have an awesome migrations tool that handles all this.

**Comment by elhigu** [comment]
@jamesone do you mean implementing schemafile style of migration management? So basically knex would figure out what kind of schema DB currently has and then will do incremental change so that DB schema will look the same that schemafile?

**Comment by jamesone** [comment]
Yep! That sounds about right. Would this be a big job? I haven't gone through the codebase properly, so don't really know.


Sent from Outlook<https://aka.ms/qtex0l>
________________________________

**Comment by elhigu** [comment]
yes, its a huge and difficult job and there is already discussion about this https://github.com/tgriesser/knex/issues/1086

Closing as duplicate.

**Comment by elhigu** [comment]
In your case you could probably just reset your DB from old dumps, every time when changing branch and then run fresh migrations on top of older DB image.

**Comment by joeytwiddle** [comment]
When changing branch, it is usually enough to run the down migrations, until you are at a common point in history.

But you may not know which branch those files were on. (Especially if you have switched through many branches recently.)

But ... what if `knex` **stored the migration scripts** it had run into the `migrations` table?

Advantage: Then knex would be able to retrieve and run `down` on those migrations, even if the files weren't available locally. This could be very convenient for the developer!

Disadvantage: The `migrations` table would contain the copy of the migration script when it was first run. If the `down` side of the migration script has been edited since then, it would probably be better to run the updated file, rather than the old script that knex stored in the DB. (This might be mitigated, if knex made a lot of effort to keep the DB updated with the latest version of every script it could find, but even that would have pitfalls.)
