### ISSUE TITLE
Cannot insert explicit value on seed run

### ISSUE THREAD

**Issue by kirkor** [tgriesser/knex#2262]
I'm using MSSQL server.

I want to insert data with ID's and getting this SQL error:

`Cannot insert explicit value for identity column in table 'AS_DEF' when ID ENTITY_INSERT is set to OFF`

The resolution is to execute `SET IDENTITY_INSERT as_def ON` but I can't do this in the same session. Any solution for this?

**Comment by elhigu** [comment]
You can set `SET IDENTITY_INSERT as_def ON` for each connection in afterConnect hook or you can start transaction, set `SET IDENTITY_INSERT as_def ON` inside transaction and then do the insert.

**Comment by kirkor** [comment]
I'm new to node.js and knex as well. I cant work it out :(

Do you have any working example?

I'm trying transactions currently. And have something like this:
`
exports.seed = function (knex, Promise) {

    const tableName = 'as_def';

    return knex.transaction(function (trx) {
        return knex(tableName)
            .transacting(trx)
            .del()
            .then(function () {
                return trx.raw('SET IDENTITY_INSERT ' + tableName + ' ON').then(function() {
                    return knex
                    .transacting(trx)
                    .insert([{...},])
                    .into(tableName);
                });
            })
            .then(() => {
                return questions(knex, Promise);
            })
            .then(() => {
                return answers(knex, Promise);
            })
            .then(trx.commit)
            .catch(trx.rollback);
    });
};
`

**Comment by kirkor** [comment]
`afterCreate` is not working as well:

`afterCreate: function (conn, done) {
            var request = new sql.Request(conn);
            request.query('SET IDENTITY_INSERT [ey_survey_analysis].[dbo].[assessments_definitions] ON;', function (err, recordset) {
                if(err) {
                    console.log('error');
                }
            });

            done();
        }`

For me looks like a BUG :P

**Comment by elhigu** [comment]
You have some errors in both of your examples.

First one should go somehow like this:

```
exports.seed = function (knex, Promise) {
    return knex.transaction((trx) => {
        return trx('as_def').del()
            .then(() => trx.raw('SET IDENTITY_INSERT as_def ON'))
            .then(() => trx('as_def').insert([{...},]));
    })
    .then(() => console.log('transaction was committed'))
    .catch((err) => console.log('transaction was rolled back'))
    ;
};
```

If it fails, check the error and try to run with DEBUG=knex:* environment variable set to see if some of the sent queries does not make sense.

Second example calls done, before query is even ran, which might cause problems. Add console.log to see if afterCreate is really called.

Definately its a bug, but I'm still not convinced it is in knex. Try to start with checking that all the simplest things are working. For example that afterCreate is called the way it should, the query inside does right thing etc. and build the code up until you find where the problem is.

**Comment by elhigu** [comment]
Looks like you are also doing different queries in first and second try. Which one it is that should set the id to be possible to set?
```
SET IDENTITY_INSERT as_def ON
```
or
```
SET IDENTITY_INSERT [sa].[dbo].[as_def] ON
```

**Comment by kirkor** [comment]
To have better understanding of this problem I've run SQL Server Profiler, and something really strange just happens. In query log I can clearly see that ```SET IDENTITY_INSERT``` is executed but the second query is still not working... this is really strange but looks more like an SQL Server problem.

I decide to move forward and just passing inserted ids from one promise to another, and this is working fine for me - until more complex case will be in place. 

Much appreciate your help. If you need more info about this problem, just let me know I will pass you all information.

**Comment by dcunited001** [comment]
yeh, i'm running into this problem. i'm trying this, but no dice.

```javascript
userInsertColumns = ['id', 'andOther', 'userColumns'];
userInsert = `INSERT INTO users ([${ userInsertColumns.join("],[") }]) values (?,?,?,?,?)`
_.each(createUsers, async (user) => {
   await knex.raw(userInsert, _.pick(user, ...userInsertColumns).values).wrap(
     "SET IDENTITY_INSERT users ON;\r\n",
     "SET IDENTITY_INSERT users OFF;\r\n"
   );
});
```

i've tried it nearly every other conceivable way, spending a total of at least 6 hours on getting this to work. i tried removing the `identity(1,1)` from the table, but that caused problems when running my application.

**Comment by DHFW** [comment]
My solution to this problem is listed below. However, it feels like bypassing the strength of knex. I liked @kamote 's solution however that not was not merged. Or, if there was a way to do the wrap function around an insert would also be nice. @elhigu do you have a better solution because the provided code example did not work. It seems that every command is a separate context for MS SQL Server, like @kirkor found out.

```Javascript
exports.seed = function(knex) {
  const list = [
    { RoleID: 3, RoleName: 'Administrators' },
    { RoleID: 4, RoleName: 'Registered Users' },
   ...
  ];
  const values = list.map((i) => `(${i.RoleID}, '${i.RoleName}')`).join(',');
  return knex
    .transaction((trx) => {
      return trx('roles')
        .del()
        .then(() =>
          trx
            .raw(
              `insert into [roles] ([RoleID], [RoleName]) values ${values};`,
            )
            .wrap(
              'SET IDENTITY_INSERT roles ON;',
              'SET IDENTITY_INSERT roles OFF;',
            ),
        );
    })
    .then(() => console.log('transaction was committed'))
    .catch((err) => console.log('transaction was rolled back', err));
};
```

**Comment by jorions** [comment]
I was having the same issue as an MS SQL Server user.

The point @DHFW and @kirkor made ("It seems that every command is a separate context for MS SQL Server") was playing a role here, it seems, given that the `IDENTITY_INSERT` kept being seen as `OFF` when I had everything in 1 transaction, but framed as 3 separate `.raw`, `.insert`, and `.raw` queries.

I found this to be a bit cleaner:
```
function saveToTable(knex, schema, table, mappedData) {
  const { bindings, sql } = knex
    .withSchema(schema)
    .insert(mappedData)
    .into(table)
    .toSQL();

  const newQuery = `SET IDENTITY_INSERT ${schema}.${table} ON; ${sql} SET IDENTITY_INSERT ${schema}.${table} OFF;`

  return knex
    .raw(newQuery, bindings)
}
```

I suppose I could use `.raw().wrap()` instead of manually creating a `newQuery`. Additionally, note that the `schema` was a relevant level of specificity for my situation, but may not apply to your own.

Hope someone finds this useful!

**Comment by guntribam** [comment]
Please @elhigu accept the pull request. I'm using an ORM build on top knex(lucid) and without this i lost a great power. Please reconsider
