### ISSUE TITLE
Autocommit option for MySQL

### ISSUE THREAD

**Issue by kirrg001** [tgriesser/knex#2290]
Hey 👋

I would like to disable autocommit (`SET autocommit=0`) on a single connection for innodb via knex. I don't want to set it globally in my MySQL config, just per connection. The reason is that multiple insert statements are autocommitted in InnoDB, even a rollback.

If i raise a PR, does it get merged and released?

It looks like Oracle supports this already, [see](https://github.com/tgriesser/knex/blob/master/src/dialects/oracle/transaction.js#L45).

For reference:
- [mysql conversation](https://github.com/mysqljs/mysql/issues/1726#issuecomment-301576446)
- [innodb documentation](https://dev.mysql.com/doc/refman/5.7/en/innodb-autocommit-commit-rollback.html)
- [knex existing issue](https://github.com/tgriesser/knex/issues/165)

Happy about feedback.

Thanks!
Kate

**Comment by wubzz** [comment]
Maybe `afterCreate` could be used for this?

```javascript
const knex = require('knex')({
	client:     '...',
	connection: {...},
	pool:       {
		afterCreate(connection) {
			return connection.query('SET autocommit=0;');
		}
	},
});
```

Haven't tested (or ever used) this myself, it just occurred to me.

**Comment by kirrg001** [comment]
@wubzz Thanks for your suggestion.

But that wouldn't work with transactions i assume?

**Comment by elhigu** [comment]
@kirrg001 the example @wubzz gave will run `SET autocommit=0;` query to every connection that is opened by the pool. Also connections that are used by transactions. Just remember that disabling autocommit will not has an effect on statements causing implicit commit https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html

**Comment by kirrg001** [comment]
> Do you mean that multiple insert statements are currently autocommitted also when they are done inside transaction?

Yeah exactly, this is because of autocommit's behaviour. Insert statements are autocommitted.

```
show variables like '%autocommit%'
autocommit ON

BEGIN
CREATE TABLE ugly (a INT, b CHAR (20), INDEX (a));
INSERT INTO ugly VALUES (10, 'bla');
INSERT INTO ugly VALUES (20, 'blubb');
ROLLBACK;
SELECT * FROM ugly;
```

(do the same with autocommit is off)

**Comment by elhigu** [comment]
Your example has an error... 

```
show variables like '%autocommit%'
autocommit ON

BEGIN; -- Start transaction
CREATE TABLE ugly (a INT, b CHAR (20), INDEX (a)); -- DDL statement causes implicit commit
INSERT INTO ugly VALUES (10, 'bla'); -- Since earlier transaction was committed starts new transaction and autocommits
INSERT INTO ugly VALUES (20, 'blubb'); -- the same
ROLLBACK; -- creates transaction and rolls it back
SELECT * FROM ugly; -- returns 2 rows
```

Like this you can do it correctly and rows inside transaction are not autocommitted

```
show variables like '%autocommit%'
autocommit ON

CREATE TABLE ugly (a INT, b CHAR (20), INDEX (a));

BEGIN;
INSERT INTO ugly VALUES (10, 'bla');
INSERT INTO ugly VALUES (20, 'blubb');
ROLLBACK;
SELECT * FROM ugly; -- returns zero rows
```

**Comment by kirrg001** [comment]
Interesting. I didn't knew that the table creation autocommits the transaction. Thanks.

Still i am not sure if i am able to determine if a table get's created during my transaction or not. That's why i am still interested how i can run the transaction with autocommit disabled? 

So imagine i allow to execute any database statements (table creation, inserts, updates) from an external caller/lib, but i provide the API for that e.g. the connection to work with. But all of the statements should run in a single transaction. So the connection is always the same - it's the connection where we began a transaction.

**Comment by elhigu** [comment]
In mysql autocommit and implicit commit are 2 different things. 

Autocommit causes that if statement is  outside of transaction, the implicit transaction created for the statement is automatically committed after success. But as seen in my test code above autocommit doesn't cause that inside explicit transaction data would be committed after each statement (which would effectively prevent completely usage of transactions).

Implicit commit is much stronger thing, which happens automatically for these statements https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html. If statement that is ran inside explicit transaction causes implicit commit, it closes the open transaction once and for all.

In mysql table is created inside a transaction and that transaction will be automatically committed. If table creation fails, probably then transaction is left open until explicit commit/rollback statement.

Sadly with mysql and oracle it is impossible to create table and run inserts there all in single transaction.

If you like to emulate that you can first create table, then run inserts in transaction and if insert transaction fails drop the created table.

In your case I'm pretty sure that knex doesn't notice that your transaction was closed because of DDL statement and it will allow to send more queries to the same connection (this is undocumented functionality and it might change later on)...

**Comment by kirrg001** [comment]
Thanks for taking time and explaining.

> autocommit doesn't cause that inside explicit transaction data would be committed after each statement (which would effectively prevent completely usage of transactions).

Yeah makes 100% sense.

> Anyway it doesn't change the fact that all the queries are still not ran in a single transaction.

Correct.

> If you like to emulate that you can first create table, then run inserts in transaction and if insert transaction fails drop the created table.

I know but right know i think it's somehow hard to manage 🤔  Because as a migrator tool you never know when a table get's created and if other insert statements will follow.

> Sadly with mysql and oracle it is impossible to create table and run inserts there all in single transaction.

I understand that `autocommit` and `implicit commits` are two different concepts, but why does this work?

```
BEGIN;
SET autocommit=0;
CREATE TABLE test2 (a INT, b CHAR (20), INDEX (a));
INSERT INTO test2 VALUES (30, 'mega');
INSERT INTO test2 VALUES (20, 'supergeil');
SELECT * from test2;
ROLLBACK;
SET autocommit=1;
SELECT * from test2; -- returns zero rows
```

---

I think your inbuilt [knex migrate shell tool](http://knexjs.org/#Migrations) suffers from the same problem. I just tested it.
If i add 3 migration scripts. The first inserts a table called `table1`. The second inserts an entry to this table and the third one fails. So i run `knex migrate:latest`, all three scripts are executed and i can see the error from the third script. The result is, that the insert is not rolled back, which i believe it should.

**Comment by elhigu** [comment]
in your example I suppose that following happens:
```

BEGIN; -- start transaction
SET autocommit=0; -- sets autocommit off
CREATE TABLE test2 (a INT, b CHAR (20), INDEX (a)); -- closes transaction
INSERT INTO test2 VALUES (30, 'mega'); -- opens new transaction and leaves it open, because autocommit is off
INSERT INTO test2 VALUES (20, 'supergeil'); -- is ran in transaction that was already open
SELECT * from test2; -- shows results seen in currently active transaction
ROLLBACK; -- rollsback those inserts
SET autocommit=1;
SELECT * from test2; -- returns zero rows
```

>  think your inbuilt knex migrate shell tool suffers from the same problem. I just tested it.

I'm not sure what you mean by "the same problem". I don't remember from top of my head if each migration in changeset is ran in separate transaction or not... if new transaction is opened for each, then I would expect that inserts would not have been rolled back if that migration was success. 

Also that insert migration should have entry in the migrations table showing that running it was success.

**Comment by kirrg001** [comment]
Thanks for testing. So my example proofs that disabling autocommit for specific transactions/connections, rolls back insert statements - doesn't matter if a table was created within the transaction?

**Comment by elhigu** [comment]
> So my example proofs that disabling autocommit for specific transactions/connections, rolls back insert statements - doesn't matter if a table was created within the transaction?

It doesn't prove anything about general situation. It just happens to work that way in this specific case where there was no other statements triggering implicit commits, but only one in the start of transaction. It would be exactly the same case where create table is done first in one transaction and after that inserts are done in the second transaction.

Even if autocommit is disabled in the start of each transaction, it wouldn't change the fact that implicit commits do make things to behave nasty. It would just work nasty in a different way. With mysql one just have to know how the DB works... there is no way to hide the differences in this case. 

So I don't see any reason to change how knex works in this case. Only way to hide the DB differences here is to do every operation that causes implicit commit in separate transactions (so that other DBs will emulate the mysql/oracle's implicit commits) and all the other queries normally in transaction.

**Comment by kirrg001** [comment]
Just wanted to share this. I just looked at a different popular [migrate tool, node-db-migrate](https://github.com/db-migrate/node-db-migrate). 

And they are disabling `autocommit` for running migrations on MySQL. See https://github.com/db-migrate/mysql/blob/master/index.js#L25 to avoid this problem.

**Comment by elhigu** [comment]
That looks strange, they are disabling auto_commit before starting transaction, and then starts transaction which will anyways make implicit commit 🤔 So I have no idea what problem they are trying to solve, since auto_commit setting wont affect to those implicit commits. So yeah that migration lib works a bit differently than knex / sequelize. It doesn't make transactions to work in a general case correctly and to have correct rollback functionality with mysql + statements with implicit commits manual work is necessary 😕

```
MariaDB [knex_test]> SET AUTOCOMMIT=1;
Query OK, 0 rows affected (0.00 sec)

MariaDB [knex_test]> delete from accounts;
Query OK, 1 row affected (0.00 sec)

MariaDB [knex_test]> select * from accounts;
Empty set (0.00 sec)

MariaDB [knex_test]> SET AUTOCOMMIT=0;
Query OK, 0 rows affected (0.00 sec)

MariaDB [knex_test]> insert into accounts (last_name, email, logins) VALUES ('foo', 'foo', 2);
Query OK, 1 row affected (0.00 sec)

MariaDB [knex_test]> select * from accounts;
+----+-----------+-------+--------+-------+------------+------------+-------+
| id | last_name | email | logins | about | created_at | updated_at | phone |
+----+-----------+-------+--------+-------+------------+------------+-------+
| 58 | foo       | foo   |      2 | NULL  | NULL       | NULL       | NULL  |
+----+-----------+-------+--------+-------+------------+------------+-------+
1 row in set (0.00 sec)

MariaDB [knex_test]> rollback;
Query OK, 0 rows affected (0.01 sec)

MariaDB [knex_test]> select * from accounts;
Empty set (0.00 sec)

MariaDB [knex_test]> insert into accounts (last_name, email, logins) VALUES ('foo', 'foo', 2);
Query OK, 1 row affected (0.00 sec)

MariaDB [knex_test]> start transaction;
Query OK, 0 rows affected (0.00 sec)

MariaDB [knex_test]> rollback;
Query OK, 0 rows affected (0.00 sec)

MariaDB [knex_test]> rollback;
Query OK, 0 rows affected (0.00 sec)

MariaDB [knex_test]> select * from accounts;
+----+-----------+-------+--------+-------+------------+------------+-------+
| id | last_name | email | logins | about | created_at | updated_at | phone |
+----+-----------+-------+--------+-------+------------+------------+-------+
| 59 | foo       | foo   |      2 | NULL  | NULL       | NULL       | NULL  |
+----+-----------+-------+--------+-------+------------+------------+-------+
1 row in set (0.00 sec)

MariaDB [knex_test]> 
```

Sequelize defaults to auto_commit=1 for mysql transactions https://github.com/sequelize/sequelize/pull/5960

**Comment by kirrg001** [comment]
Your example is helpful and shows that it can cause nasty side affects. But i think `autocommit=0` should only be executed straight before/after the transaction starts - i think it's unexpected that random statements are executed before the transaction starts, because this is in the control of the migration tool? `autocommit=0; BEGIN;....COMMIT;autocommit=1;`

> Sequelize defaults to auto_commit=1 for mysql transactions sequelize/sequelize#5960

But they explicitly allow to disable autocommit, [see](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L1734). And people using it, [reporting](https://github.com/sequelize/sequelize/issues/6828) the usage without getting warned that they are doing something wrong. Of course, that DDL statements still won't rollback is a different topic. 

---

If i instantiate a transaction with knex and run `txn.raw('SET autocommit=0')` straight afterwards, that should work i guess? As long as i ensure that it get's set to 1 afterwards.

**Comment by elhigu** [comment]
Allowing to disable / set it would be good feature to have I have nothing against having some option for that.

Actually it makes sense that `autocommit=0` and `autocommit=1` is set outside of transaction. Unsetting / setting them inside transaction would make rolling back completely impossible:

```
TRANSACTION START; -- transaction starts
SET AUTOCOMMIT=0;
...
SET AUTOCOMMIT=1; -- this actually commits the transaction because of implicit commit
ROLLBACK; -- this won't rollback anything
```

> But they explicitly allow to disable autocommit, see. And people using it, reporting the usage without getting warned that they are doing something wrong. Of course, that DDL statements still won't rollback is a different topic.

As I have already mentioned in this thread, even with `autocommit=0` rolling back will leave traces to DB. In also that issue last comments are `Yep, there's basically no way to roll DDL statements back`, `Time to switch to Postgres.`. So if it doesn't matter in your case that table creation statements etc are not rolled back setting `autocommit=0` may be enough for  you, but the code won't be compatible with other databases (whose rollback will also rollback table creation).

> If i instantiate a transaction with knex and run txn.raw('SET autocommit=0') straight afterwards, that should work i guess? As long as i ensure that it get's set to 1 afterwards.

In your case this should be fine. Setting it to one afterwards might be a problem, because when transaction is committed, knex will not allow you to send more queries there. So you probably have to do commit / rollback with `knex.raw('COMMIT; SET autocommit=1;')` or something like that.
