### ISSUE TITLE
getting "Knex: Timeout acquiring a connection. The pool is probably full." error

### ISSUE THREAD

**Issue by Suhel182** [tgriesser/knex#2302]
I am facing "Unhandled rejection TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?" issue. There are tons of running queries so i'm not able to find the query causing it. This problem seems to get serious when postgres size increases. Is there any solution?

**Comment by skumar568** [comment]
I am also facing this issue.

**Comment by wubzz** [comment]
The solution is to isolate the source and fix it. This is not a "query" error, but rather an application architecture issue. The error occurs when knex is unable to acquire a connection within (default) 60 seconds, and most likely the reason for that is that the pool is full.

In other words there are many things that can cause the error. Two of the most common are:
1. You forget to commit transactions / forget calling `.transacing(trx)` on query builders which causes the transaction to idle
2. The pool is continiously kept busy at max capacity for at least (default) 60 seconds non-stop, for instance due to heavy traffic or long running procedures.

You should look over your database state when this error occurs - are there a lot of idle connections? are there too many connections? etc.

**Comment by rsfernandes** [comment]
I am also facing this error.

While we are working to dig our architecture connections, Theres a way to prevent this error to crash the application? Or at least the error could point out the stack ? 

`rejecter(new _bluebird2.default.TimeoutError('Knex: Timeout acquiring a connection. The pool is probably full. ' + 'Are you missing a .transacting(trx) call?'));
                 ^
TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

**Comment by wubzz** [comment]
@rsfernandes As long as you use `catch` handlers on your builders I don't see how this error would crash the entire application.

As for the stack, I recommend `longStackTraces`. There's nothing built into knex specifically for this error stack.

**Comment by mifi** [comment]
FWIW I got this error with an AWS Aurora database service, and it was caused by auto shutdown feature which terminates the database after inactivity (auto-startup of the database takes like a minute or so, and that caused knex to time out)

**Comment by elhigu** [comment]
https://github.com/tgriesser/knex/issues/3159 There is list of some work around suggestions for aurora.

**Comment by booboothefool** [comment]
@wubzz 
> 2. The pool is continiously kept busy at max capacity for at least (default) 60 seconds non-stop, for instance due to heavy traffic or long running procedures.

If this is the issue, what are possible recommendations to take if cannot simply do less work? 😅

**Comment by mifi** [comment]
Increase the timeout?

**Comment by tito300** [comment]
My problem was not with knex but rather with the security group inbound rule on my aws RDS. It was set to my local machine ip address only and so I could not connect to it from the ec2 instance. was frustrating because the error message was not helpful. 
If you have this error message, it could be related to the fact that knex cannot establish a connection. so check your networks too!

**Comment by elhigu** [comment]
Yeah, I suppose that can happen if connection is blocked completely... maybe setting up different connection timeout and acquite timeout could distinguish between these two cases.

**Comment by batadamnjanovic** [comment]
I solved this problem with these versions:
```
"knex": "^0.21.1",
"objection": "^2.1.3",
"pg": "^8.0.3"
```

**Comment by LispyAriaro** [comment]
You may have to switch to Node 12 NOT Node 14

**Comment by PedramMarandi** [comment]
I had a database pool limit, I could fix the issue by setting min and max

**Comment by gainsboroughtech** [comment]
I had the same issue on my mac. i was running knex from command line terminal and suddenly started seeing this Knex: Timeout... issue.  I figured out that the problem was moving to zsh shell instead of bash.  I've been using bash for a long time, and i recently tried switching to zsh per Apple guidelines.  As soon as i went back to bash it was fixed.

Hope it helps someone.

**Comment by paul4156** [comment]
> You may have to switch to Node 12 NOT Node 14

This worked for me on mac docker-compose node:12 instead of node (v14). Thanks.

**Comment by Offirmo** [comment]
I was trying to use the server's node version by using `nvm exec 12 node ./src/index...` and was having the error above.

**Comment by nelegatti** [comment]
@batadamnjanovic you saved me after two full days of research. TY !!

**Comment by zhuzongzhi** [comment]
> 
it works,thanks.
