### ISSUE TITLE
Case sensitivity in queries

### ISSUE THREAD

**Issue by ErisDS** [tgriesser/knex#233]
It seems that knex (and therefore bookshelf) doesn't have any way to handle case sensitivity, which results in inconsistent results across the various supported databases.

SQLite is case sensitive by default.
MySQL it depends on collation, but usually case insensitive
PostGRES not sure ??

In a related issue in Ghost with regard to [tag names](https://github.com/TryGhost/Ghost/issues/1402) which should be case sensitive unique, [@halfdan mentioned](https://github.com/TryGhost/Ghost/issues/1402#issuecomment-27715417) that ActiveRecord (which I know a lot of newer bookshelf stuff is based upon) allows for this to be determined on a per-query basis:

http://edgeguides.rubyonrails.org/active_record_validations.html#uniqueness

At the moment, I can find no way to make specifically case insensitive or case sensitive queries across all 3 databases and so we're having to do a fetch all & process in JS. I also raised https://github.com/tgriesser/knex/issues/152 whilst investigating this previously in relation to email addresses.

Seems like a reasonably fundamental thing for working with multiple dbs? As per usual with bookshelf/knex I have no idea where to start looking at fixing this (see also https://github.com/tgriesser/knex/issues/46#issuecomment-33230040), so if anyone has guidance I'd love to help getting it fixed.

**Comment by jamesdixon** [comment]
ping

**Comment by jimmynavio** [comment]
I would love to see this implemented.

**Comment by jimmynavio** [comment]
As a work around you can use whereRaw. Just make sure you sanitize!
For full case insensitive search on a column I am using the following:
.whereRaw('LOWER(column) LIKE ?', '%'+value.toLowerCase()+'%');

**Comment by esatterwhite** [comment]
MySQL is case insensitive. The formatter needs to allow allow for `LIKE BINARY` and  `REGEXP BINARY

**Comment by austingray** [comment]
@jimmynavio +1 saved me some time with your workaround

**Comment by rhys-vdw** [comment]
I agree that having a portable case insensitive comparison `where` function would be great. I'm not sure exactly what it would look like.

I'm going to restore the 'PR Please' tag, @tgriesser.

**Comment by mcfa77y** [comment]
+1

**Comment by craftjk** [comment]
+1

**Comment by cshutchinson** [comment]
+1

**Comment by cshutchinson** [comment]
thanks @ jimmynavio thanks for solution to my issue

**Comment by deje1011** [comment]
@jimmynavio Your solution works fine for me as long as the query does not contain a question mark (although the question mark character alone works, the problem only occurs if it is a combination of a question mark with other characters). 

Error: Expected 126 bindings, saw 312\n    at replaceRawArrBindings (/.../node_modules/knex/lib/raw.js:99:11)\n    at Raw.toSQL

In knex/lib/raw.js I found a regular expression that replaces '?' with bindings (line 80, replaceRawArrBindings): 

````
raw.sql.replace(/\?\??/g, function (match) {
````

I tried to change that expression to [^\\]\?\?? in order to be able to escape the question mark but without success (I get a "Syntax Error" for the resulting sql).

Any Idea on how to solve that problem? Or more specific, how can I search for a string that contains a question mark with knex.raw?

**Comment by elhigu** [comment]
Looks like every dialect (mysql, postgres, mssql, sqlite3, oracle) supports `lower(string)` function so that sounds like good baseline. Also query compilers can be overridden for each dialect e.g. if one likes to use `ilike` for that on postgres or `COLLATE NOCASE` with sqlite3.

For explicitly case sensitive comparison... probably mysql is only db which isn't always case sensitive by default so it would need dialect specific implementation e.g by method @esatterwhite suggested.

**Comment by ryanvanderpol** [comment]
+1 from this postgres user

**Comment by savovs** [comment]
That would be awesome. +1

**Comment by savovs** [comment]
Here's @jimmynavio 's workaround modified a bit 🍡 
`.whereRaw("LOWER(name) LIKE '%' || LOWER(?) || '%' ", searchText) `

**Comment by jtal** [comment]
me too +1 !

**Comment by jcbize** [comment]
One thing to keep in mind here is that queries using `LOWER(column)` will not use indexes created for that column, and so a full table scan will be performed, which is obviously bad for all search use cases.

The way to avoid this is to create a new index on `LOWER(column)`, but most people won't know or think to do this.

That's why it's important to have overrides on a per dialect basis as @elhigu suggested, to provide safe and sensible defaults for different possible configurations.

**Comment by ald890** [comment]
@jcbize How to create new index in migrations with LOWER(column) ?

**Comment by nickyhajal** [comment]
Also wondering if there's a way make a `LOWER(column)` index in Postgres from a knex migration - any insight?

**Comment by esatterwhite** [comment]
don't the knex migrations basically have you just write SQL?

```sql
CREATE INDEX lower_column_idx ON table(lower(column))
```

**Comment by elhigu** [comment]
I'm not really sure what actually should be done here. Since this issue doesn't propose API or tell exactly in which cases one should apply this case sensitivity.

If this is still wanted, please open new issue (and refer this one), which actually describes concrete use-cases and initial API proposal how things should work.

**Comment by lehni** [comment]
@elhigu you mention overriding  query compilers for each dialect [here](https://github.com/tgriesser/knex/issues/233#issuecomment-220386909). Is there more information about this somewhere?

**Comment by elhigu** [comment]
@lehni I'm not sure what are you looking for... the comment was  about internal implementation detail how that can be done in knex. It is not suitable way to workaround this issue. More information is when you look code of compilers of each dialect.

**Comment by ds11yadav** [comment]
> ```sql
> ```sql
> CREATE INDEX lower_column_idx ON table(lower(column))
> ```
> 
> 
>       
> ```

can you help me on knex . while i have join operation and where clause need to capmare to the text filed with case insensitive .?

**Comment by jpcmf** [comment]
@vladinator1000 your solution works for me, thank you :)

**Comment by castor55** [comment]
If you wanna do an insensitive search, you can use `ilike`.
`where('colume name', 'ILIKE', '%${search word}%')`

**Comment by bkilinc** [comment]
will this break switching to sqlite and mysql ?

**Comment by abcd-ca** [comment]
how can I do a case insensitive order by? with a raw query I could do `ORDER BY lower("firstName"), lower("lastName")`

**Comment by jtal** [comment]
It looks like I +1 request for this feature in 2016. I no longer remember
what a knex is. But I'd like to renew my +1, for old times' sake. Lets get
case insensitive order by in whatever this thing is!

**Comment by sombriks** [comment]
any newer issue addressing what to do with whereILike when underlying database does not support it?

i mean `where lower(col) like lower('%val%')` could be an option but would that be beneficial in any form?
