### ISSUE TITLE
JSON(B) datatype uses "text" in most databases which causes issues

### ISSUE THREAD

**Issue by raijinsetsu** [tgriesser/knex#2368]
This could be considered a bug or enhancement depending on the direction development goes.

# Environment

Knex version: 0.12.9
Database + version: mssql, mysql, maria, and others
OS: any

# Feature discussion / request
We have a mandate to use an SQL database and cannot use a document store but we still want to primarily work with JSON data to minimize table conversions. We primarily support MSSQL and MySQL/MariaDB as that is what our customers are most comfortable with. These databases have support for the JSON(B) data type (some only within the last year) but Knex continues to use TEXT for these implementations. This leads to issues: some of our JSON documents exceed the maximum size of the TEXT data type in some of these implementations (maximum sizes differ) and we get exceptions when inserting these documents.

As I see it, Knex could handle this in a few ways:
A) Knex makes a runtime determination of whether or not the database supports the JSON(B) datatype.
B) Knex gives the developer the ability to specify the datatype to use instead of the JSON(B) data type when not supported.
C) Combine both of the options above
D) Bring MySQL and MariaDB in line with MSSQL by using LONGTEXT instead of TEXT

The API for (B) might look something like this:
```
var knex = require('knex')({
  client: 'mysql',
  jsonDatatype: (knex, callback) => {
    // ... use knex to get version somehow
    if (compareVersions(version,'5.7.8') < 0) {
        // tell the driver to use the LONGTEXT data type
        callback('LONGTEXT');
    } else {
        // tell the driver to use the JSON data type
        callback('JSON');
    }
  }
});
```

The proposed API could be implemented directly in the driver (ie. option (A)) allowing dynamic detection of JSON support. I still like the idea of being able to specify the type to use if JSON is not support, which might make the API for (C) look like this:
```
var knex = require('knex')({
  client: 'mysql',
  jsonDatatype: (knex, supported) => supported ? 'JSON' : 'LONGTEXT'
});
```

Option (D) would obviously be the easiest to implement.

**Comment by elhigu** [comment]
A) not worth it to do runtime check, we trust that people will use enough modern mysql if one likes to use json datatype (there is PR to fix it for mysql, waiting for travis to get 5.7 easily available)

B) with `.specificType` + simple helper which decides type by dialect you can do this already very easily

C) No need for this, option B) should be enough automatic detection makes things unnecessary complicated

D) I think option B) should work for this one too (and at some point when we change mysql json type to use real json type we can set mariadb to use longtext with big warnings in changelog)

I would suggest to not use `.json` type at all unless you are really running the program with platform where you are doing some json queries too. Otherwise using json to store something instead of blob or just a string is not really beneficial. 

I would rather just throw an error if application code is trying to create json column on a DB which doesn't really support it. That would be also safer choice in compared to just changing type from text -> json and text -> longtext...

**Comment by raijinsetsu** [comment]
Hi Elhigu,
Thanks for the input. I disagree that checking for supported datatypes at connection time would be difficult, complicated, or introduce significant performance drain. Doing so would elevate Knex by increasing the number of things the drivers could abstract.

As far as a solution for our problem, we can evaluate altering the columns to use the appropriate TEXT datatype in the four primary database we support. Are there instructions/documentation on how to extend the Knex implementation (through monkey-patching) such that I could expose a new API? That way, in our schema builders, we could reference our function as if it were provided by Knex?

**Comment by elhigu** [comment]
> I disagree that checking for supported datatypes at connection time would be difficult, complicated, or introduce significant performance drain.

Looks like you haven't tried to do that with all the time growing set of mysql compatible DB engines. It is complicated to maintain because there are 100 mysql clones and more are coming out all the time. Each clone might return different version strings / numbers and keeping that mapping up is the problem (this happened already with postgresql dialect).

Also I still don't consider that being very useful feature, because in either way you will have to write cross db compatible code by using the feature set that all the dialects you are abstracting away support.

> Doing so would elevate Knex by increasing the number of things the drivers could abstract.

Not really. If you are going to support all the databases, you cannot use json functionality effectively, because all DBs doesn't support them. So you would end up having separate code for DBs using json and separate code for other (which means that you are not really abstracting underlying DB away).

I have not seen any use case where using `.json()` in schema and then having it as text column in some dialect and with real `jsonb` column in other dialect would have been beneficial, only problems caused by type differences on different platforms. If you have some rare case it is, then implementing that in your own schema building code is trivial and in that case you have to have various versions of your queries too to be able to benefit those `jsonb` columns in your application.
 
So I stand by my opinion that that emulating .json() type with text column is more harmful than useful and throwing an error on non supported dialects would be the correct behaviour.

> Are there instructions/documentation on how to extend the Knex implementation (through monkey-patching) such that I could expose a new API? That way, in our schema builders, we could reference our function as if it were provided by Knex?

There is really no good way to extend knex API. However for queries with `.modify` you can emulate that a bit, by having set of custom helpers and pass them to query builder like `knex('mytable').modify(mySpecialHelper).where(...)...`. When I do custom things for schema building I just write simple helpers and call them inside createTable handler like this:

```js
knex.schema.createTable('mytable', t => {
  defaultColumns(t, knex);
  mySpecialMaybeJsonColumnOrSomethingElse(t, knex);
});
```

That is pretty clear syntax to `extend` schema builder.

**Comment by MNGoldenEagle** [comment]
@elhigu This reasoning makes sense from a practical standpoint but the Knex documentation doesn't make this clear.  Specifically the line "defaulting to a text column in older versions or in unsupported databases" for the json() method would lead many people (including myself) to believe that for any client that doesn't natively support json/jsonb, it will switch to text under-the-covers, when in fact it simply errors.

**Comment by elhigu** [comment]
@MNGoldenEagle I agree that how current schema API of `knex` is confusing in many ways. Because of historical reasons in many places it tries to emulate unsupported datatypes with some non compatible column types among other non-obvious ways for user. Sadly we really cannot change much current API either because it makes it too hard for old projects to migrate to changed behaviour (everyone would need to fix their old migration files etc.). 

IMO Its beyond repairing. Thats why right now I've taken my main task in knex to be writing completely new migration API which can address that problem and it will be more consistent in many ways and for example will never try to emulate unsupported column types with incompatible ones. I also home that I can add schema API versioning support to new on, so that we can make also backwards incompatible changes there in case if we see that we made bad API choices at some point. Old API will be left as legacy API which won't get updates anymore and it will be maybe dropped when some day in distant future knex 1.0 is released.
