### ISSUE TITLE
Use `undefined` to update column to DEFAULT value

### ISSUE THREAD

**Issue by sgoll** [tgriesser/knex#2394]
`.insert(data)` allows the `data` object (or the array of objects) to contain properties set to `undefined` to explicitly set the corresponding columns to DEFAULT (or NULL when `useNullAsDefault` is set).

`.update(data)`, on the other hand, ignores any property set to `undefined` (as opposed to properties that are simply absent from the object). The docs are rather explicit about this:

> If a key to be updated has value undefined it is ignored.

The relevant code is in [`_prepUpdate` in `compiler.js`](https://github.com/tgriesser/knex/blob/6ffcaedc381843928bfcf4d8ce1b9893571f928f/src/query/compiler.js#L601) where `data` is reduced via `omitBy`/`isUndefined`.

I am wondering what is the reason for this. Should this be changed? Given the current restriction, how is it possible to update a column to its DEFAULT value without resorting to raw queries and why is the analogy between insert() and update() explicitly avoided here?

**Comment by elhigu** [comment]
It is intentional that in `update` with `undefined` attribute is not updating value to `default` nor `null`. This was discussed carefully when support for default values when inserting multiple rows was added (not sure where the whole discussion was but here is part of it https://github.com/tgriesser/knex/pull/962).

To update row with default you should do `.update({ column: knex.raw('DEFAULT') })` we don't want to make something arbitrary like `undefined` to be automatically considered as a default value. Actually that would be also semantically wrong, since `undefined` means more like something does not exist so in context of `update` it means that attribute is not updated.

When inserting multiple rows it was necessary evil to treat those cases where some of the inserted rows didn't have all the same attributes set to behave somewhat sane. e.g. to be able to write 

```
.insert([{col1: 1}, {col2: 2}])
```
instead of 
```
.insert([{ col1: 1, col2: knex.raw('DEFAULT') }, { col1: knex.raw('DEFAULT'), col2: 2 }])
```
