### ISSUE TITLE
destroy not calling callback

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [tgriesser/knex#2435]
# Bug
Running `destroy` twice does not call callback on second destroy.  
I would have expected destroy to always call the callback.  
 
```javascript
// try-knex-destroy.js
const KNEX = require('knex')

knex_db = KNEX({
  client: 'sqlite3',
  connection: {filename: ':memory:'},
  useNullAsDefault: true,
})

knex_db.destroy(() => {
  console.log('destroy 1')
  knex_db.destroy(() => {
    console.log('destroy 2') // second destroy callback is never called
  })
})
```

console  
```terminal
$ node try-knex-destroy.js 
destroy 1
$ 
```

### Environment
node: v8.5.0  
Knex version: knex@0.14.2  
Database + version: sqlite3 + 3.21.0  
OS: OS X

**Comment by elhigu** [comment]
I'm not sure if this is a bug, since destroy should never be called multiple times. Also other people would expect that to work other way around, that knex prevents callback from being executed multiple times since it could potentially try to do some cleanup accidentally multiple times. 

If you want some callback to be after every destroy() call you can do `knex.destroy().then(() => console.log('I will be called even if I was already destroyed'));`

Anyways this is certainly something that could be documented.

**Comment by BebeSparkelSparkel** [comment]
"since destroy should never be called multiple times" it seems that an error should be given to the callback if this does happen or the promise should be rejected.

If it does not then everything is left hanging.

**Comment by elhigu** [comment]
Yeah, I would like it better if it would reject / throw too in case when destroy() is called too many times. 

IIRC that was intentional functionality to silently not do anything if knex was already destroyed. We need to dig up PR and issues why it was done that way to be able to tell if reasoning still applies (or if I'm just remembering wrong).

> If it does not then everything is left hanging.

Nothing should be hanging even if second call is ignored. First call should have already destroyed 
the pool and waited all connections to drain etc. I don't know what you mean by "everything is left hanging".

**Comment by BebeSparkelSparkel** [comment]
I have tests that create a new in memory sqlite database for every test.
After each test I need to destroy the database.
Sometimes there is overlap with the destroys and the afterEach is left hanging.

**Comment by elhigu** [comment]
Then there is some other problem causing the hanging in your test setup. Calling destroy twice does not hang anything. You can see that I call here knex destroy 5 times concurrently for in memory sqlite db and it does not hang. https://runkit.com/embed/vhuvl9sl92s7

Try to trace what your test setup is doing when it hangs, remove code until there is just hanging code left and then reproduce the hanging in single file or in runkit. That way it will be obvious what causes hanging, if it is some error in test setup or if there is bug in knex causing it.

IMO Isolating and getting to the root cause of failures is the most important skill of the developer.

**Comment by BebeSparkelSparkel** [comment]
Thanks for the advice.

Here is an exact example of the problem that I'm having. I'm relying on the docs provided for the callback method provided in the docs:
"
If you ever need to explicitly teardown the connection pool, you may use knex.destroy([callback]). You may use knex.destroy by passing a callback, or by chaining as a promise, just not both.
"
Meaning I should have the same results if I use the callback or promise method.

```javascript
const KNEX = require('knex')

describe('after each destroy database', function() {

  let knex_db
  const new_database = () => {
    console.log('create')
    knex_db = KNEX({
      client: 'sqlite3',
      connection: {filename: ':memory:'},
      useNullAsDefault: true,
    })
  }

  const destroy_database = done => {
    console.log('destroy')
    knex_db.destroy(done)
  }

  before(new_database)
  after(destroy_database)

  describe('needs to be destroyed after each', function() {
    beforeEach(new_database)
    afterEach(destroy_database)

    it('test 1', ()=>{})
    it('test 2', ()=>{})
  })

  describe('tests need to be run on the same database', function() {
    it('test 3', ()=>{})
    it('test 4', ()=>{})
  })
})
```
Console error:
```terminal
$ npx mocha test/try-knex-destroy.js 


  after each destroy database
create
    needs to be destroyed after each
create
      ✓ test 1
destroy
create
      ✓ test 2
destroy
    tests need to be run on the same database
      ✓ test 3
      ✓ test 4
destroy
    1) "after all" hook: destroy_database


  4 passing (2s)
  1 failing

  1) after each destroy database
       "after all" hook: destroy_database:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

If I change the destroy_database function to (using promises):
```javascript
  const destroy_database = () => {
    console.log('destroy')
    return knex_db.destroy()
  }
```
Then there is no timeout error:
```terminal
$ npx mocha test/try-knex-destroy.js 


  after each destroy database
create
    needs to be destroyed after each
create
      ✓ test 1
destroy
create
      ✓ test 2
destroy
    tests need to be run on the same database
      ✓ test 3
      ✓ test 4
destroy

  4 passing (166ms)
```
Meaning there is inconsistent behavior between your promise and callback methods, which I think you would agree is not a good thing.
If that is the intended behavior (which it shouldn't be) that inconsistency should be documented for the destroy method.

**Comment by elhigu** [comment]
Ok right, your error is that you are creating new database twice, when you start your tests (before and beforeEach) and then in the end in `after()` you are not actually destroying the database that you created in `before()` but you are trying to destroy again the DB instance you created in the last  `beforeEach()`. 

That could hang in the end of process, because the db instance created in the first `before()` call is never destroyed.

So you need to separate the instance that you are initializing / destroying in before / after from the ones created in beforeEach / afterEach.

**Comment by BebeSparkelSparkel** [comment]
Thanks, I've done that by just having a bool flag.
Still it seems odd that the use of a promise and a callback get different results
