### ISSUE TITLE
Why does the count method not just return the count

### ISSUE THREAD

**Issue by guidsen** [tgriesser/knex#2436]
Knex version: 0.13.0

When using the count method, the result is `[ { 'count(*)': 1 } ]`.
What is the motivation behind this and why doesn't it just return `1`?

```
const result = knex('team_user')
  .where('team_id', 3)
  .count();

// result always equals [ { 'count(*)': 1 } ]
```

**Comment by elhigu** [comment]
Because count query returns one row, with column name `count(*)` and when ever knex query returns row(s) result is parsed to an array of objects. 

So knex does not care what kind of query was sent when it decides how to parse query result.

**Comment by guidsen** [comment]
Yes, but does it make sense? Like you say, it always "returns one row, with column name `count(*)`". Why should the Knex user transform it themselves?

**Comment by elhigu** [comment]
Yes it makes sense and it is by design. Knex cannot know all the different kind of queries that you are making and decide which would be perfect way treat the result. For example:

```
knex('foo').select('boo').count()
```

Could not just return singlenumber.

Or how about:

```
knex('foo').select(knex.raw('count(*)');
```

Is the exact same query, but should that also return just single number or result with single row?

If knex starts to analyze what kind of query was made to return result in prefect format, there will be no end to that road. 

Knex is pretty low level _query builder_ which just allows you to generate what ever SQL you like to send to DB then it allows DB to return _anything_ back and returns that in consistent format. It is job of some higher level library made top of knex can start doing semantic analysis what kind of query was sent and how in that particular case result should be extracted.

Anyways using knex directly without any higher level library like bookshelf or objection on top of it gets pretty inconvenient on any bigger projects.
