### ISSUE TITLE
select() produces inconsistent return types

### ISSUE THREAD

**Issue by ctrom** [tgriesser/knex#2453]
# Environment
Knex version:0.14.2
Database + version: (PostgreSQL) 9.5.10
OS: Linux
# Bug

Doing a SELECT without a WHERE clause produces inconsistent results.
If I execute:
```
let r1 = await books.select()
console.log(r1)
let r2 = await books.where('id', 1).first()
console.log(r2)
let r3 = await books.select()
console.log(r3)
```
The log prints:
An **array** for `r1`
An **object** for `r2`
An **object** for `r3`

If I change the order of the statments:
```
let r1 = await books.select()
console.log(r1)
let r3 = await books.select()
console.log(r3)
let r2 = await books.where('id', 1).first()
console.log(r2)
let r4 = await books.select()
console.log(r4)
```
The log prints:
An **array** for `r1`
An **array** for `r3`
An **object** for `r2`
An **object** for `r4`

It seems that `books.select()` will produce an array consistently, until `books.where('id', 1).first()` is called, after which `books.select()` stops returning arrays and returns objects.

**Comment by wubzz** [comment]
This isn't necessarily inconsistent, though I guess I see why you'd think so at first glance. 

`books` in this case is and instance of a query builder, and each call to the query builder naturally changes the state of the instance and thereby also the generated SQL. The call to `.first` is (internally) essentially the same as `.limit(1)`, and that state stays for the next `.select()` statement since it is still the same query builder instance.

Another example is that the `.where('id', 1)` call applies not only to `r2` but also `r4` in the last example.

For your described expected behavior you would need to use `book.clone()` followed by `.select()` / `.first()`.
