### ISSUE TITLE
.afterCreate callback is not invoked after upgrade from 0.14.2 to 0.14.3

### ISSUE THREAD

**Issue by basharov** [tgriesser/knex#2463]
# Environment

Knex version: 0.14.3
Database + version: Postgres 10.2
OS: Debian 10.2-1.pgdg90+1

# Bug

1. I have a callback that executes some code as described in http://knexjs.org/#Installation-pooling-afterCreate

2. WIth 0.14.2 all works just fine, but when I upgrade to 0.14.3, the callback is never executed. I tried to downgrade to 0.14.2 and it worked again.

**Comment by elhigu** [comment]
Cannot reproduce:

```js
const knex = require('knex')({
  client: 'pg', 
  connection: 'postgres:///knex_test', 
  pool: { afterCreate: function (conn, done) { console.log('AFTERCREATE'); done(); } }
});

> knex.raw('select 1').then(console.log)
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> AFTERCREATE
Result {
  command: 'SELECT',
  rowCount: 1,
  oid: null,
  rows: [ anonymous { '?column?': 1 } ],
  fields: 
   [ Field {
       name: '?column?',
       tableID: 0,
       columnID: 0,
       dataTypeID: 23,
       dataTypeSize: 4,
       dataTypeModifier: -1,
       format: 'text' } ],
  _parsers: [ [Function: parseInteger] ],
  RowCtor: [Function: anonymous],
  rowAsArray: false,
  _getTypeParser: [Function: bound ] }
```

**Comment by elhigu** [comment]
Also please read: https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md#what-is-minimal-code-to-reproduce-bug-and-why-i-have-to-provide-that-when-i-can-just-tell-whats-the-problem-is

Maybe there is something wrong in your setup, which we can spot from the example how to reproduce the problem.

**Comment by djcuvcuv** [comment]
@elhigu @basharov I am seeing this very same behavior as well. I was not able to get this to work in the latest version of knex, but when I installed version 0.14.2, it suddenly started working. I could be wrong here, but isn't it simply because 0.14.2 depends on node-pool.js, whereas version greater than 0.14.2 depend on tarn.js?

Follow the below links to see that the package.json dependencies seems to corroborate the above fact:
https://github.com/tgriesser/knex/blob/0%2C14%2C2/package.json#L12
https://github.com/tgriesser/knex/blob/0.14.4/package.json#L21

**Comment by elhigu** [comment]
@djcuvcuv please add test code or it didn't happen. I just demonstrated above that after create was called with 0.14.3. afterCreate is not implemented by pool, but it is implemented in knex side.

**Comment by djcuvcuv** [comment]
@elhigu Thanks for the quick response. Absolutely, let me reproduce this in as simple a way as possible and provide it here. In the interim though, per your comment about it being implemented on the knex side, I see no evidence of this in the latest version of knex. All I see is the below reference, which seems to be never used upstream:
https://github.com/tgriesser/knex/blob/master/src/client.js#L237-L238

**Comment by elhigu** [comment]
> All I see is the below reference, which seems to be never used upstream

You just pasted link to the place where afterCreate functionality is implemented.  Tarn calls that `create ` function every time when it is adding new connection to the pool.

And global knex (even if I would have one, I never install nothing with npm globally) wouldn't superseed that locally installed one.

**Comment by djcuvcuv** [comment]
@elhigu I understand; just wanted to rule out other possible issues. Please find below two reproductions; the first which uses knex 0.14.4 and does not produce any afterCreate artifacts, and the second, which uses knex 0.14.2 and does produce afterCreate artifacts.

```
chris-mbp2017:node-test ccovney$ node
> const knex = require('knex')({
    client:'mssql', 
    connection: {
        server: 'localhost',
        user: 'dummy-user',
        password: 'dummy-pw',
        database: 'dummy-db',
        requestTimeout: 3600000,
        options: {
            trustedConnection: false,
            instanceName: undefined,
            encrypt: true
        }
    },
    pool: { 
        min: 3,
        max: 11,
        afterCreate: (conn, done) => { console.log('AFTERCREATE'); done(); }
     }
});

> knex.client.acquireRawConnection().then(console.log)
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> (node:32841) [DEP0064] DeprecationWarning: tls.createSecurePair() is deprecated. Please use tls.Socket instead.

chris-mbp2017:node-test ccovney$ npm list knex
/Users/ccovney/Downloads/node-test
└── knex@0.14.4 
```

```
chris-mbp2017:node-test ccovney$ node
> const knex = require('knex')({
    client:'mssql', 
    connection: {
        server: 'localhost',
        user: 'dummy-user',
        password: 'dummy-pw',
        database: 'dummy-db',
        requestTimeout: 3600000,
        options: {
            trustedConnection: false,
            instanceName: undefined,
            encrypt: true
        }
    },
    pool: { 
        min: 3,
        max: 11,
        afterCreate: (conn, done) => { console.log('AFTERCREATE'); done(); }
     }
});
> (node:32931) [DEP0064] DeprecationWarning: tls.createSecurePair() is deprecated. Please use tls.Socket instead.
AFTERCREATE
AFTERCREATE
AFTERCREATE

chris-mbp2017:node-test ccovney$ npm list knex
/Users/ccovney/Downloads/node-test
└── knex@0.14.2 

chris-mbp2017:node-test ccovney$ 
```

Please let me know your thoughts and thanks for your help!

**Comment by elhigu** [comment]
Thanks for reproduction guide. Try to make query instead of calling acquireConnection() which is not part of public API.

0.14.4 doesn't prefill pool (by design), so it is expected that after creates are not launched when knex instance is created.

Also does this happen only with mssql? For me i is a bit nasty to test on locally.

And one more helpful piece of information would be if you can include debug prints that are outputted when knex is run with `DEBUG=knex:*` environment variable set.

**Comment by djcuvcuv** [comment]
No problem. My use case is only with mssql, so I cannot speak to other use cases I'm afraid :(

Ah ok, but even if it doesn't prefill the pool, shouldn't we still see the 'AFTERCREATE' log at least after the `acquireRawConnection()` function is called?

I use `acquireRawConnection()` because I want to access the raw mssql driver, so that I can do output parameter binding for Stored Procedures. Output parameter binding takes a callback, which distinguishes it from input parameter binding.

Unless there is way to support both in/out param binding with one of knex's public APIs, I think my use case needs to use the private `acquireRawConnection()` function. Our flow basically looks like this:
```
require('knex')({/* config obj */}).client.acquireRawConnection()
    .then((pool) => { 
        pool.request().output({/* options */}).execute('dummy-stored-procedure');
    });
```

Very interested to hear your thoughts and thanks again!
