### ISSUE TITLE
Keeping timezone information in MSSQL for a datetime field ("datetimeoffset")

### ISSUE THREAD

**Issue by electrotype** [tgriesser/knex#2501]
In SQL Server, need a column that is a datetime and information about its timezone. The type for that in SQL Server seems to be `datetimeoffset`. How can I make knex use this type in a schema migration?

If I use `timestamp` the timezone is not kept since `datetime` is actually used as the type for the resulting column.

**Comment by elhigu** [comment]
Have you tried to create that column with `.specificType('comlumnName', 'datetimeoffset')` ?

http://knexjs.org/#Schema-specificType

**Comment by electrotype** [comment]
Thanks, I will! I just wish `timestamp` would use `datetimeoffset` by default in MSSQL, as it uses `timestampz` for Postgres.

**Comment by electrotype** [comment]
I think you are wrong about this one! ;-)

https://www.postgresql.org/docs/9.1/static/datatype-datetime.html : 
>  timestamptz is accepted as an abbreviation for timestamp with time zone; this is a PostgreSQL extension.

**Comment by elhigu** [comment]
@electrotype nope, I know that postgres documentation is pretty vague what `timestampz` actually adds to the normal `timestamp` field (this is pretty common misconception about `timestamptz` type). If you look carefully you see that both column types are 8 bytes so with timezone actually does not have any extra information. Neither of the columns has a way to actually request what was the timezone of the original inputted value, since both are just stored internally as 8 bytes telling microseconds from 4713 BC.

Docs also mentions:
 
> The type time with time zone is defined by the SQL standard, but the definition exhibits properties which lead to questionable usefulness.

Basically only difference with timestamp and timestamptz fields is the way, how they are printed out by the database. So `timestamptz` columns are automatically converted to local timezone that is set for the database server connection when from `timestamp` columns no timezone information is printed out and they are not converted when printing them. 

Here is demonstration of the difference of the data types:

```
mikaelle=# set timezone='+02;
SET
mikaelle=# select '2010-01-01T00:00:00.000+00:00'::timestamptz as gmtTz, '2010-01-01T00:00:00.000+00:00'::timestamp as gmtNoTz, '2010-01-01T00:00:00.000+06:00'::timestamptz as plus6Tz, '2010-01-01T00:00:00.000+00:00'::timestamp as plus6NoTz;
         gmttz          |       gmtnotz       |        plus6tz         |      plus6notz      
------------------------+---------------------+------------------------+---------------------
 2010-01-01 02:00:00+02 | 2010-01-01 00:00:00 | 2009-12-31 20:00:00+02 | 2010-01-01 00:00:00
(1 row)

mikaelle=# set timezone='utc';
SET
mikaelle=# select '2010-01-01T00:00:00.000+00:00'::timestamptz as gmtTz, '2010-01-01T00:00:00.000+00:00'::timestamp as gmtNoTz, '2010-01-01T00:00:00.000+06:00'::timestamptz as plus6Tz, '2010-01-01T00:00:00.000+00:00'::timestamp as plus6NoTz;
         gmttz          |       gmtnotz       |        plus6tz         |      plus6notz      
------------------------+---------------------+------------------------+---------------------
 2010-01-01 00:00:00+00 | 2010-01-01 00:00:00 | 2009-12-31 18:00:00+00 | 2010-01-01 00:00:00
(1 row)

mikaelle=# 
```

**Comment by electrotype** [comment]
Thanks a lot for the clear explanation. I've learned something today.
