### ISSUE TITLE
Expose list of in-progress operations

### ISSUE THREAD

**Issue by igor-savin-ht** [tgriesser/knex#2503]
# Feature discussion / request

1. Since our code relies heavily on asynchronous events, unit tests are not inherently aware of when all the background actions are done. In practice this sometimes results in fixture part of the tests trying to delete data that is still referenced from the data that is still in the process of being inserted from the previous test (e. g. audit kicks in which is of no benefit for the most of the tests)

2. If knex would somehow expose data about whether or not there are any active queries or inserts at this point, this would allow to implement client-side logic which would patiently wait for everything to wrap up before cleaning the data.

I'm not sure this is possible at all currently - does knex track unfinished operations at all or purely relies on event-based listeners?

I will be able to implement this functionality if it gets approved, but I would need some directions :).

**Comment by elhigu** [comment]
Knex does not track on going queries, but it provides events so that you can track them. I don't think that bookkeeping should be implemented as knex core functionality (I have written various query / transaction timer statistics implementations using knex events for our projects).

Basically you just need to listen knex.on('query',...) and respective error / result events. There is unique identifier stored in every query which can be used to match different events to be for the same query.

If other collaborators disagree lets open this again.

**Comment by igor-savin-ht** [comment]
@elhigu Yeah, makes sense if there isn't already existing bookkeeping mechanism in place. Thanks!
