### ISSUE TITLE
Expose knex.ident()/knex.ref() function

### ISSUE THREAD

**Issue by wubzz** [tgriesser/knex#2507]
# Feature discussion / request

1. Explain what is your use case

Generating an identifier such as `table.column` -> `"table"."column"` currently requires `knex.raw('??', 'table.column')` which gets pretty tedious to keep repeating around the codebase.

There have been several issues asking:
- How to do this?
- Is it possible via public API?
- Would a PR adding a way to expose this type of function be accepted?

We have yet to do something about this, so I figured I would revive the discussion with a new feature proposal.

2. Explain what kind of feature would support this

Exposing a new function on the `make-knex.js` object *(returned by calling `knex({})`)* that simply proxies its arguments to `client.formatter(this.raw()).columnize(...arguments)` would allow for syntax such as `knex.ident('table.column')`

3. Give some API proposal, how the feature should work

```javascript
//Old
knex('Table1')
.where('Table1.UserId', knex.raw('??', 'Table2.UserId'))
.select()

//New
knex('Table1')
.where('Table1.UserId', knex.ident('Table2.UserId'))
.select()
```

*(Open for better function name than 'ident'/'identifier')*

I realize that this does not result in much less code, but that is not the goal. It's simply a new public-API-exposed function that serves a specific purpose and can be documented as such.

**Comment by elhigu** [comment]
In objection we have `ref()` for column / json references, `lit()` for these cases and in addition those helpers also supports casting references columns / literals to different types, which is necessary in many cases.

I think this would be good feature to have also in knex.

**Comment by elhigu** [comment]
this ident builder could maybe even have knex.indent('Table.Column').withSchema('Schema') supported.

**Comment by wubzz** [comment]
Won't `.withSchema` add some overhead? Since `Schema.Table.Column` as input should yield the same result, I think. Or maybe add it anyway for consistent syntax with `queryBuilder`?

Casting would also be great, it's another requested feature. Though, we'd also need to expose `knex.castX` somehow since one might want to cast values and not just references. How does Objection handle this? For example `'2018-02-23'::date`

**Comment by elhigu** [comment]
@wubzz I don't see how it would add any significant overhead. Problem with `part1.part2.part3` syntax is currently ambiguity, that one has to interpret it differently every places in knex API.  for exmample `part1.part2` may mean `table.column` or `schema.table` depending where you use it and when used as `part1` it may mean `table`, `column` or `schema`. 

Though it may be possible to interpret those correctly in every builder API method case by case though, when we know that certain api need reference to table so `schema.table` and `table` would be possible and `schema.table.column` should fail and if column ref is needed by some other API then `schem.table.column`, `table.column` and `column` would be valid references.

I remember there were some problems when was the last time I looked into this `part1.part2.part3` syntax and AFAIK that syntax is not currently officially supported by knex (not tested / documented). Not sure if it had something to do with joins or what was it.

I like copying/stealing ideas from all the other libs out there :)

Here are some examples how they work in objection http://vincit.github.io/objection.js/#ref81 and here is builder API http://vincit.github.io/objection.js/#referencebuilder 

It relays more to builder pattern and it evaluates those builders to strings lazily, just before making query (so that one doesn't have to know dialect / have db connection in hand until the very last possible moment). One use case for lit() was also to be able to decide for example which postgres array syntax to use in different places in code (even when using raw sql with value bindings).

**Comment by wubzz** [comment]
I personally have no strong opinion on if implementation should be a builder or a function. I do however think we should leave casting for a seperate issue, even if it eventually gets baked into a single builder/function later on.

**Comment by elhigu** [comment]
Its fine by me.

**Comment by wubzz** [comment]
Closed since it's now merged.
