### ISSUE TITLE
Knex prevents process from exiting since upgrade to tarn

### ISSUE THREAD

**Issue by LaurentZuijdwijk** [tgriesser/knex#2510]
# Environment

Knex version: >0.14.4
Database + version: All
OS: Linux

# Bug

Since upgrading from generic-pool to tarn, node processes stay open instead of exiting.

```
const Knex = require('knex');
const opts = {
  client: 'sqlite3',
  connection: {
    filename: './dev.sqlite3'
  },
}
knex = Knex(opts);
```
I expect this code to exit immediately, but in the latest version the process keeps running. This is caused by tarn as a connection pool as far as I can tell. 

I can see two solutions for this:
1. Destroy the pool when no connections are needed. 
2. If pool.max = 0, use a raw connection instead of a pool.

**Comment by fl0w** [comment]
Hasn't this always been the case though? I distinctly have muscle memory to surround my CLI tools with a `finally`-block to teardown knex (with `knex.destroy()`).

**Comment by wubzz** [comment]
I can reproduce this jumping between 0.14.0 and 0.14.3. 

I believe this is because with the example config `generic-pool` library would never have started any timers *(setInterval)* since it requires `evictionTimeoutMillis` to be explicitly set. 

`tarn.js` on the other hand has [default values](https://github.com/Vincit/tarn.js/blob/master/lib/Pool.js#L75) *(thank god)* for cleaning up the pool, which means it has to setup a [cleanup timer](https://github.com/Vincit/tarn.js/blob/master/lib/Pool.js#L92) when the pool is created. Pretty sure this is what's keeping the process alive. @koskimas @elhigu Can correct me on that.

First thought that popped into my head is to not create the timer until after the first `acquire` call, but I haven't looked into what kind of implications that may yield instead.

**Comment by elhigu** [comment]
@wubzz that sounds correct that process not exiting is probably caused by interval that is ran by the pool for checking for idle connections . 

I think that this is correct functionality that process should not exit if pool is not destroyed. 

If this is really not wanted functionality, I believe that pool could be changed in a way that idle connection reaper interval would be removed if pool is empty to allow process to exit if `pool.min = 0` and all the connections has been removed.

**Comment by LaurentZuijdwijk** [comment]
@elhigu I would suggest making the pool optional so that all use cases can be supported. I would also suggest bumping the version number for a breaking change like this.

**Comment by elhigu** [comment]
It was undocumented functionality / bug so it is debatable if it should have been bumped also I'm not sure how that functionality was in 0.13. I had always impression that it was obligatory to call `knex.destroy()` to exit.

Also 0.14.0, 0.14.1 and 0.14.2 were so broken that actually 0.14.3 if the first verion after 0.13 so there actually was minor bump anyways from 0.13 -> 0.14.3 (nobody should have used 0.14.0, 0.14.1 or 0.14.2).

About using single connection knex I don't see why it couldn't be allowed (there will be at least one layer of pools with some dialects anyways even that it looks like single connection to knex users). It will just need feature request (with initial API plan for it) and then PR with implementation, tests and documentation.

Anyways if you are having single connection knex, it still will keep process from exiting until that single connection is closed. I'm not sure if I want to include feature that actually creates new connection for every query and then automatically closes the connection after single query has been executed.

**Comment by koskimas** [comment]
I think we could pretty easily make tarn call `clearInteval` for the reaper loop when the pool becomes empty and then start the reaping loop again after the first `acquire`.

**Comment by koskimas** [comment]
@wubzz fixed this in tarn and I just released a new patch version of it. @LaurentZuijdwijk reinstalling should now give you a fixed version. Could you try it out?

**Comment by LaurentZuijdwijk** [comment]
Works perfectly, thanks a lot @wubzz  and @koskimas . My tests finish as quickly as before now. :+1:
