### ISSUE TITLE
Performance of knex.select().from() is very slow compared to knex.raw()

### ISSUE THREAD

**Issue by jeremija** [tgriesser/knex#2518]
# Environment

Knex version: 0.14.4
Database + version: SQLite 3.1.13
OS: Arch Linux, Mac High Sierra OS 10.13.3

# Bug

Using `knex.select().from()` causes a big performance degradation when compared to `knex.raw()`. For the same query, the performance can be up to 4x slower:

```
$ node test.js
preparing database...
running benchmarks...
select `id`, `name` from `test` [knex.raw()   : 9999 rows in 49ms]
select `id`, `name` from `test` [knex.select(): 9999 rows in 191ms]
```

I'd expect `knex.select().from()` to only be slightly slower than the raw query. It seems to be worse when querying large tables (`N=100000`):

```
$ node test.js
preparing database...
running benchmarks...
select `id`, `name` from `test` [knex.raw()   : 99999 rows in 493ms]
select `id`, `name` from `test` [knex.select(): 99999 rows in 808ms]
```

I first noticed this with Oracle, but I quickly realized it happens with SQLite3 as well. A full test case is available here: https://github.com/jeremija/knex-bug-report:

```
git clone https://github.com/jeremija/knex-bug-report
npm install
N=100000 node test.js
```

Might be related to #1795.

**Comment by elhigu** [comment]
Here is online version of your benchmark https://runkit.com/embed/8szo1dhyi9wc 

I wouldn't consider this as a bug nor big problem since it is natural that query building and result parsing must take longer time when not using knex.raw ,which basically just sends query to the driver and returns unprocessed result to the caller... however I am a bit interested to see from profiling data what is it actually that is making the biggest difference. This is not related to #1795.

> It seems to be worse when querying large tables (N=100000):

Actually your results show (runkit version) that select version is only ~1.5x compared to raw with large tables and repeated runs and with smaller table difference is bigger ~4x.

**Comment by elhigu** [comment]
Closing since I don't see this being bug. Any extra information about profiling etc. is welcome though.

**Comment by jeremija** [comment]
>> It seems to be worse when querying large tables (N=100000):
>
> Actually your results show (runkit version) that select version is only ~1.5x compared to raw with large tables and repeated runs and with smaller table difference is bigger ~4x.

You're right about 1.5x, but I don't think that's the best way to look at it since the query time difference is not constant. For example (unfortunately I could not run this in runkit since it timed out):

```
$ N=1000000 node test.js
preparing database...
running benchmarks...
select `id`, `name` from `test` [knex.raw()   : 999999 rows in 2908ms]
select `id`, `name` from `test` [knex.select(): 999999 rows in 3500ms]
```

As the query construction surely does not take `592ms`, this most likely means extra processing power is used during the row mapping, which (for me) was unexpected since there were no joins or anything special that was happening in the query.

**Comment by wubzz** [comment]
Slightly modified the test version by adding some timers to query execution

>preparing database...
running benchmarks...
query 14 ms
select `id`, `name` from `test` [knex.raw()   : 9999 rows in 15ms]
query 14 ms
select `id`, `name` from `test` [knex.select(): 9999 rows in 46ms]

Looked at how `sqlite3` processes the response since the time to compile and run query comparison between `raw` and `builder` seems equal. Turns out it maps every row and picks enumerable keys from each object. This naturally causes more and more delay when more and more rows are returned.

```javascript
//helpers.skim
// Pick off the attributes from only the current layer of the object.
export function skim(data) {
  return map(data, (obj) => pick(obj, keys(obj)));
}
```

Temporarily disabled this function and the result is

>preparing database...
running benchmarks...
query 14 ms
select `id`, `name` from `test` [knex.raw()   : 9999 rows in 15ms]
query 13 ms
select `id`, `name` from `test` [knex.select(): 9999 rows in 16ms]

Now obviously running a `postProcessResponse` is neccessary, but the question is if this specific function is needed or not. I don't know `sqlite3` enough to answer this nor why the function itself is needed originally.

Seems the exact same applies to Oracle, MySQL, Maria, MSSQL as well. Does not apply for Postgres or RedShift.

**Comment by kirrg001** [comment]
@elhigu I was testing knex vs. mysql vs. bookshelf yesterday, see issue [here](https://github.com/bookshelf/bookshelf/issues/1774). The test suite was attached in the issue - you can download the zip file. It was a very simple setup with **only 7 entries in my target table**.

I did a simple stress test with wrk, Node 6 and MySQL.

> wrk -t20 -c300 -d60s --timeout 30s http://localhost:2369/

The average response when using MySQL was: ~170ms
The average response when using Knex was: ~280ms (using `knex.select(*).from('posts')`).
The average response when using Bookshelf was: ~480ms

Knex needs over 100ms more than MySQL 🤔

**Comment by elhigu** [comment]
@kirrg001 From your timings I suppose that results you are returning are quite big to parse. The same thing @wubzz found out should cause similar slowdow in your case if there is lots of data returned (biggest delay is when driver transport / parses result and second biggest is when knex loops over result and processes it too).
