### ISSUE TITLE
Raw query escape 

### ISSUE THREAD

**Issue by ericsin112** [tgriesser/knex#2519]
I'm using Knex.js with oracledb. I'm trying to insert record to database.

`knex.raw("insert into table (url) values ('http://abc.com?a=2')")`

Result:
`http://abc.com:1a=2`

I've tried to use `\\` or `\\\\` to escape `?` but also not work (Results: `\:1` & `\\:1`).

How can I escape `?` and save the value(http://abc.com?a=2) to database?

**Comment by wubzz** [comment]
I cannot reproduce this with the given example.

`knex.raw("insert into table (url) values ('http://abc.com?a=2')").toString()`
>insert into table (url) values ('http://abc.com?a=2')

If no binding is supplied the `?` cannot be replaced.

If a binding were to be supplied, it would be replaced by it.
`knex.raw("insert into table (url) values ('http://abc.com?a=2', ?)", ':').toString()`
>insert into table (url) values ('http://abc.com':'a=2')

If you escape the `?` while still supplying a binding, an error will be thrown due to unexpected bindings
`knex.raw("insert into table (url) values ('http://abc.com\\?a=2')", ':').toString()`
>Error: Expected 1 bindings, saw 0

If you escape the `?` without a binding, all is well.
`knex.raw("insert into table (url) values ('http://abc.com\\?a=2')").toString()`
> insert into table (url) values ('http://abc.com?a=2')

Please reopen with a better way to reproduce the issue *(if it still is one)*. Preferably with an attached test file.

**Comment by ericsin112** [comment]
It can escape when I using `toString()` method to check the query, but when I actually execute the query, the result wasn't escaped.

Here is the example...

> const Knex = require('knex');
> 
> const client = new Knex({
>   // your config
> });
> 
> console.log('sql', client.raw("select 'http://abc.com\\?type=report' as result from dual").toString());
> 
> client.raw("select 'http://abc.com\\?type=report' as result from dual")
>   .then(res => {
>     console.log('res', res);
>   }).catch(err => {
>     console.log('err', err);
>   })

Results: 

> sql select 'http://abc.com?type=report' as result from dual
> res [ { RESULT: 'http://abc.com\\:1type=report' } ]

**Comment by elhigu** [comment]
@ericsin112 don't use toString() to check the executed query. Use `.toSQL().toNative()`

**Comment by elhigu** [comment]
@ericsin112 Are you really trying to use full uri as column name? I can tell you it won't work (as you see).

Maybe you are trying to do this (you can see that the url value containing ? mark is passed as binding to prevent sql injection):

```
knex.select(knex.raw('?', ['http://abc.com?action=a'])).from('dual').toSQL().toNative();
``` 

https://runkit.com/embed/efr3nksr2hlu

**Comment by H6LS1S** [comment]
Why does this work for default values ​​in migration ?

```js
exports.up = function(knex, Promise) {
  return knex.schema.table(tableName, t => {
    t.string('link')
      .nullable()
      .defaultTo('https://somewebsite/path?p=12345&id=12345');
  }
}
```

```sql
CREATE TABLE public.sometable
(
    id integer NOT NULL DEFAULT nextval('sometable_id_seq'::regclass),
    link character varying(255) COLLATE pg_catalog."default" DEFAULT 'https://somewebsite/path$1p=12345&id=12345'::character varying
)
```
