### ISSUE TITLE
.using('column') with joinclause

### ISSUE THREAD

**Issue by junh2017** [tgriesser/knex#2568]
# Environment

Knex version:0.14.1
Database + version:mysql 5.7

# Feature request

knex('table1').join('table2').using('col')
instead of knex('table1').join('table2','table1.col','table2.col')

**Comment by elhigu** [comment]
Sorry I need to reject this request. I don't want to add more APIs which are actually more obscure and less versatile about what they should do than the current alternative. Knex should reflect closely the actual SQL that is generated from builder. Usually join column names are not the same.

If more magic is needed for knex, then you should try objection.js or some other ORM.

**Comment by junh2017** [comment]
Hi,I understand you. But isn't "using('column')" an original API of mysql?I think knex should at least have full APIs generated from building because I don't want to use other ORM if it is not very necessary when I already used knex.
You can see the api here:https://dev.mysql.com/doc/refman/5.7/en/join.html.

**Comment by elhigu** [comment]
@junh2017 ah right, I didn't know about that feature existing. But I still wouldn't like to implement it to knex, because it would need to be emulated on other DBs with joins anyways and in that case it would be easiest to convert it to join in mysql too.

If / when we have separate API extensions for every dialect I could consider adding this to mysql specific APIs. But I don't see that happening any time soon.
