### ISSUE TITLE
How to execute multiple queries in one run?

### ISSUE THREAD

**Issue by kobalicek** [tgriesser/knex#257]
I'm facing a problem that I would like to execute multiple queries separated by ';' by a single exec, is that possible?

My test code which is failing looks like:

```
      var query = '' +
        'UPDATE "records_raw" ' +
        'SET "title" = ? ' +
        'WHERE "id" = ?' +
        ';' +
        'UPDATE "records_raw" ' +
        'SET "title" = ? ' +
        'WHERE "id" = ?' +
        ';';

      var bindings = [
        "x", "1",
        "y", "2"
      ];

      knex.raw(query, bindings).exec(function(err, result) {
        assert.isNotError(err);
      });
```

The error:

```
Error(cannot insert multiple commands into a prepared statement, ...
```

Is there a way to disable prepared statements for such queries?

**Comment by tgriesser** [comment]
Okay so if anyone here is interested - I'm working on some new things in the upcoming refactor to make this possible.

I'm wondering about what the ideal api would be for this... do we want to have a single chain?

```js
knex
  .update('records_raw')
  .set({title: x}).where({id: 1})
  .end()
  .update('records_raw')
  .set({title: y}).where({id: 2})
  .spread((resultA, resultB) => {
     
  })
```

or something more like:

```js
knex.multiQuery([
  knex.update('records_raw').set({title: x}).where({id: 1})
  knex.update('records_raw').set({title: y}).where({id: 2})
]).spread((resultA, resultB) => {

})
```

Also looking at making the possibility of making the `knex.raw` case work automatically by splitting on the semicolon.

**Comment by Hesse** [comment]
Splitting on semicolon on raw queries would be a great start.

**Comment by Hesse** [comment]
I'm running into a problem right now where my delete is not completed in time before my insert, so I'm getting duplicate key errors being thrown. 

I'm doing something like 
knex("mytable")
.where({
  id: 32423
})
.del()
.then( ->
  knex("mytable")
  .insert()
 ..... 

you get the gist.. 

The del doesn't complete in time.

**Comment by locnguyen** [comment]
@tgriesser my vote is for knex.multiQuery

**Comment by ryanstinson** [comment]
@tgriesser any update on the ability to execute multiple statements in a single query? I would prefer:

.update('records_raw')
  .set({title: x}).where({id: 1})
  .end()
  .update('records_raw')
  .set({title: y}).where({id: 2})
  .then(function(err, result) {
    result[0] //result 1
    result[1] // result 2
  });

**Comment by rfink** [comment]
+1

**Comment by chrisbroome** [comment]
In order to do proper splitting on semicolons, we'd need to parse the entire raw query using a dialect-specific parser. Specifically, if strings contain `;`, they should be ignored. Here are two examples of valid SQL that would be nontrivial to parse.

```SQL
-- generic SQL
SELECT * FROM book WHERE title = 'Lord of the Rings; The Fellowship of the Ring';
```

```SQL
-- MySQL specific
CREATE PROCEDURE dorepeat(p1 INT)
  BEGIN
    SET @x = 0;
    REPEAT SET @x = @x + 1; UNTIL @x > p1 END REPEAT;
  END
```

Also note in the first case we'd end up with 2 statements, so the code would need to take into account empty results from the split.

Honestly, overall, I think this is a bad idea. There's just too much of a chance for SQL injection and not splitting queries correctly.

Also, when executing multiple statements, you almost always want that to happen in the same transaction. Knex already solves this problem really well with `.transacting(function(transaction) { /* code */ })` syntax. In the rare case where you don't need a transaction, you can simply use bluebird to join your knex statements and get the results.

So because of these issues, my opinion is that this shouldn't happen.

:-1:

**Comment by bgw** [comment]
> Also, when executing multiple statements, you almost always want that to happen in the same transaction. Knex already solves this problem really well with `.transacting(function(transaction) { /* code */ })` syntax. In the rare case where you don't need a transaction, you can simply use bluebird to join your knex statements and get the results.

I can tell you from experience that in certain cases, there's a *huge* performance difference between these two approaches and batching multiple values to the server as one command.

I understand it's very hard to implement cleanly, which is why it hasn't been done yet, but this issue has greatly limited my use of knex for a project.

**Comment by ericrini** [comment]
+1

SEE: https://github.com/tgriesser/knex/issues/1075

**Comment by elhigu** [comment]
I'm failing to see any usecase for this feature. Would love to close this ticket as won't fix. If one is depending order of the queries being run on the same connection then you probably want to use transactions.

**Comment by jurko-gospodnetic** [comment]
The one thing I see that makes this 'multiple query' usage into something that we'd like to have is that it's a potential performance win in some cases. It requires less round-trips to communicate all the queries and the results to and from the server.

But it's not like I have a measurable use case available. Only speaking from past experience/memory...

**Comment by elhigu** [comment]
@jurko-gospodnetic It could be the case when you don't have connection pooling. With pooling sending multiple queries is basically just putting data to TCP socket. Also if your performance depends on TCP buffers not being filled enough then knex is already too slow for you :) In that case better to use driver directly.

**Comment by nicholaswmin** [comment]
> jurko-gospodnetic commented on May 20
 
> The one thing I see that makes this 'multiple query' usage into something that we'd like to have is that it's a potential performance win in some cases. It requires less round-trips to communicate all the queries and the results to and from the server.

I'm using [node-mysql (mysqljs)][1] on an enterprise grade project for this particular reason.

There's a considerable performance improvement on such operations that I leverage by taking advantage of the multiple-queries feature of the [node-mysql (mysqljs)][1] driver. 

It might prove a showstopper for me if Knex doesn't support this. So I'll revive this thread to ask just that.

> Are multiple-queries in one statement supported in Knex.js now? 


[1]:https://github.com/mysqljs/mysql

**Comment by elhigu** [comment]
@nicholaswmin can you tell a bit more specific what do you mean by "considerable performance improvement"? How sending multiple queries this way is considerably more efficient than just sending multiple queries through the same connection? Any benchmarks?

**Comment by nicholaswmin** [comment]
No benchmarks but right off the bat I can say this:

A single call to the db (packed with all the statements) eliminates the server-db network round-trips.

On the other hand, sending multiple queries through the same connection is not a silver bullet. This solution would only work with non-transactional flows, see [this Issue][1]

[1]: https://github.com/tgriesser/knex/issues/1806

**Comment by elhigu** [comment]
@nicholaswmin Are you sending huge amount of small queries and mostly ignored or small results? In that case I suppose difference may be noticeable, since it allows driver to pack multiple queries to each TCP packet, where otherwise each TCP packet would have mostly headers and really small amount of payload.

**Comment by nicholaswmin** [comment]
@elhigu They are small queries indeed but their results are needed so they can be used further down the transaction/query chain.

**Comment by elhigu** [comment]
Wireshark is pretty common cross-platform tool used to analyse network traffic. 

I don't believe that there is any way to get see to that level with node. 

One way could be maybe to use iptraf or anything to measure amount of sent / received data when sending the same amount of queries with packed in one query or passed separately to driver.

**Comment by danielgindi** [comment]
I would love to see a `multiQuery` syntax.

**Comment by Sequoya42** [comment]
Any update ?
Is it possible now to make multiQuery?
If so, using what syntax?

**Comment by VictorioBerra** [comment]
```javascript
// Create Schema
let createScript = `

CREATE TABLE Class ( 
	Id                   integer NOT NULL  ,
	Name                 varchar(100)   ,
	CONSTRAINT Pk_Classes_Id PRIMARY KEY ( Id )
 );

CREATE TABLE Material ( 
	Id                   integer NOT NULL  ,
	Description          varchar(500)   ,
	CONSTRAINT Pk_Material_Id PRIMARY KEY ( Id )
 )

-- ... and so on (leave off the last comma or remove it later.) ... 

`;

let statements = createScript.split(';');
let statementPromises = [];

for (var i = 0; i < statements.length; ++i) {
    statementPromises.push(knex.raw(statements[i]));
}

let Promise = require("bluebird");
Promise.all(statementPromises).then(function() {
    console.log('Schema generated. Populating tables with data...');

     // ...

```

**Comment by mscheffer** [comment]
that's just a loop

**Comment by VictorioBerra** [comment]
@mscheffer the question was:

> I'm facing a problem that I would like to execute multiple queries separated by ';' by a single exec, is that possible?

Which my answer solves. If you have a faster better solution please provide it.

**Comment by elhigu** [comment]
@VictorioBerra Splitting from `;` doesn't work in general case, since there can be `;` inside string literals and comments. If you are reading in data dump, I would say that easies way is to pipe the SQL dump code to sqlite shell. Sadly that doesn't work for in-memory databases, because they are just single connection.

Also in your case, where you are creating SQL strings in inside template string and then splitting it, using `knex.schema.*` builders effectively the same thing, but more secure. 

As far as I know there is no way to achieve this feature of running multiple queries in single command for all dialect drivers. I think it was mysql and oracledb or mssql, which had that support and with mysql you still get just the result of the last query as a response (which might be ok though).

**Comment by amedley** [comment]
**Remember to use transactions if you are modifying data using multiple queries so that you can make sure they run in succession! This rule of thumb applies even if the queries are running in one execution.**

**MULTIPLE QUERY EXECUTION USING RAW SQL**
I ran into a similar situation where one of our knex migrations needed to run `CREATE DATABASE` multiple times in a row. I hoped to separate the queries with semicolons, but knex threw a syntax error. The solution for that is to include `"multipleStatements": true` in your connection object, so the end result of that may look like this:

```
"host": "192.168.x.x",
"user": "userLogin",
"password": "userPassword",
"database": "schemaToUse",
"multipleStatements": true
```

After that, you can use a raw statement like so:

```
return knex.raw("CREATE DATABASE schema0; CREATE DATABASE schema1; CREATE DATABASE schema2")
   .then((result) => {
   })
   .catch((error) => {
   });
```

**MULTIPLE QUERY EXECUTION USING KNEX QUERY BUILDER**
If you need to use the knex query builder instead of writing the raw SQL yourself, then you have to convert the results in `Knex.QueryBuilder` to a string, and then join multiple queries together. Here's one example:

```
// Suppose that we wanted to add 100 currency for all players in multiple games
const addCurrency = 100;
const updateCurrency = { currency: "currency + " + addCurrency };
const queries = [
   knex.table("game0.stats").update(updateCurrency),
   knex.table("game1.stats").update(updateCurrency),
   knex.table("game2.stats").update(updateCurrency),
];
const multiQuery = queries.join(";");
console.log(multiQuery);
return knex.raw(multiQuery)
   .then((result) => {
   })
   .catch((error) => {
   });
```

This also helps reduce human error when writing redundant queries that need to be executed in succession. Again with something like this I would suggest wrapping it in a transaction.

**Comment by elhigu** [comment]
I think this can be closed since this is mostly limited by db drivers. At least proper feature request is needed.

**Comment by AksharaKarikalan** [comment]
`.query(function (query) {
query.select(knex.raw(` (SELECT leave_trackers.available_leave_days from leave_trackers)`)) -
(knex.raw(`SELECT ((DATEDIFF(${saveLeave.end_date}, ${saveLeave.start_date}) + 1) - 
(WEEK(${saveLeave.end_date}) - WEEK(${saveLeave.start_date})) -
(case when weekday(${saveLeave.end_date}) = 6 then 1 else 0 end) -
(SELECT IFNULL(sum(total), 0)
from
(
SELECT count(holidays.date) as total
FROM holidays, leave_applications
WHERE holidays.date between ${saveLeave.start_date} and ${saveLeave.end_date}
GROUP BY holiday_id) as holiday_leave 
)
) as available_days
FROM leave_applications
group by leave_apply_id
)) AS total_available_leave_days`)))`

I want to do this query in knex and its not working fine for me as I guess '-' in between queries is problem, can someone help me to convert this properly?, thanks!

**Comment by elhigu** [comment]
@AksharaKarikalan even if you do multiple subqueries and subtraction between those, you are still making just single query. So I removed comment which is irrelevant to this issue.

**Comment by shriram9494** [comment]
how to upload file in mysql database using knex js , node js and postman,
how??

**Comment by VictorioBerra** [comment]
@shriram9494 Your question has nothing to do with this issue, please move things like that to StackOverflow.
