### ISSUE TITLE
Question: Why doesn't knex use the original connection pools provided by drivers?

### ISSUE THREAD

**Issue by cemremengu** [tgriesser/knex#2610]
I am pretty sure you thought this before but just wondering if this a possibility. If so this can solve a lot of problems, make knex much simpler and help focus on other issues. 

A generic pool wrapper can be used to forward the operations to the original connection pool provided by the driver. :genius:

**Comment by wubzz** [comment]
One issue is that not all dialects have built-in pooling support, AFAIK. We've had many issues in the past and switching pool libs every year didn't really help in that regard. Right now we're using what I would consider a stable and tested library.

But personally - as a user - I would also like the option to use the built-in pool system provided by the dialect, just as you are suggesting. Having this option can potentially drop a lot of weight on knex's shoulders imo.

**Comment by elhigu** [comment]
I agree everything that @wubzz wrote. Furthermore knex was originally also meant to allow easy switching between databases and all pools are not really compatible how they work and what kind of parameters can be passed there.  So having own pool was originally easier choice than trying to make everything work the same way with builtin pools.

Also some features for example for timeouts etc. are a lot easier to implement in pool instead of knex. With current pool we have complete control to add features there if knex needs it.
