### ISSUE TITLE
question marks in values are replaced by $1, $2, this is incorrect

### ISSUE THREAD

**Issue by mscheffer** [tgriesser/knex#2622]
# Environment

Knex version:0.14.6
Database + version:redshift

# Bug
Question marks in values are replaced by $1 when calling

```javascript
    knex(table).insert(line).toString()
```

this isn't required, and it should be considered a bug, as the data is affected

a question mark is valid as part of a SQL value, it only has a special meaning in a statement, if i understand this correctly

i found this because i'm checking string lengths before inserting, and, because that single question mark is replaced by two characters my insert fails with an error.

correct me if im wrong (im no SQL expert, very far from it) but this seems to be a bug.
i can imagine that fixing it might cause compatibility problems with existing projects, so maybe make it an option ?

**Comment by mscheffer** [comment]
... /knex/lib/dialects/postgres/index.js line 212

i guess i will escape the ? for now

**Comment by elhigu** [comment]
You should not use ’.toString’ for any other purpose except maybe for debug prints. It is also mentioned in documentation. 

When values are passed correctly as bindings question marks in values work just fine without escaping.

**Comment by mscheffer** [comment]
no, the substitution is made later, toString() is not to blame.

im using "raw" to execute some SQL i modified, i have to use toString(), that's not where the problem lies.

it's the call to "raw" itself that transforms the ? into a $1, and only for postgress/redshift, at line 212 in index.js

im working on doing what i want in another way, without using raw altogether

**Comment by elhigu** [comment]
Yes, I know that substitution is done later, but `.toString()` is still to blame here. It causes values to be rendered to SQL string instead of keeping them as parameter bindings.

If you really need to modify your SQL generated with knex, you should use `.toSQL()` and and then modify only the sql string which has parameter bindings in place. Then you can still use `knex.raw(sql, bindings)` to run the query.

If you are running queries that are created with .toString() (which is bad idea) you need to be 10x more careful in verifying that all inputted data is validated to not contain SQL injections (not always so trivial that it sounds).

**Comment by israelidanny** [comment]
@elhigu I'm not sure this should be closed?
I have another use case - upon migration, I run a few SQL files that contain some functions, types e.t.c that I want to use in my app. 

A few of the functions have question marks inside of strings or regex objects, and knex is butchering them.

Surely there has to be a way to not assume that every question mark is a binding?

**Comment by elhigu** [comment]
@israelidanny Yes this should have been closed. The thing described in OP is not a bug, but expected behaviour. If you have separate feature request for different functionality you can open one.
