### ISSUE TITLE
Raw array binding not replaced as expected

### ISSUE THREAD

**Issue by eric-burel** [tgriesser/knex#2629]
# Environment

Knex version: 0.14.6
Database + version: SQL Server
OS: Ubuntu

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

The request does not seem to be correctly created:
```
  const qData = db.raw(
      `Select * from SOME_TABLE where SOME_PARAM = ? and SOME_OTHER_PARAM in (?)`,
      [42, ["an", "array]]
    );
```
If array is of length 1, rows are found as expected. But not if it is of length > 1.
I could not managed to display the outputed SQL though (`toSQL` only displays the request and its binding but I'd like to display the built request for debugging).

2. Error message
No error, but I got 0 rows instead of 2.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.
Will try to do asap. I can debug by myself if I find out how to output the full built query.

**Comment by elhigu** [comment]
The thing you are trying to do probably shouldn't even work anyways. Currently correct way to do your query is:

```js
  const anArr = ["an", "array];
  const qData = db.raw(
      `Select * from SOME_TABLE where SOME_PARAM = ? and SOME_OTHER_PARAM in (anArray.map(() => '?').join(','))`,
      [42, ...anArray]
    );
```

or something like that.  Here is some discussion about it https://github.com/tgriesser/knex/issues/791 basically knex would need some wrappers for arrays to allow user to tell how an array should be expanded to SQL string (or maybe it should be passed directly to the db driver).

Closing as... "kind of bug maybe, but there are workarounds and resolving underlying issue requires that one feature that has been discussed to be implemented" :p

**Comment by eric-burel** [comment]
Thanks I was trying to figure out smth similar. It's okay as long as the workaround makes sense.
Just a question, will I enjoy parameters sanitization with such a raw query to avoid code injection? I guess that's what bindings are for?

**Comment by elhigu** [comment]
Yes, bindings are never rendered to strings by knex, but passed as parameters to db driver. Huh, I hadn't seen that example in docs. It is wrong, that needs to be fixed. Only reason why it seems to work is that knex is rendering an array to string and array.toString() separates values with comma by default. That doesn't work in real life as you noticed :)

I suppose converting `knex.raw('?', [[1,2,3]])` to `knex.raw('?,?,?', [1,2,3])`, it could be reasonable default behavior and then separate wrappers could be given if array needs to be passed some different way to the underlying db driver.

I haven't investigated that enough so that I could write proper feature request about it yet. One has to investigate different array and list syntaxes of mysql, sqlite,postgres,oracle and mssql and see what kind of similarities can be found.

**Comment by eric-burel** [comment]
Thans @elhigu for your fast answer! I've submitted a small PR to the docs to clarify this point: https://github.com/knex/documentation/pull/116
For sql server this is the correct syntax but I don't know for the others.
