### ISSUE TITLE
.select(0) should give select 0, not select *

### ISSUE THREAD

**Issue by linkenneth** [tgriesser/knex#2658]
# Environment

Knex version: 0.14.6
Database + version: PostgreSQL 10.4
OS: MacOS 10.13.4 (High Sierra)

Select applicable tempalate from below.
If issue is about oracledb support tag @ atiertant. For MSSql tag @ smorey2 .
Rest of dialects doesn't need tags.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

select(0) should give select 0 in SQL, instead gives select *.

I suspect there's a check somewhere that reads

```
if (!args[0]) { ... }
```

which should probably be

```
if (args[0] !== undefined) { ... }
```

2. Error message

Compare:
```
> knex('user').select(0).toSQL()
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'a59d89c8-a6e5-4cf1-babc-33603f9a7a9f',
  sql: 'select * from "user"' }
> knex('user').select(knex.fn.now(), 0).toSQL()
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'a1a63acd-ea77-4a90-af79-fafc8bf1fcb8',
  sql: 'select CURRENT_TIMESTAMP, 0 from "user"' }
```

The second error message illustrates correct behavior in other cases.

EDIT: what is more problematic is this:

```
> knex('user').select(0, knex.fn.now()).toSQL()
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'f6ced08b-f018-4f5e-81ce-04d9cacedd86',
  sql: 'select * from "user"' }
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

See above.

**Comment by elhigu** [comment]
Actually AFAIK `knex.select(1)` or `knex.select(0)` are currently undefined behaviour. Correct syntax to do that would be really `knex.select(knex.raw('0'))`.

So if we want to support this special case where integers / numbers etc. can be passed directly as literals to select it should be also documented.

**Comment by linkenneth** [comment]
Hmm, interesting. `knex.select(knex.raw('0'))` makes sense, but at the same time it's counter-intuitive. I would expect literals to work as `.select` fields just as literals work as `.insert` data. If I didn't explicitly check I would have accidentally `select *` in a subquery.

Do you think this is something that should be implemented eventually? I can imagine that this isn't the highest priority of course.

**Comment by elhigu** [comment]
@linkenneth yeah, it is also counter intuitive that only numbers are treated as literals, when strings are treated as identifiers. With insert it is completely different story, since also strings, boolean and null are treated as literal values and nothing as identifiers by default. 

To allow numbers being this kind of special case is quite ugly, but in the other hand it is also handy time to time. If I would be designing this API from scratch I wouldn't allow that kind of special case.

**Comment by linkenneth** [comment]
I'll just leave this here then? Feel free to close.

**Comment by wubzz** [comment]
I would classify this is a bug. The only reason it does not work is due to argument check `!columns` and as we all know `0` would return true in this case. To illustrate why this is a bug, here are some examples:

```javascript
console.log(knex.select(0).from('table').toString()); // select * from "table"

console.log(knex.select(1).from('table').toString()); // select 1 from "table"

console.log(knex.select(0, 1).from('table').toString()); // select * from "table"

console.log(knex.select(1, 0).from('table').toString()); // select 1, 0 from "table"
```

**Comment by elhigu** [comment]
@wubzz yep definitely it is a bug. Only problem is which way it should be fixed. I'm ok which ever solution mentioned above, but when that solution is done all the other places in knex should work the same way too (I'm not saying that they should be fixed and tested right away of course). 

So when ever number is passed to API where normally strings are interpreted as column identifiers, the numbers are interpreted as literals (afaik join APIs also works that way currently). Or to be changed to throw an error because invalid argument.
