### ISSUE TITLE
Should I have a separate migration/seed for each table? Having issues with foreign keys. What is best practice?

### ISSUE THREAD

**Issue by booboothefool** [tgriesser/knex#2669]
I currently have one migration that creates all my tables that has a chained `.createTable`s, so they are created in the proper order.

For my seeds, I label them like `01_a`, `02_depends_on_01_a`, etc. so they run in the proper order.

When I say "proper order", I mean that the referenced table is created before the foreign key, so the foreign key has something to point to a.k.a. I can't just migrate/seed my tables in any order.

I feel like I'm putting in a lot of effort to just ensure this table is created before that table. My questions are:

1. Is there an easier way to deal with these foreign key dependencies?
2. Should I have only one table per migration/seed?

**Comment by ricardograca** [comment]
You're doing it correctly. Having one table per migration is also correct. There's no "better" answer in this case. It all depends on what's more important to you: less migration files or less code in each of the migration files.

**Comment by elhigu** [comment]
Strictly speaking, you don't have to create new migration file for every table. Only for every change you are deploying to staging / production or for example one migration per pull request if there are multiple developers working in multiple branches on the same app.

We are basically doing zero or 1 migration file per added feature. Not because it looks nice, but it is just easiest workflow for us.
