### ISSUE TITLE
Leak of __core-js_shared__ while testing using hapi/lab

### ISSUE THREAD

**Issue by nlemoing** [tgriesser/knex#2678]
# Environment

Knex version: 0.14.6
Database + version: 2.15.0
OS: macOS High Sierra v10.13.5

# Bug

When running unit tests using hapi/lab, all tests pass but this error message appears at the end: `The following leaks were detected:__core-js_shared__`. This message goes away when I don't include my knex configuration in the app. The tests don't make any queries or use knex in any way besides including the file.

I am using hapi v17.2.3 and lab v15.4.1.

knexConfig.js:
```
const Knex = require('knex');

const connectionOptions = {
    host: "db_host",
    user: "db_user",
    password: "db_password",
    database: "db_name"
};

const poolOptions = {
    min: 0,
    max: 10
};

module.exports = Knex({
    client: 'mysql',
    connection: connectionOptions,
    pool: poolOptions
});
```

**Comment by tgriesser** [comment]
This is because knex currently uses babel-runtime, which IIRC adds a global to make a `Symbol` polyfill work in environments that don't have it. We're looking to get rid of babel but for now it's probably simplest just to whitelist this, it's an intentional global, falsely labeled as a "leak".

From the hapi/lab docs:

```
-I, --ignore - ignore a list of globals for the leak detection (comma separated), this is an 
alias of globals property in .labrc file
```

So either add it in globals in .labrc or add it to the cli option.
