### ISSUE TITLE
Support multiple migration directories

### ISSUE THREAD

**Issue by kibertoad** [tgriesser/knex#2690]
# Feature discussion / request

There are two clear use-cases when having multiple migration directories is beneficial:

1. Large long-running project with huge amount of migrations becomes more manageable if you can split migrations by year;
2. If project uses migrations for versioned data seeding/modification, it may be more convenient to have separate directory for structural and separate directory for data migrations.

In order to achieve this goal, it should be possible to pass an array of paths as 'directory' parameter in Migrations API.

Migration location within provided list should be interchangeable as far as check for missing migrations is concerned, so that migration could e. g. be moved from "latest" to "2017" at any given moment.

**Comment by kibertoad** [comment]
@elhigu This is something that my current project could use so I could work on a PR of this if you would approve such change :)

**Comment by elhigu** [comment]
Maybe related issue: https://github.com/tgriesser/knex/issues/607 not exactly the same I think. 

I suppose what you are proposing is doable and pretty easy; just go through all migration directories, collect filenames, sort them and run migrations as currently (and store only migration filename).

 Writing tests for this is most difficult, where you should move migrations from one directory to another and add new migration directory on the fly etc.

Just to be sure. This change won't allow to lose any of old migration files?

**Comment by kibertoad** [comment]
Yup, tests gonna take a while :).
Which loss do you have in mind? You mean that knex should still require old migration files to be present in at least one of the specified directories? Then yeah, I don't think that we should make the check less strict than it currently is in this regard.

**Comment by elhigu** [comment]
This sounds good to me, I don't have any problems for accepting PR for this. So @kibertoad go ahead if you are up to implement this 👍

**Comment by kibertoad** [comment]
@elhigu Started working on it, one question I have - there was a rather strange decision to put Migrator class inside migrate/index.js which makes finding it less trivial than it should be. Would you mind if I extracted it into migrator.js?

**Comment by kibertoad** [comment]
@elhigu I've only done the refactoring part for now which would enable me to do the actual change easily. If you could review #2695 so that it could be merged, actual feature would have a much more readable diff :).

**Comment by elhigu** [comment]
Its merged now :)

**Comment by elhigu** [comment]
Implemented in https://github.com/tgriesser/knex/pull/2735

**Comment by ShreelekhaB** [comment]
Is there a documentation on how to use this feature ? I want to create multiple migration directories and how to use make command to specify which directory to use and similar related documentation ?

**Comment by elhigu** [comment]
https://github.com/knex/documentation/pull/129

**Comment by anjee10** [comment]
@elhigu @kibertoad thanks for making this feature!

> "`sortDirsSeparately`: if true and multiple directories are specified, all migrations from a single directory will be executed before executing migrations in the next folder (default `false`)",

Does this mean, that single directory will be taken into process by ascending order? like if I have 2017, 2018, 2019, 2020, 2021, 2002 directories, and having `sortDirsSeparately` set to `true`, so will it pick 2017 first and then picking others in order?

One more thing I was wondering on, when I have above setting to `true` and have above migration yearly directories, and when I make a new migration file by migrate:up, will it land in current year directory? because directory will be an array of paths, just wondering if there is any auto thing that I don't need to worry when I create migration, it goes to correct directory. 

Last thing, is there anything like I specify just a single migration directory path, and it auto discovers  if there's any sub directories exist and then it follows `sortDirsSeparately` flag if set.

Thanks,
Anil
