### ISSUE TITLE
Happy Path for Squashing Migrations Together

### ISSUE THREAD

**Issue by maxwellgerber** [tgriesser/knex#2728]
# Environment

Knex version: `"0.9.0"`
Database + version: `Postgres 9.4`
OS: `macOS High Sierra`

# Feature discussion / request

1. Explain what is your use case
We have been using knex for years and have hundreds of migrations written. Every time we run a set of integration tests, we run all of our migrations forward to bring the DB into the expected state, and after the tests we run all migrations backward to clean up. Over the years this has become a pretty inefficient process, and we'd love to have the capacity to squash all the existing migrations into a single "base" migration for local development and testing purposes, while maintaining the history of all the migrations we've run in the past for historic reasons.

2. Explain what kind of feature would support this
We'd love to see a tool like Django's [migration squasher](https://docs.djangoproject.com/en/dev/topics/migrations/#migration-squashing), which concatenates migrations together in an intelligent way.
That's obviously a huge request to solve a relatively small problem - another less drastic approach would be to add a key to each migration export's options and leave the creating of the squashed migration up to the user.

3. Give some API proposal, how the feature should work

Suppose we have the following files in our `migrations/` dir:
```
201801010_first_migration.js
201801020_second_migration.js
201801030_third_migration.js
```
And then we add in a new migration
```
201802000_squash_migration.js
```
That migration would have a new config option, which could look something like:
```
exports.config = {
   squashes: [
    '201801010_first_migration.js',
    '201801020_second_migration.js',
    '201801030_third_migration.js'
  ]
}
```
Then, when knex runs the migrations, it can choose whether to run each sub-migration individually or a single squash migration, depending on what is more efficient. For example, if we connect to a DB where the first and second migrations have run, and we want to run UP, we can just run the third migration. But, if we connect to a fresh DB instead, we only need to run the squash migration.

**Comment by elhigu** [comment]
You could just run migrations, take sql dump from database and apply that when initializing fresh DB. 

> Every time we run a set of integration tests, we run all of our migrations forward to bring the DB into the expected state, and after the tests we run all migrations backward to clean up. 

This is very inefficient way to setup / teardown DB for tests. What we've been doing many years is that when we start running tests, we restore database from some SQL dump, then run any new migrations which has been added after dump was created on top of it to have completely correct schema setup fast.

That is done only once when running tests is started. 

After that we only truncate all tables (with knex-db-manager) and sequences between test cases, which is easily 1000x faster than rolling migrations back. When DB has been truncated we use objection.js to push adequate test data in as a nested JSON object and objection ORM resolves efficient order of queries to push all the data to DB tables.

I don't see how this feature would resolve slowness of migrations during tests since there would still be lots of DDL queries made, which are really slow by their nature.

**Comment by Xqua** [comment]
Hey! I just built a tool that might help with this: **[adonis-lucid-migration-squash](https://github.com/[your-username]/adonis-lucid-migration-squash)**

Its made for Adonis but it uses Knex so ... 

**What it does:**
- Takes your production database schema
- Generates a clean, single Knex migration file
- Includes automated verification to ensure 100% accuracy
- Reduces deployment time (1 migration instead of 100+)

**Quick example:**
```bash
# Dump your schema
pg_dump -s --no-owner --no-acl > schema.sql

# Convert to Knex migration
python -m pg_to_knex schema.sql baseline_migration.ts

# Done! Clean baseline migration with verification
```
