### ISSUE TITLE
Pluck doesn't play nicely with postProcessResponse

### ISSUE THREAD

**Issue by dhensby** [tgriesser/knex#2797]
# Environment

Knex version: 0.14.6
Database + version: MSSQL 2017-CU9
OS: Mac OS 10.13.6

For MSSql tag @smorey2 .

# Bug

1. When using `pluck` in conjuction with a `postProcessResonse` callback that re-writes object keys, the pluck returns empty objects instead of the appropriate values.

2. No error messages, incorrect return type and value

3. https://runkit.com/dhensby/5b8e99c06ea1f900121315d6

**Comment by dhensby** [comment]
Yes, I agree that is the most likely cause.

It seems a pretty severe limitation of `pluck` if it can't work with the documented use case of `postProcessResponse` (to manipulate column names).

**Comment by dhensby** [comment]
Could the API of pluck be added to to accept a hash of SQL column to rewritten column? Or just a second argument?

**Comment by elhigu** [comment]
It is probably easier to just write `knex('test').select('id').map(row => row.ID)`

**Comment by wubzz** [comment]
Can we close this and instead add a note about it in docs for pluck? @elhigu @dhensby 

I understand the problem, but there's no correct way of solving this as far as I can tell. `postProcessResponse` can be used for anything - not just altering column names - so there is no way for `pluck` to know whether or not columns are being changed or not, and if so into what.

> Could the API of pluck be added to to accept a hash of SQL column to rewritten column? Or just a second argument?

In this case it sounds like you already know the expected output column, so I'm not sure what you'd gain from a hash rather than using the known column name?

**Comment by elhigu** [comment]
> Can we close this and instead add a note about it in docs for pluck?

Yep 👍
