### ISSUE TITLE
Migration create table race condition?

### ISSUE THREAD

**Issue by brandonros** [tgriesser/knex#2818]
# Environment

Knex version: 0.15.2
Database + version: Postgres 10.5
OS: Linux

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I would have expected the Knex migrator to work without error.

2. Error message

`create table "knex_migrations" ("id" serial primary key, "name" varchar(255), "batch" integer, "migration_time" timestamptz) - duplicate key value violates unique constraint "pg_type_typname_nsp_index"`

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to mysql or postgresql, then single file example which initializes
   needed data and demonstrates the problem.

```
export const migrateDatabase = async (db: Knex): Promise<any> => {
  return Promise.resolve(db.migrate.latest())
}

await migrateDatabase(db)
```

**Comment by kibertoad** [comment]
@brandonros This doesn't looks like sufficient amount of code to reproduce. What are the migrations that you are actually running? Your code shouldn't be running migrations more than once.

**Comment by brandonros** [comment]
Unfortunately, that was all the code that was running. It was in a Jasmine `beforeAll` block. It worked on my machine, but not my teammate's nor Jenkins. I had to work around it all. I wonder if it was some kind of concurrency or something?

**Comment by kibertoad** [comment]
@brandonros A bit too early to close it, don't you think?

You do understand what `db.migrate.latest()` is doing, right? It runs migrations from directory specified in config. Are you saying that there is no directory and no migrations?

**Comment by brandonros** [comment]
Why not change the migrations code to `create table if not exists` ?

**Comment by elhigu** [comment]
Probably this issue was actually caused, because it was removed from there... it was removed, because we added warning about using it because in most of the cases users actually doesn't want to use it because it would work really unexpected way when created table has also constraints / indexes. 

Some locking mechanism could be added there though, or add parameter to crateTableIfNotExist for suppressing the warning message, since in this case it would work just fine.
