### ISSUE TITLE
Support executing arbitrary SQL before SELECT query

### ISSUE THREAD

**Issue by kibertoad** [tgriesser/knex#2849]
# Environment

Knex version: 0.16.next2
Database + version: MySQL 5.7

# Feature discussion / request

**Problem statement**

Currently there is no way to execute multi-statement queries with proper selected value mapping that look like this:
```
SET @prev_user=-1;

SELECT user_id
FROM 
<...>
```

It is obviously possible to execute it within single knex.raw statement, but that prevents result row mapping from working which defeats the whole purpose of using knex.

**Proposal**

`knex.set(name, value)` - sets user variable before executing the rest of the query (requires multi-statement support to be enabled in driver). Obviously knex is not expected to be able to access or modify these variables using fluent builder style, that part is left to knex.raw fragments.

**Comment by elhigu** [comment]
One can already implement this outside of knex level by selecting to send multiple queries to the same connection. That has been one design principle of knex, that single builder does not generate multiple queries.

If your driver supports multiple statements (which is for example with mysql pretty dangerous IIRC because it would require to not use bindings) one should be able to do this by: 

```
knex.raw('SET @prev_user=1; ?;', [knex('table').select('user_id')])
```

**Comment by kibertoad** [comment]
@elhigu Thanks!
