### ISSUE TITLE
how to get one page data list and total count from database with knex.js?

### ISSUE THREAD

**Issue by mrleex** [tgriesser/knex#2856]
# Environment

Knex version: 0.15.2
Database + version: pgsql 10.1
OS: windows

Tried the following:
```
var model = knex.table('users').where('status',1).where('online', 1)
var totalCount = await model.count();
var data = await model.offset(0).limit(10).select()
return {
    totalCount: totalCount[0]['count']
    data: data
}
```
but get { "totalCount": "11", "data": [ { "count": "11" } ] }
how can I get dataList without write where twice?

stackoverflow link:
[https://stackoverflow.com/questions/52775863/how-to-get-one-page-data-list-and-total-count-from-database-with-knex-js](url)

thank you :)

**Comment by wubzz** [comment]
The problem here is that you're reusing the builder for two different type of queries; Count & Select.

This is the builder:
`var model = knex.table('users').where('status',1).where('online', 1)`

This makes the builder a 'Count' query:
`var totalCount = await model.count();`

This only appends an offset and limit to the same builder from `totalCount`:
`var data = await model.offset(0).limit(10).select()`

What you need to do is not use the same builder twice. There are plenty of ways to go around this. Some examples:

```javascript
var model = knex.table('users').where('status',1).where('online', 1)
var totalCount = await model.clone().count();
var data = await model.clone().offset(0).limit(10).select()
return {
    totalCount: totalCount[0]['count']
    data: data
}
```

```javascript
var getModel = () => knex.table('users').where('status',1).where('online', 1)
var totalCount = await getModel().count();
var data = await getModel().offset(0).limit(10).select()
return {
    totalCount: totalCount[0]['count']
    data: data
}
```

And more...

**Comment by mrleex** [comment]
@wubzz thank you !
