### ISSUE TITLE
knex object is not available on knexjs.org

### ISSUE THREAD

**Issue by tundebabzy** [tgriesser/knex#2974]
# Environment
This happens on knexjs.org

# Bug
Users should be able to pop open the console and build queries using the knex object. However, as at today (28 Dec 2018), if you open the console, you will meet an error message:
```
Uncaught TypeError: expecting a function but got [object Undefined]
```

**Comment by kibertoad** [comment]
Support for WebSQL was dropped, actually. I guess we need to update documentation to remove all references to it.

**Comment by elhigu** [comment]
Actually that kind of should work, since all the exam ples in documentation page are built with knex. So query building n browser should work. However there is some js errors on documentation page right now, which might cause this. There is an open issue about it in the documentation repo. Linkin this to the same issue and both can be fixed at the same time https://github.com/knex/documentation/issues/163
