### ISSUE TITLE
SQLITE3 whereIn errors

### ISSUE THREAD

**Issue by malammar** [tgriesser/knex#3042]
# Environment

Node Version: v8.10.0
Knex version: v0.15.2
Database + version: Sqlite3 v4.0.4
OS: MacOSX (running nodeJS)

# Bug

I am receiving an error when running this query on an in memory Sqlite3 v4.0.4 database.

## Query

```
userCategories = [[2, 2], [5, 2], [8, 2], [1, 3], [2, 3], [3, 3], [7, 3]]
db('user_category').whereIn(['user_id', 'category_id'], userCategories)
```

## Error Message

```
{"errno":1,"code":"SQLITE_ERROR"}
select * from `user_category` where (`user_id`, `category_id`) in ((2, 2), (5, 2), (8, 2), (1, 3), (2, 3), (3, 3), (7, 3)) - SQLITE_ERROR: row value misused
```

Test code: https://runkit.com/malammar/5c5dce448e738d001591bba2

## Workaround

```
db('user_category').whereIn(
  ['user_id', 'category_id'], 
  db.raw(`(VALUES (`${userCategories.join('),(')}))`)
```

**Comment by elhigu** [comment]
could you add the query that should be created for sqlite? I'm surprised that this is not caught by integration tests... (well not so surprised after all, because most of the tests of knex actually just checks that query is generated the way that it was meant to be done and not that query does what it should).

**Comment by elhigu** [comment]
I really need to contact runkit people again about its sqlite3 require... it has been broken for months again :|
