### ISSUE TITLE
knex weighs 8.46MB (90% is deps)

### ISSUE THREAD

**Issue by leeoniya** [tgriesser/knex#3048]
Considering using knex in a project and decided to weigh it first.

https://packagephobia.now.sh/result?p=knex

knex.js itself is just 876kB of the 8.46MB, the rest is dependencies.

http://npm.broofa.com/?q=knex

`liftoff` adds 2.57MB (used only for CLI), `bluebird` & types add 660kB (can be replaced with native Promise?), `lodash` adds 1.34MB (can be reduced by only requiring needed functions, or replacing with [1] variants).

some other deps are used only for cli stuff as well. is it possible to split CLI into its own package if some of the weight cannot be reduced?

[1] https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore

**Comment by leeoniya** [comment]
also, `src` and `scripts` can probably be removed from the npm distribution, shaving ~400kB or about 50% of knex itself).

**Comment by elhigu** [comment]
Thanks for the analysis. If some day slimming down package size is a priority this info will be helpful. 

Closing as there is nothing to do for now. Btw. knex + dependencies to run querybuilder on browser is like 370kB (pretty huge, but it contains all the dialects).

**Comment by leeoniya** [comment]
> If some day slimming down package size is a priority this info will be helpful.

given how old/mature this lib is, and that it's 8.5MB with 30% being a single CLI dep, i suspect that "some day" === "never". you could just be realistic about it :)

i would actually be interested in helping with this effort if there is a real chance of the work being integrated, given that all tests pass.

the codebase is pretty big and trying to figure out exactly what each dep does in this lib is a bit daunting. can you briefly tell me what `liftoff` is used for and why Bluebird is used instead of native Promises? Also, is Node 6.x the permanent minimum version? 6.x will EOL in April and 8.x will EOL in Dec. Can we start dropping various polyfills and aim for >= 10.x?

> Btw. knex + dependencies to run querybuilder on browser

given that knex is a query builder, i don't see the point of this anyways, besides maybe some demo playground for learning.

**Comment by elhigu** [comment]
> > If some day slimming down package size is a priority this info will be helpful.
> 
> given how old/mature this lib is, and that it's 8.5MB with 30% being a single CLI dep, i suspect that "some day" === "never". you could just be realistic about it :)

If stable version and complete rewrite is done some day I don't see this completely impossible. But... some day probably means distant future... flying cars, hover boards 'n stuff ;)

> i would actually be interested in helping with this effort if there is a real chance of the work being integrated, given that all tests pass.

If it doesn't make development / fixing knex harder I don't see any reason why not to accept PRs making it slimmer. But for example dropping bluebird cannot be done yet etc. (there is another issue about it).

> the codebase is pretty big and trying to figure out exactly what each dep does in this lib is a bit daunting. can you briefly tell me what `liftoff` is used for and why Bluebird is used instead of native Promises? Also, is Node 6.x the permanent minimum version? 6.x will EOL in April and 8.x will EOL in Dec. Can we start dropping various polyfills and aim for >= 10.x?

Node 6 support is planned to  be dropped around April.

> > Btw. knex + dependencies to run querybuilder on browser
> 
> given that knex is a query builder, i don't see the point of this anyways, besides maybe some demo playground for learning.

For example knex documentation page uses it to show generated queries for examples for each dialect. Also some mobile frameworks, which are using browser / some other js engine than node to create queries benefits from it. With plain query builder part one can write own glue separately how to pass those queries to database driver.

**Comment by tgriesser** [comment]
> why Bluebird is used instead of native Promises?

Because this library was started in 2012 when there was no such thing as async/await, or bluebird, and Promises were generally frowned upon but I decided to go with them anyway... first using Q, then when.js and finally Bluebird. I'm currently working on a project where the codebase was started in 2014 using knex and it very much depends on the guarentees of Bluebird. Taking it out of knex wholesale would be a full rewrite for this project and I suspect it wouldn't be the only one. I agree we can dramatically simplify things internally using async/await but at this point I'd rather wait until node 6 is EOL'ed before doing this so we don't need to Polyfill.

> can you briefly tell me what `liftoff` is used

Liftoff is used for the CLI, to allow you to have the knexfile (another concept we should probably do away with), scripts, etc. be specified in different languages other than js. CoffeeScript was quite popular when this project was written and is actually what it what was originally written in. gulp-cli uses Liftoff for the same reason.

Sure, we can split this out into like a `knex-cli`, but if I take the time do that I'd personally rather do it alongside structuring the project into a multi-package monorepo, clean up the tests, etc. 

If you want to open a PR with `knex-cli` fully split out, tests and all, but within the same codebase I would be open to making that change. I have access to that package on npm since this was something I obviously wanted to do but never got to.

> given how old/mature this lib is, and that it's 8.5MB with 30% being a single CLI dep, i suspect that "some day" === "never". you could just be realistic about it :)

It's old, I wouldn't say mature. At some point I would like to get around to doing a proper rewrite, I've started a few in the past and each time have gotten new ideas on how to approach it. Currently leaning toward a sort-of hybrid approach of incremental and full-rewrite, e.g. a fork which I can iterate on with a real-world codebase/test-suite without worrying about needing a solid upgrade path right away, or doing all of the languages at once, and then merging that back in.

I think I have some better ideas for it now but it's just a matter of where my time is best spent. To me knex generally works, so I typically just use it in every-day things without too many complaints. I've also been focused on building http://nexus.js.org lately so I haven't had as much time for knex (you might notice that library has zero dependencies).

Maintaining legacy projects is hard. There's so many things I would have done differently in hindsight but I don't really need to justify all of the choices/mistakes made here. If there's time to get around to fixing these things with a proper migration path then it'll happen, if not, feel free to use or build something else that aligns better with your view of how much a package should weigh.

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

**Comment by ricardograca** [comment]
> For example knex documentation page uses it to show generated queries for examples for each dialect.

It does? Can you give me a example documentation section where this is true? I looked at the `.returning()` section which I think should produce different queries and there was no change whatsoever when alternating between all the available dialects in the dropdown.

**Comment by elhigu** [comment]
> > For example knex documentation page uses it to show generated queries for examples for each dialect.
> 
> It does? Can you give me a example documentation section where this is true? I looked at the `.returning()` section which I think should produce different queries and there was no change whatsoever when alternating between all the available dialects in the dropdown.

Its currently broken / fixes are not yet released to live page. There are issues about it in the documentation repo. Page shows some javascript errors, which breaks also the functionality of changing dialect.
