### ISSUE TITLE
beforeDestroy is deprecated despite being the only way (AFAIK) to detect disconnects

### ISSUE THREAD

**Issue by TheThing** [tgriesser/knex#3087]
# Environment

Knex version: 0.16.3
Database + version: postgresql 11.2
OS: Centos 7

# Feature discussion / request

Currently the beforeDestroy event in pool is marked as deprecated (for some odd reason).
From all my testing and reading the source code for knex, detecting database connections dropping/disconnecting unexpectedly (like say, shutting down the database or from network going down) is the beforeDestroy handler.

the query-error is never called for any of the errors from a database going down. Not for when it goes down, and neither when a random SQL query gets back "connect ECONNREFUSED"

I'm currently using this feature to detect when a connection drops and do a graceful migration of knex from the primary database to the slave database. (So just endlessly reconnecting is not the solution)

All I want is what has been mentioned MANY times before, some knex.on('name-of-event') or something to detect when a connection goes down unexpectedly or ECONNREFUSED is thrown.

And no, afterCreate doesn't work because it only gets called after a successful connection and never gets called.

**Comment by elhigu** [comment]
> the query-error is never called for any of the errors from a database going down. Not for when it goes down, and neither when a random SQL query gets back "connect ECONNREFUSED"

Sounds like  that is a bug. query-error should be called the same way it is called for any other error that is coming form db driver / pool.

> And no, afterCreate doesn't work because it only gets called after a successful connection and never gets called.

There is no beforeDestroy if nothing was created so afterCreate is actually called if beforeDestroy is called or there might be another bug there. 

As a work around for knex.on('query-error', ...) not working, you can setup own listener to connection in afterCreate. Though I have no idea why beforeDestroy was deprecated long ago.

I think this issue could be closed, since having beforeDestroy doesn't really solve anything (connections are destroyed all the time and it doesn't mean database is being unavailable). But instead of this one bug report about knex.on('query-error', ...) not working would be better.

**Comment by TheThing** [comment]
I'm also not so sure I want `knex.on('query-error')` to be the place for detecting connection status although I do agree that it's an annoying bug that `query-error` does not get called on all those exceptions.

My reasoning is that if the database suddenly goes down or internet explodes, I'd like to be able to detect that and start handling it immediately without having to wait for the next user query to fetch something and then have that throw an error into the user's face, so to speak, and then start handling it.

Also, according to most of my readings from knex issues and such, the reason why knex doesn't provide a lot of functionality when it comes to disconnects and/or reconnection and that type of stuff is that all of those things should be handled by the pool library and not-so-much by knex (which I agree with). However, knex doesn't allow you to specify or pass in all the parameters into the pool to handle all those instances (for example, the beforeDestroy which is essentially the `destroy` property in the pool library, is now being deprecated among other things).

**Comment by wubzz** [comment]
I think it's important to distinguish between 'query' errors and 'connection' errors. What is described here is a loss in connection, or a server going down. That by definition cannot be classified as a 'query' error. The `query-error` event in knex is only emitted when the sql server - for whatever reason - cannot process the sql it has been provided. That was by design when it was added. Whether or not it should be changed I don't know, just thought I'd add this in for context..

Although undocumented it seems `.on('error')` is emitted when connection to the server isn't possible. Perhaps that can help?

**Comment by elhigu** [comment]
> I'm also not so sure I want knex.on('query-error') to be the place for detecting connection status although I do agree that it's an annoying bug that query-error does not get called on all those exceptions.

Even that is not a good place to do it since having single connection close doesn't mean that DB/network is down. It just means that single connection was closed. Best way to check that DB is available is to write simple polling routine and check it for example every second (it is simple and robust, there is no reason to make it more complicated).

If database goes suddenly down or internet explodes you need to do a query to see that you don't have connection to the service anymore. Just listening for example if single connection is disconnected doesn't mean that DB is down. To have that logic you would need to make query to DB on every disconnect to verify if DB/network is down or if connection was closed for any other reason. 

Neither for example getting connection from pool to make a query does mean that when query is done that database is still up. 

> Also, according to most of my readings from knex issues and such, the reason why knex doesn't provide a lot of functionality when it comes to disconnects and/or reconnection and that type of stuff is that all of those things should be handled by the pool library and not-so-much by knex (which I agree with).

Please be specific of which issues you are talking about. If feature is very useful, reasonable and necessary and possible to implement cleanly in knex there is no reason why it shouldn't. I still don't know why `beforeDestroy` was deprecated... I could try to dig that up though, but I still haven't heard any reason why that would be useful (for this issue it doesn't make it easier, you still would need to do additional query to verify that DB is alive and for that simple polling would be more robust).

**_I think this issue could be closed, since having beforeDestroy doesn't really solve anything (connections are destroyed all the time and it doesn't mean database is being unavailable). But instead of this one bug report about knex.on('query-error', ...) not working would be better._** <- closing this in favor of https://github.com/tgriesser/knex/issues/3113

**Comment by TheThing** [comment]
Thanks for creating that issue. I also wanted to expand on a few things.

> > I'm also not so sure I want knex.on('query-error') to be the place for detecting connection status although I do agree that it's an annoying bug that query-error does not get called on all those exceptions.
> 
> Even that is not a good place to do it since having single connection close doesn't mean that DB/network is down. It just means that single connection was closed. Best way to check that DB is available is to write simple polling routine and check it for example every second (it is simple and robust, there is no reason to make it more complicated).

Maybe but I'm trying to avoid needlessly polling the database every second, especially when I know I can do it smarter.

> If database goes suddenly down or internet explodes you need to do a query to see that you don't have connection to the service anymore. Just listening for example if single connection is disconnected doesn't mean that DB is down. To have that logic you would need to make query to DB on every disconnect to verify if DB/network is down or if connection was closed for any other reason.

I actually do that. When a pool connection is unexpectedly dropped I check for the reason in the event handler:

```
/**
 * Event handler for when the pool gets destroyed or connection is dropped.
 * Here we check if the connection has been marked with _ending = true.
 * There are some checks available we can use to check if current
 * connection was abruptly disconnected. Among those from my testing
 * are as follows:
 *
 * conn.__knex__disposed = 'Connection ended unexpectedly'
 * conn.connection._ending = true
 *
 * I went with connection._ending one as I feel that one's the safest.
 * 
 */
function beforeDestroy(conn) {
  if (conn.connection._ending) {
    checkActiveConnection()
  }
}

const client = knex({
  'client': 'pg',
  'connection': { /* Connection info here */ },
  pool: {
    afterCreate: afterCreate,
    beforeDestroy: beforeDestroy,
  }
})
```

this gives me a somewhat red flag that tells me something might be up with the database connection and that I should check the status to make sure it's still there.

```
function checkActiveConnection(attempt = 1) {
  if (attempt > 5) {
    isUrgent = true
    return gracefulServerMigrate().then()
  }
  client.raw('select 1').catch(err => {
    if (err.code === 'ECONNREFUSED') { // err.code === 'ETIMEDOUT'
      isUrgent = true
      return gracefulServerMigrate().then()
    }
    if (err) {
      let wait = 3000 // shorter timeout for err.code like '57P03' and such.
      if (err.code === 'ETIMEDOUT') { // Longer timeout in case of timeout
        wait = 10000
      }

      console.log(`Error while checking connection status: (${err.code}) ${err.message}`)
      setTimeout(() => checkActiveConnection(attempt + 1), wait)
    }
  })
}
```

> Neither for example getting connection from pool to make a query does mean that when query is done that database is still up.

Absolutely but it gives me a good indication point about connection problems in the pool.

> 
> > Also, according to most of my readings from knex issues and such, the reason why knex doesn't provide a lot of functionality when it comes to disconnects and/or reconnection and that type of stuff is that all of those things should be handled by the pool library and not-so-much by knex (which I agree with).
> 
> Please be specific of which issues you are talking about. If feature is very useful, reasonable and necessary and possible to implement cleanly in knex there is no reason why it shouldn't. I still don't know why `beforeDestroy` was deprecated... I could try to dig that up though, but I still haven't heard any reason why that would be useful (for this issue it doesn't make it easier, you still would need to do additional query to verify that DB is alive and for that simple polling would be more robust).

Oh I'm not throwing you guys under the bus or anything like that. I can understand the logic behind keeping pool issues separate from knex which is mostly a query builder. It definitely helps for me and others especially if we have access to the pool and can do checks and monitoring there. However knex wraps around the pool library and options (which is annoying) and the `beforeDestroy` is ironically the only method for being notified if something were to happen to the pool.

Concerning my readings about knex keeping connection/disconnects issues contained within pool and not knex itself, I'm referencing issues such as #407, #448, #1455 and etc. basically, this is definitely a pool issue and I agree with that but to deprecate and remove one of the important handler from the actual pool library is not the ideal solution imo.

**In all honesty, I really don't like the name of that handler to begin with,** lol. I think a much better name instead of `beforeDestroy` would be something like `poolItemDestroyed` or something similar that gets called after the resource cleanup. To me that seems more descriptive about what it does or can do and it allows me to add custom logic when a pool connection gets destroyed and maybe do something in response. Like notify my system monitoring service about the number of pool connections that get opened or closed or etc.

**Comment by elhigu** [comment]
> Maybe but I'm trying to avoid needlessly polling the database every second, especially when I know I can do it smarter.

Smarter means usually less robust and more work (e.g. you might suddenly create 1000 status check queries to DB just because all connections were dropped / or make accidental retry-fail loop etc. )  here is some nice dude from AWS talking about it https://youtu.be/O8xLxNje30M?t=2744

Even on websites I many times opt to simple polling instead of using for example websockets, becuase that polling can 

>  However knex wraps around the pool library and options (which is annoying) and the beforeDestroy is ironically the only method for being notified if something were to happen to the pool.

This would be helpful for that and  will be cleaner to have than beforeDestroy https://github.com/Vincit/tarn.js/issues/14 

All of those issues mentioned have been resolved:

#407 can only be done by polling and there is no reason why knex should do that internally

#448 database errors can happen at any time so one should always write proper error handling code when doing queries. Also new pool which doesn't autostart helped with this because not there will be no leaked errors during knex initialization

#1455 was also fixed by new pool

**Comment by TheThing** [comment]
Very good input elhigu.

In conclusion, I think I still plan on using `beforeDestroy` myself for connection monitoring within the pool and to the database. I just wanted to raise the issue due to the deprecated message stating us to let you know if we were to use it and how we were using it.

That tarn issue looks really cool and it would be nice to have access to the tarn pool so we can hook into the internal events in there for those purposes (I'm not sure knex exposes the pool property, don't remember seeing it but I could be wrong).

In any case, my job here is done and you can close this off for now and I think definitely fixing the `query-error` event to execute on all query errors would alleviate most of my worries and help me a long way. I'll be watching that issue.

Thanks again for your help and input o/
