### ISSUE TITLE
setting date time to null crashes migrations 

### ISSUE THREAD

**Issue by JoueBien** [tgriesser/knex#3092]
# Environment

Knex version:
Knex CLI version:  0.16.3
Local Knex version:  0.15.2
Database + version:
MYSQL 5.7
OS: OSX

# Bug
Setting date time to null no longer works as expected. Using null causes error. Documentation dose not reflect this change or provide a defaultTo example for null date times. 

Not Working Example that used to work
```
exports.up = function(knex, Promise) {
    return Promise.all([
        knex.schema.createTable('users', function (t) {
            t.increments('id').primary();
            t.string('name');
            t.string('email');
            t.string('pw');
            t.timestamp('deleted_at').defaultTo(null);
            // t.timestamps();
        })
    ]);
}
```

 # Error message
```
Using environment: development
migration file "20181207102033_user.js" failed
migration failed with error: create table `permissions` (`id` int unsigned not null auto_increment primary key, `user_id` int unsigned, `allow_user_id` int unsigned, `enabled` boolean default '1', `start_at` timestamp, `end_at` timestamp, `deleted_at` timestamp, `created_at` datetime, `updated_at` datetime) - ER_INVALID_DEFAULT: Invalid default value for 'end_at'
Error: ER_INVALID_DEFAULT: Invalid default value for 'end_at'
```

**Comment by kibertoad** [comment]
Ouch. I'll check it out, thanks.

**Comment by kibertoad** [comment]
@JoueBien Can you check if this works with exact same DB and driver version, when using older knex version? From what I'm seeing it is MySQL and not knex that is throwing the error. I guess we could improve null handling for MySQL driver, though - since MySQL default to null already, we can simply ignore it.

**Comment by kibertoad** [comment]
I think what you are encountering is insane MySQL defaults: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp

We've encountered same issue in production ourselves - I have no idea who could have ever thought that updating all TIMESTAMP columns in a table to current date unless instructed otherwise is a good idea. You might want to change the server config value mentioned on a link above.

**Comment by kibertoad** [comment]
While what is said above still stands, there definitely was a room for improvement on knex side as well; it is important to set nullability explicitly for timestamp column due to aforementioned reasons, and previously this was not happening. You would have to recreate your table for fix to have effect, but it seems to work well now.

**Comment by kibertoad** [comment]
Makes sense to keep it open until related PR is merged.
@JoueBien Were you able to resolve original issue?

**Comment by JoueBien** [comment]
@kibertoad sorry about that I didn't mean to close the issue - saw it late last night but didn't get a chance to re-open it. In any case thanks for the fix. 
I've been look at getting an environment up with and earlier build of MySQL but haven't had much luck - all the traditional tools I've used seem to have bumped versions and I'm just figuring out how to get MySQL community server up at home on a windows machine (which I haven't done before).
