### ISSUE TITLE
Mac OS Electron-Packager Issue

### ISSUE THREAD

**Issue by natw2012** [tgriesser/knex#3154]
# Environment

Knex version: 0.16.3
Database + version: SQLite3 4.0.6
OS: OSX El Capitan 10.11.5

# Bug

1. 
Error seems to be because it can't find the database file. Works totally fine during development before packaging as long as database file is in same directory. 

I'm able to develop and package on Windows 10 and it works so seems to be OSX specific.

2. Error message: "Sorry! Uncaught Exception!TypeError: Error processing argument at index 11, conversion failure from undefined"

3. 
![image](https://user-images.githubusercontent.com/11684133/56384941-b7c72000-61eb-11e9-9c2b-acf64e2de6e8.png)

similarly, doesn't work when replacing the settings.get with just a "./test.db"

**Comment by elhigu** [comment]
Sounds like user error of electron or bug in sqlite3 driver. Nothing in this report seem to point knex having a bug. First try to use sqlite3 directly and if you can make that work with your electron setup only then try to include also knex. 

Can be reopened if this problem is shown to be caused by a bug in knex.
