### ISSUE TITLE
Type inference in JS for select queries

### ISSUE THREAD

**Issue by pvider** [tgriesser/knex#3156]
# Environment

Knex version: 0.16.5
Database + version: Postgres 10 / Any knex compatible
OS: Windows/Linux/MacOS
IDE: Visual Studio Code (latest)

# Feature discussion / request
I need type inference in JS for select queries, right now I don't know better way to get it than write some helpers. Here is primitive oversimplified helper example, of course it can be extended to support other knex methods, refactored to classes etc.

```js
/** Swaps promise type with promise of array of result type
 * @template T
 * @param {T} result
 * @returns {Promise<Array<T>>}
 */
const typed = (promise, result) => {
    return promise
}

/** Typed select query
 * @template T
 * @param {string} tableName
 * @param {T} object
 * @returns {Promise<Array<T>>}
 */
const select = (tableName, object) => {
    return typed(knex(tableName).select(Object.keys(object)), object)
}
```

Then I can use it like this:
```js
;(async () => {
    const result = await select('Response', {
        isDeleted: false,
        isChosen: false,
        isCompleted: false
    })
    const [first] = result
    console.log('first result element', first)
})()
```
And Visual Studio Code infered the type for `first` constant:
```
const first: {
    isDeleted: boolean;
    isChosen: boolean;
    isCompleted: boolean;
}
```

Our backend server based on REST API become big enough to make use of type inference, so I would like to have built-in knex type inference for select queries.

About API proposal: `knex.select` could also accept `object` along with current `array` parameter, for example:
```js
const result = await knex('Response').select({
        isDeleted: false,
        isChosen: false,
        isCompleted: false
    })
```

PS. knex is great, thank you for all your hard work!

**Comment by lorefnon** [comment]
I believe the ideal solution for this is to make the typescript APIs generic in terms of the the type of row of the (potentially joined) table being operated upon and the result of the current operation. 

I have a preliminary implementation in https://github.com/tgriesser/knex/pull/3168 which does something similar (but needs more testing).

This happens to be my first PR in this repo so I would like some feedback if this is something the maintainers would be interested in. 

The value proposition is less in terms of type safety (because knex allows things `sometable.someColumn` which can not be checked through typescript) and more around intellisense and tooling (as has been requested in this issue). 

Also, in [greldal](https://github.com/gql-dal/greldal) we expose knex instances to power-users (in various hooks) and it would be great if we could expose well-typed knex instances as we already know the types of data sources and results from the GraphQL schema.

Finally, if the above approach is acceptable to the maintainers, I'd like to know if it is fine to integrate [dtslint](https://github.com/Microsoft/dtslint) for test cases for the type definitions. I'd be willing to integrate that as a part of aforementioned PR.

**Comment by pvider** [comment]
With #3168 knex is greatly typed, big thanks to @lorefnon!
