### ISSUE TITLE
Prevent Timeout Error with AuroraDB?

### ISSUE THREAD

**Issue by karam94** [tgriesser/knex#3159]
I'm using a serverless AuroraDB.
One of the advantages of a serverless database is cost saving as the database goes to sleep after a certain amount of inactivity.

Is there no solution to preventing the timeout error that occurs every time the database starts from cold by increasing a timeout of some sort?

This comment here:
https://github.com/tgriesser/knex/issues/2820#issuecomment-481710112

Suggests to just no longer let the database go to sleep, but this defeats the point of using a serverless database in the first place. Is there no workaround?

Thanks

**Comment by elhigu** [comment]
Change `acquireConnectionTimeout` to be long enough to handle case where DB is unresponsive or add some pre-query method, which waits for database to get available, before doing any queries. 

Also you should setup pool timeouts to purge idle connections very aggressively, so that pool is empty when aurora goes sleeping.

**Comment by elhigu** [comment]
However you should *not* set configuration property  `propagateCreateError: false`. That will cause you some nasty problems in unexpected connection errors. So if Aurora is responding with failure when it is not ready, you indeed should first create some code to make sure aurora is available before doing queries.

That sounds like strange design from aurora side to not have option for transparent mode that just waits until DB ready and then opens the connection.

**Comment by karam94** [comment]
> Change `acquireConnectionTimeout` to be long enough to handle case where DB is unresponsive or add some pre-query method, which waits for database to get available, before doing any queries.
> 
> Also you should setup pool timeouts to purge idle connections very aggressively, so that pool is empty when aurora goes sleeping.
> 
> How long it takes for aurora to boot up and start responding?

Well, this is the thing.
According to the docs here for acquireConnectionTimeout: https://knexjs.org/
The default is 60 seconds. Aurora takes about 20-30 seconds to boot up, not 30. However knex seems to stop trying after about 10 seconds. Are changes required to the connection pools too?

**Comment by elhigu** [comment]
Knex passes that timeout to the pool internally and there is a test case that for example with timeout of 100ms that error is thrown. It is of course possible that there is a bug somewhere with default timeout or with longer timeouts... but... 

```
knex = require('knex')({ client: 'pg', connection: 'postgres://testuser:knextest@localhost:25432/o4c', pool: {min: 1, max: 1}});

knex.transaction(trx => { console.log('hogging the only connection for transaction'); });
> hogging the only connection for transaction

start = new Date(); end = null; knex.transaction(trx => { console.log('hogging the only connection for transaction'); }).catch(e => {console.log(e); end = new Date()});
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
> end.getTime() - start.getTime()
60001
> 

```

So according to my brief test it waits 60 seconds just fine. So if there is some reproduction, which actually shows knex really having a problem with this please open bug report with reproduction code. You probably should be able to reproduce that without having real aurora DB in the other end. I wish this issue wont be flooded with trying to hunt that bug (I will remove any messages unrelated to original topic: this issue is about possible workarounds).
