### ISSUE TITLE
1 Persistent connection

### ISSUE THREAD

**Issue by mathieumagalhaes** [tgriesser/knex#3178]
# Environment

Knex version: 0.16.5
Database + version: MySQL 8
OS: MacOS Mojave

# Feature discussion / request

> Pool does keepalive connections automatically if connection in pool is broken for some reason.
> 
> _Originally posted by @elhigu in https://github.com/tgriesser/knex/pull/3177#issuecomment-488787728_

This does not seem the case for me. Or we misunderstood eachother. I'd like a persistent, non releasable single connection. If needed this can be one without the pool ofcourse, my pull request was a way to implement this but I admit it's hacky. With pool max 1 and min 1, connection still gets released and re-acquired between different requests.

**1. Explain what is your use case**
I have Knex setup for my backend API.
What I see between two requests (even to the same API endpoint instantly afterwards) is that a connection is acquired at the beginning of each API request and released at the end of each API request.

The connection is _not_ released _between_ multiple queries in that API's body, but it _will_ releasing _after_ each API request, even for a next request within some milliseconds between the previous request.

This is slowing down each request which I do not desire in my current application.

I tried:
- _Setting pool config to min 1 and max 1_
- _Messing with idle timeout_
- _Other Knex configurations_

But I am not able to achieve what I really need without modifying code.

**2. Explain what kind of feature would support this**
I would like to have Knex use one single persistent (keep alive) connection instead of releasing and acquiring new ones. Or at least only releasing after x amount of seconds/minutes passed.

**3. Give some API proposal, how the feature should work**
Some possibilities:

* Make it so when pool config max is set to 1 and min is set to 1, a connection is acquired once and saved for later use, releasing this connection isn't possible
#3177 (My current hacky workaround)

* Make it so pooling is not at all used and a single connection is created through the database native driver libraries, when a configuration flag/boolean is set to true

* Setting idleTimeout of _tarn.js_ to 0? https://github.com/Vincit/tarn.js/issues/24
(But that seems not to be for this specific use case if I understood correctly)

* Create a timeout to keep these pooled connection open (no release) unless the timeout exceeds since last query, refresh that timeout on each query. Something like that?

Thanks in advance for taking a look at this!

**Comment by mathieumagalhaes** [comment]
Could someone also explain me this phenomenon?
And possibly provide a workaround?

Running two identical queries one after the other in an API, I'm seeing a delay in the first query across multiple request. Even with #3177.

I understand that the first request will still need to acquire a new connection but future request doesn't as I can confirm with knex:debug logs. 
But I'm still getting slower times for the first query across multiple requests.

_Tested logging time before/after queries (awaiting result of each query in between)._

```
--- Express Request 1: ---
Getting the keepAlive connection once here, so these times aren't relevant.

--- Express Request 2: ---
before insert 1556916990905
  knex:query insert into `users` (`email`) values (?) undefined +11s
  knex:bindings [ '...' ] undefined +11s
after insert 1556916990942
Query total: 37ms

before insert 1556916990943
  knex:query insert into `users` (`email`) values (?) undefined +11ms
  knex:bindings [ '...' ] undefined +11ms
after insert 1556916990945
Query total: 2ms

--- Express Request 3: ---
before insert 1556917484652
  knex:query insert into `users` (`email`) values (?) undefined +8m
  knex:bindings [ '...' ] undefined +8m
after insert 1556917484676
Query total: 24ms

before insert 1556917484673
  knex:query insert into `users` (`email`) values (?) undefined +9ms
  knex:bindings [ '...' ] undefined +9ms
after insert 1556917484675
Query total: 2ms
```

**Comment by elhigu** [comment]
> The connection is not released between multiple queries in that API, but it will releasing after each request, even for a next request within some milliseconds between the previous request.

Then you need to fix your code. If that happens only when you are doing separate API requests, it means that your API code has a bug. I suppose you are reinitializing new knex instance on every request or something like that.

Please add that reproduction code, I'm pretty tired of having to ask that repeatedly 😞

Below is an example of complete reproduction code (which shows that knex actually works as you have been told). 

docker-compose.yml:
```
version: '3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '23306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=testrootpassword
      - MYSQL_DATABASE=knex_test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
    healthcheck:
      test:
        [
          'CMD',
          '/usr/bin/mysql',
          '-hlocalhost',
          '-utestuser',
          '-ptestpassword',
          '-e',
          'SELECT 1',
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always
```

Start DB and install deps: 

`docker-compose up`

`npm install knex mysql`

test.js
```
const util = require('util')
const pause = util.promisify((a, f) => setTimeout(f, a))

const knex = require('knex')({
  client: 'mysql',
  connection: {
    port: 23306,
   database: 'knex_test',
  host: 'localhost',
  user: 'testuser',
  password: 'testpassword',
  charset: 'utf8'},
  pool: {min: 1, max: 1 }
});

// check pool status, both are 0
function poolStats(msg) {
  console.log(msg);
  console.log({
    numUsed: knex.client.pool.numUsed(),
    numFree: knex.client.pool.numFree()
  });
}

async function main() {
  poolStats('------ before first query ------');
  console.log(await knex.select(1));
  poolStats('------ after first query ------');
  await pause(1000);
  poolStats('------ before second query ------');
  console.log(await knex.select(1));
  poolStats('------ after second query ------');

  const launchedQuery = knex.select(1).then();
  poolStats('------ when launched query still running ------');
  await launchedQuery;
  poolStats('------ just after launched query ------');

  await pause(60000);

  poolStats('------ just before last two queries before destroy ------');
  console.log(await knex.select(1));
  console.log(await knex.select(1));
  poolStats('------ before destroy ------');
  await knex.destroy();
}

main();

```


```
DEBUG=knex:* node test.js

Mikaels-MacBook-Pro:backend mikaelle$ DEBUG=knex:* node test.js 
------ before first query ------
{ numUsed: 0, numFree: 0 }
  knex:client acquired connection from pool: __knexUid1 +0ms
  knex:query select 1 undefined +0ms
  knex:bindings [] undefined +0ms
  knex:client releasing connection to pool: __knexUid1 +8ms
[ RowDataPacket { '1': 1 } ]
------ after first query ------
{ numUsed: 0, numFree: 1 }
------ before second query ------
{ numUsed: 0, numFree: 1 }
  knex:client acquired connection from pool: __knexUid1 +1s
  knex:query select 1 undefined +1s
  knex:bindings [] undefined +1s
  knex:client releasing connection to pool: __knexUid1 +3ms
[ RowDataPacket { '1': 1 } ]
------ after second query ------
{ numUsed: 0, numFree: 1 }
------ when launched query still running ------
{ numUsed: 1, numFree: 0 }
  knex:client acquired connection from pool: __knexUid1 +1ms
  knex:query select 1 undefined +4ms
  knex:bindings [] undefined +4ms
  knex:client releasing connection to pool: __knexUid1 +2ms
------ just after launched query ------
{ numUsed: 0, numFree: 1 }
------ just before last two queries before destroy ------
{ numUsed: 0, numFree: 1 }
  knex:client acquired connection from pool: __knexUid1 +1m
  knex:query select 1 undefined +1m
  knex:bindings [] undefined +1m
  knex:client releasing connection to pool: __knexUid1 +1ms
[ RowDataPacket { '1': 1 } ]
  knex:client acquired connection from pool: __knexUid1 +1ms
  knex:query select 1 undefined +2ms
  knex:bindings [] undefined +2ms
  knex:client releasing connection to pool: __knexUid1 +1ms
[ RowDataPacket { '1': 1 } ]
------ before destroy ------
{ numUsed: 0, numFree: 1 }
```

**Comment by mathieumagalhaes** [comment]
@elhigu Isn't the case as I'm testing with a console.log in Knex' constructor and not seeing it twice.

Also your example is showing exactly what I'm trying to prevent/discuss?
Releasing connection to pool after each query

Nevermind though.

**Comment by elhigu** [comment]
> @elhigu Isn't the case as I'm testing with a console.log in Knex' constructor and not seeing it twice.

@mathieumagalhaes ok, good.

> Also your example is showing exactly what I'm trying to prevent/discuss? Releasing connection to pool after each query

No it is not. You are not trying to prevent connections being released back to pool. You are trying to prevent connections from being discarded from pool.

When connection is released back to pool it is still kept active in pool and it is not disconnected from DB server (as you can see from numUsed / numFree that when pool starts it is empty and after first query is done there is always one resource either in use or free waiting for next query to get it).

> The connection is not released between multiple queries in that API's body, but it will releasing after each API request, even for a next request within some milliseconds between the previous request.

Unless you are using transaction, connection is released back to pool after each query also inside your API method. Not only after single API request.

> This is slowing down each request which I do not desire in my current application.

No, that is not slowing down anything as you should be able to see from my reproduction code (though I should have added there query timers to show how long it takes for each query to run, knex debug logs shows time that has passed since last debug row).

You still have not even showed any proofs or even any logs which would show that taking connection from pool would take any time at all. And still no reproduction for the problem you are experiencing.

> This does not seem the case for me. Or we misunderstood eachother. I'd like a persistent, non releasable single connection.

There is no such thing as "persistent" connection. You cannot tell to database server that it is never allowed to close a connection or that there will never be networking problems between db server and client.

Closest thing to that is to have pool that has min and max limit 1, that way the same single connection is always returned and if it is broken for some reason, pool will automatically create new one to replace broken one.

> Running two identical queries one after the other in an API, I'm seeing a delay in the first query across multiple request. Even with #3177.

You should add reproduction code, which actually shows how you are timing your queries. Please read https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md#what-is-minimal-code-to-reproduce-bug-and-why-i-have-to-provide-that-when-i-can-just-tell-whats-the-problem-is

No one can know what you are doing wrong or if it is a knex bug without being able to investigate your problem.

**Comment by nhusby** [comment]
> Could someone also explain this phenomenon to me?
> Is there something else going on with the pool I'm not seeing?
> And possibly provide a workaround?
> 
> Running two identical queries one after the other in an API, I'm seeing a delay in the first query across multiple request. Even with #3177.

Hopefully you've solved this problem (perhaps by accident) by now, but I'll post as an FYI for anyone that comes across it.

If I read correctly, you're seeing an 11 second round trip on the first query (which is reporting as 37ms execution time).  That's like a quarter of eternity in CPU time.  The phenomenon you're experiencing is probably a DNS lookup.  The lookup has to go across the internet and potentially cascade across multiple servers.  The first lookup takes forever, then it's cached for a while.  

To solve this, you shouldn't use host names for server connections.  Not even "localhost".  Use IP addresses instead.  (that's 127.0.0.1 instead of localhost)
