### ISSUE TITLE
DistinctCount, Count return type is too complex

### ISSUE THREAD

**Issue by jpike88** [tgriesser/knex#3247]
https://github.com/tgriesser/knex/blob/0d1fb16240d4d4a482513ba1e07d31b6cc272a08/types/index.d.ts#L501
https://github.com/tgriesser/knex/blob/0d1fb16240d4d4a482513ba1e07d31b6cc272a08/types/index.d.ts#L502

^ this is causing  over 100 errors in my TS check because I'm treating the return types as a number, but now it's number | string... the errors look like this:

```Type 'string | number' is not assignable to type 'number'```

Can this be reverted to just number, and if someone wants to treat it as a string they can just cast it? This really needs to be reversed I think.

**Comment by kibertoad** [comment]
@lorefnon

**Comment by kibertoad** [comment]
@jpike88 What version are you using?

**Comment by lorefnon** [comment]
I think the current type is correct because in pg count can return bigint which will be casted to string (by default)

You can consider using `count<Record<string, number>>()`.

**Comment by jpike88** [comment]
0.17.3

I use mysql, where a count = a number... this really causes a lot of cruft, I have to shove a generic in like 70 places and remember to do that every time I write a count check. I'll have my devs scratching their heads because they can't have count go straight to a function that has a return type of number. I think this should be reconsidered, maybe have a function that is an alias of count called bigIntCount or something, which gets the desired type result. Bigint usage sounds like a rare scenario anyway...

**Comment by lorefnon** [comment]
I don't have a very strong opinion on this. I've reverted the change here in https://github.com/tgriesser/knex/pull/3249 and will leave it up to the maintainers of the project to take a call here.

**Comment by kibertoad** [comment]
@lorefnon For all intents and purposes you are as much a maintainer as the rest of us :). The technicalities of finalizing that were slow due to the only maintainer with admin permissions was travelling in Europe, but hopefully he will catch up this week.
I fully trust your judgement on this particular issue. What do you think is going to be the most commonly convenient option here? Is bigint converted to string actually an edge case? Do other DBs such as Postgre is most cases also return a number? Let us not forget that there are alternative solutions, not necessarily through typings possible here, e. g. implementing builder method .asNumeric() which would ensure that end result is converted to numeric if it's already not one (and that would force numeric type), or even the one outside of knex, util function countAsNumeric(knexBuilder) that returns numerics. In this particular case I believe that question is "which tradeoff option is going to be most convenient for the majority of users".

**Comment by elhigu** [comment]
I think `number | string` is correct and there probably will be other parts in api where this will cause same kind of problems. I wouldn't be very happy to have just `any` typing here either, since it is too allowing, but I understand that this is really inconvenient from user's perspective. Problems of trying to type dynamic results...

I wish there would be a way for user to tell what is actually type of returned count... but at least I don't know how I could tell that nicely with typescript without adding any higher level generic to typings, which would be used by the user first to describe correct type for all the parts of API dealing with ints or bigints...

I don't think having separate builder methods wouldn't be any better than making those methods as generics where user must tell the return type when calling it every time separately. That is one option too... I don't have strong opinion either to which way this should be resolved. I'm happy with any solution @lorefnon chooses to fit the best.

**Comment by jpike88** [comment]
Why not just have an alias for count called countBigInt or something, or overload count with a second optional argument that returns a number/string on command?

Ergonomically it sidesteps this problem, and for those Postgres users who need the flexibility, it would satisfy them? How often will we run into a scenario like this again? Seems like an edge case to me.

**Comment by lorefnon** [comment]
MySQL count also returns bigint (
https://dev.mysql.com/doc/refman/8.0/en/group-by-functions.html#function_count).
So this is not just a postgres issue. Although it is likely that connectors
handle the conversion differently.

I'll go through the code to understand better how it handles large numbers
(by loosing precision or by stringifying) and get back here.

In general, in typed languages, type signatures conventionally cover the
full domain of result types and not the most common subset, so I am
hesitant to return just number though typescript gives us quite some leeway
here.

> For all intents and purposes you are as much a maintainer as the rest of
us :).

Thanks 😊 This means a lot.

**Comment by elhigu** [comment]
> Maybe, have count use parseInt if a string is detected... Throw an error (or just show a warning) if the number exceeds Number.MAX_SAFE_INTEGER (which is 2^53 - 1), and suggest they use countAsString instead. They'll probably only be using this method with a string return type a few times in their own codebase.

Knex should not do `parseInt` here automatically even with safety checks, one should setup their DB driver to do that conversion. When data is still in DB driver we know the original database type of the returned column and can interpret them as we like. Knex cannot do that parseInt there also because it has no idea when results are got that certain column was returned because of someone added .count in their query... if we take that road we would just have more problems when people are trying to figure out why in some cases knex is returning something that it shouldnt (doing implicit conversions under the hood). One design principle of knex has been that it should not interfere implicitly with the data types that is returned from the driver (except for normalizing result structure to single array instead of driver specific result object).

**Comment by elhigu** [comment]
Maybe one option would be to provide generic solution where one can tell that return type is string or number and non-generic one that is number | string which is actually truth in general case.

like: 

```
// returns number
builder.count<number>('id');

// returns number | string
builder.count('id');
```

funny thing is that actually with typescript you need to setup all builder methods anyways in a correct order to be able to get correct return type for the generated query. So actually this having typed queries is not really bringing any real typesafety for your app... at any moment if you make small error when using typings you may still get completely invalid data from DB and typings still will tell that "its fiiiine".

That is basically the reason why I don't care much if that type is any or something else.

**Comment by jpike88** [comment]
Maybe give it a generic default type of number? That way if someone wants the extra 'power' they can force it, but general use cases expect the value to be treated like a number

```
count<T=number>
```

**Comment by jpike88** [comment]
Would appreciate movement on that PR, I've added a couple more type issues, types are pretty problematic right now.

**Comment by lorefnon** [comment]
From https://github.com/tgriesser/knex/issues/3247#issuecomment-498429671: 

> I think number | string is correct and there probably will be other parts in api where this will cause same kind of problems. I wouldn't be very happy to have just any typing here either, since it is too allowing, but I understand that this is really inconvenient from user's perspective. 

Yes, I concur. I am not inclined to change this to just `number` because I'd like to minimize the possibility of types lying to consumers<sup>[1]</sup> as much as possible. 


> I wish there would be a way for user to tell what is actually type of returned count... but at least I don't know how I could tell that nicely with typescript without adding any higher level generic to typings, which would be used by the user first to describe correct type for all the parts of API dealing with ints or bigints...

This is actually possible. I have updated my PR to support this. By default count will continue will resolve to `number | string`, but following one time declaration will make all counts resolve to number:

```
declare module "knex/types/result" {
     interface Registry {
         Count: number;
     }
}
```

I acknowledge that this is rather unorthodox, but IMHO this is the most straightforward sound solution to present contention. There does exist some prior precedent of similar usage eg. in [fp-ts](https://gcanti.github.io/fp-ts/recipes/HKT) (which is where I took inspiration from).

From https://github.com/tgriesser/knex/issues/3247#issuecomment-498528370: 

> MySQL count also returns bigint (
https://dev.mysql.com/doc/refman/8.0/en/group-by-functions.html#function_count).
So this is not just a postgres issue. Although it is likely that connectors
handle the conversion differently.

> I'll go through the code to understand better how it handles large numbers
(by loosing precision or by stringifying) and get back here.

There is indeed inconsistency in the behavior of connectors as well as dialects. 

Example of the former is mysql, which throws on out-of-range numbers by default, but casts to string when `supportBigNumbers` is set to true (https://www.npmjs.com/package/mysql). 

Example of latter case is mssql which supports BIG_COUNT for counts returning bigint as a semantically equivalent alternative to count. 

Ideally we should also have dialect specific typings, but even if we do, to support mysql style connector-level configuration, above approach is likely to come in handy. 

> funny thing is that actually with typescript you need to setup all builder methods anyways in a correct order to be able to get correct return type for the generated query. So actually this having typed queries is not really bringing any real typesafety for your app... at any moment if you make small error when using typings you may still get completely invalid data from DB and typings still will tell that "its fiiiine".

I agree that the current state suffers from lack of typesafety. But I believe that now typescript has gained enough facilities (esp. with support for [higher order type inference](https://devblogs.microsoft.com/typescript/announcing-typescript-3-4/#higher-order-type-inference-from-generic-functions) in typescript 3.4) that we can make a serious attempt to fix this.

I'll create a separate request to discuss the scope of having dialect specific typings so we can improve typesafety for individual dialects (so things like sqlite not supporting returning can be caught at compile time), and we can then collectively decide if the gains are substantial enough to warrant this change.

---
<sup>[1]</sup>There do exist cases currently where types do lie to consumers, esp. when builder is mutated and the returned type is not used at all, then inferred selections etc. can go out of sync, but there is little we can do in that case without introducing a breaking change, which I don't want to do.

**Comment by elhigu** [comment]
Not to mention, that actually in most of the drivers user can choose how for example bigints are serialised (for example to some bigint library object). So being able to tell the correct type would be really useful.

**Comment by jpike88** [comment]
```

declare module "knex/types/result" {
  interface Registry {
    Count: number;
  }
}
```

putting this is globals doesn't make errors like this:

```Type 'string | number' is not assignable to type 'number'.```

```
const baseQuery = sql.knex('clientGroup')
			.where('active', 1);
		const clientGroups = await baseQuery;
		const count = await baseQuery.clone().countDistinct('clientGroup.id as CNT')
			.then(res => res[0] && res[0].CNT || 0);
```

**Comment by jpike88** [comment]
@lorefnon can you repro? if so can this be reopened

**Comment by lorefnon** [comment]
If you add an import for the module being augmented, it should work as expected: 

```ts
import "knex/types/result"; // <- Needed in same file

declare module "knex/types/result" {
    export interface Registry {
      Count: number;
    }
}
```
