### ISSUE TITLE
Error when inserting string with question marks

### ISSUE THREAD

**Issue by dekelev** [tgriesser/knex#3304]
# Environment

Knex version: 0.17.6
Database + version: MySQL 5.7.25 (NPM module: mysql 2.17.1)
OS: Mac OSX 10.14.5

# Bug

Syntax error is thrown when using a query with parameters bindings and strings that contains question-marks ?/??

**Live example:**

https://repl.it/repls/MerryExcitedColdfusion

**Expected behavior:**

Question marks in strings should be ignored when replacing binded parameters.

**Error message:**

Error: Expected 1 bindings, saw 2
    at replaceRawArrBindings (/home/runner/node_modules/knex/lib/raw.js:146:11)
    at Raw.toSQL (/home/runner/node_modules/knex/lib/raw.js:85:13)
    at Raw.Target.toQuery (/home/runner/node_modules/knex/lib/interface.js:12:21)
    at Raw.toString (/home/runner/node_modules/knex/lib/raw.js:76:17)
    at printQuery (evalmachine.<anonymous>:6:23)
    at evalmachine.<anonymous>:10:1
    at Script.runInContext (vm.js:107:20)
    at Object.runInContext (vm.js:285:6)
    at evaluate (/run_dir/repl.js:133:14)
    at ReadStream.<anonymous> (/run_dir/repl.js:116:5)
    at ReadStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at ReadStream.Readable.push (_stream_readable.js:220:10)
    at lazyFs.read (internal/fs/streams.js:181:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:463:17)

**Comment by elhigu** [comment]
> Question marks in strings should be ignored when replacing binded parameters.

No. Raw doesn't know anything about what kind of content you are trying to send to DB. It doesn't parse it and it should not parse it. If you need to put questionmarks to raw strings, you have to escape them with like `\\?`

**Comment by dekelev** [comment]
Escaping question-marks doesn't just affect the parameter binding replacement. it will also save these escaping slashes in the DB field, which is an undesired side-effect.

The library should handle this more gracefully, like removing the escaped characters or use a regex to exclude question-marks inside string literals (i.e. inside single-quotes).

**Comment by elhigu** [comment]
>Escaping question-marks doesn't just affect the parameter binding replacement. it will also save these escaping slashes in the DB field, which is an undesired side-effect.

Escaping questionmarks doesn't save anything to DB, those slashes are never sent to the database. I have no idea what you mean by that.

Sounds like you are storing raw queries to database... which is fine, though obviously they need to be in a format that knex understands... otherwise maybe you should try using mysql driver directly to run those queries?

> The library should handle this more gracefully, like removing the escaped characters or use a regex to exclude question-marks inside string literals (i.e. inside single-quotes).

Sadly starting to parse and trying to fix passed SQL would be really unreliable and would always have strange corner cases where it just won't work + all dialects has their own special cases and multitud of sting formats etc. where replacement should be ignored... so that road would cause huge maintenance burden and it would still be a bad solution for the problem.

Better would be to change knex internally to not use questionmark as binding character, but to use something less common pattern.

If you are upto implement that to knex I could write feature request with spec how that should be implemented.

**Comment by dekelev** [comment]
@elhigu Thanks for the reply. The issue was only raised after starting to use the 3rd-party knex module, knex-on-duplicate-update.

When using the `onDuplicateUpdate` method with data that contains escaped question-marks, the escaped characters are saved in the DB.

The code is available [here](https://github.com/felixmosh/knex-on-duplicate-update/blob/master/lib/index.js)

Can you suggest a solution that can be implemented in that module without changing Knex code?

**Comment by elhigu** [comment]
One could fix that module and get rid off `this.toString()` which is really dangerous to use like that. It shoudl be used only fro debugging. I suggest

**Comment by dekelev** [comment]
Thanks, I'll check it out.
