### ISSUE TITLE
Inserting 'undefined' into a DEFAULT field violates NOT NULL constraint in SQLite

### ISSUE THREAD

**Issue by coolaj86** [tgriesser/knex#332]
```bash
insert into "schedules" ("created_at", "dtstart", "event", "next", "previous", "rrule", "until", "updated_at", "xattrs") values (?, ?, ?, ?, ?, ?, ?, ?, ?)
[ Thu Jun 19 2014 13:07:34 GMT-0600 (MDT),
  1403204974631,
  '{"type":"log"}',
  1403204974631,
  null,
  'UNTIL=20140619T191234Z;FREQ=DAILY;COUNT=1',
  1403205154631,
  Thu Jun 19 2014 13:07:34 GMT-0600 (MDT),
  undefined ]
```

I believe the `undefined` and corresponding key should be omitted, otherwise `undefined` -> `null` takes precedence over `DEFAULT` and causes an error (whereas in postgresql `DEFAULT TO` seems to be processed whenever a null value is passed).

Also, I don't think the javascript date object is being properly stringified for a SQLite's timestamp field, but I haven't confirmed that.

**Comment by elhigu** [comment]
With sqlite3 undefined keys shouldn't be given if there are null constraint. I wouldnt like to make spec how insert work to behave different way when inserting single row or multiple rows. 

Completely ignoring undefined will work only when inserting single rows. When inserting multiple rows dropping undefined values is not even possible since one cannot give different set of columns for different rows...
