### ISSUE TITLE
 Treat unhandled rejections as tests failure

### ISSUE THREAD

**Issue by kibertoad** [tgriesser/knex#3320]
Ideally we should add this snippet to knex mocha setup to treat unhandled rejections as tests failure and not just warnings:

```
process.on('unhandledRejection', (reason) => {
  console.error('Unhandled Rejection:', reason);
  process.exit(1);
});
```

But first we need to fix all our existing unhandled rejections in tests.

**Comment by vonagam** [comment]
Here is a package that you can use instead of custom snippet - [`loud-rejection`](https://github.com/sindresorhus/loud-rejection). Just require `loud-rejection/register` through mocha `--require` option or in setup file. It will allow tests to finish running instead of abrupt exit on an unhandled rejection.

**Comment by elhigu** [comment]
I'd rather have that snipped instead of extra dev dependency just for that.

**Comment by vonagam** [comment]
Ok, here is a snippet that won't abrupt exit tests:

```js
let count = 0;

 process.on('unhandledRejection', (reason) => {
  console.error('Unhandled rejection:', reason);
  count++;
});

 process.on('exit', (code) => {
  if (count !== 0) {
    console.error(`Total count of unhandled rejections: ${count}`);
    process.exitCode = code || 1;
  }
});
```
