### ISSUE TITLE
Is it possible that knex is resolving concurrent INSERTs in the wrong order?

### ISSUE THREAD

**Issue by maximedupre** [tgriesser/knex#3327]
# Environment

Knex version: `"knex": "0.16.5",`
Database + version: MySQL 5.7.18
OS: macOS 10.14.5

# Bug

For example, I have something that looks like this:

	const async insertVersion = (): void => {
		return (await trx.raw('INSERT INTO versions SET project_id = ?', body.project_id))[0].insertId;
	};

	insertVersion().then((id: number): void => {
		console.log(id) // 3
	});

	insertVersion().then((id: number): void => {
		console.log(id) // 4
	});

The problem is that 4 is printed before 3 in the console. The id is an AUTO INCREMENT field, so how can the the row with id 4 be returned before the the row with id 3?

**Comment by kibertoad** [comment]
This has nothing to do with knex. You need to _await_ each insert if you want them to be executed strictly sequentially, or chain promisrs.

**Comment by kibertoad** [comment]
Nor driver nor db itself do guarantee you that insert which starts first is executed before insert that starts second.

**Comment by maximedupre** [comment]
Thanks for the quick reply and sorry if this ticket is irrelevant.

> Nor driver nor db itself do guarantee you that insert which starts first is executed before insert that starts second.

Are you certain of this? If you concurrently insert two rows in the same table, shouldn't the first inserted row be returned first? The first inserted row would of course be the one with the smallest id (3 in this case).

**Comment by kibertoad** [comment]
@maximedupre Yes, very sure. Databases are extremely complex beasts, designed to handled heavy load, and they have their own internal logic regarding what should be executed in what order in order to maximize performance, and you shouldn't make any assumptions about that. The fact that you've executed the statement from your end doesn't necessarily mean that databases already started running it.
First inserted row, indeed, will be returned first, but there are no guarantees that the row you _started_ inserting first from your end is the one that database will end up having inserted first.
And in this regard knex doesn't affect much. It's an SQL builder that doesn't do any magic, it doesn't try to be smart or optimize anything. Those things are up to mostly database and, to some extent, driver.

**Comment by maximedupre** [comment]
Thanks for the explanation. 

> First inserted row, indeed, will be returned first, but there are no guarantees that the row you started inserting first from your end is the one that database will end up having inserted first.

I find bizarre that row with id 4 can be inserted before row with id 3. In my mind, row with id 4 depends on row with id 3, because if row with id 3 had not been inserted, then row with id 4 would have id 3...

I guess it's more complex than that under the hood, as you explained.

**Comment by ricardograca** [comment]
I have my doubts that this is an issue caused by the database. I've seen similar behavior with queries in Bookshelf, where you send queries A, B and C, and they always resolve in the order C, B and A. It's very consistent, so it makes me think there's something else going on.

Maybe it's not Knex's fault, it could be a driver issue, but I think there's more here than meets the eye. Example: https://github.com/bookshelf/bookshelf/issues/1622. I know that issue is slightly more contrived, but it seems to contain a similar behavior.

**Comment by ricardograca** [comment]
@maximedupre How consistent is this behavior? What if you fire more than 2 consecutive queries? Is it more random?

**Comment by elhigu** [comment]
In the example it is possible that either one of two may have either one of IDs. 

For example when you send 2 queries to knex to parallel connections it might happen that pool notices that first connection was not valid and creates completely new connection for the one and the second connection was ready already so second query would get to DB driver sooner that first one... 

That is just one case... there are plenty of other places between client code and database where for some reason one query actually gets executed before another one, even if they were triggered from javascript in opposite order.

Also reading result for connections and printing them out has nothing to do with the order in which they were executed. For example if other connection suffers from random packet loss, it may slow it down so that second query result reach client first.

**Comment by maximedupre** [comment]
I would say the ordering of the results is correct more often than not. But the wrong order still occurs very frequently (~40%). The different results seem to come in batches. For example, I will get the wrong order 4 times, then the right order 6 times. It might be related to the busyness of my CPU?

I (seemingly) fixed the problem by adding a `await trx.raw('LOCK TABLES versions WRITE');` to force the seconds query to wait for the first one to unlock the table. I'm sure this is not ideal, but it's what I have found to work so far.

**Comment by elhigu** [comment]
use transaction and they will be got in the same order that you send the queries, because they will be send to database through the same connection.

**Comment by ricardograca** [comment]
If the results are not consistent, then this appears to be a database issue related to connections.

**Comment by elhigu** [comment]
> . For example, I will get the wrong order 4 times, then the right order 6 times. It might be related to the busyness of my CPU?

It might be related to anything... as I tried to explain in the earlier message there is nothing that is event trying to guarantee order of the results in the code case of the original post.

**Comment by maximedupre** [comment]
I am already using transactions. For example, both `insertVersion()` are in a different transaction.
