### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by guozilin** [tgriesser/knex#3362]
# Environment

Knex version: 0.15.2
Database + version: 5.7.22
OS: 

Select applicable template from below.
![image](https://user-images.githubusercontent.com/17874134/61526100-57df5000-aa4c-11e9-8b49-b7fe308efd90.png)
I'm getting lots of errors like TimeoutError: 
```
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

**Comment by ricardograca** [comment]
It means you're exhausting the connection pool. Could be caused by a number of different reasons, and it's impossible to diagnose without analyzing your code. In any case it's almost certainly not Knex's fault.

If you are sure it could be a bug please provide the minimal test code for reproduction according to the [instructions here](https://github.com/tgriesser/knex/blob/master/CONTRIBUTING.md#what-is-minimal-code-to-reproduce-bug-and-why-i-have-to-provide-that-when-i-can-just-tell-whats-the-problem-is).

As it says in the issue template that you used to create this issue:

> GitHub issues are for knex development. Please send questions how to use knex to Stack Overflow or ask about it in gitter chat.

**Comment by elhigu** [comment]
Also never set propagateCreateError to false. Knex will not work correctly.
