### ISSUE TITLE
TypeError: Cannot read property 'all' of undefined

### ISSUE THREAD

**Issue by hubitor** [tgriesser/knex#3375]
# Environment

Knex version: 0.19.1
Database + version: PostgreSQL 11.4
OS: Antergos (Arch Linux)

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
I wanted to run a migration in order to add a new column to a table. I have already added columns to a table successfully this way:

```
exports.up = function (knex, Promise) {
    return Promise.all([
        knex.schema.table("myTable", table => {
            table.string("myColumn");
        })
    ]);
};

exports.down = function (knex, Promise) {
    return Promise.all([
        knex.schema.table("myTable", table => {
            table.dropColumn("myColumn");
        })
    ]);
};
```
This time knex has thrown an error (see below). I've managed to run the migration successfully this way:

```
exports.up = function (knex, Promise) {
    return knex.schema.table('myTable', function (table) {
        table.string('myColumn');

    })
};

exports.down = function (knex, Promise) {
    return knex.schema.table('myTable', function (table) {
        table.dropColumn('myColumn');
    })
};
```

but I found it weird that suddenly the first method suddenly does not work.

2. Error message
```
TypeError: Cannot read property 'all' of undefined
    at Object.exports.up (/home/user/databases/config/migrations/20190727133408_add_columns_myTable.js:2:20)
    at Object.current.then (/home/user/node_modules/knex/lib/migrate/Migrator.js:454:40)
    at Object.tryCatcher (/home/user/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/user/node_modules/knex/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/user/node_modules/knex/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/home/user/node_modules/knex/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/home/user/node_modules/knex/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/home/user/node_modules/knex/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/user/node_modules/knex/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/user/node_modules/knex/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

**Comment by ricardograca** [comment]
The second argument `Promise` was removed in version 0.18.4: https://github.com/tgriesser/knex/commit/2ccaf3d7244f68bc3553e35ef49a2a2a53322496

If you want to use `Promise.all` it is available natively in Node.js since version 0.12, so just remove the second argument to the `up` and `down` functions:

```js
exports.down = function (knex) {
  return Promise.all([])
}
```

**Comment by nmaxcom** [comment]
I had the same issue. Since you removed it, I'd like to know if it's advisable to use promises for migrations?

What "method" would you suggest?

**Comment by ricardograca** [comment]
@nmaxcom Did you see my last comment? It explains what to do...

**Comment by nmaxcom** [comment]
No, it doesn't. You said:

> If you WANT to use Promise.all it is available...

This explains how to use Promise.all in Knex in case I want to, which is great, but it's not what I asked. _Because_ you guys removed it from Knex's migration template I'm wondering if it's because it's not a great idea to use them. Thus my question.

Is it advisable to use Promises in migrations? Is there a better way to work with migrations?

**Comment by elhigu** [comment]
Generally using promises / async / await is pretty much obligatory, since migration up / down expects that promise is returned.

However using `Promise.all` is not a good idea, because it tries to run many requests parallel., which may cause problems with some drivers at least (drivers should buffer queries that are going to single transaction and should run them sequentially). `Promise.all` also will behave pretty unexpectedly, when one of the ran promises fail.

**Comment by ricardograca** [comment]
The reason it was removed from the template is precisely because it's been available natively as a global object since Node 0.12, and it was left up to the user to decide on what Promise implementation to use. Previously it was being passed as second argument as a convenience to the user.

**Comment by nmaxcom** [comment]
Thanks @elhigu ! Very informative.

I wanted to know because I found many different implementations of this in the wild. It would be great to mention it in the docs because if it's not there people won't know about it and we'll keep using it despite not being great for Knex.

**Comment by Isanderthul** [comment]
instead of removing the second argument, I did the following:
```
exports.down = function(knex, promise) {
    return (promise || Promise).resolve();
};
```

**Comment by elhigu** [comment]
@Isanderthul instead of removing second argument, you could have as well done 

```
exports.down = function(knex, promise) {
    return (undefined || Promise).resolve();
};
```

**Comment by nmaxcom** [comment]
@elhigu Not sure why you edited your post to add:

> but the question doesn't make any sense

I don't know what you wanted to achieve by adding such an unproductive and arrogant comment like that. But more importantly, it is wrong.

It does make perfect sense to ask that when I know very little about Knex, SQL and much less migrations. A brand new concept for me. Any form of reasoning needs prior knowledge whether it comes from observations, or "traditional" data (inductive reasoning).

Knex's documentation could be updated and improved a lot. I didn't read anything about Knex's migration procedures that would indicate at all if it was a sync or an async procedure. Even if it said that there are other ways to handle async events. Hence my question.

**Comment by ricardograca** [comment]
You can open new issues on the documentation repository for things that you think are lacking: https://github.com/knex/documentation

**Comment by elhigu** [comment]
@nmaxcom Now that I checked the documentation page I didn't see it explicitly mentioned there so you are right. Question actually did make sense. I'm sorry that the final response did feel arrogant. 

I edited it because I sent it before I had finished writing the post completely. I do it all the time. To me it was obvious, that one should use promises in some way and one should actually nowadays implement those methods like: 

```
exports.up = async function(knex) {
} 
```
