### ISSUE TITLE
[QUESTION] Transaction returns bluebird promise?

### ISSUE THREAD

**Issue by palashk92** [tgriesser/knex#3417]
We recently migrated from knex 0.15.2 to 0.19.1. In the CHANGELOG, I noticed that starting from 0.18.0 you've removed bluebird from knex. However while looking at the `transaction.js` file I still see bluebird being used and it looks like the Promise being returned is a Bluebird promise and not a native one. Is my understanding correct? Or am i missing something?

**Comment by kibertoad** [comment]
I think most accurate answer would be "sometimes it returns Bluebird promise due to certain internal complexities, but you shouldn't count on it". Promises being Bluebird ones are no longer part of public API, you shouldn't depend on them being that way (and calling Bluebird-specific methods) anymore.

**Comment by kibertoad** [comment]
Eventually there will be less and less Bluebird usage in knex, but changes that large don't happen overnight :)

**Comment by kibertoad** [comment]
Please reopen if you have any further questions.

**Comment by palashk92** [comment]
Apologies for the late response and thank you for clarifying!

**Comment by kibertoad** [comment]
You are welcome!
