### ISSUE TITLE
Add propagateCreateError to PoolConfig type declaration

### ISSUE THREAD

**Issue by SmallhillCZ** [tgriesser/knex#3455]
# Environment

Knex version: 0.19.4
Database + version: N/A
OS: N/A

# Bug

Option `propagateCreateError` is missing in the pool part of the knexfile typings.

Definition from `tarn.js`:
```ts
// If true, when a create fails, the first pending acquire is
// rejected with the error. If this is false (the default) then
// create is retried until acquireTimeoutMillis milliseconds has
// passed.
propagateCreateError: true
```

I also have two questions connected with this:
 1) Why aren't `PoolOptions` typings reexported from tarn.js?
 2) Why is propagateCreateError set to true by Knex (without documenting it)

**Comment by elhigu** [comment]
That should not be allowed to be passed by the user. Knex will not work correctly if that is set to false.

Propagate error is true, because otherwise tarn will just hide for example connection errors and library user cannot react to them properly.

Dont believe any source in internet which tells you to set it to false to fix some strange error by setting it to false. 

Knex is designed to work correctly only if that parameter is true.

**Comment by capaj** [comment]
> Knex is designed to work correctly only if that parameter is true.

Why is it in the type definitions then?

This should be a type error:
![image](https://github.com/knex/knex/assets/1305378/dd2679a3-4811-460f-bb7a-a056dd1c537d)

yet it is not.
