### ISSUE TITLE
native enums

### ISSUE THREAD

**Issue by calvinmetcalf** [tgriesser/knex#394]
postgres has enums, we shouldn't have to manually create one with constraints

**Comment by kentnek** [comment]
Hi, so any update on this? I'd prefer the native enums over constraints.

**Comment by carragom** [comment]
Reading the comments on http://stackoverflow.com/questions/10923213/postgres-enum-data-type-or-check-constraint/10984951#10984951 looks like the general consenus actually is that native enums have all the benefits and no drawbacks.

1. They can be easily listed with a view, see [here](http://stackoverflow.com/questions/10923213/postgres-enum-data-type-or-check-constraint/10984951#comment22570870_10984951).
2. They can be casted for extended filtering, see [here](http://stackoverflow.com/questions/10923213/postgres-enum-data-type-or-check-constraint/10984951#comment66932544_10984951).

+1 on native PostgreSQL enums.

**Comment by elhigu** [comment]
Pretty much only drawback I can think of with enum vs. check constraint is that when you take the enum value out of DB it is jus a number and needs some mapping to have readable values on javascript side or convert enum to string before returning it from DB. Benefit is that enum takes less space.

Looks like there is not that much interest for this, since during the 3 years that this issue has been open there hasn't been that many comments / upvotes, but still if someone likes to implement option to use native enums instead of check constraints one I would consider taking that pull request in.

**Comment by jeffwillden** [comment]
I vote for supporting enum types. I landed here because of their benefits listed above. One of the "drawbacks" elhigu mentioned, that the value comes out of the DB as a number, is actually a benefit since if the records are sent to a client-side app. The number is obviously more compact in JSON. That can add up to big savings when sending large numbers of records that have different enumerated statuses, for example.

**Comment by elhigu** [comment]
@jeffwillden If you read my last comment carefully you will notice that I actually mentioned also the benefit of enums consuming less space :)

I agree that there are times when using enums is better choice, questing is not about that. It is just a choice which way of the functionality is more commonly useful. In knex the choice was using check constraints.

Also in my personal work experience I've never came across in situation where I was wishing that my enums would be smaller in JSON (I completely understand that it is possible case and looks like you came across with one situation like that). On the other hand I've been cursing various times when I had to be working with DB that had enums stored as numbers which made interpreting raw DB data much harder.

Anyways looks like this discussion is starting to go in circles... Default functionality is not going to change, but if someone likes to implement an option `{ nativeEnum: true }` for enum column builder I wont object.

**Comment by geekabhi** [comment]
will it be implemented for mssql as well?

**Comment by elhigu** [comment]
@geekabhi should be implemented for every supported platform. However I haven't heard anyone wanting this feature so bad that they would have started implementing it.

**Comment by heisian** [comment]
ouch.. will definitely be using a combination of `knex.raw` and `knex.specificType` here instead of the default enum method...

**Comment by heisian** [comment]
awesome!
