### ISSUE TITLE
table.primary() documentation vs implementation

### ISSUE THREAD

**Issue by myndzi** [tgriesser/knex#450]
documentation says to use `table.primary(['col1', 'col2'])` for a composite key, but this throws errors. If you use `table.primary('col1', 'col2')`, it succeeds. `table.unique` on the other hand requires the array syntax. These should be straightened out and made consistent in the documentation and the implementation. Would submit a patch, but unsure which way you want to go with.

**Comment by whitelynx** [comment]
I'd like to see this be made consistent as well.

Supporting both should be possible, since there's already [a helper function to support that](https://github.com/tgriesser/knex/blob/master/lib/helpers.js#L20-L29)... seems like `TableBuilder` [needs to be updated](https://github.com/tgriesser/knex/blob/master/lib/schema/tablebuilder.js#L76-L83) to use it.

**Comment by wubzz** [comment]
I'm closing this in favor of #1430 where I'm going over this more in-depth cross-dialect.
