### ISSUE TITLE
Modifying columns

### ISSUE THREAD

**Issue by ErisDS** [tgriesser/knex#46]
I think it is a reasonable expectation that it would be possible to:
- rename a column
- change the data type
- add or drop the null constraint
- change the default 

And probably other things that I have not thought of. 

I would imagine the syntax for doing this would be something like

```
 knex.Schema.table('table_name', function (t) {
        t.string('my_column').renameTo('something_else');
        t.string('my_column').changeTo('text');
        t.string('my_column').nullable() < adds nullable if not already present
        t.string('my_column').notNullable() < removes nullable if present
        t.string('my_column').defaultTo('whatever') < adds or updates the default
  });
```

Maybe there needs to be something extra in the chain, possibly at the `knex.Schema.table` level to indicate that this is a modify statement not an add.

I realise that this is tricky to implement across various databases, especially in SQLite where you have to create a whole new table, but in a system which requires migrations, without these tools it is going to be necessary to use knex.raw and write all the migrations for each DB supported, which sort of defeats the point of having a nice ORM especially one which is about to support migrations.

**Comment by dkushner** [comment]
@tgriesser, @bendrucker: Has there been any update on this functionality? Writing raw queries in every migration I have that modifies a column (virtually all of them), is getting a bit frustrating.

**Comment by bendrucker** [comment]
No, sorry

**Comment by ricardograca** [comment]
Would it be possible to modify the `renameColumn()` method so that it returns the modified column object so that one can chain any of the column chainable methods to it? Namely I'm trying to update a reference after renaming a column:

    table.renameColumn('stuff_id', 'some_stuff_id').references('some_stuff.id')

This produces an error saying that:

    Object #<TableBuilder_PG> has no method 'references'

If that would be a breaking change (looks like it, although I'm not sure if anyone is using the current return object) then at least provide a way to select a column that already exists.

**Comment by ErisDS** [comment]
Sorry to effectively be nagging on an ancient issue - but I'm desperate to be able to modify the length of text columns. I'd be more than happy to pitch in and try to contribute this if there's a consensus on what the API should be?

**Comment by olalonde** [comment]
Is it yet possible to modify column types or should I use `.raw()`?

**Comment by ricardograca** [comment]
@olalonde Nope, you should use `.raw()`.

**Comment by tgriesser** [comment]
@ErisDS the plan is to make the builder not constrained to normal statements but also add an api for altering the tables:

```js
knex.alterTable(tableName).modifyColumn(colName, type)
knex.alterTable(tableName).drop(colName)
```

I'm also working on an API for defining what the table structure for a database *should be* so you can eventually use these objects to compare against what the current state of the database is (similar to what ghost does, but a bit more tested/spec'ed out)

```js
const {database, table, column} = require('knex').Schema

var db = database({name: 'tryghost'}, [
  table('posts', [
    column('id', 'int'),
    column('slug', 'string'),
  ])
])

knex.select(db.posts).where(db.posts.id, 1)

// SELECT posts.* FROM posts WHERE posts.id = 1
```

Working on moving some stuff around to get to a better api than having to use `raw`

**Comment by light24bulbs** [comment]
Nullable is now possible.  Are all of these done?

**Comment by ErisDS** [comment]
Perusing the code it looks like there may have been some progress towards this? https://github.com/tgriesser/knex/blob/master/src/schema/columnbuilder.js#L71

Any chance of an update? Where are you at with these changes, what could be done to help?

**Comment by niftylettuce** [comment]
Any update with this?

**Comment by niftylettuce** [comment]
Looks like we can use `.alter` method or something?

**Comment by RobertWarrenGilmore** [comment]
Bump!

**Comment by RobertWarrenGilmore** [comment]
I would love to see an API like `table.modifyColumn('myCol').notNullable().defaultTo('hello')`.

**Comment by danswater** [comment]
Bump!

**Comment by ErisDS** [comment]
I'm as keen as anyone to see some movement on this issue. If you agree, and would like to inspire some movement on this issue, the best thing to do is to take the time to explain what your use case is and why you need knex to add support. Perhaps even offering some help - docs & QA are just as useful as code.

Adding a comment without content isn't likely to inspire any change in the status quo here, in fact I think it's more likely that the people you want to hear you hit "unsubscribe" on the issue as a result.

**Comment by kuanb** [comment]
Per @ErisDS suggestion, my situation is: I have a schema with col type `string` I would like to change to `datetime`. I'm open to running a process where I drop the existing `string` col and add a new one with `datetime`, and would appreciate documentation on how to go about doing this.

**Comment by rhys-vdw** [comment]
@kuanb This is a feature request thread - that means there is no specific API for doing this. At the moment you'll need to use other `schema.table` methods to create a new column, copy the data over, and then delete the original column. If you need more help with this I'd suggest opening a new issue or creating a StackOverflow question.

**Comment by kuanb** [comment]
@rhys-vdw apologies for any confusion I caused. My intent was to provide a "response" to @ErisDS comment that we should include use cases to demonstrate need for something like this to occur. I understand this is a feature request. 

I currently am able to perform the migration fine using `knex.raw( ... )` but wanted to demonstrate that I was in a situation where such a feature from the `knex` library would have been nice. Perhaps I misunderstood `ErisDS request.

**Comment by rhys-vdw** [comment]
Ah right, I was just responding to "and would appreciate documentation on how to go about doing this.". No stress. :)

**Comment by ivawzh** [comment]
+1 for column date type modification

**Comment by tkellen** [comment]
Honest question. Is this abstraction actually serving a useful purpose? Just write SQL.

Knex should be a query builder, not a migration system. Here is an example of a migration system that makes at least a little sense:

https://github.com/tkellen/node-postgres-ansible-api-boilerplate/blob/master/careen.js
https://github.com/tkellen/node-postgres-ansible-api-boilerplate/blob/master/package.json#L6-L9
https://github.com/tkellen/node-postgres-ansible-api-boilerplate/tree/master/migrations

**Comment by ivawzh** [comment]
Why do I have to touch SQL? Imagine a case that if one day I want to switch from PostgreSQL to MySQL. How long will it take for me to learn all the gotchas on both side and rewrite all the raw SQL migrations. Plus, if ActiveRecord can do migration right, why Knex can not?

**Comment by tkellen** [comment]
Switching between MySQL and PostgreSQL seamlessly is a pipe dream that will never happen for anyone on a meaningful scale ever.  All database systems have strengths and weaknesses. It makes absolutely no sense to limit yourself to a subset that works across both so you can arbitrarily decide to switch between one or the other.

ActiveRecord doesn't do migrations "right". There is a huge set of functionality it doesn't provide a DSL for. You are right that more human effort has been dumped into ActiveRecord's migration system though. The reason for that is simple numbers.

Knex:
<img width="143" alt="screen shot 2016-04-16 at 10 44 59 am" src="https://cloud.githubusercontent.com/assets/1004324/14581952/4c234b4e-03c0-11e6-8bd7-d5a493db9fdf.png">

ActiveRecord:
<img width="160" alt="screen shot 2016-04-16 at 10 44 33 am" src="https://cloud.githubusercontent.com/assets/1004324/14581948/4003c564-03c0-11e6-81b2-f5c2dca341d9.png">

My question remains. Where is the value in these DSLs? Anything you want to migrate can be expressed in SQL. You don't need to build some half-baked sugar on top of it. People have been talking about altering columns here for *3 years*. Meanwhile SQL has been trucking along doing the same thing just fine for 30 odd years.

Also, RE: switching between PostgreSQL and MySQL, what happens if you decide to migrate away from javascript and move to ruby? How much time will it take you to transcribe all of your SQL migrations from one silly pointless DSL to another?

**Comment by ricardograca** [comment]
@tkellen While I'm more inclined to agree with you these days, I think there is still value in having an interface for easily changing a database's structure from the javascript side.

While the argument about easily changing database servers often comes up, I think realistically that's not the main use case, due to the reasons you mentioned, and because when you create an application you do it with a set of dependencies in mind, including the database server. From my point of view the main benefit is just having a standard interface that allows this functionality in all your apps without having to constantly write the same thing over and over again, or constantly including your own private helper methods.

That is, instead of everybody writing their own code for this, and ending up with a lot of different ways it is accomplished, we would have a sort of standard way of doing it. I know that SQL is already something standard, but it's too generic. Using SQL alone you can do it anywhere and at any time, but this feature is about tailoring it to something more specific, making it more predictable.

Changing a database's structure is probably something that is shared by a great number of programs that use a database, so it makes a good candidate for having a module that does all the heavy lifting.

What's your suggestion to this problem?

**Comment by tkellen** [comment]
My suggestion is to use something like [careen](https://github.com/programble/careen), [db-migrate](https://github.com/db-migrate/node-db-migrate), etc.

Basically, find the most minimal abstraction possible and use it. That means something to run arbitrary SQL files, a facility to track which have been run, and some functionality for rolling them up or down.

In my opinion, migrations never belonged in Knex. I tried to use them years ago, coming from a ruby background using Sequel and ActiveRecord. Like most people in this thread, I imagined that some day we'd have the same level of support here. I even [landed](https://github.com/tgriesser/knex/pull/540/files) some [PRs](https://github.com/tgriesser/knex/pull/511/files) adding functionality to the migration system.

At some point, I recognized two things:

1. A monumental effort would be required to achieve feature parity with more mature tools.
2. Mature tools are still wildly incomplete and provide zero value over SQL.

For example, here is a check constraint that prevents an employee from being double-booked on a schedule.

```sql
ALTER TABLE utilization ADD CONSTRAINT employee_over_utilized EXCLUDE USING gist (
  employee_id
  WITH =,COALESCE(sketch_calendar_id::text, 'null')
  WITH =,BOX(
    POINT(EXTRACT(EPOCH FROM first_day), EXTRACT(EPOCH FROM first_day)),
    POINT(EXTRACT(EPOCH FROM last_day), EXTRACT(EPOCH FROM last_day))
  )
  WITH &&
);
```

You can't build constraints like this fluently using any DSL I know of. Even if you could, I still wouldn't expend the effort learning it. SQL does everything you want it to. Painting a shitty javascript veneer over it isn't helping anyone get anything done.

**Comment by ErisDS** [comment]
> Switching between MySQL and PostgreSQL seamlessly is a pipe dream that will never happen for anyone on a meaningful scale ever.

Whilst switching a production system from one db to another is hard, it's not impossible. Nonetheless, I think you're totally missing an entire ORM use case here. What about software that allows you to choose your DB when you install it? That's what I'm working on 😉  

Knex works really nicely in most places as it provides a great API (or javascript veneer if that's what you want to call it) for the most common use cases, and then it has an escape valve of `knex.raw` that lets you dropdown to the magic of SQL when you need to go beyond those basics. All good JavaScript libraries work this way - they wrap things up in magic but let you escape when you need to.

When it comes to the migration system, this issue is talking about a handful of common cases that it would be great to have a veneer for because of the complexity of the differences between SQL versions - that is, there is no one SQL query that will work for multiple DBs. It doesn't propose that every possible migration ever should have an abstraction.

**Comment by ivawzh** [comment]
Thanks, I'm trying out db-migrate now. So far so good.

**Comment by tkellen** [comment]
> Whilst switching a production system from one db to another is hard, it's not impossible. Nonetheless, I think you're totally missing an entire ORM use case here. What about software that allows you to choose your DB when you install it? That's what I'm working on 😉

If I were maintaining Ghost, I would have separate migration files for each RDBMS. Yes, you'd have some minor duplication in your codebase, but how much clarity would it provide for new contributors? Would your existing test suite easily cover failures? Would you be able to more easily leverage the strengths of each respective database you support by dropping this edifice?

More pedantically, this is not an ORM use case.

> Knex works really nicely in most places as it provides a great API (or javascript veneer if that's what you want to call it) for the most common use cases, and then it has an escape valve of knex.raw that lets you dropdown to the magic of SQL when you need to go beyond those basics. All good JavaScript libraries work this way - they wrap things up in magic but let you escape when you need to.

Agreed--I see the value in a query builder over munging SQL strings, Knex is great for that!

> When it comes to the migration system, this issue is talking about a handful of common cases that it would be great to have a veneer for because of the complexity of the differences between SQL versions - that is, there is no one SQL query that will work for multiple DBs. It doesn't propose that every possible migration ever should have an abstraction.

I see the point you're making here, but it's been three years and we're still talking about altering a column. Also, where do you draw the line at basic? For example, I consider robust check constraints to be a basic tenet of good database design.

**Comment by joepie91** [comment]
So, I've just read through the entire thread, and it's not clear to me what the current status is. Could a maintainer answer the following?

1. What is the current state of internals documentation? That is, information about how the codebase is structured, why it is structured that way, and so on.
2. What is the current state of this feature request? What parts have been implemented, what parts have not? Where are potential 'attachment points' for implementing the remainder?
3. What, if any, are the blockers *at this moment* for implementing this and sending in a PR? What parts of the internal architecture need changing and how, to make this a possibility?

I'm potentially interested in implementing this and submitting a PR, but before I can commit to doing that, I need to have a better idea of what the current situation is like, and how much work I can expect it to be.

**Comment by elhigu** [comment]
@joepie91 

1. There is no other developer documentation, except the code. CONTRIBUTING.md describes some stuff how to run tests etc. 
2. As far as I know there has been no effort to implement this. If one starts to implement this I can help by trying to find some related pull requests where e.g. column renaming is implemented. 
3. I'm not aware of any blockers, why this couldn't be implemented. I don't believe that one has to change internal architecture for this. I would recommend to choose one specific thing what you like to modify and implement that first and then select next thing what to modify and implement that. I suppose that the biggest challenge is to find a correct query for every dialect for certain change.

People who knows better feel free to correct / add info here, I just wanted to answer something to start with so that question won't just stay hanging there in silence...

**Comment by ricardograca** [comment]
@elhigu What you say is mostly right, but there is some resistance from some collaborators for getting this merged. Tim himself seems to be ok with it if anyone actually does all the work including tests.

The biggest challenge will be in regards to SQLite which doesn't natively support modifying columns, so it requires all sorts of workarounds.

**Comment by elhigu** [comment]
@ricardograca We have been supporting APIs which doesn't work on every dialect. Specially with sqlite there are some features, which just throw an exception of not being supported or just ignored like `.returning()`. 

So I don't mind if e.g. certain column modify methods doesn't work on sqlite if it is actually pretty much impossible to implement without creating some temporary columns + data migrations to support it.

**Comment by RWOverdijk** [comment]
A huge 👍  here.

**Comment by elhigu** [comment]
Implemented in  #1759

**Comment by ErisDS** [comment]
@elhigu I think this is a mistake? There are 4 features requested here:

1. rename a column
2. change the data type
3. add or drop the null constraint
4. change the default

Only 1 and 3 are implemented. 2 is still a pretty enormous missing feature?

**Comment by elhigu** [comment]
@ErisDS yeah, I wanted to link the original PR with most off the discussion, should have linked both :)

**Comment by PierBover** [comment]
Ok, so we can alter a table, a column, etc.

Is there a simple way of seeding only to a column?

**Comment by elhigu** [comment]
@PierBover what do you mean by "seeding only to a column"?

**Comment by PierBover** [comment]
If for example we add a new column, is there a simple way of filling it with values other than using raw queries?

**Comment by elhigu** [comment]
@PierBover you either use `defaultTo()` when creating the column or first create data and then update it with normal knex queries. There is no additional magic in knex for this (and I don't think there should be either).

```js
return knex.schema.alterTable('MyTable', t => {
  // deafault value / expression to seed (one cannot create select queries here)
  t.integer('newColumn').defaultTo(1);
  t.integer('newColumn2').defaultTo(knex.raw('some expression e.g to create random data')); 
}).then(() => {
  // just create populate query after creating new column like normally done with SQL
  return knex('MyTable').update({ newColumn: 2, newColumn2: 3 });
});
```

**Comment by ricardograca** [comment]
@PierBover Yes: http://knexjs.org/#Seeds-CLI

**Comment by PierBover** [comment]
Right @ricardograca but that is for seeding the whole table, no?

Thanks for the suggestion @elhigu 👍

**Comment by 2rhop** [comment]
I am starting a new project to seed tables with knex.js, [here](https://github.com/2rhop/knex-seeder). Any help will be nice!
