### ISSUE TITLE
Discussion: Error Handling

### ISSUE THREAD

**Issue by tgriesser** [tgriesser/knex#522]
I'm still experiencing some disconnect issues in MySQL on timeout errors. We should carefully think out the standard error handling behavior and / have some default options and custom errors for the different potential cases that can happen among different databases.

Opening this ticket as a single place to discuss anything error related and reference any error related behavior.

**Comment by skuester** [comment]
Is this discussion still open? It seems that a year is a long time for a discussion on fatal error handling to be left hanging.... did it move elsewhere?

**Comment by Roam-Cooper** [comment]
I came here looking for global error handling. :) we want to throw our own db error on a query error.

**Comment by jmm** [comment]
Is there an abstract, database engine-agnostic way of detecting errors like a unique index violation on insert? Or any plans / interest in providing it? Example:

  ```js
  Model.forge(modelData).save()
  .catch(function (e) {
    // Query violated a unique index constraint
    if (e.code === knex.errors.unique_failure) // ...
  });
  ```

  Which would work consistently regardless of engine (client adapter). Currently it seems you'd have to find and match error message substrings or code numbers for each engine, something like:

  ```js
  var errors = {
    sqlite3: {
      unique_failure: /UNIQUE constraint failed/,
    },

    postgres: {
      unique_failure: /unique_violation/,
    },
  };

  // I don't think knex.client or its properties are actually documented -- using
  // for illustration
  var engine = bookshelf.knex.client.config.client;

  Model.forge(modelData).save()
  .catch(function (e) {
    if (errors[engine].unique_failure.test(e.message)) // ...
  });
  ```

  Ugly.

**Comment by williscool** [comment]
Is this not a priority for this project?

**Comment by elhigu** [comment]
@williscool which part of the discussion do you mean? There is global `query-error` event already http://knexjs.org/#Events-query-error also there has been made many fixes to handling pool when database connection is being cut off and there is separate issue which hasn't been implemented yet about how to catch database  connection error when knex is being initialized  https://github.com/tgriesser/knex/issues/1542.

**Comment by williscool** [comment]
@elhigu thanks for the quick response.

I meant the database connection event monitoring part.

For instance with https://github.com/Automattic/kue

I can get directly to the redis client to monitor connection stuff on it to know my app's queue is starting properly and monitor if it goes down

```
const queue = kue.createQueue({ redis: config.services.redis_url});

  // https://github.com/NodeRedis/node_redis

   
  queue.client 
    .on('connect', function() {
      logger.verbose({ service: 'redis' , msg: 'connected' });
    })
    .on('ready', function() {
      logger.verbose({ service: 'redis', msg: 'ready' });
      ready();
    })
    .on('error', function(err) {
      logger.verbose({ service: 'redis', msg: err });
    })
    .on('disconnected', function() {
      logger.verbose({ service: 'redis', msg: 'disconnected' });
      lost();
    });
```

looking for something similar for knex

**Comment by elhigu** [comment]
@williscool In knex there is connection pool, which is pinging connections in the pool every now and then if the certain pool connection is alive. If connection is in pool and it dies, then it is just discarded. 

So there is no need for ready event, since for every query connection is requested from pool. In pool you have afterConnectionInit or something like that method, which can be used to run some initial queries when new database connection is created for the first time.

`knex.on('query-error', function (err) {...})` event can be used globally to get any connection / and other errors.

And here are some error scenarios I can think of:

Disconnected event is not interesting for the knex, since pool decides when connections are created / discarded.

If connection is outside of the pool (e.g. bound for certain transaction) and one is doing query there and connection is lost, then probably query timeout or some other error is returned from promise. 

If one tries to get connection from pool and there are none available, then after timeout connection acquire timeout error is thrown.

It is pretty much impossible to create events like redis have for knex because of multitude of different db drivers which doesn't actually support listening for connection errors (sorry I don't remember the details of that from top of my head, @wubzz might remember)...

**Comment by wubzz** [comment]
@elhigu Sums it up pretty good.

At most what we can do is begin proxying events from the `pool2` module over to the internal knex code allowing for listening to these errors, however cryptic they may appear. (See [this](https://github.com/tgriesser/knex/blob/master/src/client.js#L164)) Not sure if it applies to all dialects, but would probably also have to emit something [here](https://github.com/tgriesser/knex/blob/master/src/client.js#L210) as well.

**Comment by elhigu** [comment]
@wubzz It might be useful to be able to catch the case where whole db is out of reach. I wouldn't mind merging pull request which implements that for all drivers... sounds like lot of work and hard to test automatically.

**Comment by vellotis** [comment]
I once started to implement [`knex-generic-errors`](https://www.npmjs.com/package/knex-generic-errors) "plugin". I saw a need to know if something went wrong with my query and what went wrong. The concept may be developed further.

**Comment by yonatannn** [comment]
@vellotis is knex-generic-errors compatible with knex 0.13? I noted it tried to trap/replace knex.query method but in 0.13 I can't seem to locate this method

**Comment by joaosousafranco** [comment]
Ive got the same issue in 0.18.0, ive reverted to 0.17.2 and it works

**Comment by elhigu** [comment]
Closing old issue. In next tarnjs version, pool exposes events, which anyone can use to monitor pool behaviour closely. If there is something specific to discuss about error handling then new issue about it should be opened.
