### ISSUE TITLE
Detect (and drop) duplicate field names

### ISSUE THREAD

**Issue by Vanuan** [tgriesser/knex#568]
Steps to reproduce:

```
knex.select('a').select('a as a').from('t').toString()
```

Expected behaviour:

```
"select `a` as `a` from `t`"
```

(or maybe error?)

Actual behavior:

```
select `a`, `a` as `a` from `t`
```

Results in

```
ERROR SQL ERROR: ER_DUP_FIELDNAME: Duplicate column name 'a'
```

**Comment by wubzz** [comment]
Closing this but willing to reopen in the event that some stronger arguments arises.

A sort of work around for this could be to use the newer object syntax, such as:

```javascript
const columns = {a: 'a'};

console.log(knex('test').select(columns).toString());
//select `a` as `a` from `test`
```

That way the `columns` object could be manipulated instead of working directly on the builder, which would ultimately prevent duplicate column names.
