### ISSUE TITLE
Postgres Array columns

### ISSUE THREAD

**Issue by thataustin** [tgriesser/knex#569]
I'm a little new to knex, so I'm not sure if this sort of issue is welcome here, but I'd like to submit a PR to allow for the creation of [Postgres Array columns](http://www.postgresql.org/docs/9.3/static/arrays.html).

Is it okay to add db-specific features to the knex dialect files, or are those files just a bridge that allows access to features present in all DB's, but implemented differently in any given one?

**Comment by tarikjn** [comment]
I am interested in this as well (except reading instead of inserting). Arrays and Composite types.

Although a very easy solution I found is to use Postgres native functions to convert to json first, and I don't even need to `JSON.parse` it since it seems to be auto-parsed by Knex.

```javascript
knex('users').select('username', knex.raw('array_to_json(addresses) as addresses_json'))...
```

Hopefully this trick proves useful to anyone using Arrays/Composites.

**Comment by bendrucker** [comment]
> it since it seems to be auto-parsed by Knex

node-postgres does that

To loop back on the original request, we have no desire to hamstring next and constraint it to the least common denominator (SQLite) and the expense of great DBs like Postgres. In order to keep Knex what it is, I think it's enough to either cast a value (e.g. in MySQL an array column is a JSON string) or even throw an exception. As long as there's user feedback we're good.

**Comment by demisx** [comment]
With PostgreSQL 9.4, do I need to fall back to knex.raw in order to create a JSON array column `json[]` or is there a better way to do this in Knex? I am talking about creating schema in migration. So far, I could only find `table.json()` method that I believe can create single object json columns only.

**Comment by bendrucker** [comment]
Knex doesn't support array columns at all at the moment. So you're always going to be doing raws.

**Comment by demisx** [comment]
Thanks Ben. I've got it created with:

```js
table.specificType('photos', 'jsonb[]');
```

Still better than doing `knex.raw(alter table foo add column photos jsonb[])` kind of stuff.

**Comment by bendrucker** [comment]
Yeah, totally forgot about `specificType`

**Comment by araskin** [comment]
Thanks for the 'specificType' workaround. Very useful!

**Comment by wubzz** [comment]
Closing as `.json` and `.jsonb` exists on the schema builder. In edge cases `specificType` is fallback.

**Comment by oleoneto** [comment]
`table.specificType('tags', 'character varying(20)[]')`

**Comment by villesau** [comment]
@wubzz I think this should be reopened. The original question was not about JSONB but postgres native array types.

**Comment by elhigu** [comment]
Better to create new feature request, which follows the issue template and proposes API.

**Comment by elhigu** [comment]
Though I don't see any benefit of having separate builder method compared to `.specificType` if this will be postgresql only feature.

**Comment by thataustin** [comment]
Yea, I think the best PR to come out of this would just be to document how to do it with `specificType`.  It's a great function because it also empowers the reader to know how to do other PG-specific types.

**Comment by redeemefy** [comment]
> `table.specificType('tags', 'character varying(20)[]')`

It is important to use `'character varying(<size>)[]'` since using `'STRING[]'` won't work.

**Comment by martin-trummer** [comment]
TEXT works for string arrays:
```typescript
table.specificType('strarray', 'TEXT[]');
```
