### ISSUE TITLE
Seprate Read And Write Support

### ISSUE THREAD

**Issue by majimboo** [tgriesser/knex#703]
Are there plans to support, writing to master and reading from a read-replica just by a simple config?

**Comment by bendrucker** [comment]
That would be an interesting feature. It's something that would require a number of very substantial changes so it's not something you'll see for quite a while. Check out the roadmap and especially the pool (#696). Right now only node-mysql supports clustering and we'd need uniform support in order to do this.

This request is definitely a helpful data point in thinking about how to structure the pool API. We'd need to at least have a synchronous API for checking whether a connection was available from the read pool and preferentially using that. If not, we'd need to carefully think through how to choose which pool to make an async connection request to (read only or duplex). 

We'll reopen this and discuss further when the pieces needed to make this happen are shipped or at least more firmly defined.
