### ISSUE TITLE
Using where with an array should use IN query

### ISSUE THREAD

**Issue by mgartner** [tgriesser/knex#711]
It would be nice if `where` automatically used an `IN` statement when a value is passed that is an array, so that you don't have to explicitly call `whereIn`.

```js
knex('users').where({
  first_name: 'Test',
  role: ['owner', 'admin', 'user']
}).select('id')

// SELECT id FROM users WHERE first_name = 'Test' AND role IN ('owner', 'admin', 'user');
```

**Comment by tgriesser** [comment]
Might be sort of convenient but then you hit a bunch of weird edge cases and it's a slippery slope to becoming more of a weird query DSL rather than (as close as we can) 1-to-1 with SQL, plus with Postgres' arrays it would get really ambiguous.

I would like to get something in here though that'd allow something like:

```js
knex('users').fromJS({
  where: {first_name: 'Test'},
  whereIn: {role: ['owner', 'admin', 'user']},
  select: 'id'
})
```

or something along those lines
