### ISSUE TITLE
Use of Prepared Statements

### ISSUE THREAD

**Issue by sparticvs** [tgriesser/knex#718]
While skimming the codebase, I don't see any use of prepared statements. Am I missing something?

**Comment by bendrucker** [comment]
Use `knex.raw` for that.

**Comment by tgriesser** [comment]
@sparticvs The builder automatically parameterizes queries that are constructed to prevent against sql injection, but doesn't yet offer true prepared statements. Might be something we look into in the future though.

**Comment by sparticvs** [comment]
Thanks for the response @tgriesser. A quick follow up, could point me to the file with the sanitization functions? If not, I will look for them later.

**Comment by tgriesser** [comment]
Knex just parameterizes the query and passes off to the sanitation in each of the individual client libs, e.g.

https://github.com/felixge/node-mysql/blob/master/lib/protocol/SqlString.js

https://github.com/brianc/node-postgres/blob/4a2b3d4a9242570ae04f8de17202229c1c74e50c/lib/client.js#L240-L286

**Comment by sparticvs** [comment]
Gold. Thanks a bunch.

**Comment by proehlen** [comment]
@tgriesser 

> The builder automatically parameterizes queries that are constructed to prevent against sql injection

I think you should add this feature to the front / page docs.  Had to find this issue to know if you were doing it or not and I think it's a selling point for your library.

**Comment by minecrawler** [comment]
However, I am still very confused. Does parameterization happen automatically (If so, none of the examples is clear about that)?! Or do I have to use knex.raw() and parameterize manually?

**Comment by elhigu** [comment]
@minecrawler 

Yes parametrization happens automatically. Strings generated in knex documentation page has parameters inlined, because they are generated with `.toString()` method of the query builder. It is just to make documentation more readable.

To see parametrized generated sql strings which are sent to database driver you can call `.toSQL()` method of the query builder (`toSQL` and `toString` are documented here http://knexjs.org/#Interfaces-Other).

I agree that someone could write a chapter about how queries are actually sent to database to the documentation. Pull requests are welcome.
