### ISSUE TITLE
Disable debug for particular query

### ISSUE THREAD

**Issue by Kagami** [tgriesser/knex#725]
Hi. I have the following use case:
* I want to debug all my queries
* Except several queries which are too verbose and wipe out my logs

I can disable global debug and enable debug for all queries except those but I think it would be better to have the ability to disable debug for the specific query instead.

Fix should be very straightforward: https://github.com/tgriesser/knex/blob/1411f2310aa6efb3242ff313038d67da3c0a347f/lib/runner.js#L156
Change this to:
```js
(this.client.isDebugging === true || this.builder._debug === true) && this.builder._debug !== false
```

What do you think?

**Comment by bendrucker** [comment]
I don't think this is something we want to encourage. Global debugging is good for development but otherwise we want people to be using query events for logging.

**Comment by Kagami** [comment]
But this shouldn't break anything, am I right?

If it was unclear I want the following behavior:

```js
var knex = require('knex')({
  dialect: 'sqlite3',
  debug: true,  // Enable global debug
  connection: {
    filename: './data.db'
  }
});

knex.insert({user_name: 'Tim'}).into('users');  // This will be logged
knex.insert(huge_list_of_data).debug(false).into('users');  // This _won't_ be logged
```

I have a lot of queries and it would be messy to put `.debug()` for everything _except_ the one I don't want to log.

**Comment by bendrucker** [comment]
Yup, I understand what you're asking for. The issue is not that this is likely to break someone's setup, but that have generally declined requests relating to adding features to `debug`. It's really intended as a dev feature and not for production consumption. There's definitely interest in more robust logging and I think that should come in the form of an entirely separate package instead of polluting debugging features to the point where people mistakenly think it's okay to turn them on in production.

**Comment by tkellen** [comment]
If you want this now you can do
```js
knex.client.isDebugging = true;
knex.insert(...);
knex.client.isDebugging = false;
```

**Comment by Kagami** [comment]
@tkellen thanks, I will try it.
@bendrucker Ok, I understand your motivation but I thought this should be really easy to fix (oneline fix) and the proposed behaviour should also be more logical and consistent: the debug function already taking the argument, it just doesn't recognize the `false` value.

**Comment by bendrucker** [comment]
Definitely not about the code complexity here—my concern is for documentation and how users perceive a feature like this. What makes debug special is that it's auto-logging to stdout. When you use events, you have to explicitly do the logging and it's easy to filter your query data right at the source (i.e. in your event handlers). 

What I don't want here is for someone to turn on debug in production and think that's it's okay to pick out specific sensitive queries and turn debugging off. That's why I'm suggesting we keep debug mode locked. 

I'd love for you to go ahead and outline your query logging needs and why you want this. I think logging is a good candidate to add to migrations and schema building as the initial packages to be split out of knex. 

I'm still not decided on what query logging should look like. I think most people are going to want to plug the log events into a first class logging system like good, winston, or bunyan. So I'm imagining we'd have a fairly light API a la good and put specifics into individual "transport" modules that interface with other systems.

**Comment by Kagami** [comment]
Thanks for detailed answer.

>I'd love for you to go ahead and outline your query logging needs and why you want this.

Well, I'm definetely not going to use this debug in production. My use case:
I have [an application](https://github.com/bitchan/bitchan-node) which uses knex to interact with database. For debugging purposes it's very handy to turn queries logging on (very simple type of logging, just SQL request string and bindings; I used to do similar things with SQLAlchemy, it has debug option too). I'm sure no one will use this type of logging in production setup, it's just helps me to debug application. But some of the queries have very huge input and wipes out all other debugging information making it almost impossible to follow. So I'd like to turn them off without writing a lot of boilerplate.

Btw, I'm using winston for real logging purposes, but I don't think anyone would need SQL queries in log files in my case, it's almost only needed while development. If you provide some sort of more general logging which allows to select logging transports and filters, I will be happy too, but it's not strongly required for my tasks.

>I'm still not decided on what query logging should look like.

You may take a look at [python's logging module](https://docs.python.org/2/library/logging.html). It's very flexible and handy. I've been using winston for some time, but it lacks a lot of python's logging abilities. E.g. very flexible [logging config](https://docs.python.org/2/howto/logging.html#configuring-logging) which allows to configure all varations of transports/formatters/filters for the end user without touching a single line of code. It's hard to achieve with winston.

**Comment by bendrucker** [comment]
That makes sense. I'll merge a PR that implements this. If an argument is supplied it must be a boolean. Otherwise no arguments are allowed. Docs should specifically mention that the intention is for disabling particular queries that are especially long.

**Comment by Kagami** [comment]
Ok, thanks, I'll make a PR.

>If an argument is supplied it must be a boolean.

Do you mean `typeof & throw` checking should be added [here](https://github.com/tgriesser/knex/blob/1411f2310aa6efb3242ff313038d67da3c0a347f/lib/interface.js#L47)?

**Comment by bendrucker** [comment]
Yes. It should behave precisely as documented which is not the case right now.
