### ISSUE TITLE
modularize out sql generater

### ISSUE THREAD

**Issue by calvinmetcalf** [tgriesser/knex#821]
It might be a good idea to think about pulling out the sql generation code into it's own library, I recentely needed to do postgres queries against a hosted postgres db that does not enable the standard tcp interface (it has a rest based sql api, you heard me right), in other words I need the sql generation aspects but not the runner, pooling, or connection aspects of knex. I ended up just duplicating the relevant code [in the library I made](https://github.com/calvinmetcalf/cartodb) but it would have been nice to be able to have required the sql code from knex that as a dependency and sub classed it.

**Comment by StreetStrider** [comment]
I want to add `+1` to this, since I've found Knex when I was looking for «just SQL query builder». But Knex was good enough for me (promises, robust chainable API, `clone` for partials) so I've decided to use it as a whole, not just builder.

But (imo) «just query builder» still have strong reasons to be implemented. For instance, it's fully db-driver-agnostic, which is important for cases, like topic starter's one.

@calvinmetcalf, take a look at [Squel](http://hiddentao.github.io/squel/). I was using it one time. It had some issues but it well enough for many cases. But I think you have some knex-queries already, so you want Knex-like query builder with exact API, right?

**Comment by calvinmetcalf** [comment]
@StreetStrider I was actually able to just pull all the relevant code out of knex and use that, but it seems like an awful waste and not very reproducible as it took me a fair bit of time

**Comment by tkellen** [comment]
+1000, I've been lobbying for this for years! Granted, I've done nothing to help :/

**Comment by tgriesser** [comment]
Totally agree - I've realized that in order to do this and also #798 the construction/building of queries needs to be changed a bit so things are more easily composed and not dependent on the "client" object like they are now. Mainly we need to invert the construction/execution of queries and formalize how query fragments are built.

So, if you're only after the construction of postgres modules, I guess, if you were requiring this on its own, what would the dependency tree look like?

Would you require:

`knex-core-builder-postgres`

which would in turn depend on:

`knex-core-builder`

which would then be enough to build query strings, but with any postgres specific stuff added on?

Also... does it make sense to have a whole bunch of tiny individual library modules floating around on github each with their own version numbers and repos and such... or would it make more sense to have a build step which separated things out well defined namespaces which could be easily required individually/modularly, a la [lodash](https://github.com/lodash/lodash/tree/npm):

```js
var PGBuilder = require('knex/postgres/builder')
// this would know nothing about pools, connections, anything like that.
// or potentially:
var PGBuilder = require('knex/builder/postgres')
```

I think if well documented and done properly, the latter approach can be nice, particularly when it comes to the dependency hell that can potentially arise with having to coordinate version bumps in lots of tiny little modules.

I'm working on formalizing some of the query construction a bit now and would love to make progress on this soon.

**Comment by calvinmetcalf** [comment]
so having them in separate repo's is the way I'd do it as it allows you to version and update them individually and most importantly it means you have to nail down an API you are going to stick with, if there is a large chance that you are going to still end up developing the whole thing as a single unit and will need to end up coordinating releases then you're better off doing it lodash style.

> knex-core-builder-postgres

> which would in turn depend on:

> knex-core-builder

exactly this would also help with the idea @knownasilya and I have been throwing around of wanting geospatial extentions for postgres, we'd be able to sub class the postgres one, add some stuff, and then use it as it's own adapter

**Comment by tkellen** [comment]
I would start with something like this:
https://github.com/endpoints/endpoints/tree/05d8e933cc384c44b11f16b3283bd9a0cbcccab8/src

It's hell to manage dependencies if you split things up before you nail down the API between them. That sort of code organization allows you to play with how things are broken up without constantly `npm linking`.  Once things are pretty dang solid, then break 'em out.

**Comment by calvinmetcalf** [comment]
then you can end up with something like https://github.com/crypto-browserify

**Comment by knownasilya** [comment]
Yes please!

**Comment by LinusU** [comment]
I would love seeing this, is there any progress or anything the community could do to help?

@tgriesser Would you accept a pull request that moves the query builder out to a separate module?

**Comment by elhigu** [comment]
Closing old issue. I don't see any drawbacks if someone likes to implement this though.
