### ISSUE TITLE
There is no pool defined on the current client

### ISSUE THREAD

**Issue by cavinsmith** [tgriesser/knex#823]
Knex 0.8.4
pg 4.3.0
Postgres 9.4
Centos6 

FYI: Knex 7.6 @ same conditions works perfeclty.

**Comment by blah238** [comment]
I think you meant Knex 0.8.4, but I'm also seeing this after updating from 0.8.3.

**Comment by cavinsmith** [comment]
@blah238 yep, 0.8.4

**Comment by kswope** [comment]
Same problem.  I'm a knex noob so I just stumbled into the solution in minutes.  Must not be a default pool setting in the connection string anymore. 

Here is the example from the docs
```
 var knex = require('knex')({
  client: 'mysql',
  connection: {
    host     : '127.0.0.1',
    user     : 'your_database_user',
    password : 'your_database_password',
    database : 'myapp_test'
  },
  pool: {
    min: 0,
    max: 7
  }
});
```

**Comment by pkinney** [comment]
This is occurring if no pool configuration is defined when creating the client.

With the logic added in https://github.com/tgriesser/knex/commit/054be4606808e49577c931b78e20ee2928c87d89, if not pool object is specified in the config options, the pool is not initialized.

```javascript
if (config.pool && config.pool.max !== 0) {
  this.initializePool(config);
}
```

**Comment by kswope** [comment]
Is this a production ready library?  I've never seen a lib completely remove a default setting suddenly.  Usually if such a show stopping change was to be made a deprecation warning would show up in the logs somewhere.  Now I'm afraid to move forward with this.

**Comment by blah238** [comment]
@kswope I assume that since it wasn't documented and such deprecation notices have been made in the past that this is just a bug. I could be wrong, of course.

**Comment by natorojr** [comment]
@kswope Knex is definitely a production ready library -- and an awesome one at that.

Unfortunately, seems like there was a slight oversight in commit https://github.com/tgriesser/knex/commit/054be4606808e49577c931b78e20ee2928c87d89

I'm sure Tim did not intend to break existing code. 

I think the fix is simply:

```javascript
if (!config.pool || (config.pool && config.pool.max !== 0)) {
  this.initializePool(config);
}
```
I'll submit a pull request in a few hours.

In the meantime, you'll need to explicitly add pool entry to your config.

**Comment by tgriesser** [comment]
Wow. Can't believe I missed this, the tests weren't even doing what I'd meant them to either - sorry for the breakage here.

**Comment by natorojr** [comment]
Thanks for the immediate patch release @tgriesser 
Hopefully it didn't affect too many installations :)

**Comment by ttamminen** [comment]
Is this really fixed?

I have tried 0.8.4, 0.8.5 and 0.8.6 versions and I always get "Error: There is no pool defined on the current client".

**Comment by galenandrew** [comment]
This error is still present in `v0.9.0` with the following config:
```
{
  client: 'pg',
  connection: {
    charset: 'utf8',
    host : process.env.POSTGRES_HOST,
    port : process.env.POSTGRES_PORT,
    user : process.env.POSTGRES_USER,
    password : process.env.POSTGRES_PASSWORD,
    database : process.env.POSTGRES_DB,
  },
  migrations: {
    tableName: '_migrations',
    directory: './lib/migrations'
  },
  seeds: {
    directory: './lib/seeds'
  },
}
```

Per the docs:
> This connection pool has a default setting of a min: 2, max: 10 for the MySQL and PG libraries.

This does not appear to be the case. It looks like  because [`poolDefaults`](https://github.com/tgriesser/knex/blob/0.9.0/lib/client.js#L165) never gets called as a result of [`initializePool`](https://github.com/tgriesser/knex/blob/0.9.0/lib/client.js#L154) only being called when a pool config is passed.

**Comment by galenandrew** [comment]
@tgriesser, the issue is because the `if (this.driverName && config.connection) {` conditional fails in [/lib/client.js#L39](https://github.com/tgriesser/knex/blob/0.9.0/lib/client.js#L39). `this.driverName` never gets set, which as a result never initializes the pool.

**Comment by galenandrew** [comment]
Ok, more info on why I was getting this error.<br>_TL;DR it was not an issue with the `driverName` or `poolDefaults`, but rather with the config object including the environment specific configs._

---

My app is running in docker with the following knex set up…

**knexfile.js**
```javascript
module.exports = {
  client: 'pg',
  connection: {
    charset: 'utf8',
    host : process.env.POSTGRES_HOST,
    port : process.env.POSTGRES_PORT,
    user : process.env.POSTGRES_USER,
    password : process.env.POSTGRES_PASSWORD,
    database : process.env.POSTGRES_DB,
  },
  migrations: {
    tableName: '_migrations',
    directory: './lib/migrations'
  },
  seeds: {
    directory: './lib/seeds'
  },
};
```

**db.js**
```javascript
var config = require('./knexfile');

module.exports = require('knex')(config);
```

Initially I was running into issues with Knex CLI where it couldn't read my `knexfile.js`, although the [documentation](http://knexjs.org/#knexfile) clearly provides a similar example as a _"Basic Configuration"_.

After reading through #328 I followed @bendrucker's [comment](https://github.com/tgriesser/knex/issues/328#issuecomment-53658019) and updated my knexfile.js to the following:
```javascript
exports.development = exports.staging = exports.production = {
  // rest of my basic config
}
```

This of course made the migrations and CLI work properly, but then introduced the pooling error because the config object being passed into `require('knex')(config)` included the nested environment configs.

_It appears that the package was properly selecting the config based on the environment, but never properly initialized the client's Dialect. I see this as a parity issue between the configs the library and CLI accept._

**Comment by dkushner** [comment]
Is there any update on this? I am also running into this error. 

@galenandrew, thanks so much for putting the work into addressing this bug.

**Comment by galenandrew** [comment]
@dkushner, to clarify…are you running into the config environment error or the "no pool defined" error? Per my last comment, my "no pool defined" error was a result of errors in the config I was passing into Knex, not an error with the library.

**Comment by krainboltgreene** [comment]
This is a rather annoying error message since it doesn't actually tell you what's wrong, only one possible issue.

Any chance we can get this reopened and addressed?

**Comment by nicholasf** [comment]
Interesting. I'm also debugging this today.

**Comment by nicholasf** [comment]
In my case it was happening because I had missed the database URL in the config (for postgres) So the connection was being set to `undefined` and the error message was about a connection pool.

**Comment by Hesse** [comment]
Any movement on this one?

**Comment by rafaljanicki** [comment]
Same problem here

~~~~
var knex = Knex({
  client: 'mysql',
  connection: {
    host: process.env.DATABASE_HOST,
    port: process.env.DATABASE_PORT,
    user: process.env.DATABASE_USER,
    password: process.env.DATABASE_PASS,
    database: process.env.DATABASE_NAME
  }
})
~~~~
The same error for both 0.10 & 0.11 versions. I've also added pool configuration, but it didn't help

**Comment by CreepGin** [comment]
This error also applies to calling `knex.destroy()` before a running promise fully resolves. So make sure to place `knex.destroy()` at the right scope, or be sure not to forget your `await` keywords.

**Comment by krainboltgreene** [comment]
This is such a freaking annoying situation. Please please please do something about this.

**Comment by elhigu** [comment]
@krainboltgreene if you have problem related to this, please open new issue with steps to reproduce the problem. Original issue of this thread has been fixed. I agree that it would be nice to have more descriptive error message.

**Comment by krainboltgreene** [comment]
After the last 8 messages I'm really surprised, as maintainers, you haven't just made your own issue. But sure, if it gets this really annoying time wasting error attention I'll make a special issue for you.

**Comment by rhys-vdw** [comment]
> as maintainers, you haven't just made your own issue.

@krainboltgreene This error message is provided for many different error cases. This issue is for one case. Yours is presumably another. Please just respect that it's a shitty situation and and it's hard to deal with if we confuse a bunch of cases in together.

I don't think the team has shown any reluctance to discuss fixes for this, so I'm not sure exactly what you're expecting. This is an open source project so you are in a great position for helping out yourself. The collaborators are just like you - users of Knex - except we've gone to the effort of contributing. We just haven't fixed your specific problem.

> For example, in my case it wasn't that the NODE_ENV variable was missing or that I was missing options for the pool config, but rather that I was passing strings instead of integers.

This sounds like you've pinpointed that it *is* a different issue. The solution might be to do better type checking on the config object. Either way it should be discussed in another thread.

> After the last 8 messages...

**I am going to lock this thread to prevent further conflation of new problems with the old 2015 issue. If you have an error with the awful 'Pool is not defined' error, please open a new issue and reference this one.**
