### ISSUE TITLE
Testing fails after 3 retries (related to pooling)

### ISSUE THREAD

**Issue by brian-mann** [tgriesser/knex#836]
When I am testing my app it will consistently crash with this error:

```
Knex:Error Pool2 - error: Error allocating resources: sorry, too many clients already
Knex:Error Pool2 - error: Error allocating resources: sorry, too many clients already
Could not connect to your local postgres db!
Pool was destroyed
```

I don't have a pool object in my `knexfile`, I just use all the defaults. I'm using `0.8.5`. I use the `pg.app` with all defaults.

It doesn't matter how benign the test is. Even if the test is passing. If I rerun it after 3 times, the 4th time will always crash.

**Comment by tgriesser** [comment]
I'm guessing somehow the connections are being kept alive when running the tests - what testing library are you using and can you check whether this also occurs in 0.8.0 through 0.8.3? (0.8.4 is broken entirely)

/cc @myndzi

**Comment by brian-mann** [comment]
Yes, that's what's happening.

When tests are running, mocha will delete the `require` cache, which causes my app to cause a reconnection with knex.

So what I did was `memoize` the knex object on my App, so tests wouldn't create a new connection.

Then I had to create a global `spec_helper` file basically doing this:

```js
after(function(){
  App.get("knex").destroy()
})
```

That `after` function is called after all of the tests finish, which kills the last knex connection.

That then enables me to run tests back-to-back (using mocha watchers) so there wasn't build-up of the connections between test runs.

**Comment by myndzi** [comment]
Your app will need to shut down knex when the app itself shuts down, or it will never exit cleanly. In order to shut it down you will indeed need to keep a reference to it. It sounds like this is how you fixed the problem.

The error message doesn't sound familiar to me, though. Looking through the code, it appears that "too many clients already" would be the error given by the database server / database driver when attempting to open the first resource in a new pool. The error you report would be shown here: https://github.com/myndzi/pool2/blob/master/lib/pool.js#L367 and the limit imposed would be based on your database server's configuration in this case. 

I'm not sure if there's any way to implicitly clean up; how was your previous code expecting knex and/or the pooled resources to get destroyed?

**Comment by brian-mann** [comment]
My previous code didn't do anything in regards to shutting knex down. Which is why it would run out of connections during test mode. 

I implicitly assumed that when the node process exited or crashed it would remove the db connection. Are you saying it does not do this? How would those connections ever get cleaned up? That would be very concerning for production environment. 

Yes, by switching to managing the connection I was able to destroy those at the end of the test after all finished. That fixed the error I was having. Though I didn't change anything in the production environment to shut down.

**Comment by myndzi** [comment]
Ah, yes, that would indeed happen: everything in the v8 environment is of course purged on exit. The thing is, mocha doesn't spawn processes, so that wasn't happening.
