### ISSUE TITLE
Any way to format a table.column reference via the standard API?

### ISSUE THREAD

**Issue by myndzi** [tgriesser/knex#841]
I have a function whose purpose is to select an array of things, for example, for getting the ids of some 'bar' as a column of a query against 'foo' from the 'foo_bar' junction table. Now that we're strictly postgres-only, I'm rewriting this as an array subquery, so the SQL would look something like:

`SELECT foo.*, ARRAY(SELECT bar_id from foo_bar where foo_id = foo.id) AS foo_ids`

The trick here is `foo.id` -- how do I generate it? I can use `.wrap()` to tack the ARRAY around a subquery that I compose with the standard knex API, but I don't know how to get `"foo"."id"` in the `.where()` call

**Comment by wubzz** [comment]
Guessing your specific case is long since resolved, but to revive the discussion around this, the only way currently is via `knex.raw('??', ['table.column'])`.

Previous discussions include API proposals such as `knex.identifier('table.column')`.

Closing this as a 'question' and reopening a new issue as a feature request where we can maybe finally resolve this recurring issue.
