### ISSUE TITLE
Pool2 - Error: Pool.release()

### ISSUE THREAD

**Issue by jacobfunch** [tgriesser/knex#842]
I'm experiencing a new issue with the latest update to Pool2.

```
"switching to Pool2 in place of generic-pool-redux" in 0.8.0 
```

Error message:

```
Knex:Error Pool2 - Error: Pool.release(): Resource not member of pool 
Unhandled rejection Error: select "sess" from "sessions" where "sid" = $1 and CAST($2 as timestamp) 
```

The error appears when using knex.js and the connect-session-knex for session storage.
Rolling back to 0.7.5 fixed it.

**Comment by myndzi** [comment]
Can you:

1) Try with the latest 0.8 (0.8.5, I believe)
2) Run with `DEBUG=pool2` for some details
3) Or, provide a minimal test case that can reproduce the problem?

**Comment by jacobfunch** [comment]
Steps to reproduce:
1) Setup server with latest Express js, latest Knex js and latest connect-session-knex.
2) Use the session store to store all sessions.
3) Set cookie timeout to about a day.
4) Run server and set new sessions often.

When I do that I get the Pool release error. Hope it give you a clue.

**Comment by myndzi** [comment]
By 'minimal test case', I was referring to code, but hopefully that'll be enough to rig something up.

What database are you using? This may matter.

**Comment by myndzi** [comment]
Also, is the database local?

**Comment by myndzi** [comment]
There are two possibilities here; one is a "double release" scenario, and the other is that release is being called with an invalid object. If you are able to somewhat consistently reproduce the error, I'd be in your debt if you could help me figure out which of these is the case, at least if/until I'm somehow able to reproduce it on my own.

**Comment by myndzi** [comment]
I just published a new version of pool2 that adds object tagging when debugging; resources will be given a unique sequence number, and this number is referenced in destroy/remove/allocate messages. This should help determine specifically what's going on. I expect you will see a destroy for some reason with an id followed by a release with the same id. Please update, run with DEBUG=pool2, and let me know what you can find when you have the problem again. I've been running my test script all day with no luck.

**Comment by ArdentZeal** [comment]
Tue, 30 Jun 2015 09:39:29 GMT pool2 Pinging resource (id=11)
Tue, 30 Jun 2015 09:39:29 GMT pool2 Reserving request for resource (id=8)
Tue, 30 Jun 2015 09:39:29 GMT pool2 Pinging resource (id=8)
Tue, 30 Jun 2015 09:39:29 GMT pool2 Allocating resource (id=0) to request; waited 0.019s
Tue, 30 Jun 2015 09:39:29 GMT pool2 Allocating resource (id=11) to request; waited 0.015s
Tue, 30 Jun 2015 09:39:29 GMT pool2 Allocating resource (id=8) to request; waited 0.021s
[Error: insert into "strucd_activities" ("activityType", "created_at", "isSystemMessage", "listId", "listImported_at", "listImported_rowcount", "shortId", "updated_at", "userId", "uuid") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning "id" - Connection terminated]

I am using the default poolsize for development (docs say: { min: 2, max: 10 }). I guess the problem occurs because it tries to get id=11 although max should be 10.

**Comment by zacronos** [comment]
@myndzi: I've also hit the same error (`Knex:Error Pool2 - Error: Pool.release(): Resource not member of pool`) with knex 0.8.6.

In my case, I am running 2 worker processes via the `cluster` module, and that appears to be part of the issue -- I can reliably run with 2 worker processes and get the error, but then if I force it to run with only 1 worker process the error doesn't happen.  So, I would guess there's something not multi-process-safe in pool2.

I can't easily give you a minimal test case, but I'd be happy to provide some `DEBUG=pool2` logging output.  It is quite large however (>5Mb of logs before the error occurs), so I would need to share the logfiles with you outside of issue comments.

**Comment by myndzi** [comment]
@ArdentZeal I apologize; you pinged me specifically but knex receives so many messages I have it filed away into another folder and I can't really keep up with it easily.

The "id=11" is not worrisome; the id is sequential and does not correlate to the pool max at all. To get an id=11, all you'd have to do is have a couple idle resources get cleaned up.

The actual error you are receiving is "connection terminated", from the database driver, during a query that's being performed. Presumably either the query somehow or some external factor is causing the connection to be interrupted/terminated, and that is what you need to look into.

@zacronos: Obviously something is getting passed around that shouldn't be, but I can't begin to imagine why or where. I'm going to check a couple of things, but a minimal test case is almost required to run this down; I know it may not be easy, but unless you want to just ship me all your code, I can't think of how to approach this otherwise.

**Comment by myndzi** [comment]
I suppose the error could be unrelated to clustering entirely, too. I was just browsing the node source to confirm, and yeah, any data has got to be passed around through IPC. Are you trying to share a knex instance between requests or something? Making any assumptions about continuity between request callbacks? I'd bet that the resource that is attempting to be released is undefined or some such, but I don't know why it would be so.

**Comment by zacronos** [comment]
@myndzi, thanks for looking into this.  Would the `DEBUG=pool2` logs help at all?  Or can I turn on some verbose Knex logging and send that over?  I'll spend some time trying to isolate a minimal example...  there's a lot of moving parts to this code, so I feel like there's a good chance I won't capture whatever edge case is causing the bug.  But I'll see what I can do.

We're using bluebird Promises to manage things, but there is a lot going on at once.  So we're almost certainly using the same knex instance in two different "threads" of asynchronous execution (I know node doesn't truly have threads, but hopefully you know what I mean...  2 logical simultaneous execution paths).  I'm not sure what you mean about continuity between callbacks

Interestingly, the code that's hitting this problem is in a queue worker, and we were running 2 clustered processes with 2 asynchronous workers per process...  and the problem goes away when I turn it down to 1 process with 2 workers OR 2 processes with 1 worker each.  But so far I can get the problem 100% of the time with 2 and 2.  So you could be right that it has nothing to do with clustering, as I'm just kinda confused by the situation.

I'll spend a little time trying to stand up some code that exhibits this behavior.  If I succeed, I'll let you know, but in the meantime if there's any sort of logging I can provide from the real app that might point you in the right direction, just give the word.

**Comment by myndzi** [comment]
Well, I'm going off of "I can reliably run with 2 worker processes and get the error" -- that's a very helpful place to start, but only if I can run the code that's causing the error and narrow things down. If minimizing your code makes the error go away, that's a strong indicator that the problem may be in your code itself. The very fact that there are "a lot of moving parts" is the reason that I can't easily try to figure the problem out without more information, if I can't just nail it with a good guess and some code review.

What I mean by continuity between callbacks is something like, are you reusing something between two separate request handlers? That's probably not going to work out when you're using clustering, since two separate workers might be handling the parts that you assume are in the same worker space. There could perhaps be an error, say, if you assume something exists that you put in some shared memory space where both requests could get at it, when it doesn't (because the previous request was handled by another worker).

The kind of logging to be had from pool2 is "instance local" -- that is, if you have two separate workers, they're going to be logging the same or similar id numbers on the resources, and that's confusing and not helpful. Even if they could be distinguished, since the problem is a bad release, it's unlikely that the thing being released will have any identifying information that can be tracked. And since the problem seems to be related to multiple processes, it's even harder -- there's nothing to tie information from one process to another, except maybe stuff in **your** code. Knex, as far as I know, would be much the same. I'm not really sure of how to create logs that would be useful in tracking this down; I would be most effective at being "hands on". If it's possible, I might be able to work with you via a remote shell session to try and figure this out?

You can e-mail me your logs anyway at kris.re at bbhmedia.com. I doubt I'll be able to determine the problem, but the logs themselves may give me a better idea of what's going on in general, which may give me some ideas of where to focus your attention.

**Comment by zacronos** [comment]
Again, thanks for your help.  I'll email the logs over.

**Comment by elhigu** [comment]
Pool2 is not used anymore
