### ISSUE TITLE
Knex should install `pg-query-stream` as its own dependency

### ISSUE THREAD

**Issue by sedge** [tgriesser/knex#934]
If knex is the one using `pg-query-stream`, why should it be a dependancy of the app using knex? Seems a little odd to me, but maybe I'm missing something.

**Comment by diegofss11** [comment]
Since knex requires `pg-query-stream` as a `devDependency` once we install knex it will not install `pg-query-stream`  so we would need to do it by ourselves. Maybe they should move `pg-query-stream` to `dependencies` instead of `devDependencies`...

**Comment by wubzz** [comment]
By the same arguments knex should then also include `pg` as a dependency instead of depending on the app using knex? And `mssql`, `mysql`, `oracle`, `sqlite3`, and all the seperate modules developed for the respective clients, in your case `pg-query-stream`..

Knex makes no assumption about what client you are using nor if you are going to be using streams or not. For this reason they are not listed in the dependencies. Imagine the extra 'junk' for your app if we did include the above mentioned modules as dependencies instead of devDependencies.
